### ISSUE TITLE
[Feature request] Add ReloadOnChange For KeyPerFile Configuration

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/extensions#1085]
Can we have reload on change for KeyPerFile configuration?

**Comment by davidfowl** [comment]
We should look into supporting this. When updating config maps mapped to volumes on k8s we don't react to those changes today.

cc @glennc @rynowak

**Comment by Kahbazi** [comment]
@davidfowl Can I send a PR for this?

**Comment by davidfowl** [comment]
Yep!

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/extensions/pull/2808, thanks again @Kahbazi
