### ISSUE TITLE
[Feature Request] Add Expression to IStringLocalizerOfT

### ISSUE THREAD

**Issue by librame** [dotnet/extensions#1094]
### Additional context
```
// IStringLocalizerOfT
public LocalizedString this[Expression<Func<TResource, string>> propertyExpression]
{
    get { return GetString(propertyExpression); }
}

public LocalizedString GetString<TResource, TProperty>(Expression<Func<TResource, TProperty>> propertyExpression)
{
    string propertyName = propertyExpression.GetName();
    return GetString(propertyName);
}

// IHtmlLocalizerOfT
... ...
```

### For example
```
// Dummy class to group shared resources
namespace Localization
{
    public class SharedResource
    {
        // Add Property
        public string Name { get; set; }
    }
}

var localizer = new StringLocalizer<SharedResource>();
Console.WriteLine(localizer[p => p.Name]);
Console.WriteLine(localizer.GetString(p => p.Name));
```

**Comment by hishamco** [comment]
This is cool if the generic class contains all the properties that represent the resource keys, but I saw in almost localization samples I have seen that the generic class used to determine the resources location

**Comment by hishamco** [comment]
FYI I already implemented such feature on `JsonStringLocalizer` in https://github.com/hishamco/My.Extensions.Localization.Json

**Comment by anurse** [comment]
> This is cool if the generic class contains all the properties that represent the resource keys, but I saw in almost localization samples I have seen that the generic class used to determine the resources location

Yeah, I think this wouldn't really work with the current implementation pattern.

> FYI I already implemented such feature on `JsonStringLocalizer` in [hishamco/My.Extensions.Localization.Json](https://github.com/hishamco/My.Extensions.Localization.Json)

Awesome, that sounds like a useful extension!
