### ISSUE TITLE
MemoryCache does not throw error if AbsoluteExpiry set but subsequently overridden by calling upstream component with a shorter cache expiry

### ISSUE THREAD

**Issue by LittleColin** [dotnet/extensions#1130]
### Describe the bug
If method A caches a result for say, an hour, but calls an upstream component method B (that may even use an entirely different MemoryCache instance) but caches for 5 minutes - method A's result will be cached for 5 minutes too.

### To Reproduce
1. Using version 2.1 of aspnetcore and the MemoryCache extension
2. Use the following code in the ValuesController (default web api sample):
```csharp
[HttpGet]
public async Task Get()
{
    var result = await _memoryCache.GetOrCreateAsync("mykey",
        async entry =>
        {
            // The following line will be silently ignored!
            entry.AbsoluteExpiration = DateTime.Now.AddHours(12);
            
            var other = await OtherMethod();
            return new string[] {"value1", "value2"};
        });

    // Other than waiting for 5 minutes, the only way to examine the actual timeout set is via reflection
    var memoryCache = typeof(Microsoft.Extensions.Caching.Memory.MemoryCache)
        .GetField("_entries", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
        .GetValue(_memoryCache);
    var cacheDictionaryType = memoryCache.GetType();
    var cacheEntry = cacheDictionaryType.GetProperty("Item").GetValue(memoryCache, new[] { "mykey" });
    var expiration = (DateTimeOffset)cacheEntry.GetType().GetProperty("AbsoluteExpiration").GetValue(cacheEntry);
    if (expiration.Offset.TotalMinutes < 60)
    {
        throw new Exception("What? I set the absolute expiration to 12 hours");
    }

    return result;
}

private async Task OtherMethod()
{
    return await _memoryCache.GetOrCreateAsync("myotherkey",
        async otherEntry =>
        {
            otherEntry.AbsoluteExpiration = DateTime.UtcNow.Add(TimeSpan.FromMinutes(5));                    

            return "my other data";
        });
}
```
3. Just run the webapi
4. See that the exception with message "What? I set the absolute expiration to 12 hours" is thrown

### Expected behavior
Ideally we would have an option to allow the downstream component to force the longer cache time, perhaps a property "ForceAbsoluteExpiryOverride=true". At the least I would expect an error to tell me that this line had been ignored:
entry.AbsoluteExpiration = DateTime.Now.AddHours(12);

### Additional context
See https://sartorialsolutions.wordpress.com/2019/02/15/aspnetcore-memorycache-magic-dependencies-and-danger/ for more info and https://github.com/aspnet/Docs/issues/10962

**Comment by anurse** [comment]
How would the caching system know the two entries are interdependent like this? The caching system is simply calling a function here. Doing something like this would require adding a dependency model to link cache entries as dependent upon other entries, which is much more complexity than we plan to add to this caching API.

**Comment by LittleColin** [comment]
I believe you may have misread the issue @anurse as the issue is not about creating a dependency but breaking a magic dependency created simply based on callstack. Method A cache timeout should not be influenced or dependent on calling method B which happens to cache its result for a shorter time.

**Comment by anurse** [comment]
Ah gotcha! Thanks for that clarification!
