### ISSUE TITLE
ConfigurationBinder: Support for DI service resolution

### ISSUE THREAD

**Issue by gtrifidis** [dotnet/extensions#1145]
### Is your feature request related to a problem? Please describe.
There is no problem. This is clearly an enhancement request.
My request is about adding support to the **ConfigurationBinder.Bind**, to be able to resolve interfaces to their concrete types, whilst iterating through the instance's properties, using an IServiceProvider. 

### Describe the solution you'd like
It looks like the most transparent change I can think of at the moment is, adding an IServiceProvider property to the BinderOptions object. 
The **CreateInstance** method signature would change to accept a BinderOptions instance.
```csharp
private static object CreateInstance(Type type, BinderOptions options)
```
It would then make a check for the existence of an IServiceProvider and try to resolve the interface.
```csharp
private static object CreateInstance(Type type,BinderOptions options)
{
	var typeInfo = type.GetTypeInfo();

	if (typeInfo.IsInterface || typeInfo.IsAbstract)
	{
		if(options!=null && options.ServiceProvider != null)
		{
			return options.ServiceProvider.Get(type);
		}
		throw new InvalidOperationException(Resources.FormatError_CannotActivateAbstractOrInterface(type));
	}
}
```
As far as I can see, this doesn't change any of the public methods signatures and doesn't introduce any new dependencies.

As for the consuming side of things, my expectation would be something like this
```csharp
public MyClass(IConfiguration configuration)
{
	this.configuration = configuration;
	IApplicationSettings appSettings = ServiceProvider.Provider.Resolve<IApplicationSettings>();

	this.configuration.Bind(appSettings,(options)=> {
		options.ServiceProvider = ServiceProvider.Provider;
	});
}
```

### Describe alternatives you've considered
An alternative can be, to get the ConfigurationBinder code and implement the above in a MyConfigurationBinder type of class. It's a maintenance nightmare, but still a possible alternative.

### Additional context
This can decouple anyone consuming a configuration object, from it's concrete implementation.

**Comment by anurse** [comment]
What does this enable that the [Options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1) doesn't currently support?

**Comment by gtrifidis** [comment]
Besides the decoupling of anyone consuming a configuration object, from it's concrete implementation,
it could be used from the configuration object perspective (again for decoupling), if it references an interface/service (transient/singleton/scoped) but doesn't have access to the concrete implementation.

**Comment by anurse** [comment]
> Bare in mind that it's been a year since this one

Yep, I realize that. We're doing some backlog clean-up and this one got missed earlier.

This is exactly what the Options pattern allows though, isn't it? You define options types specific to your components (not necessarily coupled to the Configuration layout) and then use the Options system to wire them up to specific config.

**Comment by gtrifidis** [comment]
You are probably right. I might have to go through some of the code and see if I can achieve the same using the Options pattern, but that might take a while.

So feel free to close this one and if I have any new findings worth bringing up, I'll reopen I guess.

Thanks.
