### ISSUE TITLE
Setting configuration variables with dots in names via env vars in Linux

### ISSUE THREAD

**Issue by schmaxit** [dotnet/extensions#1171]
### Describe the bug
Can't configure using environment variables when configuration variable name contains a dot on Linux.
An example of the need for this is setting the log level of classes in nested namespaces

### To Reproduce
Running the project in [logging_env_test.tar.gz](https://github.com/aspnet/Extensions/files/2902577/logging_env_test.tar.gz)
 with:
```Logging__LogLevel__logging_env_test=Trace Logging__LogLevel__logging_env_test_nested=Error  dotnet run```

prints:
```
[...]
trce: logging_env_test.nested.LoggedClass[0]
      LogTrace
dbug: logging_env_test.nested.LoggedClass[0]
      LogDebug
info: logging_env_test.nested.LoggedClass[0]
      Information
warn: logging_env_test.nested.LoggedClass[0]
      LogWarning
fail: logging_env_test.nested.LoggedClass[0]
      LogError
crit: logging_env_test.nested.LoggedClass[0]
      LogCritical
[...]
```

Tested on aspnet core 2.1

**Comment by queil** [comment]
Having a similar issue with `SERILOG__MINIMUMLEVEL__OVERRIDE__MICROSOFT.ASPNETCORE=Warning`. It works in powershell but not in bash

**Comment by Rick-Anderson** [comment]
You need to replace `.` with double underscore `__` AND you can only have 2 levels of nesting. See #3095

**Comment by maryamariyan** [comment]
related to https://github.com/dotnet/runtime/issues/35989. Refer to comment https://github.com/dotnet/runtime/issues/35989#issuecomment-619257166
