### ISSUE TITLE
Options bind behavior

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/extensions#1181]
``` C#
class A
{
    public List<TimeSpan> B { get; set; }
}
[Fact]
public void BindArray()
{
    var dic = new Dictionary<string, string>
    {
        { "a:b:0", "00:00:01" },
        { "a:b:1", "00:00:02" },
        { "a:b:2", "00:00:03" },
        { "c:b:0", "00:00:04" },
        { "c:b:1", "00:00:05" },
        { "c:b:2", "00:00:06" },
    };
    var config = new ConfigurationBuilder().AddInMemoryCollection(dic).Build();

    var options = new A();
    config.GetSection("a").Bind(options);
    config.GetSection("c").Bind(options);
    Assert.Equal(TimeSpan.FromSeconds(4), options.B.First()); //fail
}
```
Collection property value why not replace but add? How can change the behavior?

**Comment by anurse** [comment]
In both of the `Bind` calls, you're giving the same keys to the binder: `b:0`, `b:1`, `b:2`. Thus the ones from the second call overwrite the values in the first call.

The `:0`, `:1`, `:2` suffixes give the specific array index to set. Arrays defined in two different sections or two different providers don't add to each other, they overlay on top of each other.
