### ISSUE TITLE
Configuration.AzureKeyVault long to load when having dependency on Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by Hartdrooz** [dotnet/extensions#1218]
### Describe the bug

When I have a dependency on the nuget package Microsoft.Azure.ServiceBus and I use the extension of Azure Key Vault in the package Microsoft.Extensions.Configuration.AzureKeyVault it takes around 30 seconds to start my application.  I am building rest api using .Net Core 2.2.

This bug seems to occurs when I execute the application inside Visual Studio 2017, if I run my application using docker I see a lot of logging to retrieve the token for Azure Key Vault but it doesn't take 30 seconds to have the application ready.

### To Reproduce
Create a new web api project with Visual Studio using .Net Core 2.2

Add the nuget package Microsoft.Azure.ServiceBus and Microsoft.Extensions.Configuration.AzureKeyVault in the project.

In the Program.cs file configure the CreateWebHostBuilder method this way: 

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((context, builder) => 
                {
                    var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
                    builder.SetBasePath(Directory.GetCurrentDirectory())
                           .AddJsonFile("appsettings.json",
                                         optional: false,
                                         reloadOnChange: true)
                           .AddJsonFile($"appsettings.{env}.json",
                                         optional: true,
                                         reloadOnChange: true)
                           .AddEnvironmentVariables();

                    IConfigurationRoot configuration = builder.Build();

                    string keyVaultEndpoint = configuration["KeyVaultEndpoint"];

                    string clientId = configuration["ClientID"];
                    string clientSecret = configuration["ClientSecret"];

                    builder.AddAzureKeyVault(keyVaultEndpoint, clientId, clientSecret);

                });
    

### Expected behavior
The application should not take around 30 seconds to be ready only because of the Service.Bus package.

**Comment by martincostello** [comment]
Do you have a lot of secrets in your key vault? I noticed there was a change to load these in parallel for 3.0, presumably to speed things up: #944

**Comment by Hartdrooz** [comment]
No I have only like 10 secrets and I notice the behavior I have is only when I add the Service.Bus nuget package.  Why I found this is because I was having two web api one without the service bus nuget package and the other with.

**Comment by TraGicCode** [comment]
While we are not using azure service bus we are in AKS and notice it also takes around 40-50 seconds for the Azure Key Vault Configuration Provider to initialize which is way to long.  We only have 1 secret in our vault

Any Updates on this?

**Comment by rosponda57** [comment]
Hi, we have the same problem.
Maybe You have some updates for this issue?

**Comment by anurse** [comment]
The Azure SDK team is releasing new integration packages which work in apps using 2.1 or higher (see https://github.com/aspnet/Announcements/issues/408 for details). We recommend converting to use those and filing relevant issues on https://github.com/Azure/azure-sdk-for-net/
