### ISSUE TITLE
Performance improvement for Microsoft.Extensions.Caching.SqlServer

### ISSUE THREAD

**Issue by MarkCBB** [dotnet/extensions#1268]
### Problem/Performance improvement
There are variables never used but fetched from the database and converted in the code. This means two unnecessary costs: fetching the value from the database and converting the value.

For more details about the impact in performance see the section Additional context.

NB: I'm continuing based on [this answer](https://github.com/aspnet/Caching/pull/406#issuecomment-428639431) written by @muratg in a pull request opened some time ago in the previous location of this repository.

### Proposed solution
The files changed in [this Pull Request](https://github.com/aspnet/Caching/pull/406/files) addressed this performance optimization. Removes the usage of the non used variables and modifies the query to don't select from the database those values when are not needed.

If you consider to merge these changes I can send another pull request for the current location of the repository.

### Describe alternatives you've considered
This improvement requires the removal of some code sections and the optimization of the query sent to the database. No more alternatives.

### Additional context
I've created [this performance test](https://github.com/MarkCBB/test-performance-sqlserver-cache) -easy to set up and run- in order to know if the improvement makes any difference based in execution times. In my opinion there are variations making this improvement meaningful. In the readme.md file you'll find how to run this test and more detailed times.

Find below a resume of the execution times in milliseconds:

* Average. Optimized: 23643, non optimized 25276 (optimized is 1633 faster)
* Slowest. Optimized: 28287, non optimized 31622 (optimized is 3335 faster)
* Fastest. Optimized: 21845, non optimized 23004 (optimized is 1159 faster)

**Comment by muratg** [comment]
cc @davidfowl

**Comment by MarkCBB** [comment]
This issue and its related pull request implements some housekeeping, code
cleaning and a few performance improvement. I understand the low priority
as the gain is low, but honestly, I don’t see why this pull request should
be closed losing the work done. Also, recently I’ve updated the branch
resolving all conflicts with the last changes in master branch.
May be is time to review the pull request, merge it and then close the
issue ;)
Please, could you take a look or keep this pull request alive?

**Comment by JunTaoLuo** [comment]
The linked PR has been merged.
