### ISSUE TITLE
InMemoryDirectoryInfo doesn't work if rootDir has trailing slash

### ISSUE THREAD

**Issue by MikeChristensen** [dotnet/extensions#1272]
### Describe the bug
InMemoryDirectoryInfo won't match if rootDir parameter ends with a slash

### To Reproduce
1. Using version '...' of package '...'
Latest (2.2.0)

2. Run this code '....'
```
var curDir = @"C:\GlobTest\";
var files = Directory.EnumerateFiles(curDir, "*.config", SearchOption.AllDirectories);
InMemoryDirectoryInfo dirInfo = new InMemoryDirectoryInfo(curDir, files);

var results = new Matcher()
    .AddInclude("**/*.config")
    .Execute(dirInfo);

// Expect: results.Files.Count() > 0
```

3. With these arguments '....'

### Expected behavior
Provided *.config files exist in C:\GlobTest, those files should be returned.

If you change the first line to:

```
var curDir = @"C:\GlobTest";
```

Then everything works.  Note, this behavior is the same regardless of whether you pass in `**/*.config` or `/**/*.config` as an include.

### Additional context
Include the output of `dotnet --info`

**Comment by HaoK** [comment]
I don't think this has anything to do with config, I think this is an issue in filesystems in the InMemoryDirectoryInfo class probably...  https://github.com/aspnet/Extensions/tree/master/src/FileSystemGlobbing
