### ISSUE TITLE
Make NullExternalScopeProvider / NullScope public?

### ISSUE THREAD

**Issue by kierenj** [dotnet/extensions#1354]
Hi - I'm creating a new logger provider.  It's going to hook into SignalR in debug scenarios to let a web client retrieve any logger output relating to its request.

I wanted to make the behaviour as similar to the 'official' logger providers as possible - so I wanted to take (for instance) the `ConsoleLoggerProvider` as a basis, and drop in changes as necessary.

However, `NullExternalScopeProvider` and `NullScope` are `internal`.  Is there a reason for this, or could they be shared externally?

Should I approach writing a logger provider differently?  I like all of the conventions for config, option reloading, etc, that the 'convention' of the Extensions packages bring.

**Comment by kierenj** [comment]
Ok, this may be a non-starter anyway - any probably a separate issue but: my `LoggerProvider` depends on a SignalR hub.  SignalR depends on `ILogger<>`...  Of course, I get circular references.
I just can't see a way around it.  Is there anything I can do?  Does the `IEnumerable<ILogger<>>` resolver have any logic that can be tweaked by user code?

**Comment by anurse** [comment]
You shouldn't do async things (and SignalR calls are definitely async things) in loggers anyway. Instead, I'd suggest having the logger put the log messages into a concurrent queue of some kind, in a singleton service. Then have a [background service](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2) scoop up the latest log messages and flush them down to your clients (doing all the async work.

> my `LoggerProvider` depends on a SignalR hub

To be clear, you should use `IHubContext<THub>` to send messages from outside a SignalR Hub. See the documentation on [sending messages from outside a hub](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2).

> However, `NullExternalScopeProvider` and `NullScope` are `internal`

How are you using these types? Making new types public takes some design work so I want to understand the motivating scenario.

**Comment by kierenj** [comment]
I'm doing what you indicate there - writing to a boundedchannel synchronously in the logger and have a background task which is reading from it / writing to SignalR in the way you describe (via `IHubContext<THub>`)

However:
- Resolving `IHubContext<THub>` in turn requests `ILogger`
- My `ILogger` comes from the provider implementation, which in turn needs some class which uses `IHubContext<THub>`

I can't instantiate an `IHubContext` before logging is set up, and I can't instantiate a logger because it's requesting an `IHubContext`.  

I believe I need to use DI to instantiate both parts here - so I feel like it's a dead end?

(It's been a while - I'm sure I tried using the singleton scope to resolve an `IHubContext`, which seems an obvious way to do it - but may try that one again.  I know at one point I had an issue with a mix of lifetimes..)

But I think I'm doomed anyway if hub calls will log messages, and log messages invoke the hub ?

`NullExternalScopeProvider`, `NullScope` - I'm just looking at the Console logger provider as a basis for writing my own provider.  They look like convenient classes to use, and I guessed that the built in providers were suitable "exemplary" implementations to base my own on.

**Comment by anurse** [comment]
> * My `ILogger` comes from the provider implementation, which in turn needs some class which uses `IHubContext<THub>`

That's the problem. You can't have the circular reference. Instead, I would have a **shared** reference from the logger to the "queue" and another reference from the background service to the "queue". Then the reference isn't circular, the queue can be created first and given to each of the provider and background service. Something like this **pseudo** code:

```csharp
// Register as a logger provider in ConfigureLogging
public class MyLoggerProvider : ILoggerProvider
{
    public MyLoggerProvider(MyLoggerMessageQueue queue)
    {
        _queue = queue;
    }

    public void Log(...)
    {
        _queue.EnqueueMessage(...);
    }
}

// Register as a singleton service in ConfigureServices
public class MyLoggerMessageQueue
{

    public void EnqueueMessage(...)
    {
        // .. write the message to some kind of queue ..
    }

    public IReadOnlyList<...> DequeueAllMessages()
    {
        // .. dequeue all the messages in the queue and return them ..
    }
}

// Register with AddHostedService in ConfigureServices
public class MyLoggerBackgroundService : BackgroundService
{
    public MyLoggerBackgroundService(IHubContext<MyLoggerHub> hub, MyLoggerMessageQueue queue)
    {
        _hub = hub;
        _queue = queue;
    }

    public async Task ExecuteAsync(CancellationToken ct)
    {
        while (!ct.IsCancellationRequested)
        {
            var messages = queue.DequeueAllMessages();

            // Maybe some batching is good here, any maybe you want to transform the messages somehow.
            await _hub.Clients.All.SendAsync("LogMessagesReceived", messages);

            // 'x' is some delay that makes sense for your service
            await Task.Delay(x);
        }
    }
}
```

> But I think I'm doomed anyway if hub calls will log messages, and log messages invoke the hub ?

This is definitely a problem to consider. You may need to filter out certain messages because it's definitely the case that *sending* the messages to the clients will generate more messages. You won't get "recursion" in the pattern I showed above, but the background service will generate more logs, which will go into the queue, which means there will always be logs for the background service to send when it wakes up and it will never be "idle"

**Comment by kierenj** [comment]
Feeling stupid for not having seen that solution, thank you. :)  Of course because it's a queue that's shared, it's not a major issue if the consumer only kicks in after everything has finished setting up (loggers kick in early to document all of that..).

In terms of the first question for this issue, I was wondering about which conventions and ideas to go with when creating my own provider in general - I have a more mature batching JSON file logger which pushes to disk (and then to Elasticsearch via filebeat), which is perhaps a more reasonable use case.

I can see there's `NullExternalScopeProvider` used by default here in `ConsoleLoggerProvider` -
https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Console/src/ConsoleLoggerProvider.cs#L19 .  The amount of builder extension methods is pretty intense too, with only one option/setting I'd really consider specific to the console (the "use colours" flag).

My intention is for the logger to have the same standard feature set, for the principle of least surprise.  Or at least, I can't think of a reason why I'd exclude features that the MS team thought were worthwhile including in a simple provider that almost everyone would use :)

**Comment by anurse** [comment]
Returning to the original question re: `NullExternalScopeProvider` and `NullScope`, we don't plan to add these as public APIs. Yes, they are simple, but new public APIs are costly to maintain (they restrict what changes we can make, since public API changes are breaking changes to customers). They also don't need to be shared (they're not types exchanged between multiple components), so copying the code is a very reasonable alternative.
