### ISSUE TITLE
Let `ConsoleLifetime` only stop the application if `CancelKeyPress` was not already handled.

### ISSUE THREAD

**Issue by ericwj** [dotnet/extensions#1371]
### Is your feature request related to a problem? Please describe.
If the host is running any console application then it may in fact handle `Console.CancelKeyPress` sometimes or always. It will not always be desirable to exit upon encountering the key combination unconditionally. However it is very easy to check whether `Ctrl+C` has already been handled and act accordingly.

### Describe the solution you'd like
Make the call to [StopApplication](https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/Internal/ConsoleLifetime.cs#L88) conditional on `e.Cancel == false`:
```C#
private void OnCancelKeyPress(object sender, ConsoleCancelEventArgs e)
{
    if (!e.Cancel) {
        e.Cancel = true;
        ApplicationLifetime.StopApplication();
    }
}
```

### Describe alternatives you've considered
This is a small change the handily beats the user having to replace `IHostLifetime` altogether or adding an option to `ConsoleLifetimeOptions` which would typically have the same value throughout the lifetime of the application.

### Additional context
I consider using `HostBuilder` for an application that needs to handle `Ctrl+C` in a special way.

**Comment by Tratcher** [comment]
What else is handling the CTL+C in your scenario?

How do you ensure the callbacks are wired up in the appropriate order?

In theory this could cause issues if you ran two hosts in the same process, only the first would stop.

**Comment by ericwj** [comment]
That theory is true already. There is only one bool to set to true or false. I didn't test it but what would happen if the `CancelKeyPress` handler is removed altogether? `ExitProcess` will be raised, correct? And it will block on `_shutdownBlock` and still exit gracefully. Just guessing however.

The point is this host might run literally any software, even a console UI which handles Ctrl+C. In my case Ctrl+C is just a keypress like any other. It may cancel something or not. It might exit something but not the process outright or at least in a very indirect way.

I think `HostBuilder` should put the hard coded service registrations at the end of the method with `TryAddSingleton` - if I'm correct that will leave already registered `IHostLifetime` services as they are and registers `ConsoleLifetime` only if there is not already another `IHostLifetime`. Second, it will also wire up the key press handler last such that any user code gets to preview the key press. The downside is that in this case these registrations cannot completely be removed, but then that would fail the host since there is other stuff that depends on e.g. `IHostLifetime` at least to be present.

**Comment by Tratcher** [comment]
You can already override the ConsoleLifetime service registration. The last registration wins.

**Comment by ericwj** [comment]
I guess I will do that, but for anyone who didn't check the implementation of `HostBuilder` and `IHostLifetime` the behavior of Ctrl+C in presence of user handlers must be confusing.
