### ISSUE TITLE
Microsoft.Extensions.Configuration.Json preview4 not compatible with netstandard2.0

### ISSUE THREAD

**Issue by jherby2k** [dotnet/extensions#1505]
### Describe the bug
preview4 of the Microsoft.Extensions.Configuration.Json package does not work with netstandard2.0 projects, I believe because of a [(now fixed) bug](https://github.com/dotnet/corefx/issues/37006) in Microsoft.Bcl.Json.Sources. Preview3 was fine, as it still used Newtonsoft.Json.

### To Reproduce
1. Upgrade a netstandard2.0 library project to reference Microsoft.Extensions.Configuration.Json 3.0.0-preview4.19216.2.
2. Try to run it.

### Expected behavior
No exception.

### Screenshots
N/A

### Additional context
I believe this can be fixed by simply updating to the latest Microsoft.Bcl.Json.Sources nightly.

**Comment by BrennanConroy** [comment]
Preview4 didn't have the issue you linked. Could you give more details of what errors you're seeing?

**Comment by jherby2k** [comment]
That issue was only closed 2 days ago so I figured that was the problem. I have a library that targets netstandard2.0 and netcore2.1. netstandard2.0 fails at load time if I upgrade to preview4. Getting the exception while take a little bit - I'll update this issue in a few hours.

**Comment by BrennanConroy** [comment]
>That issue was only closed 2 days ago so I figured that was the problem.

Yes, but it was a very short lived issue that only affected nightly preview 5 bits.

**Comment by anurse** [comment]
This should be resolved in the GA builds.
