### ISSUE TITLE
Unclear How To Use Current Code With Command-Line Programs

### ISSUE THREAD

**Issue by jlodom** [dotnet/extensions#1513]
In June of 2017 I began writing a number of back-end, command-line programs for my organization using .NET on Linux. I wanted to use the most stable and supported libraries as part of this effort, and my research indicated that Microsoft.Extensions.Logging was the correct approach for logging for both present and future projects. In the subsequent two years the approach has proven to be everything desired.

However, I now see that the ILoggerFactory approach that was current when I began has been deprecated. The new approach to create loggers is highly ASP-centric, and I cannot find good instructions on adapting it for a command-line (batch) application. Preferably I would like to be able to use it without adopting ASP's foundation for automatic configuration and the like. 

I am requesting some supported, future-proof functionality to create ILogger objects easily in a command-line application without ASP support. Thank you.

(I can provide code if desired, but I think my request should be fairly straightforward.)

**Comment by davidfowl** [comment]
It's a bit convoluted today using the ILoggingBuilder pattern in a console application without a host. You have a couple of options here:

1. Use the generic host in your console application. The host isn't tied to ASP.NET and gives you way to do do config and logging out of the box (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#configurelogging).
2. If you're on 2.2, continue to use the LoggerFactory and deprecated methods and mark suppres the warning.
3. Create a ServiceCollection and call AddLogging() (e.g https://github.com/aspnet/Extensions/blob/e2f51bb31a313fd329765b6fcff1b6923f6d0fc3/src/Logging/samples/SampleApp/Program.cs#L26) then use the new provider methods to AddConsole etc
4. In 3.0, we added a nicer way to bootstrap the factory that should solve the problems you describe above https://github.com/aspnet/Extensions/blob/3c4e2261e49561197a2afa77bf5354c58f30e3f8/src/Logging/samples/SampleApp/Program.cs#L24-L33.

We're currently pushing people towards 1 as there's lots of value there outside of logging but those are your options. If you do choose one of them, I'd like to know which one and why. Hope that helps
