### ISSUE TITLE
Azure Key Vault Configuration Provider doesn't support complex configuration types?

### ISSUE THREAD

**Issue by AlphaCreativeDev** [dotnet/extensions#1522]
We recently migrated our secret configuration from appsettings.json to Azure Key Vault.  When using appsettings.json we always used complex strongly typed configuration classes such as ExternalAPIConfig where in appsettings.json this looked like the following:

`"ExternalAPIConfig : {
"APIUrl" : "https://myapiurl",
"APIKey" : "myapikey"
}`

Then in startup.cs we would make GetSection and Bind calls like this:

`
ExternalAPIConfig apiConfig = new ExternalAPIConfig();
Configuration.GetSection("ExternalAPIConfig").Bind(apiConfig);
`

or register a service configuration like this:

`
services.Configure<ExternalAPI>(Configuration.GetSection("ExteranlAPIConfig"));
`

or grab a connection string like this:

`
var connectionString = Configuration.GetConnectionString("ConnectionStringName");
`

This always worked perfectly and was very clean.  After switching over to using Azure Key Vault we are finding that local dev secrets stored in secrets.json work identically to the way that they do when being consumed from appsettings.json, so what is above works perfectly (I assume b/c both use the underlying json configuration file provider).

However when we consume the same secret value from Key Vault (we are pasting the body of the setting from appsettings.json into the value for the secret in key vault so our secret values are json) using the Azure Key Vault Configuration Provider it appears that the kv provider treats the values of secrets as strings and does not recognize them as json objects so the only way to get at the value is with the .Value property of the ConfigurationSection as a string.

So when deployed to staging or prod where the values are actually pulled from key vault we can no longer use GetSection or GetConnectionString as shown above and instead we have to do something like this:

`
            services.Configure<ExteranlAPIConfig>(options => 
            {
                var config = JsonConvert.DeserializeObject<ExternalAPIConfig>(Configuration.GetSection("ExteranlAPIConfig").Value);
                options.APIUrl= config.APIUrl;
                options.APIKey= config.APIKey;
            });
`

or

`
Dictionary<string, string> connectionStrings = JsonConvert.DeserializeObject<Dictionary<string, string>>(Configuration.GetSection("ConnectionStrings").Value);
`

So now I have to introduce environment specific code all over startup.cs just b/c my configuration source is different.  It seems like I should be able to use these functions the same way whether I am using the json provider or the key vault provider.  This feels very unnatural and results in different code depending on which provider we are using which seems to kind of defeat the purpose of the provider abstraction.  Hoping we are missing something obvious here or just doing something plain wrong and would be happy to learn that is the case.  What I have outlined above works but is that really the best approach?

**Comment by AlphaCreative** [comment]
No we have a key vault key called ExternalAPIConfig and the value of that key is this json: { "APIUrl" : "https://myapiurl", "APIKey" : "myapikey" }  Again our thought process here was that we would be able to "lift and shift" from appsettings.json to key vault.  Key in appsettings.json => secret key in key vault, json body value in appsettings.json => secret value in key vault.  Since all of our configuration objects are strongly typed classes with more than one property we assumed (incorrectly obviously) that the key vault provider would behave just like the json file provider.  We were hoping we would not have to resort to a vault secret per config property because that seems like it would result in a lot of secrets with no cohesion and would not jive with a strongly typed config entity and the ability to bind it in a single statement like we have been using with appsettings.json

**Comment by tiagodenoronha** [comment]
I had complex object types as well in my appsettings. What I did was Create several keys that mapped to that object. Taking your object as an example, we have 2 keys: ExternalAPIConfig--APIUrl and ExternalAPIConfig--APIKey. 
When we configure the object, the values are passed correctly as we do Configuration.GetSection<ExternalAPIConfig>()

**Comment by anurse** [comment]
The syntax @tiagodenoronha mentioned ("Parent--Child--...") is the expected way to express complex objects. The config system doesn't specifically support hierarchical data, it's just a convention applied on top.

In my experience, I've mostly seen creating rich object structures in their JSON config and then **only** putting the few keys that actually need to be secret in Key Vault.

I'll leave this open and backlog it though to track the idea of a feature to handle secret values that are JSON payloads. The KeyVault provider *could* certainly do this if it was deemed valuable.

**Comment by AlphaCreative-Mike** [comment]
Yes this issue needs to remain open.

**Comment by anurse** [comment]
Actually, the Azure Key Vault integration is now provided in a new package maintained at https://github.com/Azure/azure-sdk-for-net (see https://github.com/aspnet/Announcements/issues/408) so the remaining request (support for JSON values in the KeyVault config provider) should be filed over there.

**Comment by AlphaCreative-Mike** [comment]
New issue created here: https://github.com/Azure/azure-sdk-for-net/issues/11943
