### ISSUE TITLE
Setting a message color for console log messages results in identical foreground and background colors

### ISSUE THREAD

**Issue by kamsar** [dotnet/extensions#1655]
### Describe the bug
The `ConsoleLoggerProcessor`'s `WriteMessage` method always sets the `MessageColor` to be identical for the foreground and background color. Thus, if a non-null value is passed in `LogMessageEntry.MessageColor`, the console message is unreadable. The standard ConsoleLogger appears to never pass a non-null value, so this is likely a simple typo.

https://github.com/aspnet/Extensions/blob/711b5b34e1533564c3ef1513192e3f71a9537dbe/src/Logging/Logging.Console/src/ConsoleLoggerProcessor.cs#L62

### Expected behavior
The console message should be readable instead of having an identical foreground and background color. A logical solution would seem to be to add `MessageBackground` property to `Microsoft.Extensions.Logging.Console.Internal.LogMessageEntry` and use that for the background, i.e. instead of 

```
console.Write(message.Message, message.MessageColor, message.MessageColor);
```
```
console.Write(message.Message, message.MessageBackground, message.MessageColor);
```

### Screenshots
![image](https://user-images.githubusercontent.com/103677/57121795-952a2080-6d2e-11e9-91a7-4d53e572a53e.png)

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537
```

**Comment by gfoidl** [comment]
> A logical solution would seem to be to add `MessageBackground`  property to `Microsoft.Extensions.Logging.Console.Internal.LogMessageEntry`

Or just pass `null` as background color?
https://github.com/aspnet/Extensions/blob/711b5b34e1533564c3ef1513192e3f71a9537dbe/src/Logging/Logging.Console/src/WindowsLogConsole.cs#L19-L24
https://github.com/aspnet/Extensions/blob/711b5b34e1533564c3ef1513192e3f71a9537dbe/src/Logging/Logging.Console/src/AnsiLogConsole.cs#L23-L29
So with `null` the default background color is kept (and the size of `LogMessageEntry` isn't increased).

**Comment by kamsar** [comment]
@gfoidl that would prevent having a background per-message, but could certainly be a reasonable compromise.

**Comment by kamsar** [comment]
As a hacky workaround, because I don't need `LogLevel` emitted in my console log at this time, I'm using an empty string for the log message, and the `LevelForeground`/`LevelBackground`/`LevelString` to emit the actual message with arbitrary colors.
