### ISSUE TITLE
[2.1 backport] Enable EventLog logger by default on Windows

### ISSUE THREAD

**Issue by shirhatti** [dotnet/extensions#1680]
We need to backport https://github.com/aspnet/Extensions/issues/1628 to 2.1

**Comment by anurse** [comment]
Looks simple enough. We should consider this for June. Putting it in the milestone.

**Comment by anurse** [comment]
This is super old now :). Do we still want to do this? It's not as simple as a backport since we actually never did it in `WebHost` (even in 3.x).
