### ISSUE TITLE
AddEnvironmentVariables cannot work  in asp.netcore2.2

### ISSUE THREAD

**Issue by liuyl1992** [dotnet/extensions#1684]
Environment:  .NetCore2.2

As long as using the ConfigureAppConfiguration and set the AddEnvironmentVariables method, cannot get  system environment variables by IConfiguration["XXX"]

![image](https://user-images.githubusercontent.com/16396828/57271847-bb9be300-70c3-11e9-9baf-2c90639242c4.png)
![image](https://user-images.githubusercontent.com/16396828/57271872-c8203b80-70c3-11e9-8705-be0c33ebe63d.png)
![image](https://user-images.githubusercontent.com/16396828/57271938-f140cc00-70c3-11e9-9a59-a9fb780c50da.png)

**Comment by davidfowl** [comment]
This isn’t a bug, there’s no ASPNETCORE_ prefix implied by default

**Comment by Tratcher** [comment]
Though WebHost reads "ASPNETCORE_" env vars by default...
Try listing out the config:
https://github.com/aspnet/AspNetCore/blob/d3400f7cb23d83ae93b536a5fc9f46fc2274ce68/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L179-L186

Also, you need to restart your editor before environment variable changes take effect.

**Comment by anurse** [comment]
Closed as we haven't heard from you. If you're still hitting this issue, let us know by filing a new bug with a repro project and/or dump of config.
