### ISSUE TITLE
TimestampFormat is not validated, consequent exception doesn't show up in console

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/extensions#1689]
There's a direct call to `ToString` here, but if TimestampFormat is not valid it'll throw. 

https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Console/src/ConsoleLogger.cs#L111-L121

However you actually won't see the exception of it in your console until that field is valid again (are old messages cached?)

Running on 3.0.100-preview5

EDIT:
Not only do you not get the exceptions, it dismantles kestrel completely. Causing connection hangs followed by connection resets.

**Comment by NinoFloris** [comment]
Also it seems Standard Date and Time Format Strings don't work once there's any extra character beside the format is supplied. So this works `"u"` but this doesn't `"'['u']'"` respectively logging `2019-05-08 20:11:12Z` and `[u]`.

Though to really get a converted Z 8601 time (so converted into utc) doesn't seem possible with `u`. You just get your local timezone time with a Z character at the end. `K` helps a bit here by at least presenting the actual timezone, but true conversion into UTC time doesn't seem possible.
Would an additional option be possible? `"TimestampKind": "Utc"`

**Comment by anurse** [comment]
So the issue here is that you don't see the exception anywhere? That does seem unpleasant. Perhaps we should catch exceptions here and force a useful message into the queue (something like "Error formatting log message: {blah...}"

**Comment by NinoFloris** [comment]
It also stalls kestrel completely for some reason (exception escaping to lower levels?)
