### ISSUE TITLE
New IAzureAppServicesLogMessageFormatter interface

### ISSUE THREAD

**Issue by Yves57** [dotnet/extensions#1736]
I would like to be able to customize the Azure App Services logger messages (to add more information).
I could rewrite a new logger from scratch, but of course I want to reuse the existing blob management logic.

So I think that a new interface

```
public IAzureAppServicesLogMessageFormatter
{
   string Format<State>(DateTimeOffset timestamp, LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);
}
```

implemented as singleton would be interesting. It has no impact on the current behavior nor performance, and allows to easily improve the customization possibilities.

I set explicitly the `AzureAppServices` prefix in the interface name, because this kind of customization targets a specific logger (it would be probably a different formatter for a Console or a Debug logger). So this interface seems to be specific to the logger type.

If it makes sense to you, I can submit a PR.

Additional note about a small performance improvement: the `StringBuilder` in `BatchingLogger.Log()` could have an initial capacity set in the constructor, because it allocates always at least three chunk in the code
```
var builder = new StringBuilder();
builder.Append(timestamp.ToString("yyyy-MM-dd HH:mm:ss.fff zzz"));
builder.Append(" [");
builder.Append(logLevel.ToString());
builder.Append("] ");
```

**Comment by anurse** [comment]
We don't expect to be able to prioritize this kind of change to the main app service logger. In general, we're looking to move to a model where the console logger is able to provide this kind of functionality and are looking at custom formatters in #2479 .
