### ISSUE TITLE
MEF2 provider for Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by gthvidsten** [dotnet/extensions#1743]
I'm used to using MEF2 (System.Composition) in my solution and would like to continue using that in the Microsoft.Extensions.Hosting service model. However, I'm not able to get the custom ServiceProviderFactory to work properly.
My code is partially based on @nblumhardt's [extensions](https://github.com/dotnet/corefx/issues/37249#issuecomment-489885424) to add existing types into the MEF container (which is also [propsed](https://github.com/dotnet/corefx/issues/37249) as an addition to dotnet/corefx).
The main problem is that I'm not able to add the `IHost` to the MEF container and I'm always getting this exception:

> No service for type 'Microsoft.Extensions.Hosting.IHost' has been registered

I have an [example solution](https://github.com/gthvidsten/MEF2-DI-Extensions/tree/master/src) here you can clone to see the error, and hopefully be able to find out what I'm doing wrong.

I'm guessing that everything boils down to `MefExtensions/MefServiceProviderBuilder.cs:16` where I loop through all defined services and try to add them to the MEF container.
I can see that the `IHost` is catched in the `if` on line 26, but adding it using `.WithPart()` doesn't seem to help.

I've also tried using conventions and adding the contained assembly like the following, but it had no effect:

```csharp
ConventionBuilder conventions = new ConventionBuilder();
conventions.ForType(service.ServiceType)
    .Export((c) => { c.AsContractType(service.ImplementationType); })
    .Shared();
_containerConfig.WithAssembly(service.ImplementationType.Assembly);
```

So now I'm all out of ideas, and I hope you can help me get this working properly.

I know that many other DI providers have added support for this on their own, so I believe this might be quite useful to others, like me, who are used to MEF and want to continue using it in .NET Core Hosting, so anything you can do to help me should also help others (and maybe this should even be a part of `System.Composition` in the end!)

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
