### ISSUE TITLE
Register Multiple instances as part of a single method call

### ISSUE THREAD

**Issue by chris31389** [dotnet/extensions#1762]
### Is your feature request related to a problem? Please describe.

I find it difficult to register multiple instances of a class based of all instances of another registered class.

If I have the following classes

``` csharp
public interface IFoo
{
    string Name { get; }
}

public class Foo : IFoo
{
    public Foo (string name) => Name = name;
    public string Name { get; }
}

public interface IBar
{
    void SayHello();
}

public class Bar
{
    private IFoo _foo;
    public Bar(IFoo foo) => _foo = foo;
    public void SayHello() => Console.WriteLine($"Hello {_foo.Name}");
}

public interface IApplication
{
}

public class Application : IApplication
{
    public Application(IEnumerable<IBar> bars)
}

IServiceCollection serviceCollection = new ServiceCollection()
    .AddScoped<IApplication,Application>()
    .AddScoped<IFoo>(serviceProvider => new Foo("A"))
    .AddScoped<IFoo>(serviceProvider => new Foo("B"));
```

I have two registered instances of the `IFoo` interface.

### Describe the solution you'd like

I want to register multiple instances of a class that takes IFoo as an injected parameter
I was hoping for something like this:

``` csharp
serviceCollection.AddScopedInstances<IBar>(serviceProvider =>
    serviceProvider
        .GetServices<IFoo>()
        .Select(foo => new Bar(foo));
```

### Alternatives

Currently the only way I can work out how to do this is to register the IEnumerable:

``` csharp
serviceCollection.AddScoped<IEnumerable<IBar>>(serviceProvider =>
    serviceProvider
        .GetServices<IFoo>()
        .Select(foo => new Bar(foo));
```

I'm not sure how this would be affected by registering another IBar

**Comment by anurse** [comment]
I think I need a little more clarity on what you're trying to do here. You have two instances of `IFoo` and you want two instances of `Bar` in the container, each of which gets a different `IFoo`?

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
