### ISSUE TITLE
How to get only console logs in output?

### ISSUE THREAD

**Issue by Pilchie** [dotnet/extensions#1773]
_From @wpitallo on Thursday, May 30, 2019 8:44:22 PM_

How to get only console logs in output?

Hi, currently I have set my logs to only log program output but I am still getting a lot of unwanted information. Is there a way to get just my logs and also none of the namespaces etc

![image](https://user-images.githubusercontent.com/12214559/58662970-abc29800-832b-11e9-99af-59b1ae7a98e8.png)

Also is there an easy way like in Node.js to log in color without having to configure custom providers?

_Copied from original issue: dotnet/core#2814_

**Comment by wpitallo** [comment]
Hi @Pilchie, hope that you are well! Not sure if its possible but can't we get a unified logging experience across MST, products. Especially on Azure, I have been using Azure Cosmos DB and Azure functions and the logging experience is really really bad. On cosmos db in the data explorer does not even support multi-line logging which is mind boggling.

**Comment by anurse** [comment]
> Hi, currently I have set my logs to only log program output but I am still getting a lot of unwanted information

This output is controlled by the "Debug Window Logger". You can disable it and replace it with your own (which can output the text in whatever format you'd like):

```csharp
Host.CreateDefaultBuilder(args)
    /* other configuration ... */
    .ConfigureLogging(logging =>
    {
        // Removes ALL the default providers
        logging.ClearProviders();

        // Add back any providers you'd like, such as the standard console logger
        logging.AddConsole();

        // Add a custom provider, which is a class that implements ILoggerProvider
        logging.Services.AddSingleton<ILoggerProvider, MyCustomLoggingProvider>();
    });
```

> Also is there an easy way like in Node.js to log in color without having to configure custom providers?

The default console provider does use colors for highlighting the log level, but there's no built-in way for you to include specific colors. On Linux/macOS (and recent Windows 10 versions) you could embed [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to set certain colors, but it would depend on your terminal supporting them.

> can't we get a unified logging experience across MST, products

`ILogger` is fairly unified now, [Azure Functions supports it natively](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#ilogger). I can't speak to Azure Cosmos DB, that would be a good question for them. I'm not sure what logging needs they provide. If you're referring to logging from their client SDK, perhaps filing an issue on [their repo](https://github.com/Azure/azure-cosmos-dotnet-v3) would be a good way forward.

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
