### ISSUE TITLE
Configuration: Splitting the config in multiple files and using $ref 

### ISSUE THREAD

**Issue by alexandrosntak** [dotnet/extensions#1787]
Hello there. :) 

My config is getting large and merging changes can be very annoying.

I would like to be able to use the $ref keyword to reference json in other files (even in the same file would be an upgrade). This would give a much better overview of the changed parts when merging, while keeping the config parts smaller.

I tried it and then searched around but didn't find a way to do this. Is it possible at all? Will it ever be possible?

**Comment by anurse** [comment]
You can do this already by adding multiple config files and layering keys, is this not suitable? For example:

appsettings.foo.json
```json
{
    "Foo": { ... foo settings ... }
}
```

appsettings.bar.json
```json
{
    "Bar": { ... bar settings ... }
}
```

Then, in your Program.cs, you need to register each of these files:
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration(config =>
            {
				// Here's where we register the additional files!
                config.AddJsonFile("appsettings.foo.json");
                config.AddJsonFile("appsettings.bar.json");
            })
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
}
```

Does that work for your scenario?

**Comment by alexandrosntak** [comment]
Hello @anurse and thank you for your comment. I already use that mechanism for a part of the configuration and it is handy. Unfortunately, it is not very practical for all the use cases I have. :)
