### ISSUE TITLE
[Perf] Impact of Logging providers

### ISSUE THREAD

**Issue by sebastienros** [dotnet/extensions#1817]
![image](https://user-images.githubusercontent.com/1165805/58991976-6d4f3200-879e-11e9-9a1c-9af84ea1dd14.png)

Comparing PlaintextNonPipelined with and without a logging provider, even though nothing is actually logged (Warning level). What is interesting in the difference in committed memory on a scenario that is non-allocating.

/cc @halter73

**Comment by anurse** [comment]
To be clear, there's no regression here (i.e. from perf with logging on in 2.x), this is simply about exploring the difference between logging enabled and logging disabled? This seems viable to investigate for late-3.0 or 3.1, but not something we're going to be able to prioritize right now.
