### ISSUE TITLE
[Discussion] DebugLogger class made internal in ASP.NET Core 3.0

### ISSUE THREAD

**Issue by anurse** [dotnet/extensions#1823]
The [`DebugLogger`](https://github.com/aspnet/Extensions/blob/28f85d7af4f2aef88939ad44a4852b8ebdbddb51/src/Logging/Logging.Debug/src/DebugLogger.cs) class was never intended to be constructed by user code. It is only constructed by the `DebugLoggerProvider` class. In 3.0 we are cleaning this up by making `DebugLogger` `internal`, to match with other logger implementations (such as `ConsoleLogger`, etc.).

This is the discussion issue for https://github.com/aspnet/Announcements/issues/367.

**Comment by TimHess** [comment]
Hello, this comment is more around the change to make `ConsoleLogger` `internal`, but as I missed that change until now and don't see a discussion for it I'll comment here.

I work on [Steeltoe](https://github.com/SteeltoeOSS/Steeltoe), and one of the pieces of functionality we provide is a way to change log level settings for any given namespace or logger at run-time. We currently accomplish this by wrapping `ConsoleLogger` and managing the list of loggers and respective filter levels. As all the relevant classes are now marked `internal`, our implementation can't work with 3.0.  I'd rather not reinvent the wheel here as logging to the console is not the core feature we're trying to offer, but I don't see a way to continue to do what we've been doing with these changes.

**Comment by anurse** [comment]
I'm not entirely sure why you need `ConsoleLogger` in order to do this wrapping though. I see that [`DynamicLoggerProvider`](https://github.com/SteeltoeOSS/steeltoe/blob/c623ad18ac23651ee6178fd3a2dc113af4bc0f9f/src/Logging/src/DynamicLogger/DynamicLoggerProvider.cs) is creating a logger using `ConsoleLoggerProvider` (which is public) and then try-casting to `ConsoleLogger`. Why do you need to try-cast though? Couldn't you wrap it in your own `ILogger` that applies filtering and then delegates to the underlying logger?

Also, I'm not sure that the way you're doing this would work with the native filtering that exists in Logging already. If you filtered out messages of a certain level using the native filtering, we'd never call your `ILogger`, wrapped or not.

> one of the pieces of functionality we provide is a way to change log level settings for any given namespace or logger at run-time

This should be feasible with the native filtering. We can probably chat with you to figure out a way to move forward with the native support rather than wrapping like this.

**Comment by anurse** [comment]
cc @glennc @rynowak

**Comment by TimHess** [comment]
Thanks for the response - this implementation has been around since ConsoleLogger was at 1.1.0, so I wouldn't be surprised if it is past due for a rethink. I've got the same feeling about a more native solution than the current wrapper that I'm still working on and I'll work with Glenn outside this thread as-needed.

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
