### ISSUE TITLE
AddKeyPerFile does not load secrets in linux

### ISSUE THREAD

**Issue by jaijitendra** [dotnet/extensions#1830]
### Describe the bug
I have asp net core project which I am deploying inside linux containers in kubernetes cluster. My secrets are in /secrets folder and I used` builder.AddKeyPerFile("/secrets", false);` to load the secrets/configurations. But it does not work. configuration["File1"] returns empty. File1 is a file inside /secrets folder which contains one of the secret.

When I execute the below in the service code, I am able to read the secrets.
```
                List<KeyValuePair<string, string>> secrets =
                    new List<KeyValuePair<string, string>>();

                foreach (var secretFile in Directory.GetFiles("/secrets", "*.*", System.IO.SearchOption.AllDirectories))
                {
                    secrets.Add(
                        new KeyValuePair<string, string>(
                        Path.GetFileName(secretFile), File.ReadAllText(secretFile)));
                }
```

**Comment by anurse** [comment]
> I used` builder.AddKeyPerFile("/secrets", false);` to load the secrets/configurations. But it does not work.

The path provided to `AddKeyPerFile` is absolute, so this is look for the `/secrets` directory in the root of your filesystem.

Also, it's important to note that in general, if you're on Linux and start the path with `/`, it will be treated as an **absolute** path.

It's a little odd that the key-per-file provider doesn't support relative paths (for example `./secrets` throws) though, so we'll leave this open to track fixing that.
