### ISSUE TITLE
Where is Microsoft.Extensions.Http.Polly 2.2.4?

### ISSUE THREAD

**Issue by chrisb-de** [dotnet/extensions#1837]
Hi,

we are using the AspNet Extensions in one of our projects. It seems you unified the repositories of the different extensions into one single repository.

Currently we are using Microsoft.Extensions.Http.Polly 2.2.0. This version is still in it's own repository. So far so good.

We are about to upgrade our Polly version to 7.x.x but Microsoft.Extensions.Http.Polly 2.2.0 restricts us to 6.1.0 and we are looking for an upgraded version.

So you released "Microsoft.Extensions" Version 2.2.4 a while ago. This version also contains the Microsoft.Extensions.Http.Polly codebase and doesn't contain any restrictions on the Polly version. Thus we tried to upgrade to this version, but we are unable to find this package either on https://www.nuget.org/ nuget.org nor on https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json.

Could someone point me to the correct nuget-feed? I seem to be unable to find it myself by googling or browsing nuget.org :-(

Cheers
chrisb-de

**Comment by anurse** [comment]
The Microsoft.Extensions.Http.Polly package is still on NuGet.org and has multiple versions supporting Polly 7.x.x

> So you released "Microsoft.Extensions" Version 2.2.4 a while ago. This version also contains the Microsoft.Extensions.Http.Polly codebase and doesn't contain any restrictions on the Polly version.

There is no "Microsoft.Extensions" package. This repo contains all the previous packages in a single repository but the packages remain independent.
