### ISSUE TITLE
Remaining pubternal APIs in Extensions

### ISSUE THREAD

**Issue by davidfowl** [dotnet/extensions#1861]
We're moving away from pubternal and are either making things public or internal. Here are the remaining pubternal APIs in the Extensions namespace (all aren't here as yet but the ones that are in the shared framework are)

- [ ] - [Microsoft.Extensions.FileSystemGlobbing.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.Extensions.FileSystemGlobbing.Internal.md)
- [ ] - [Microsoft.Extensions.Hosting.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.Extensions.Hosting.Internal.md)
- [ ] - [Microsoft.Extensions.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.Extensions.Internal.md)
- [x] - [Microsoft.JSInterop.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.JSInterop.Internal.md)

**Comment by Tratcher** [comment]
@anurse @davidfowl Are we fixing this in 3.0?

**Comment by anurse** [comment]
* JSInterop is Blazor-related (@SteveSandersonMS @rynowak). Seems small, can it just be public or internal?
* Microsoft.Extensions.Internal is `ISystemClock` in Caching, which we can try to remove
* Microsoft.Extensions.Hosting.Internal seems safe to internalize
* Globbing isn't a small set, but we could try.

Let me take a first look at everything but JSInterop.

**Comment by SteveSandersonMS** [comment]
The JSInterop one was already made internal yesterday. Checking it off the list.

**Comment by anurse** [comment]
ISystemClock is on the public types:
* MemoryCacheOptions
* SqlServerCacheOptions

Removing it would be a breaking change. Thoughts? Seems reasonable, if we can find another way to feed it in from tests.

**Comment by davidfowl** [comment]
Leave it and it becomes a public API that we document.

**Comment by anurse** [comment]
In caching though? That seems sketchy

**Comment by Tratcher** [comment]
We've debated for a long time over making this a proper API. https://github.com/aspnet/Extensions/issues/151#issuecomment-293580924

**Comment by anurse** [comment]
We could move it to Primitives. I'd endorse that.

**Comment by Pilchie** [comment]
Moving this to backlog now, since we won't make any further changes here for 3.0

**Comment by julealgon** [comment]
> We've debated for a long time over making this a proper API. [#151 (comment)](https://github.com/dotnet/extensions/issues/151#issuecomment-293580924)

@Tratcher was it brought up again more recently? Having an abstraction for the time is such a common requirement that it would be nice to have a unified, system-defined interface for it instead of having it implemented in multiple libraries (some of them from Microsoft itself).

The argument that "it only has a single implementation" is just not enough to justify not adding it IMHO.

**Comment by Tratcher** [comment]
See https://github.com/dotnet/runtime/issues/36617
