### ISSUE TITLE
OptionsMonitor OnChange is triggered even though the last ConfigurationProvider has not changed

### ISSUE THREAD

**Issue by TheReaLee** [dotnet/extensions#1862]
We have the following scenario where configuration providers are set as follows:
1. appsettings.json,
2. appsettings.{env.EnvironmentName}.json
3. User Secrets File
4. Azure App Configuration
5. Azure Key Vault
6. Environment Variables
7. Command Line Arguments

Command Line Arguments (7) is the configuration provider which its settings take priority over the other providers. See: https://github.com/aspnet/Extensions/issues/1711

Let's say that both in **appsettings.json** and **Azure App Configuration** we have the following setting (Name: **Lee**). If I were to change the value to: (Name: **Peter**) from within the **appsettings.json** file, the OnChange<TOptions> event of OptionsMonitor would still trigger (not **expected**) as the returned value is **Lee** due to the Order of precedence described above (1. AppSettings.json, 4. Azure App Configuration).

The question: Is this expected behavior? Should the OnChange<TOptions> event still trigger even though the TOptions returned contained the original setting due to order of precedence?

**Comment by TheReaLee** [comment]
@Eilon any updates on this?

**Comment by Eilon** [comment]
(BTW I don't work on this project anymore. I just label things for fun 😄)

So you're saying the OnChange is unexpected because the effective value didn't change?

**Comment by anurse** [comment]
This is the expected behavior. The config system isn't factoring in specific keys when it handles change notifications, it just signals the token any time any config provider's data changes, even if that data would have been overridden by a higher layer.
