### ISSUE TITLE
Make ConsoleLoggerOptions.IncludeScopes default to true

### ISSUE THREAD

**Issue by halter73** [dotnet/extensions#1883]
### Is your feature request related to a problem? Please describe.

We should make ConsoleLoggerOptions.IncludeScopes default to true so it's easier to correlate logs that belong to the same request and/or connection.

### Describe the solution you'd like

We should make ConsoleLoggerOptions.IncludeScopes default to true.

### Describe alternatives you've considered

We've already tried making IncludeScopes default to false. Even if you did know the option exists (which I suspect most people don't), by the time you have logs that you want to include scopes in it's often already too late. You might not be able to easily repro the issue again.

### Additional context
https://github.com/aspnet/AspNetCore/pull/10413#discussion_r286279945

**Comment by halter73** [comment]
@BrennanConroy @anurse @davidfowl @Tratcher I just want to make sure everyone sees this before it's too late.

**Comment by anurse** [comment]
I don't expect we'll be able to do this in 3.0 given our current time scale (and how dramatic the user-visible change is). We can chat more about it though.

**Comment by halter73** [comment]
@davidfowl made a bargain... We'll see if he keeps to it 😄

The deal is that we can enable ConsoleLoggerOptions.IncludeScopes by default if we remove the manual logging of connection id's from Kestrel.

Below is the output for a request to the SignalRSample app looks like with IncludeScopes enabled. It definitely does add a lot of noise to the logs if you aren't interested in all the scope metadata.

If we decide that the current console logger with scopes is too noisy, we should default to just logging RequestPath and RequestId. That's a mode the console logger should support even if we don't decide to make it the default.

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      => ConnectionId:0HLNR8DSAQPOH => RequestPath:/ RequestId:0HLNR8DSAQPOH:00000001, SpanId:|3b4d0e58-40fb880a36ed8edf., TraceId:3b4d0e58-40fb880a36ed8edf, ParentId:
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      => ConnectionId:0HLNR8DSAQPOH => RequestPath:/ RequestId:0HLNR8DSAQPOH:00000001, SpanId:|3b4d0e58-40fb880a36ed8edf., TraceId:3b4d0e58-40fb880a36ed8edf, ParentId:
      Sending file. Request path: '/index.html'. Physical path: 'C:\dev\aspnet\AspNetCore\src\SignalR\samples\SignalRSamples\wwwroot\index.html'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      => ConnectionId:0HLNR8DSAQPOH => RequestPath:/ RequestId:0HLNR8DSAQPOH:00000001, SpanId:|3b4d0e58-40fb880a36ed8edf., TraceId:3b4d0e58-40fb880a36ed8edf, ParentId:
      Request finished in 152.81980000000001ms 200 text/html
```

**Comment by Tratcher** [comment]
Request paths can get long too. Why not just RequestId?

**Comment by halter73** [comment]
I'd be OK if it was just RequestId. I actually prefer that.

**Comment by davidfowl** [comment]
You can't tie the console logger to specific properties to do with the request. That'd need to be some generic filtering mechanism.

**Comment by halter73** [comment]
Agreed. We'll probably want to design some configurable filtering API.

Unfortunately this messes with my plans for doing something to trace RequestId's for all logs in a request scope 3.0 by default 😢
