### ISSUE TITLE
IServiceCollection should be more generic regarding checking services

### ISSUE THREAD

**Issue by wasabii** [dotnet/extensions#1890]
Other DI containers would like to provide a `IServiceCollection` abstraction that consults an existing service registry of some fashion. Not all of these registries support things such as enumeration.

It would be better if IServiceCollection was not a list-like interface. But instead provided interfaces to check if a registration existed. As of now, extension methods used by MS distributed libraries invoke the non-overridable TryAdd/etc methods, that end up trying to enumerate the `IServiceCollection` and check for equality. This is basically impossible to properly implement if your registry cannot enumerate up ServiceDescriptors.

It would be better if IServiceCollection did not support enumeration, but instead provided methods to check if a registration existed.

**Comment by anurse** [comment]
Can you provide an example of a container that does this? It would be a pretty major breaking change for us to do this since the `IServiceCollection` interface is prolific.

**Comment by wasabii** [comment]
Autofac.

**Comment by wasabii** [comment]
For example, take Microsoft.Extensions.Options. `Configure` and such end up invoking `AddOptions`, each time. Which invoke `TryAddScoped` and such, to add `IOptionsManager` and friends.

`TryAddScoped` is an extension method. It's operation is to enumerate all of the items in the `IServiceCollection`, and check whether the `ServiceDescriptor` is is trying to add already exists. This means every invocation of `Configure` ends up enumerating the entire `IServiceCollection`. That's bad right off the bat from a performance perspective.

But it also means that if `IServiceCollection` doesn't support enumeration, there's no way to get that method to work right. And, since it's an extension method, there's no way to override it for an implementation of `IServiceContainer`.

Autofac supports `RegistrationSources`, which are classes in the container that can provide types, without knowing up front what types they provide. That means you can't actually enumerate an Autofac container and determine the full set of what is actually available in it. You can only know whether it does or does not provide a service for a type. TryAdd really should just be invoking Contains. Instead of enumerating and testing. But there's no Contains method available on `IServiceCollection`, so, of course, they don't.

**Comment by anurse** [comment]
Oh yeah, I get the reasoning, was just looking for the specific container that you knew of that does it.

Like I said, it'll be tricky to get right and without being massively breaking (given all the things dependent upon `IServiceCollection` today). It's not an unreasonable idea, just tricky.

**Comment by davidfowl** [comment]
I can’t see us making this change as I don’t see the benefit outweighing the cost of the break.

**Comment by wasabii** [comment]
Welp, I leave it with ya'll.

The whole picture on my end, though, is incredibly obnoxious. All of these MS libraries provide `Add*` methods, that register stuff, and usually that stuff is internal; and coupled with these poor abstractions make working with it a nightmare if you use other containers.

**Comment by davidfowl** [comment]
Instead of proposing a breaking change, why not try to find a different approach to solve that specific problem. If you’re looking for something like a module abstraction for a set of services, I can understand but that’s not the whole story. That module needs to be registered and discovered somehow and has to be an opt-in thing. Honestly though I don’t see why it can’t be built on top of the collection and why enumeration ends up being a blocker (other than it breaking encapsulation).

**Comment by wasabii** [comment]
Not sure I follow. You can't enumerate what you don't have available. And I can't override internal methods.
