### ISSUE TITLE
Add support for “in-memory tables” in Microsoft.Extensions.Caching.SqlServer

### ISSUE THREAD

**Issue by epignosisx** [dotnet/extensions#1894]
Currently, the Microsoft.Extensions.Caching.SqlServer library does not play well with SQL Server in-memory tables. The reason is that the data type DateTimeOffset is not supported by IM tables. 

The library would need to change to a different data type like DateTime2.

**Comment by xantari** [comment]
@epignosisx I created a branch based off of the Microsoft.Extensions.Caching.SqlServer library that supports this: https://github.com/xantari/Microsoft.Extensions.Caching.SqlServerInMemory

**Comment by xantari** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/17640

**Comment by anurse** [comment]
Duplicate of https://github.com/dotnet/extensions/issues/741
