### ISSUE TITLE
Dependency injection needs to support InitializeAsync()

### ISSUE THREAD

**Issue by Kaelum** [dotnet/extensions#2106]
If the injection object needs to access `async` methods there are only 2 options, 1) Use the `IAsyncInitialization` pattern presented by Stephen Cleary in [Async OOP 2: Constructors](https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html), or 2) Use the `Task.Run(() => instance.methodAsync()).Result` method of access, neither of which is ideal.

There is a discussion to create async constructors ([Discussion: async constructors](https://github.com/dotnet/csharplang/issues/419)), but that support is a long way off, if it ever materializes.  So, I am proposing a variation Stephen Cleary's `IAsyncInitialization` interface where the ASP.NET injector will check the class for an implementation of `IInitializeAsync` (below) and execute the `InitializeAsync()` method of the class:

```cs
/// <summary>
/// Marks a type as requiring asynchronous initialization.
/// </summary>
public interface IInitializeAsync
{
    /// <summary>
    /// Asynchronously initialize the instance.
    /// </summary>
    Task InitializeAsync();
}
```

Implementing this would allow the constructor to remain lightweight, while still allowing dependencies to be injected.  By allowing the `InitializeAsync()` method to perform the heavier weight initialization, with better exception logging/handling.

**Comment by davidfowl** [comment]
The dependency injection symposium 2019... just kidding, right here is fine. Just ping the authors of said framework https://github.com/aspnet/Extensions/tree/master/src/DependencyInjection#dependencyinjection

**Comment by udlose** [comment]
has this been added now for .NET 7?

**Comment by BrennanConroy** [comment]
No. Follow up on issues like https://github.com/dotnet/runtime/issues/65656
