### ISSUE TITLE
Add logging async method

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/extensions#2141]
### Problem
im use sentry logger. sentry Problems with a large number of requests.

### Solution
add Ilogger async method. add log to queue and background insert log, like nlogger async warpper.

**Comment by anurse** [comment]
Making logging async would be very disruptive as it would mean **every** code path that calls logging would have to be async. It also means that the caller is likely *blocked* (even if via `await`) waiting for the log message to be sent.

The recommendation here is to use background worker. This is even what the console logger does (even though it's all in-process). Any logger that does heavy I/O should consider adopting this pattern:

1. The logger is synchronous and just adds messages to an internal buffer
1. A background `IHostedService` runs and collects messages from this buffer, flushing them to the I/O sink (remote service, console, file, etc.)
