### ISSUE TITLE
Missing symbols for microsoft.extensions.commandlineutils.dll 1.1.1

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/extensions#2145]
[Symbol check fails](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958010/) in VS insertion of Live Share extension. 

In particular it complains that there are no symbols for `microsoft.extensions.commandlineutils.dll` v.1.1.1.

If you publish portable pbds, please also publish Windows pdbs.

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/extensions/issues/2499
