### ISSUE TITLE
Custom aspnet xunit extensions should be converged with XUnitExtensions in arcade

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/extensions#2150]
I just noticed that aspnetcore has xunitextensions for various use-cases: https://github.com/aspnet/Extensions/tree/master/src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit. We do have the same in corefx and partner repositories: https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.XUnitExtensions

We should converge both and remove the duplication here.

**Comment by rynowak** [comment]
That would be cool. Have you done any analysis about the differences/commonalities between what's here and in arcade?

**Comment by ViktorHofer** [comment]
Yeah I did a bit of digging. https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/SkippedTestCase.cs is a 1:1 duplicate. Everything else should be beneficial for you but it seems you are using a slightly different attribute schema. You would probably need to change all your test data attributes to what we use in corefx/coreclr. Everything should be there with some tweaks. That said I think the migration is a ton of work given the amount of test code.

**Comment by anurse** [comment]
With dotnet/extensions mostly moving to dotnet/runtime, I think we planned to do this (and maybe did it already?) there. Closing this.

**Comment by ericstj** [comment]
@joperezr  -- @adamsitnik brought this up today.  With more projects added to extensions it may be relevant again.  There is a divergence between the infra we use in runtime and that which is used in extensions and aspnetcore.  Do you see value in converging them to have a consistent set of tools used for building tests in our dotnet product repos?

**Comment by adamsitnik** [comment]
cc @ViktorHofer who suggested in an offline conversation that we should aim for moving to xUnit v3 which provides plenty of these features natively

**Comment by stephentoub** [comment]
> cc [@ViktorHofer](https://github.com/ViktorHofer) who suggested in an offline conversation that we should aim for moving to xUnit v3 which provides plenty of these features natively

Longer-term, absolutely. Short term, that is likely a non-trivial task; we should not block on that.
