### ISSUE TITLE
Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync is lacking ConfigureAwait(false)

### ISSUE THREAD

**Issue by ghelyar** [dotnet/extensions#2252]
https://github.com/aspnet/Extensions/blob/master/src/Caching/Abstractions/src/MemoryCacheExtensions.cs#L119

This causes deadlocks under certain scenarios (e.g. asp.net context, when an outer awaitable is blocking synchronously)

**Comment by ladeak** [comment]
Any updates on this issue?
