### ISSUE TITLE
Which exception should I throw when the expected required configuration value is not present

### ISSUE THREAD

**Issue by advapiIT** [dotnet/extensions#2360]
Which exception should I throw when I've a missing configuration value that's required? 
Using the System.Configuration I was throwing [ConfigurationException  ](https://docs.microsoft.com/it-it/dotnet/api/system.configuration.configurationexception?view=netframework-4.8
)

Thanks

**Comment by anurse** [comment]
We don't have a specific recommendation. It's up to you :).
