### ISSUE TITLE
Suggestion: Refactor providers so they aren't forcefully pulled into Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by highlyunavailable** [dotnet/extensions#2366]
### Is your feature request related to a problem? Please describe.

I'm am trying to package up my netcoreapp with /p:PublishTrimmed=true and all of the Microsoft.Extensions.*.dll files referenced by Microsoft.Extensions.Hosting are included even when trimming. I don't call `CreateDefaultBuilder` anywhere nor do I reference things like file config providers or the EventLog logger anywhere in my own `HostBuilder`.

### Describe the solution you'd like

I'd like the HostBuilder to be able to constructed in such a way that it doesn't pull in every possible package so that I can trim out unused files properly with `PublishTrimmed`. Perhaps convenience methods packaged up in a different package (a `Microsoft.Extensions.Hosting.Extensions` if you will) that has more dependencies, allowing the base package to be lighter weight.

### Describe alternatives you've considered

1. Build my own Hosting package without the `Host.cs` file, because I can't seem to find a way to tell the trimmer to explicitly ignore a package or to trim methods that are never called. 

2.  I could submit a request for the `PublishTrimmed` switch to perform call analysis so it drops methods and thus dlls that are not called but that seems like a very difficult request to service.

**Comment by Pilchie** [comment]
@rynowak you might be interested in this...

**Comment by rynowak** [comment]
@highlyunavailable - `CreateDefaultBuilder` is the method that applies a bunch of default settings. It sounds like you really want to customize the settings, which you can do by starting with `new HostBuilder()`.

**Comment by highlyunavailable** [comment]
Yes, I get that. What I'm saying is `CreateDefaultBuilder` references a bunch of extra libraries like EventLog logging, which pulls in a TON of extra DLLs to the application package publish folder, which I can't seem to easily remove.

The problem is that if I decide to customize by making my own `HostBuilder`, I can't remove the _actual DLLs_ from the app directory with `PublishTrimmed`, which bloats deployment size.

What I expect is that I can trim out all providers I'm not using by using the `PublishTrimmed` switch, however since the `CreateDefaultBuilder` method calls the Add* methods, the DLLs cannot be trimmed due to being referenced, even though `CreateDefaultBuilder` is never called by my code. See the code at: https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/Host.cs#L56-L123 - notice all the Add* calls, e.g. `AddEventSourceLogger`, `AddEnvironmentVariables`, etc.

Reproduction steps:

Create a directory to put a project in.
Change to that directory in a command prompt.
Run `dotnet new console`
Run `dotnet add package Microsoft.Extensions.Hosting`
Run `dotnet restore` if needed.
Open the Program.cs file.
At the top, add `using Microsoft.Extensions.Hosting;` and in the Main method, add `var hostBuilder = new HostBuilder();`
Run `dotnet publish -r win-x64 -c Release /p:PublishTrimmed=true` and check the size and contents of the `bin\Release\netcoreapp3.0\win-x64\publish` folder. 

Actual behavior:

Simply adding the package caused `Microsoft.Extensions.Logging.EventSource.dll`, `Microsoft.Extensions.Configuration.Json.dll`, etc. to be included in the publish, despite not being referenced by anything in the main program DLL.

Expected behavior:

Unused providers are not referenced and are thus dropped from the final published result when using `/p:PublishTrimmed=true`.

**Comment by highlyunavailable** [comment]
I guess another way to put what I'm trying to say: Please stop referencing every other provider from the Hosting package, only reference the abstractions and let the developer pull in what they need from the provider packages.

**Comment by rynowak** [comment]
Sorry, I misread one of your original statements, which why I suggested `new HostBuilder()`. 

I'm afraid you're going to see this behavior for now because the linker doesn't do trimming within ASP.NET Core's assemblies. The linker uses conservative settings for ASP.NET Core right now because it doesn't know how to deal with DI. That's something we're working on for 5.0. We expect to able to fix this in the future via the linker. 

If you really want to see this work, you can experiment with using the XML descriptor format to remove `Host.CreateDefaultBuilder`. https://github.com/mono/linker/blob/master/src/linker/README.md#syntax-of-xml-descriptor

I would expect it to look something like (untested):
```xml
<linker>
	<assembly fullname="Microsoft.Extensions.Hosting">
		<type fullname="Microsoft.Extensions.Hosting.Host">
			<method signature="Microsoft.Extensions.Hosting.IHostBuilder CreateDefaultBuilder()" preserve="nothing" />
		</type>
	</assembly>
</linker>
```

**Comment by rynowak** [comment]
@sbomer - do you have any ideas about how this could be worked around? Is it possible to tweak the msbuild to forcibly exclude assemblies?

**Comment by anurse** [comment]
This was an intentional decision because there are only a couple packages that aren't already necessary for the core. It's possible we could think about revisiting this decision but it would be quite breaking.
