### ISSUE TITLE
Flush on shutdown

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/extensions#2395]
Other logging frameworks have different ways of telling the framework that the application is about to shut down. This is great for batching and/or async loggers since it will give them a chance to flush their buffered log message.

Example from Serilog:

```csharp
Log.CloseAndFlush();
```

Example from NLog:

```csharp
LogManager.Shutdown();
```

I cannot seem to find a similar feature of Microsoft.Extensions.Logging. I know that providers indirectly implement `IDisposable` but `Dispose` doesn't seem to be consistently called on shutdown.

Is there any way of detecting that an application is about to shut down or would it be possible to implement support for this in Microsoft.Extensions.Logging?

**Comment by davidfowl** [comment]
There's no explicit shutdown since the logger is owned by the host. An ILoggerProvider implementing Dispose is usually how we communicate the same behavior.

**Comment by ThomasArdal** [comment]
The problem is that `Dispose` is not called. If I create a new console app, add my logger to `ServiceCollection` and let the program terminate without errors, no call to `Dispose` is ever made.

**Comment by davidfowl** [comment]
Call dispose then?

**Comment by ThomasArdal** [comment]
That's a good point 😂 I guess this would be the way to go?

```csharp
var services = new ServiceCollection();
services.AddLogging(logging => logging.AddBlaBla(...));
var serviceProvider = services.BuildServiceProvider();
var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
var logger = loggerFactory.CreateLogger("mylogger");
// Do some logging
serviceProvider.Dispose();
```

**Comment by davidfowl** [comment]
Yep 😄 !
