### ISSUE TITLE
IFileProvider needs a way to Unwatch paths

### ISSUE THREAD

**Issue by davidfowl** [dotnet/extensions#2419]
IFileProvider.Watch is a memory leak as there's no way to unwatch until either the IFileProvider is disposed/finalized or until the change notification fires.

I can think of a couple of ways to do this:
- Change the implementations to return a disposable IChangeToken. It requires the caller to cast to `IDisposable` to work (this is non-breaking)
- Add a new interface member Unwatch (a little breaking)
- Change the return value of Watch to something that can be disposed (most breaking)

**Comment by gfoidl** [comment]
> Add a new interface member Unwatch (a little breaking)

Would this be possible with C# 8's default interface implementations?

**Comment by davidfowl** [comment]
@gfoidl Sure, it wouldn't help the netstandard 2.0 version but maybe that's fine.
