### ISSUE TITLE
Why doesn't LoggerExtensions accept FormattableString?

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/extensions#2485]
I wonder why LoggerExtensions class do not have overloads accepting FormattableString. Having them makes it easy to use interpolated strings.

**Comment by nvmkpk** [comment]
OK. Why no overloads accepting FormattableString then?

**Comment by pharring** [comment]
You might be tempted to add the following set of extension methods:

```csharp
    public static class ILoggerExtensions
    {
        public static void Log(this ILogger logger, LogLevel level, FormattableString formattableString)
            => logger.Log(level, formattableString.Format, formattableString.GetArguments());

        public static void LogTrace(this ILogger logger, FormattableString formattableString) => logger.Log(LogLevel.Trace, formattableString);
        public static void LogDebug(this ILogger logger, FormattableString formattableString) => logger.Log(LogLevel.Debug, formattableString);
        public static void LogInformation(this ILogger logger, FormattableString formattableString) => logger.Log(LogLevel.Information, formattableString);
        public static void LogWarning(this ILogger logger, FormattableString formattableString) => logger.Log(LogLevel.Warning, formattableString);
        public static void LogError(this ILogger logger, FormattableString formattableString) => logger.Log(LogLevel.Error, formattableString);
        public static void LogCritical(this ILogger logger, FormattableString formattableString) => logger.Log(LogLevel.Critical, formattableString);
    }
```

and then use it like this:
```
 _logger.LogInformation($"User {username} logged in");
```
where `username` is an in-scope variable.

However, this doesn't quite work the same as the current syntax because the placeholder `{username}` gets replaced with `{0}`. The compiler does what's necessary to hand the string over to `string.Format` and the original placeholder text is dropped.

**Comment by anurse** [comment]
As @pharring indicated, supporting `FormattableString` would be misleading here since it doesn't really behave the way we want it to. The placeholder _names_ need to be preserved so they can generate key-value pairs for structured logging.
