### ISSUE TITLE
RedisCache should should GetOrSet method

### ISSUE THREAD

**Issue by TangMonk** [dotnet/extensions#2541]

**Comment by anurse** [comment]
@TangMonk can you provide the full API method signatures you want added and to which type you want to propose adding them to? Also, please include the expected behavior of the proposed new APIs.

**Comment by TangMonk** [comment]
@anurse just like that:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.getorcreate?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Caching_Memory_CacheExtensions_GetOrCreate__1_Microsoft_Extensions_Caching_Memory_IMemoryCache_System_Object_System_Func_Microsoft_Extensions_Caching_Memory_ICacheEntry___0__
