### ISSUE TITLE
Using real objects for configuration, not arbitary and complex magic strings

### ISSUE THREAD

**Issue by mgwalm** [dotnet/extensions#2547]
Proposal:
Instead of using arbitrarily and complex strings to get elements from your configuration, I propose to use objects, after all we are using an OO language.

I thought we were gradually removing these types of magic strings from the framework.

To achieve this, base one’s configuration on POCO style simple objects. They can then be used to configure / build the runtime. They dont need to be POCO objects, they could also be the underlying objects that .NET uses, eg, BasicHttpBinding. Though, in this example, this means one's configuration is dependent on System.ServiceModel, which might not be ideal. If one uses simple POCO objects this dependency is removed until one needs to create the Binding in code that is alread dependent on System.ServiceModel..

Thus, all .NET configuration sections can easily be converted to these POCO objects. Thus adding the configuration of all aspects of .NET.

To achieve this one needs:

. POCO simple objects to represent the configuration required of the .NET runtime.
. An appsettings.json file that is structured in a way that it matches the POCO objects.
. Some implementations of ConfigurationProvider, IConfigurationSource to process the json file.
. A DynamicObject to cast the loaded json configuration to the POCO objects.
. Then one can have code to configure the application, eg, in your inplementation of ClientBase<IWhateverServcieContract>.
[Proposal.docx](https://github.com/aspnet/Extensions/files/3754225/Proposal.docx)

The attached file has some code samples.

**Comment by davidfowl** [comment]
Why does this need to be coupled to the configuration system? We build pocos on top of the low level name value pairs using options all the time. What do we gain by smushing those layers together?

**Comment by mgwalm** [comment]
Tried and tested code that everyone can depend on, and not have to re-write again and again.

**Comment by mgwalm** [comment]
Also, it provides a base of replacing all app.config sections across the entier code base.

**Comment by davidfowl** [comment]
Sorry that's not a convincing reason to change the existing API.

**Comment by davidfowl** [comment]
> Also, it provides a base of replacing all app.config sections across the entier code base.

Is this the goal? To replace app configuration strongly typed configuration? Why not do that specificially instead of trying to bake it into a configuration model that wasn't designed for that?

**Comment by mgwalm** [comment]
Also, it removes the dependency on complex and arbitary string like "CommonKey1:CommonKey2:CommonKey3:CommonKey4".
If you chnage the POCO structure you still neeed to changer the json layout, but you dont have to find all occurances to magic strings across you whole code base.

**Comment by mgwalm** [comment]
The goal is to replace all config sections with simple objects. Currently most of the framework has ignored all config file initialization because it has been conveniently ignored (AFAIK).

It doesnt need to be a part of the configuration extensions, but what better place to put it to be available across all the rest of the.NET frasmework.

**Comment by anurse** [comment]
Closing as we don't plan to do this. The layering here is very intentional. Configuration works with strings and Options and Configuration Binders allow converting those to objects.
