### ISSUE TITLE
IConfiguration.GetChildren() time grows exponentially based on number of keys to read

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/extensions#2550]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/776074/iconfigurationgetchildren-time-grows-exponentially.html)._

---
In the process of taking legacy applications and getting them to a state where they will run in a cloud environment, we ended up having a configuration file with ~25,000 unique keys.  (Multi-tenant application with thousands of tenants each having different configuration... it gets a bit big).  We ran into an issue where reading through all of the configuration keys was taking a long time.  While investigating the issue I narrowed it down to IConfiguration.GetChildren().

After doing some testing on key volume to time, I can report the following:

Reading ~1000 keys took about 0.1s
Reading ~2000 keys took about 0.23s
Reading ~4000 keys took about 1s
Reading ~25000 keys took about 40s

We are already changing the way we store/read configuration, but I felt it worth reporting since the key to time ratio is not linear.

---
#### Roi Chen [MSFT] on 10/15/2019, 08:25 PM: 

<p>Please help to reassign if the current area path is not proper. Thanks.</p>

#### Visual Studio Feedback System on 10/21/2019, 04:05 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by AMalininHere** [comment]
It seems that this issue is partially related to the linear representation of data in the [`ConfigurationProvider`](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config/src/ConfigurationProvider.cs). I think that tree-based implementation of [`IConfigurationProvider`](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Abstractions/src/IConfigurationProvider.cs) should be better. I could try to make a tree-based implementation to compare it with the current implementation. After that I could create an issue with details of the idea.

**Comment by brandondahler** [comment]
@AMalininHere were you able to reproduce the issue?

My basic test is seeing close to linear (probably n log n) performance of GetChildren() -- 40s for 25,000 keys is a really long time given the context.  There has to be something else going on beyond what was reported.

``` diff
--- a/src/Configuration/Config/test/ConfigurationTest.cs
+++ b/src/Configuration/Config/test/ConfigurationTest.cs
@@ -332,6 +332,29 @@ public IConfigurationProvider Build(IConfigurationBuilder builder)
             }
         }

+        [Fact]
+        public void GetChildrenPerformanceTest()
+        {
+            var dict = new Dictionary<string, string>();
+            var random = new Random();
+
+            for (int x = 0; x < 25000; ++x)
+            {
+                dict[$"abc.123." + random.Next().ToString()] = "foo";
+            }
+
+            var memConfig = new TestMemorySourceProvider(dict);
+
+            var config = new ConfigurationBuilder()
+                .Add(memConfig)
+                .Build();
+
+
+            _ = config.GetChildren()
+                .ToArray();
+
+        }
+
         [Fact]
         public void SettingValueUpdatesAllConfigurationProviders()
         {

```
