### ISSUE TITLE
3.0 IDistributedCache with RedisCache inconsistent behavior on Azure

### ISSUE THREAD

**Issue by SimonOrdo** [dotnet/extensions#2581]
I have an Azure web app using Redis Cache as the store for my IDistributedCache implementation.

1. Code worked fine in 2.2 Framework build both locally and on Azure.  I invoked the distributed cache like so:

```
           services.AddDistributedRedisCache(options =>
            {
                options.Configuration = ConnectionString;
                options.InstanceName = Env.EnvironmentName;
            });
```
2. After switching to 3.0, I updated the distributed cache configuration as such:

```
            services.AddStackExchangeRedisCache(options =>
            {
                options.Configuration = ConnectionString;
                options.InstanceName = Env.EnvironmentName;
            });
```

This works fine locally, but fails erratically in Azure with the following:

> StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 7515ms elapsed, timeout is 5000ms), inst: 0, qu: 2, qs: 20, aw: True, bw: Inactive, rs: ReadAsync, ws: Writing, in: 64, serverEndpoint: Unspecified/XXXX.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: YYYZZZZXXX, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=21,Free=32746,Min=4,Max=32767), v: 2.0.593.37019 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
>    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
>    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
>    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.RefreshAsync(String key, CancellationToken token)
>    at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Session.SessionMiddleware: Error: Error closing the session.

3. I still have code in Production that uses the previous 2.2 method and it works without issue.

4. These errors creep up for anything involving IDIstributedCache (including distributed cache tag helpers, obviously).

Could this be a configuration issue?  ALthough, I'm not sure why it would be more prevalent in Azure and not locally.

Any info on how to further trouble shoot the issue or change the configuration to try and tune the settings is appreciated.  Thanks!

**Comment by anurse** [comment]
It seems like there are frequent network interruptions/timeouts. Adding retries to the caching logic may help here. I filed https://github.com/dotnet/extensions/issues/2898 to track that work.

I'm going to close this issue and we'll use the linked issue to track timeout issues in general.
