### ISSUE TITLE
IMemoryCache Monitoring

### ISSUE THREAD

**Issue by Avivskie** [dotnet/extensions#2598]
Monitoring of changed key
Register on change occurred for item Updated/Added, either for specific key (updated) for the entire cache (Added).

**Comment by Tratcher** [comment]
IMemoryCache has notifications for when a specific entry is removed, but not globally when any entry with the given key is added or removed.

See PostEvictionCallbacks:
https://github.com/aspnet/Extensions/blob/e41d90f66109f3387063f412a0ec61c85f8ecbdb/src/Caching/Abstractions/src/MemoryCacheEntryOptions.cs#L89

**Comment by anurse** [comment]
Closing as @Tratcher's response is correct and we don't plan to add a global event here.
