### ISSUE TITLE
IMemoryCache Dependencies between cached items

### ISSUE THREAD

**Issue by Avivskie** [dotnet/extensions#2599]
Sometimes i need to have dependencies from one item in the cache to another.
for example - if Item A is depended on Item B - then i would like to have different behavior:
1. Allow deletion of A only but not of B
2. Allow deletion of B only but not of A
3. Do not allow deletion at all
4. Delete both

**Comment by anurse** [comment]
@JunTaoLuo (you might know) doesn't MemoryCache already have some notion of dependencies between items? I thought that was what the slightly-odd `IDisposable`-based API was for :).

**Comment by JunTaoLuo** [comment]
Yes that behaviour is documented at https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#cache-dependencies
