### ISSUE TITLE
Microsoft.Extensions.Hosting.Composition

### ISSUE THREAD

**Issue by ibebbs** [dotnet/extensions#2610]
I've written a small library for performing runtime-composition of non-referenced assemblies into the generic host which I'm using in a couple of projects. I think it's rather useful so was about to push it to nuget but thought I'd add some info here first to see if it's something people might be interested in merging into this repository.

My repo can found [here](https://github.com/ibebbs/Microsoft.Extensions.Hosting.Composition), and it contains a fairly comprehensive [readme](https://github.com/ibebbs/Microsoft.Extensions.Hosting.Composition/blob/master/ReadMe.md) on how the library is used.

### Describe the solution you'd like
A discussion around whether it is desirable to merge my repo into this one.

### Describe alternatives you've considered
I looked into MEF (via [System.Composition](https://www.nuget.org/packages/System.Composition)) but it seemed a bit heavyweight for my requirements and there wasn't any information about how it might be integrated into the Generic Host.

**Comment by Tratcher** [comment]
This looks similar to the IHostingStartup functionality we have in WebHost.
https://github.com/aspnet/Extensions/issues/806
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-3.0

**Comment by anurse** [comment]
I don't think this is something we'd merge directly into our repo right now, but it sounds like a good community project. I'd suggest taking a look at the docs @Tratcher posted to see how this overlaps with `IHostingStartup` though.

I'd also suggest not using the `Microsoft.` name as you won't be able to publish to NuGet.org with that prefix :). Often we've seen people do `[Some Company, Organization, etc. Name].Extensions` as a prefix.

Moving this to discussions as I don't think we intend to take action on adding this kind of component right now. That can certainly change if there's some user interest!

**Comment by ibebbs** [comment]
Hi @Tratcher, thanks for the links; yes the two concepts do look similar. TBH, I'm quite pleased that I arrived at a solution for the generic host ostensibly quite similar to the one you have provided for the web host. Are there any plans to make your solution more generic and available to the generic host?

I haven't looked a the code underlying IHostingStartup but, just from a consumption point of view, there do seem to be a few differences. Most notable of these differences is the ability of the `.UseComposition()` to load multiple instances (and versions!) of a module with different configurations. That said, I do like the simplicity of specifying the assemblies to load as a single configuration string; I might look to introduce that capability as an optional alternative for simplifying deployment.

Furthermore, I also feel that specfically enabling this scenario (via a call to `.UseComposition()` perhaps with configuration set from the environment variable) is a little more transparent to developers who might otherwise not understand why additional functionality is "magically" being composed into their webhost.

Anyway, thanks for the feedback. Obviously until something like IHostingStartup is available for the generic host, I'll be continuing to use and develop this composition library.

**Comment by ibebbs** [comment]
Just an FYI: As suggested I have renamed my repository to ["Cogenity.Extensions.Hosting.Composition"](https://github.com/ibebbs/Cogenity.Extensions.Hosting.Composition)

**Comment by ibebbs** [comment]
Interestingly I just found a very pertinent quote [here](https://github.com/aspnet/Hosting/issues/1163):

>Startup

> A note about Startup classes - While the concept of a Startup class is extremely useful, it's also very problematic as it requires
> 2 dependency injection containers to be built during the startup cycle. This causes issues where singletons aren't the same when activating the
> Startup class and when activating an IHostedService. This is because Startup.ConfigureServices lets the user add more services but also lets them
> get at hosting services in the Startup.ctor. So far, we've chosen to abandon startup as part of the generic host work but it would be possible to add back
> at any point in the future if we figure out a cleaner way to do it.

**Comment by Tratcher** [comment]
@ibebbs https://github.com/aspnet/Announcements/issues/353 is how that was addressed for Startup on generic host.

**Comment by ibebbs** [comment]
@Tratcher , thanks for the link. I've read it thoroughly (and the associated doc) but can't for the life of me work out whether this means the generic host _does_ have runtime-composition functionality. As far as I can see, this link is just about types which can be injected into various Startup types.

I'm guessing it does not and the above link is specifically about the quote I posted above which I - perhaps incorrectly - assumed to be related to `HostingStartup` related functionality.

**Comment by Tratcher** [comment]
Right, that link was just about where we ended up on the DI issues.

Generic host does not _yet_ have a runtime composition model. #806 tracks the proposed work to add one.

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
