### ISSUE TITLE
Method not found: Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Azure.Functions.Extensions.DependencyInjection.IFunctionsHostBuilder.get_Services()

### ISSUE THREAD

**Issue by krishnasingh1818** [dotnet/extensions#2611]
### Describe the bug
Microsoft.Extensions.Caching.StackExchangeRedis 3.0.0  not working azure functions 2 when using startup.cs for azure function dependency injection.

### To Reproduce
1. use Microsoft.Extensions.Caching.StackExchangeRedis 3.0.0 in azure function 2 project gives run time error of missing method

### Expected behavior
It should run fine with api project or function project

### Screenshots
![image](https://user-images.githubusercontent.com/10679463/68417232-a2035300-015b-11ea-8fb9-31765a325cfa.png)

### Additional context
Include the output of `dotnet --info`

**Comment by krishnasingh1818** [comment]
[https://github.com/krishnasingh1818/azurefunction2withmsftstackexchnage](url)

**Comment by anurse** [comment]
You're mixing 2.x and 3.x packages here:

> ```xml
>     <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
> ```

This package brings in `Microsoft.Extensions.DependencyInjection.Abstractions` version 2.2.0

But then you have

> ```xml
>    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="3.0.0" />
> ```

Which expects `Microsoft.Extensions.DependencyInjection.Abstractions` version `3.0.0`.

Crossing major versions like this isn't supported and will cause issues like this. You need to either:

* Update to an Azure Functions SDK that uses 3.x (preferably 3.1) and use all 3.1 versions of packages
* Downgrade your reference to Microsoft.Extensions.Caching.StackExchangeRedis to `2.2.0` so they are aligned
