### ISSUE TITLE
Make a YAML FileConfigurationProvider that ships with AspNetCore

### ISSUE THREAD

**Issue by jeff-pang** [dotnet/extensions#2659]
YAML is gaining popularity especially outside the .Net ecosystem. Currently for .Net to use the YAML format, there are 2 options; Write your own YAML provider or to take a 3rd party dependency. 

Parsing YAML yourself may be an overkill, so that leaves us with taking 3rd party dependency, not a big issue but there are potential downsides, such as maintenance and much more at risk of obsolescence compared to an officially supported provider.

Since AspNetCore already provides support for some of the most popular formats e.g JSON, XML, INI, in my opinion, it would make sense to also support YAML out of the box.

**Comment by davidfowl** [comment]
> Parsing YAML yourself may be an overkill, so that leaves us with taking 3rd party dependency, not a big issue but there are potential downsides, such as maintenance and much more at risk of obsolescence compared to an officially supported provider.

That the case for all 3rd party things. Fortunately we care alot about a thriving ecosystem and don't want to be the single software provider for extensible things. There are several yaml configuration providers on nuget.

**Comment by gfoidl** [comment]
See also https://github.com/aspnet/Extensions/issues/1904 (and the there linked issues).

**Comment by jeff-pang** [comment]
> That the case for all 3rd party things. Fortunately we care alot about a thriving ecosystem and don't want to be the single software provider for extensible things. There are several yaml configuration providers on nuget that I would recommend you look at before deciding it needs to be in the box.

I somewhat agree but on the other hand what is different about JSON that it got adopted OOTB but not YAML? IMHO, .Net was very late to the game to adopt JSON OOTB, hopefully we don't have to wait as long for YAML support

**Comment by buzzers** [comment]
I recently used AspNetCore and used the yaml format as a profile file. I looked through the documentation and found that the built-in yaml configuration provider was not available until 3.1. 
I think it is necessary to provide a built-in yaml configuration parser now in yaml widely used. I'm glad to see this issue in the milestone. 
I would like to know whether this repo accept the contribution code and whether a third-party library can be added, or if the yaml parser must be included in the submitted code.
@davidfowl

**Comment by anurse** [comment]
We don't plan to support YAML in the box right now. This is something we'd really want to encourage the third-party community to work towards. A built-in YAML provider would also require a built-in YAML parser (from dotnet/runtime) which is also very costly to build (and there are already great parsers out there). We also just don't have the resources to prioritize this work over the other things on our backlog when there's a clear extensibility point for the community here.

This is a prime opportunity for the open-source ecosystem, and we want to encourage that approach for this.
