### ISSUE TITLE
Service container dispose order not correct in special corner cases

### ISSUE THREAD

**Issue by peter-perot** [dotnet/extensions#2660]
### Describe the bug
The bug is related to issue https://github.com/aspnet/Extensions/issues/444 (and https://github.com/aspnet/Extensions/issues/694 and https://github.com/aspnet/DependencyInjection/pull/661).

### To Reproduce
Used version is `Microsoft.Extensions.DependencyInjection 2.2.0`.

Source code to reproduce:

```csharp
using System;
using Microsoft.Extensions.DependencyInjection;

namespace ExampleProject
{
  public static class Example
  {
    public static void Execute()
    {
      var sc = new ServiceCollection();

      sc.AddScoped<MyDisposable>();
      sc.AddScoped<AnotherDisposable>();

      sc.AddScoped<IMyIntf1>(sp => sp.GetRequiredService<MyDisposable>());
      sc.AddScoped<IMyIntf2>(sp => sp.GetRequiredService<MyDisposable>());

      var provider = sc.BuildServiceProvider();

      using (var scope = provider.CreateScope())
      {
        scope.ServiceProvider.GetRequiredService<IMyIntf1>();
        scope.ServiceProvider.GetRequiredService<AnotherDisposable>();

        // !!!! uncommenting this line causes the bug
        //scope.ServiceProvider.GetRequiredService<IMyIntf2>();
      }

      provider.Dispose();
    }

    private interface IMyIntf1
    {
    }

    private interface IMyIntf2
    {
    }

    private class MyDisposable : IDisposable, IMyIntf1, IMyIntf2
    {
      private bool isDisposed;

      public void DoSomeStuff()
        => Console.WriteLine(this.isDisposed
          ? "    Cannot execute MyDisposable.DoSomeStuffs since instance is already disposed."
          : "    Did some stuff in MyDisposable.");

      public void Dispose()
      {
        this.isDisposed = true;
        Console.WriteLine("MyDisposable disposed.");
      }
    }

    private class AnotherDisposable : IDisposable
    {
      private readonly MyDisposable myDisposable;

      public AnotherDisposable(MyDisposable myDisposable)
        => this.myDisposable = myDisposable;

      public void Dispose()
      {
        Console.WriteLine("Starting to dispose AnotherDisposable...");
        this.myDisposable.DoSomeStuff();
        Console.WriteLine("AnotherDisposable disposed.");
      }
    }
  }
}
```

Running this code works fine, as long as the code marked with _"!!!!"_ is commented out. The output is:

```text
Starting to dispose AnotherDisposable...
    Did some stuff in MyDisposable.
AnotherDisposable disposed.
MyDisposable disposed.
MyDisposable disposed.
```

This is the correct behavior, even with the double-disposal of `MyDisposable`. This issue has already been discussed and is not considered a bug, since disposable objects must deal with the case when `Dispose` is called multiple times.

Now uncomment the code marked with _"!!!!"_ and run again. Output:
 ```text
MyDisposable disposed.
Starting to dispose AnotherDisposable...
    Cannot execute MyDisposable.DoSomeStuffs since instance is already disposed.
AnotherDisposable disposed.
MyDisposable disposed.
MyDisposable disposed.
```

### Expected behavior
Disposing `MyDisposable` should occur _after_ disposing `AnotherDisposable`. Ideally, double-disposal is suppressed at all. Output should look like this:

 ```text
Starting to dispose AnotherDisposable...
    Did some stuff in MyDisposable.
AnotherDisposable disposed.
MyDisposable disposed.
```

### Remarks
The issue remains the same when `AddSingleton` is used instead of `AddScope`, and the services are resolved directly from the container (instead of the scope); then, when the container is disposed the same wrong dispose order can be observed.

**Comment by anurse** [comment]
This behavior looks to be completely by design. Disposable is happening in reverse instantiation order. You only have a *single instance* of `MyDisposable` registered, so when it's the last thing instantiated (i.e. when you have your `IMyIntf2` line uncommented) it is disposed first.
