### ISSUE TITLE
StringValues casting undefined

### ISSUE THREAD

**Issue by breyed** [dotnet/extensions#2662]
Implicitly casting various values of a `StringValues` object leads to undefined results.

``` c#
string fromList = new StringValues("a","b");
string fromEmpty = StringValues.Empty;
```

Will `fromList` be comma-separated, newline-separated, or something else?

Will `fromEmpty` be an empty string? Will it be null? Something else?

The results should be well defined. `implicit operator StringValues(string value)` needs an XML comment so that the semantics appear in the metadata-generated class definition in Visual Studio when you hit F12 on `StringValues`. Likely, other members need docs, too. Currently, `StringValues` has a summary, but that's all.

**Comment by Marusyk** [comment]
Can I take this one?

**Comment by benbhall** [comment]
I think it is `public static implicit operator string(StringValues values)` that needs the XML to address the particular issue demonstrated.

I've had a go at that and also added XML to everything else. Will pop a PR in.
