### ISSUE TITLE
OptionsMonitor OnChange is triggered even though its TOptions did not change

### ISSUE THREAD

**Issue by mrmartan** [dotnet/extensions#2671]
### Describe the bug
The documentation of `OnChange<TOptions>(this IOptionsMonitor<TOptions> monitor, Action<TOptions> listener)` states "Registers a listener to be called whenever TOptions changes." but the listener is invoked on any change to the underlying configuration source, even in the case of the values `TOptions` is bound to not changing.

### To Reproduce
1. Using version '3.0.0' of package 'Microsoft.Extensions.Options.ConfigurationExtensions'
2. Consider this code:
```csharp
services.Configure<MyOptions1>(configuration.GetSection(nameof(MyOptions1)));
services.Configure<MyOptions2>(configuration.GetSection(nameof(MyOptions2)));

services.AddSingleton<ISomeService>(sp =>
{
    var myOptions1Monitor = sp.GetRequiredService<IOptionsMonitor<MyOptions1>>();
    myOptions1Monitor.OnChange(o =>
    {
        someAction(o);
    });

   // ...
)
```
and appsettings.json:
```
  "MyOptions1": {
    "Value1": "zzz"
  },
  "MyOptions2": {
    "Value1": "xxx"
  }
```
`someAction` gets invoked even when only `MyOptions2:Value1` changes.

### Expected behavior
Registered listeners are invoked only when values of their associated `TOptions` instances change.

**Comment by HaoK** [comment]
The documentation is not clear in this case, the listener is invoked whenever any `IOptionsChangeTokenSource`'s change token fires, there's nothing which prevents tokens from being fired even if the end result of the change firing doesn't change the options instance.

**Comment by mrmartan** [comment]
Oh well, that's unfortunate. Is there a way to do it (without me storing the prevouis values somewhere first)?

First suggestion that comes to mind, for `TOptions : IEquatable<TOptions>` compare previous and current value and fire `OnChange` only when they differ.

See, in my case the `someAction` method reconfigures policies. `Polly` policies and since those are immutable they are recreated. And some of them are stateful, circuit breakers in this case. That's a problem because when any configuration changes, let's say some completely unrelated feature switch, the states of the circuit breakers reset.

**Comment by mrmartan** [comment]
So this might not be a bug, and it might have been answered, but it is a shame you are cloding it. In large distributed systems connected to multiple configuration sources (e.g. Kubernetes, Hashicorp Consul/Vault, feature toggling, SQL DB) as well as the example above I can imagine this leading to unexpected (waves) of reconfiguration when relying on `IOptionsMonitor` instances and then building custom to layers to deal with it while, it seems to me, adding it into OptionsMonitor is easy.
