### ISSUE TITLE
Could not update the package Microsoft.Extensions.Logging 3.0.0 from v1.1.0 on WPF C# .Net Framework v4.5.2

### ISSUE THREAD

**Issue by nrajasekar7** [dotnet/extensions#2676]
# Nuget update issue
I have installed the Microsoft.Extenstions.Logging nuget package to my C# WPF application long back and now i have upgraded my c# application to .Net framework 4.5.2 but when i try to update package to latest version (3.0.0) it throws error. 

# Error info
`Could not install package 'Microsoft.Extensions.Logging 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	`	

# Note
Even i tried by updating my project to .Net framework V6.0, but still same error.		

Please help me on this.

Thanks,
Rajasekar

**Comment by anurse** [comment]
`Microsoft.Extensions.Logging` is a .NET Standard package that requires .NET Framework 4.6.1 or higher (though we **strongly** recommend 4.7.2 or higher).

Can you post a sample project that reproduces the error if you are still encountering it?
