### ISSUE TITLE
Generic probes for hosted services and web services.

### ISSUE THREAD

**Issue by InEx-Niklas** [dotnet/extensions#2678]
### Feature request.
Generic probes similar to `ILogger<T>` but `IProbe<T>` instead.

#### Initial request and post coffee realization.
My initial idea was for just a generic health check for hosted service's (reporting the status of the hosted service using the current HealthCheck system), after some coffee and thinking about it i realize it would not be easy and probably require a lot of reworking of how hosted service's are run.

My new idea introduces uncomfortable semantics, sort of like being forced to build your own fuel gauge for every car you get, however it might be the easiest and most useful solution.

### Senario.
Imagine that we have one host program with two or more IHostedService's running, maybe they are related or i just want few hosts running because i want to save money.

I want to be able to monitor my services liveliness and behavior through probes, and maybe report back statistics about it self.

### Solution
* Implement a new interface `IProbe<T>`, ProbeFactory and IServiceCollection.AddActivityProbes().
* Each probe collects data for set amount of time, when the window closes, it displays the collected probe data through API or ships it of.
* Probe Tickers, Enter, Success and Failed.
* Probe scopes, Average time spent in function X,Y,Z.
* Probed data is volatile, little to no history should be kept by the running process.

### Describe alternatives you've considered
* Implementing probes as part of `ILogger<T>`.
* More extendability in the current HealthChecking system.
* I'm missing something because i cant find the documentation.
* That i'm focusing to much on one thing, and need less coffee.

**Comment by Tratcher** [comment]
@rynowak @glennc

**Comment by anurse** [comment]
Is there a reason this would need to be in `Microsoft.Extension` itself? This should all be doable in a community project. To bring something like this in to Extensions means we'd need to justify this as very broadly useful (getting some traction with a community project would help there).

Perhaps if you can provide more details on a scenario that would *use* this API and how it is better than what we currently have around `EventSource`, `EventCounter` and the existing health checks.

**Comment by InEx-Niklas** [comment]
I see liveness probes as an important part of monitoring and health checking, currently we have the ability to set probes for external and internal dependence but that requires us having to add an internal health recorder which has a limited use. 

From my perspective building something for liveness probing and probing in general into `Microsoft.Extension` is as import as building Diagnostics.HealthChecks into it, in my opinion the liveness of a service as important as its external dependence and internal state.

Maybe the initial suggestion isn't the optimal or intended implementation. I might have focused on the wrong aspects in the initial post. Going back to my initial idea for what this suggestion was supposed to be, I.e. Just add some sort of check for hosted services health to the health check system, makes one ask the question when is a service in good health? 

* Is it when all external dependencies are available? 
* When the service task has the state running?
* When some internal resources are available? 

All above questions can only tell us when we have the potential of being of good health, they might be available without fail but we are still unable to perform regular operations. Which means the question which is more important is not the current health is the service in, its how is the service is. Which makes us ask an entirely different set of questions.

Liveness is a small but important part of a services health yet it brings a lot with it, and the building blocks are there with assets like `EventSource` and `EventCounter` like you mentioned.

**Comment by InEx-Niklas** [comment]
Did i win?

**Comment by anurse** [comment]
I'm still not sure I follow exactly what you're proposing we add over top of the existing health checks. Can you show a sample of your proposed new API and how you would use it in an app?

**Comment by rynowak** [comment]
This sounds like it conflates the idea health checks and metrics. Usually these are two different things.

Some folks decide to use the health checks system for reporting metrics, and that generally works fine for them with the current APIs.

**Comment by InEx-Niklas** [comment]
@rynowak The idea is not to add metrics into health checks, the idea is to create a shared probe concept that can be used for health, readiness and liveliness checks. However because of what states like these represent they inadvertently use the same logic as metrics do, the health of one or many services is a metric in and of itself.

**Comment by InEx-Niklas** [comment]
@anurse as for API i have been spending my weekends trying to craft a API that i'm satisfied with, i'm having difficulties expressing it(like this ticket). Which might be an indicator that i'm trying to attack it from the wrong angle or from too wide a perspective.

I will focus on the essence of the idea.

```
//startup.cs
public class BasicStartup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddHostedService<ExampleServiceOne>();
        services.AddHostedService<ExampleServiceTwo>();
        services.AddHealthChecks(); // Is a probe under the hood.
        services.AddProbes(probeBuilder => 
        {
            probeBuilder.AddProbe<ActivityProbe, ExampleServiceOne>("serviceProbes");
            probeBuilder.AddProbe<ActivityProbe, ExampleServiceTwo>("serviceProbes");
        });
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseRouting();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapHealthChecks("/health");
            endpoints.MapProbe<ActivityProbe>("serviceProbes", "/activity");
        });
    }
}
```
```
//ExampleServiceOne.cs
public class ExampleServiceOne: BackgroundService
{
    private readonly  IProbeActivity<ExampleServiceOne> _probe;
    
    public ExampleServiceOne(IProbeActivity<ExampleServiceOne> probe)
    {
        _probe = probe;
    }
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            async using (_probe.ReportActivity());
            // do something
        }
    }
}
```
IProbeActivity is a IProbe.
ExampleServiceTwo has some similar logic to ExampleServiceOne, and when a request is made to localhost:15320/activity we get something like this.

```
{
  "ExampleServiceOne": "2019-12-16 09:18:00.123",
  "ExampleServiceTwo": ""
}
```
The date is updated when the dispose function is called, and in this case ExampleServiceTwo has not disposed the probe yet.

**Comment by InEx-Niklas** [comment]
Have a good Yule, and happy holidays.

**Comment by InEx-Niklas** [comment]
Any thoughts?

**Comment by anurse** [comment]
So the probes are just a way of reporting the last time a particular point in the code was hit? I suppose I still don't really see this as high-value enough for a built in feature. It seems like it could be built on top of the existing Health Checks (since it's effectively the same, just a push model instead of a pull one). You could achieve this today by having a DI service that stored this probe data and a health check that just exposed the latest value from the probe.

It doesn't seem like something we'd built in at this time though. I think it would be best done as a third-party project.
