### ISSUE TITLE
Moving configuration providers inside a ChainedConfigurationProvider causes empty string values to no longer be returned

### ISSUE THREAD

**Issue by ryangribble** [dotnet/extensions#2690]
### Describe the bug
Empty string values in a Json configuration file are not being returned from `IConfiguration.GetValue()` calls, when the providers are contained inside a `ChainedConfigurationProvider` however when they are a top level series of `JsonConfigurationProvider` the empty string values ARE returned as expected.

The problem seems to be caused by the `TryGet()` method in the `ChainedConfigurationProvider` returning a condition of `!string.IsNullOrEmpty(value)` which is `false` in the case of an empty string, thus causing the calling function to return a `default(T)` (`null` in this case) instead of the empty string value
https://github.com/aspnet/Extensions/blob/d656c4f7e22d1c0b84cab1b453c50ce73c89a071/src/Configuration/Config/src/ChainedConfigurationProvider.cs#L44-L48

Whereas the normal configuration provider implementation is returning the result of an underlying `IDictionary<string, object>.TryGet()` which is `true` in the case of an empty string value.
https://github.com/aspnet/Extensions/blob/d656c4f7e22d1c0b84cab1b453c50ce73c89a071/src/Configuration/Config/src/ConfigurationProvider.cs#L38-L39

### To Reproduce
In a console app, with the following appsettings files:

appsettings.json
``` json
{
  "TestOverride": "replace me in local config"
}
```
appsettings.local.config.json
``` json
{
  "TestOverride": ""
}
```

The following code in `Main()`

``` csharp
IConfiguration configurationNormal = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json", false, true)
    .AddJsonFile("appsettings.local.json", true, true)
    .Build();

IConfiguration configurationChained = new ConfigurationBuilder()
    .AddConfiguration(configurationNormal)
    .Build();

// This provides the correct empty string value from the 2nd config file
var value1 = configurationNormal.GetValue<string>("TestOverride");
            
// This is null!
var value2 = configurationChained.GetValue<string>("TestOverride");
```

### Expected behavior
The empty string value from the 2nd config file should be provided in both cases

### Screenshots
N/A

### Additional context
I was refactoring a web API with an existing/working configuration builder declaration, that used a pair of json configuration files similar to the example above.  In some cases, the appsettings.json contains a default placeholder such as "to be replaced in local config" and then the appsettings.local.json contains an override value, which in some cases was a blank string.

In refactoring, I moved the configuration builder into Program.cs file (to enable early logging system initiatilixation) and then to avoid having to repeat the configuration builder wiring up a 2nd time, I wanted to now pass that `Configuration` into the `HostBuilder`, so I changed to using `AddConfiguration(configuration)`.  This then had the side effect that the blank string overrides were no longer working, and due to the other elements in the Asp.Net core defualt configuration builder (namely, other declarations of appsettings.json) the end result was the placeholder value from appsettings.json being used, rather than the empty string from appsettings.local.json

Include the output of `dotnet --info`

> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100
>  Commit:    04339c3a26
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
> 
> Host (useful for support):
>   Version: 3.0.0
>   Commit:  7d57652f33
> 
> .NET Core SDKs installed:
>   1.0.0 [C:\Program Files\dotnet\sdk]
>   1.0.1 [C:\Program Files\dotnet\sdk]
>   1.0.4 [C:\Program Files\dotnet\sdk]
>   1.1.0 [C:\Program Files\dotnet\sdk]
>   2.0.0 [C:\Program Files\dotnet\sdk]
>   2.1.4 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.300 [C:\Program Files\dotnet\sdk]
>   3.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>

**Comment by isen-ng** [comment]
I just ran into this today. Seems like a simple fix. 
Will you accept a PR?

**Comment by anurse** [comment]
The config model doesn't distinguish between `null` and an empty string (since many providers don't have a means to detect the difference). This isn't something we intend to change in the design.

**Comment by iron9light** [comment]
No matter how you treat null and empty string, I think ChainedConfigurationProvider should return the same value as the inner provider.
