### ISSUE TITLE
Support double underscores for hierarchical keys when addind configuration from INI files

### ISSUE THREAD

**Issue by kimsey0** [dotnet/extensions#2701]
### Is your feature request related to a problem? Please describe.
When configuring ASP.NET Core, you can divide your configuration values into hierarchical sections. This is for example used for connection strings, which can be put into a `ConnectionStrings` section and then accessed via the [`GetConnectionString`](https://github.com/aspnet/Extensions/blob/55cdd5cb60f590b19d8248e7667717e0d4718980/src/Configuration/Config.Abstractions/src/ConfigurationExtensions.cs#L34) extension method.

According to [the ASP.NET Core Configuration documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#keys), hierarchical keys can be indicated by putting a colon (`:`) between the section name and the key, e.g., `ConnectionStrings:DatabaseConnectionString`. However:

>In environment variables, a colon separator may not work on all platforms. A double underscore (__) is supported by all platforms and is automatically converted into a colon.

When deploying ASP.NET Core apps in Docker containers via, for example Docker Compose or Kubernetes, it can be useful to pass configuration values into ASP.NET Core via environment variables. Here, [a `.env` file](https://docs.docker.com/compose/env-file/) is often used. Since colon separators do not work on all platforms, such a file would preferably use double underscores as separators, e.g. `ConnectionStrings__DatabaseConnectionString=...`

When you already have a `.env` file, you want to avoid duplicating configuration settings when debugging outside of a container. Since `.env` files follow the same basic syntax as INI files, [you may try adding them](https://github.com/aspnet/Configuration/issues/505) using [`AddIniFile`](https://github.com/aspnet/Extensions/blob/55cdd5cb60f590b19d8248e7667717e0d4718980/src/Configuration/Config.Ini/src/IniConfigurationExtensions.cs#L23). This works, except for the fact that [`IniStreamConfigurationProvider`](https://github.com/aspnet/Extensions/blob/55cdd5cb60f590b19d8248e7667717e0d4718980/src/Configuration/Config.Ini/src/IniStreamConfigurationProvider.cs) doesn't support converting double underscores into colons the same way [EnvironmentVariablesConfigurationProvider does](https://github.com/aspnet/Extensions/blob/55cdd5cb60f590b19d8248e7667717e0d4718980/src/Configuration/Config.EnvironmentVariables/src/EnvironmentVariablesConfigurationProvider.cs#L67).

### Describe the solution you'd like
Introduce the same automatic conversion from `__` to `:` in [`IniStreamConfigurationProvider`](https://github.com/aspnet/Extensions/blob/55cdd5cb60f590b19d8248e7667717e0d4718980/src/Configuration/Config.Ini/src/IniStreamConfigurationProvider.cs#L71) as currently exists in [EnvironmentVariablesConfigurationProvider](https://github.com/aspnet/Extensions/blob/55cdd5cb60f590b19d8248e7667717e0d4718980/src/Configuration/Config.EnvironmentVariables/src/EnvironmentVariablesConfigurationProvider.cs#L69).

### Describe alternatives you've considered
You could introduce a separate `.env` file configuration provider or add workarounds to codebases that want to use `AddIniFile` for `.env` files, such as manually searching for keys with double underscores and converting them:

``` cs
IConfigurationRoot configurationRoot = configurationBuilder.Build();
Dictionary<string, string> normalized = configurationRoot.AsEnumerable()
    .Where(p => p.Key.Contains("__"))
    .ToDictionary(p => p.Key.Replace("__", ":"), p => p.Value);
configurationBuilder.AddInMemoryCollection(normalized);
```

### Additional context
Adding this automatic conversion would be a breaking change for anyone currently using configuration keys with double underscores loaded from INI files. You could potentially keep both versions.

**Comment by anurse** [comment]
While the syntax may match, the `AddIniFile` method is not designed to handle `.env` files. This isn't something we plan to support in the core, but there is ample opportunity for a third-party `AddEnvFile` provider here!
