### ISSUE TITLE
req.ReadFormAsync() throws exception with Microsoft.Extensions.Primitives v 3.0 with Azure Function

### ISSUE THREAD

**Issue by dwainbrowne** [dotnet/extensions#2733]
### Describe the bug
Using Azure Functions version 2

The following line throws an exception with Microsoft.Extensions.Primitives v3.0/1
var formdata = await req.ReadFormAsync();

Exception "System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.Primitives.StringValues Microsoft.AspNetCore.Http.IFormCollection.get_Item(System.String)'.'

**If I downgrade to version 2.0 it works fine.**

### To Reproduce
**Steps to reproduce the behavior:**

1. Create a new Azure Function (using VS 2019 16.3.9)

2. Add the following line: var formdata = await req.ReadFormAsync();

3. Test function, everything should work properly.

4. Add Nuget Package Microsoft.Extensions.Primitives (3.0.1)

5. Run the function again, you  will get exception: 

System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.Primitives.StringValues Microsoft.AspNetCore.Http.IQueryCollection.get_Item(System.String

### Expected behavior
No exception should be thrown, with req.ReadFormAxync();

### Screenshots
![image](https://user-images.githubusercontent.com/15684123/69881587-7deaeb80-129b-11ea-9617-b01ad258b2a3.png)

![image](https://user-images.githubusercontent.com/15684123/69881611-922ee880-129b-11ea-831e-33b8ac89c0fc.png)

**Comment by Pilchie** [comment]
I believe this is expected.  Azure Functions runs on the 2.2 version of ASP.NET Core, so it probably already has the 2.2 version of this assembly loaded.

**Comment by pinkfloydx33** [comment]
I ran into a very similar issue. I had tried adding the Logging extensions package version 3.0.x and couldn't figure out what the problem was (tons of `MissingMethodException`s). Turns out that like Pilchie mentions, the 2.x version is already loaded by the runtime. In my case removing the reference fixed the issue.

**Comment by anurse** [comment]
Yep, this is expected, you can get errors like this if your cross major versions.
