### ISSUE TITLE
Microsoft.Extensions.ObjectPool has invalid file modified times

### ISSUE THREAD

**Issue by peppy** [dotnet/extensions#2750]
The [new 3.1 release](https://www.nuget.org/packages/Microsoft.Extensions.ObjectPool/3.1.0) of `Microsoft.Extensions.ObjectPool` has incorrect modified dates for its contained (and exposed) dll files. This in turn causes package failure of any project including this package (due to https://github.com/NuGet/Home/issues/7001).

![image](https://user-images.githubusercontent.com/191335/70215550-104e2c00-1781-11ea-8013-1b38db401a95.png)

![image](https://user-images.githubusercontent.com/191335/70215569-180dd080-1781-11ea-83c1-780cc7878b05.png)

**Comment by Bert-Proesmans** [comment]
I encountered exactly the same issues on 
`Microsoft.Extensions.Caching.Memory.dll`
`Microsoft.Extensions.Caching.Memory.xml`
`Microsoft.Extensions.DependencyInjection.Abstractions.dll`
`Microsoft.Extensions.DependencyInjection.Abstractions.xml`
`Microsoft.Extensions.Logging.Abstractions.dll`
`Microsoft.Extensions.Logging.Abstractions.xml`
`Microsoft.Extensions.Options.dll`
`Microsoft.Extensions.Options.xml`
`Microsoft.Extensions.Primitives.dll`
`Microsoft.Extensions.Primitives.xml`

It also prevents me from running NuGet pack.

**Comment by rynowak** [comment]
@aspnet/build

**Comment by rynowak** [comment]
Sorry, clicked the wrong button.

**Comment by jeroenlandheer** [comment]
All `Microsoft.Extensions` packages are on 1-1-1980. Same problems here, it prevents us from publishing PowerShell packages.

**Comment by jeroenlandheer** [comment]
For everyone who's having trouble (probably everyone who's in a timezone above GMT), you can use this PowerShell script to change the date of the files to a value which allows you to pack with Nuget:

`Get-ChildItem | Where {$_.LastWriteTime.Year -eq '1980'} | % {$_.LastWriteTime = $_.CreationTime }`

**Comment by dougbu** [comment]
@rrelyea I suspect we built 3.1.0 in the window while pack determinism was `true` i.e. before NuGet/NuGet.Client#3060 was merged and NuGet/Home#8599 was fixed. What exactly do we need to upgrade e.g. the .NET Core SDK in order to get that fix?

**Comment by dougbu** [comment]
/fyi @johnbeisner @mmitche @aspnet/build @leecow @dagood @dleeapho @MichaelSimons @richaverma1 @nguerrera @richlander @SteveCarrollMSFT this is a 3.1.0 content issue.

**Comment by wtgodbe** [comment]
We also need to update the SDK to fix the package icon issue - if this will also be caught by that, then that's even more motivation to do so

**Comment by rrelyea** [comment]
We fixed in final 3.0.100 - so use that it later.

**Comment by mmitche** [comment]
> We fixed in final 3.0.100 - so use that or later.

@rrelyea This also fixed in 3.1.100, yes?

**Comment by rrelyea** [comment]
3.0.100 matches NuGet 5.3 and VS 16.3
3.1.100 matches NuGet 5.4 and VS 16.4
Yes, we fixed on the last day or two of 3.0.100 and did not change behavior after that.
(we have not tried to refix, etc...)

@nkolev92

**Comment by Bert-Proesmans** [comment]
Can anyone instruct me what i need to do to make this issue go away? (I know about the powershell one liner as a workaround)

From the response i interpreted that some fix has been applied, but these specific libraries still have a faulty modification date. So far i updated Visual studio (which, i supposed, includes updated nuget binaries), looked for newer versions of the relevant libs to update and removed my local package cache. The end result didn't change, where i expected the modification date to be set correctly again.

**Comment by Pilchie** [comment]
We haven't published the new versions yet.  We will as part of our next servicing update when that is ready.

**Comment by anurse** [comment]
This should be resolved. Please let us know if you're still seeing this issue!

**Comment by dougbu** [comment]
Reopening because Extensions portion of the targeting pack was not previous rebuilt

**Comment by dougbu** [comment]
3.1.8 is now out with this fix included
