### ISSUE TITLE
LoggerFilterConfigureOptions should not throw an exception if the LogLevel Enum value cannot be parsed

### ISSUE THREAD

**Issue by spasecookee** [dotnet/extensions#2756]
If the enum cannot be parsed in private static bool TryGetSwitch(string value, out LogLevel level), an invalid operation exception should not be thrown, instead the enum value LogLevel.None should be used or something more appropriate. (As you're doing if the string is empty, which is not much different).

Reason: a well-meaning individual might set the LogLevel Default to either "INFO" or "WARN", which are very common Log Levels in many logging frameworks. however, when set to these values, an AspNetCore application will crash during  WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();  in Program.cs. This could too-easily take down a production application over a very common way of configuring logging options.

**Comment by anurse** [comment]
I don't think it's a good idea for the app to start working if the configuration is invalid. Starting the app with incorrect behavior is much more dangerous than failing to start the app. If the app fails to start, your existing failover processes and deployment staging can protect your production deployment from problems while you roll back. If the behavior is incorrect, it is much more difficult to detect the problem.
