### ISSUE TITLE
Missing icons in Microsoft.Extensions.* NuGet packages

### ISSUE THREAD

**Issue by SnakyBeaky** [dotnet/extensions#2768]
NuGet icons are missing for most `Microsoft.Extensions.*` packages for the latest `3.1.0`  versions.

![image](https://user-images.githubusercontent.com/8410877/70429995-15a9c000-1a7a-11ea-9842-fa9aaa04ced6.png)
*3.0.1 version had icon*

![image](https://user-images.githubusercontent.com/8410877/70430001-1a6e7400-1a7a-11ea-898d-68e3da404ca7.png)
*3.1.0 is missing an icon*

**Comment by slang25** [comment]
The problem might be that the icon is in the nupkg package twice, this will be fixed in a 3.1.1 release as I understand. I'll find the issue and link it.

**Comment by slang25** [comment]
Here we go: https://github.com/aspnet/Extensions/issues/2744

**Comment by Pilchie** [comment]
Yes, it's related to that issue.  We were switching from `IconUrl` to `IconFile`, but ended up building with a nuget too old to support `IconFile` 😢

**Comment by joelverhagen** [comment]
There these duplicates of each other? https://github.com/aspnet/Extensions/issues/2515. Feel free to close mine if so.

**Comment by Pilchie** [comment]
Latest guidance is that we might want both for a transition period (some clients like VS don't respect `IconFile` yet), but I believe we currently only have `IconFile`.  We can use this to track the idea of adding back `IconUrl`.

**Comment by wtgodbe** [comment]
This should be resolved as of 3.1.1
