### ISSUE TITLE
RedisCache missing ConfigureAwait(false) on different methods?

### ISSUE THREAD

**Issue by josundt** [dotnet/extensions#2779]
### Describe the bug
Deadlock on various methods with RedisCache (f.ex. GetStringAsync(key)).

We experience this in ASP.NET/WebAPI 2/NET Framework applications, but not with ASP.NET Core/MVC for some reason.
I still have some work to do to fully understand the inner workings of asynchronous tasks in C#, but from what I have understood, ASP.NET uses a special SynchronizationContext, whileas ASP.NET Core does not. I guess this may explain the different behavior.

Reading the following article https://devblogs.microsoft.com/dotnet/configureawait-faq/, leads me to think that there may be some missing `ConfigureAwait(false)` in your RedisCache implementation causing this undesired behavior.

We are migrating everything to ASP.NET Core, and we are reingeneering from sync to async across our code base, but in the transition phase we phase this problem. In the transition phase, we sometimes have to call an async method from a sync method and use `.GetAwaiter().GetResult()`. This fails on some of the method implementations of IDistributedCache with RedisCache.
 
Since Microsoft.Extensions libraries most are netstandard2.0 and work well with both framework and core applicatinos; and since libraries should be platform agnostic, I guess this is something you may want to look into.

### To Reproduce
Create and configure an ASP.NET/netframework/WebAPI 2 application, and use any 3rd party IoC solution for the WebApi 2 DependencyResolver to support DI:

Create a controller with the following code
```csharp
[RoutePrefix("api")]
public class MyController : ApiController {

    private readonly IDistributedCache _cache;

    public MyController(IDistributedCache cache) {
        this._cache = cache;
    }

    [HttpGet]
    [Route("cache/{id}")]
    public string GetFromCache(string id) {
        var result = this._cache.GetStringAsync(id).GetAwaiter().GetResult();
        // Code execution never reaches the next line:
        return result;
    }
}
```

_PS! I understand that the easy fix to the example above is to make the action method async and return a `Task<string>`, but this is just an example to reproduce the problem. Sometimes you have no other option than calling an async method from a sync method. With RedisCache.GetStringAsync(key) this fails, at least when hosted in a ASP.NET/netframework_

### Expected behavior
Code execution should continue on next line

**Comment by davidfowl** [comment]
Yes these libraries should have ConfigureAwait(false) everywhere.

**Comment by JunTaoLuo** [comment]
@anurse to assign.

**Comment by BrennanConroy** [comment]
ConfigureAwait was added to the GetStringAsync method. Should be in 5.0.
