### ISSUE TITLE
Remove ref project for Microsoft.AspNetCore.Testing

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/extensions#2784]
In https://github.com/aspnet/Extensions/pull/2483, we added a ref project for `Microsoft.AspNetCore.Testing`: https://github.com/aspnet/Extensions/blob/release/3.0/src/TestingUtils/Microsoft.AspNetCore.Testing/ref/Microsoft.AspNetCore.Testing.csproj. This is a non-shipping test utility project that should not need a ref project - we should determine why this was added, and figure out how to remove it.

Related - https://github.com/aspnet/Extensions/pull/2781 explicitly marked this ref project `nonshipping` - it had been getting the default value of `IsShipping=true` from Arcade, which caused `Microsoft.Extensions.Logging.Testing` to list a dependency on a stable version of that package, which will never exist.

CC @dougbu @JunTaoLuo

**Comment by dougbu** [comment]
@wtgodbe please retry your test removal of the ref/ project. I suspect the repo wasn't clean after doing that removal, leading to holdover use of the previous ref/ assembly and leading to errors about missing `internal`s. Note Microsoft.AspNetCore.Testing.csproj has `<InternalsVisibleTo Include="Microsoft.AspNetCore.Testing.Tests" />`.

The bottom line here is either
1. The ref/ assembly should never have been created since it's not used elsewhere.
2. The ref/ assembly was a shortcut to work around a deeper problem in the Extensions build infrastructure.

**Comment by wtgodbe** [comment]
@dougbu from a clean enlistment, I built these changes: https://github.com/aspnet/Extensions/commit/0684de4f07e149292e8a5f74507199e3360f81de

Which gave these errors:

> Xunit\LoggedConditionalFactDiscoverer.cs(4,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedConditionalTheoryDiscoverer.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedTestFrameworkDiscoverer.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedTestRunner.cs(11,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedConditionalFactDiscoverer.cs(4,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedConditionalTheoryDiscoverer.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedTestFrameworkDiscoverer.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]
Xunit\LoggedTestRunner.cs(11,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\code\aspnet\extensions\src\Logging\Logging.Testing\src\Microsoft.Extensions.Logging.Testing.csproj]

**Comment by dougbu** [comment]
Looks very much like an issue w/ `[InternalsVisibleTo]`.

Another possibility is ref/ assemblies from indirect dependencies aren't visible at the Microsoft.Extensions.Logging.Testing level, delivering incorrect references to the compiler. Any warnings in the build indicating something along these lines?

You've now got a binary log to check more deeply 😺

**Comment by wtgodbe** [comment]
No interesting warnings. I'm looking at the binlog locally.

**Comment by wtgodbe** [comment]
Looks like the `ProjectReference` to `Microsoft.AspNetCore.Testing` doesn't ever get resolved or wind up in the final set of References, while the rest of the `ProjectReferences` do. Looking into why.

**Comment by wtgodbe** [comment]
Ok, this is why:

https://github.com/aspnet/Extensions/blob/9695ec06e00bb2357728733bb2318c1999fc7d01/eng/targets/ResolveReferences.targets#L90-L101

`Microsoft.Extensions.Logging.Testing` wants to reference reference assemblies, not implementation assemblies. When the entry in `_ProjectReferenceByAssemblyName` for `Microsoft.AspNetCore.Testing` doesn't have `RefProjectPath` metadata, no entry for it gets inserted into `ProjectReference`. Changing the 'Reference' to an explicit 'ProjectReference' solves the problem: https://github.com/aspnet/Extensions/commit/12534efd0b6a2b0e107f022dddb2a612893b763b

**Comment by wtgodbe** [comment]
@dougbu it turns out that:

https://github.com/aspnet/Extensions/blob/0684de4f07e149292e8a5f74507199e3360f81de/src/Logging/Logging.Testing/src/Microsoft.Extensions.Logging.Testing.csproj#L21

Is the only instance in the repo where an implementation project `Reference`s a nonshipping or non-packable project. There are other instances where we have `ProjectReferences` to such projects, or test/testasset projects that `Reference` such projects, but never an implementation project with a `Reference`. If we were to have another such `Reference`, we'd see the same issue where nothing got resolved because the Referenced project has no Ref assembly.

**Comment by wtgodbe** [comment]
As far as I can tell, we don't do https://github.com/aspnet/Extensions/issues/2784#issuecomment-565249131 in AspNetCore either.

**Comment by dougbu** [comment]
> As far as I can tell, we don't do https://github.com/aspnet/Extensions/issues/2784#issuecomment-565249131 in AspNetCore either.

I'm not sure what you mean. In AspNetCore, `@(Reference)` items are _always_ used when referring to implementation projects. `@(ProjectReference)` items there are only used between samples, tests, test assets, and similar. Deviations from this are bugs.

----
In any case, please update Microsoft.AspNetCore.Testing to remove the ref/ project and change other projects to use an `@(ProjectReference)` item when they depend on Microsoft.AspNetCore.Testing.

To make it clear what's going on later, please also mark Microsoft.AspNetCore.Testing with `<IsProjectReferenceProvider>false</IsProjectReferenceProvider>`. Then regenerate the project list.

**Comment by wtgodbe** [comment]
> I'm not sure what you mean. In AspNetCore, `@(Reference)` items are always used when referring to implementation projects. `@(ProjectReference)` items there are only used between samples, tests, test assets, and similar. Deviations from this are bugs.

What I mean is, there is no instance that I could find, in this repo or AspNetCore, of an implementation project with `<Reference Include="{nonshipping project}">` - other than:

https://github.com/aspnet/Extensions/blob/0684de4f07e149292e8a5f74507199e3360f81de/src/Logging/Logging.Testing/src/Microsoft.Extensions.Logging.Testing.csproj#L21

> In any case, please update Microsoft.AspNetCore.Testing to remove the ref/ project and change other projects to use an @(ProjectReference) item when they depend on Microsoft.AspNetCore.Testing.

To make it clear what's going on later, please also mark Microsoft.AspNetCore.Testing with <IsProjectReferenceProvider>false</IsProjectReferenceProvider>. Then regenerate the project list.

Will do.

**Comment by JunTaoLuo** [comment]
Should this work item be combined with https://github.com/aspnet/Extensions/issues/2787? I think removing the ref project for M.A.Testing will be a side effect when we overhaul the ref assembly logic.

**Comment by dougbu** [comment]
@JunTaoLuo why combine the two? This is a fairly straightforward and isolated change that should improve the state in AspNetCore. #2787 is a more significant undertaking with less urgency.

**Comment by JunTaoLuo** [comment]
In the other issue you mentioned:
> As part of aspnet/AspNetCore#17311, I removed all ref/ projects for implementation projects that were not in the shared framework. Should do the same thing here.

So I thought the two issues are dupes.

**Comment by dougbu** [comment]
Nah, that's a smallish thing we can do while implementing #2787 whereas this single change is urgent -- at least as I remember things.

**Comment by JunTaoLuo** [comment]
We decided to do this in 3.1 only.

**Comment by wtgodbe** [comment]
We had to revert this as it caused issues in AspNetCore: https://github.com/dotnet/extensions/pull/2882

Might be related to the pinned dependency on the 3.1.0 extensions.refs package, which carries a ref assembly for `Microsoft.AspNetCore.Testing`. @JunTaoLuo is investigating.
