### ISSUE TITLE
Duplicate aspnet/AspNetCore#17311 improvements in this repo

### ISSUE THREAD

**Issue by dougbu** [dotnet/extensions#2787]
This should be a tell-mode infrastructure improvement. Aim is to use the same ref/ project generation and resolution infrastructure as in AspNetCore.

As part of aspnet/AspNetCore#17311, I removed all ref/ projects for implementation projects that were not in the shared framework. Should do the same thing here.

**Comment by anurse** [comment]
@dougbu what's the situation with this? It seems to have been moving from sprint to sprint ;).

**Comment by dougbu** [comment]
Yes it keeps getting kicked further down the road by higher-priority and more urgent work. Though I probably know the current code best, I'm also the most underwater these days. Fortunately, @wtgodbe volunteered to help us make actual progress.
