### ISSUE TITLE
Multiple named instances of IDistributedCache

### ISSUE THREAD

**Issue by colgreen** [dotnet/extensions#2802]
### Is your feature request related to a problem? Please describe.
The back-end cache providers such as redis and ncache support partitions, whereby I can get/set items in a given named partition. Furthermore, a given ASP.NET Core app may wish to utilise multiple IDistribitutedCache instances, one per functional area, e.g. put the 'foo' objects in a 'foo' partition, and the 'bar' objects in a 'bar' partition. The items in the two distinct partitions are stored separately, and therefore avoid key collisions. 

### Describe the solution you'd like
Named instances of IDistributedCache.

### Describe alternatives you've considered
Option 1) Direct use of the NCache and Redis APIs. I.e. the NCache and Redis APIs support partitions; it is the IDistributedCache API over those underlying APIs that does not expose the partition related functionality.

Option 2) Define compound keys for the items in a single IDistributedCache instance. This increases the key length, and results in redis and ncache placing all items into a single partition, i.e. we are prevented from using the partitioning functionality of redis and ncache.

### Additional context
Overall the redis and ncache APIs offer a lot of funtionality, e.g. around synchronised access 
 (locking and releasing of cache entries), and partitioning. Whereas IDistributedCache must provide some generic interface over all possible caches. So there needs to be a balance between simplicity and functionality, but I feel that balance could be tweaked a little towards offering some of the core functionality that is common to redis, ncache and other caching products.

Also see:

https://stackoverflow.com/questions/50822279/multiple-instances-of-idistributedcache

**Comment by colgreen** [comment]
I have also recently needed synchronised access to cache entries, i.e. to avoid race conditions when multiple entities are trying to read and write a cache entry simultaneously. The redis API supports synced access, but this is lost by the IDistributedCache abstraction.

I also think that IDistributedCache is not a good name for this interface. The consumers of the cache service require a service with a get/set API... whether the actual implementation is distributed or not is a choice that is made at startup time and not something the consumers are concerned with. In any case, we already have a MemoryDistributedCache that isn't (and cannot be) distributed, so the naming just quite fit the abstraction in my opinion.

Overall I get the feeling that this entire area needs a fresh look, possibly with a view to define a completely new 'ICache' style API. Clearly we can;t create an abstraction over all possible underlyign caches, there needs to be a balance, and I feel IDistributedCache has gone too far towards simplicity and bare minimum functionality.

**Comment by davidfowl** [comment]
I agree but I don't know that we'd do a good job here. IDistributedCache really exists as a lowest common denominator abstraction for libraries that need this behavior not for applications. Applications should use redis directly or memcached or something with features. We need IDistributedCache ourselves for things like session, the cache tag helper.

I'm hesitant to add anything new abstraction here.

**Comment by colgreen** [comment]
@davidfowl understood. One thing to bear in mind regarding session state is that it does require synchronised access of some form; the traditional ASP.NET session state providers achieved this by creating separate 'lock' entries in the back-end store, but with something like Redis the native support for synchronisation could be used instead.

I think there is a desire for there to be an abstraction over specific implementations (e.g. Redis), and at first glance IDistributedCache appeared to be what we wanted, but I take your points and will go away and reconsider/discuss. Thanks.

**Comment by anurse** [comment]
I think I agree with @davidfowl here. If you need this kind of advanced usage it's probably best to use the APIs directly. You could still put an implementation of `IDistributedCache` in place for the other components of the system (like Session) to use, but bypass that and use native APIs for more advanced scenarios.

**Comment by colgreen** [comment]
No problem. I think I came to the conclusion we would probably register multiple named copies of IDistributedCache in our IoC subsystem, or something along those lines.
