### ISSUE TITLE
IExternalScopeProvider provides different scoping than ILogger

### ISSUE THREAD

**Issue by Scooletz** [dotnet/extensions#2805]
### Is your feature request related to a problem? Please describe.

Currently, `IExternalScopeProvider` provides two methods for managing scope. First, that enables pushing the scope via 

https://github.com/aspnet/Extensions/blob/72fa6bc6bae6a0cb93f14568688e9f0a2cb882a9/src/Logging/Logging.Abstractions/src/IExternalScopeProvider.cs#L27

and the other, to go through the states with 

https://github.com/aspnet/Extensions/blob/72fa6bc6bae6a0cb93f14568688e9f0a2cb882a9/src/Logging/Logging.Abstractions/src/IExternalScopeProvider.cs#L20

Both methods accept `object` as the parameters type. This makes it different from `ILogger` that enabled pushing strongly typed (via a generic parameter) states on the stack

https://github.com/aspnet/Extensions/blob/72fa6bc6bae6a0cb93f14568688e9f0a2cb882a9/src/Logging/Logging.Abstractions/src/ILogger.cs#L38

### Describe the solution you'd like

I'd like to use a similar approach for `IExternalScopeProvider` as its used for `ILogger`. This would require to:

1. accept a visitor with a generic method for `ForEach` instead of a delegate
1. change `Push` to a generic method
1. change the default `LoggerExternalScopeProvider.State` to be generic 
1. pass down the visitor to the state instead of invoking it from ForEach to enable a "generic dispatch"

This would:

1. make it coherent with ILogger
1. enable potential implementors of `ISupportExternalScope` to use unboxed struct values
1. enable potential implementors of `ISupportExternalScope` to use the type provided by a generic parameter type

### Describe alternatives you've considered

Lowering `ILogger` to use `Push (object state)`.

### Additional context

With the forthcoming OpenTracing and overall acceptance of MS.Extensions.Logging I think it's worth it to make it a bit more expressive.

**Comment by Scooletz** [comment]
If this is something considerable, I could spike a PR for it.

**Comment by anurse** [comment]
I don't think this would work, but I guess I'd be interested to see if you can get it working :). The `ForEach` can't be made generic because each state could have a **different type**. That's why `object` is used here. The `Push` could, I suppose, be generic.

What's the goal you're trying to achieve? "Consistency" isn't necessarily a good enough reason to take a change like this (since it would be a breaking change, if it *did* work).

**Comment by Scooletz** [comment]
Even though I won't pursue this issue, I want to provide the feedback to the policy for closing an issue after 4 days. I can see that is was triaged as an `enhancement`, but it wasn't given an answer for 4 months. Then bot closes it within 4 days. In my opinion it lacks some kind balance.

**Comment by davidfowl** [comment]
Agreed. We can't make breaking changes like this though, that's the real answer that should have been given months ago 😄

**Comment by davidfowl** [comment]
I also don't really understand how it would be implemented.
