### ISSUE TITLE
NullReferenceException with custom implementation of IHostApplicationLifetime

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/extensions#2825]
### Describe the bug
A custom implementation of `IHostApplicationLifetime` causes a `NullReferenceException`.

### To Reproduce
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureServices((hostContext, services) =>
            {
                services.AddSingleton<IHostApplicationLifetime, CustomApplicationLifetime>();
                services.AddHostedService<Worker>();

            });
}

public class CustomApplicationLifetime : IHostApplicationLifetime
{
    public CancellationToken ApplicationStarted => default;

    public CancellationToken ApplicationStopping => default;

    public CancellationToken ApplicationStopped => default;

    public void StopApplication()
    {
    }
}
```

### Additional context
This is where error is happening.
https://github.com/aspnet/Extensions/blob/ecc4d9fe9381ac65848968b672eb6098ec2a2cae/src/Hosting/Hosting/src/Internal/Host.cs#L39

There's no null checking for `_applicationLifetime`. In order to fix this we could store `IHostApplicationLifetime` instead of `ApplicationLifetime` and use cast in `StartAsync(...)` and `StopAsync(...)`

**Comment by Tratcher** [comment]
IHostApplicationLifetime is not designed to be replaceable. See https://github.com/aspnet/Extensions/issues/2044.

**Comment by Kahbazi** [comment]
Oh my bad, I didn't realize that. 
So there's no way that `_applicationLifetime` could be null in `Host` and [null](https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/Internal/Host.cs#L54) [checks](https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/Internal/Host.cs#L68) could be removed? 🤔

Also is it possible to throw an exception in `HostBuilder` if another implementation for `IHostApplicationLifetime` is registered?

**Comment by Tratcher** [comment]
Yes, some hardening here might help communicate that the lifetime isn't replaceable.

**Comment by anurse** [comment]
We can consider a guard that throws a useful error, but as @Tratcher said it's by design that this cannot be replaced.

**Comment by Kahbazi** [comment]
How about a check in `HostBuilder` to make sure it's registered as singleton?

**Comment by Tratcher** [comment]
@Kahbazi that's oddly specific. Checking that we get back the right implementation type should be enough.
