### ISSUE TITLE
[Discussion] Moving Extensions repo to dotnet org 2020-01-07

### ISSUE THREAD

**Issue by Pilchie** [dotnet/extensions#2834]
As a first step towards the work describe [here](https://github.com/dotnet/announcements/issues/127), we're planning on migrating the Extensions repo to the dotnet org.  We'd like to get this done ASAP.

We don't expect any significant issues for contributors, GitHub is great about adding redirects.  However, it may impact our ability to produce nightly builds and flow dependencies for a few days.

Please let us know if you run into any other issues.

**Comment by Pilchie** [comment]
The initial move is complete.  We still have work to get builds and dependency flow working again.

**Comment by Varorbc** [comment]
Why not move to runtime?

**Comment by Pilchie** [comment]
Some parts of the extensions repo will likely move into the runtime repo in the future, but not all of it.  This is a first step towards that process.

**Comment by Pilchie** [comment]
This is done now.
