### ISSUE TITLE
C# .NET Core ReadAsStringAsync() throws System.OperationCanceledException

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/extensions#2839]
Im using C#'s `HttpClient.GetAsync()` method to make an API request from an endpoint URL, the API returns a JSON string and then I retrieve the result using `HttpContent.ReadAsStringAsync()` method. It works successfully. But when I hit `CTRL+C` on the `dotnet run` running process, unexpectedly it throws an `Unhandled exception. System.OperationCanceledException: The operation was canceled.`, is there any way to get rid of this?

My fully controller method:

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _httpClient.GetAsync("projects/7/issues?scope=all&per_page=100&page=1");
        if (result.IsSuccessStatusCode)
        {
            var content = await result.Content.ReadAsStringAsync();
            Issue[] issues = JsonSerializer.Deserialize<Issue[]>(content);
            return Json(issues);
        }
    
        return NoContent();
    }

Exception:

    Unhandled exception. System.OperationCanceledException: The operation was canceled.
       at System.Threading.CancellationToken.ThrowOperationCanceledException()
       at System.Threading.CancellationToken.ThrowIfCancellationRequested()
       at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

**Comment by justinushermawan** [comment]
@anurse Thanks for your detailed explanation. I've tried to put `cancellationToken` injected to my controller since it has the same value as `HttpContext.RequestAborted` into the 2nd argument of `GetAsync()`, and for `ReadAsStringAsync()`, it seems a non cancelable async operation, so we can't pass the `cancellationToken`  as we do to `GetAsync()`. So, the server `Run()` operation still throws `OperationCanceledException`. Should I just catch the exception on `Run()` method calling?

**Comment by anurse** [comment]
> Should I just catch the exception on `Run()` method calling?

That is probably a good plan. We could investigate suppressing the exception (but that would be breaking existing behavior ;)). In general, if the shutdown timeout elapses, the result is that `OperationCancelledException` is thrown. Another option would be to try increasing the timeout, to see if `ReadAsStringAsync()` can complete in time. But if for some reason `ReadAsStringAsync()` is never going to complete, then it won't matter what you set the timeout to :). Catching that exception and logging it as something more useful ("Shutdown timeout elapsed" or something) would probably be ideal.

**Comment by justinushermawan** [comment]
Thanks for your great help, I see now. My current solution for this case is by surrounding the server's `Run()` method with `try-catch` as below.

```
try
{
    CreateHostBuilder(args).Build().Run();
}
catch (OperationCanceledException ex)
{
    logger.Info(ex, "Shutdown timeout elapsed");
}
catch (Exception ex)
{
    logger.Error(ex, "Stopped program because of exception");
    throw;
}
finally
{
    NLog.LogManager.Shutdown();
}
```
