### ISSUE TITLE
Microsoft.Extensions libraries not working with  .Net 461

### ISSUE THREAD

**Issue by Ynot1234** [dotnet/extensions#2848]
I have a solution with two projects.  

One is .Net Core 2.1
Other is  .Net Framework 4.6.1

When I build and test locally it's fine.   

However when I build on the TFS web app, the 'Nuget Restore' task gets the following issues...

```
Package Microsoft.Extensions.Configuration.Json 2.1.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Microsoft.Extensions.Configuration.Json 2.1.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2020-01-10T13:44:14.7785469Z Checking compatibility for Microsoft.Extensions.FileProviders.Physical 3.1.0 with .NETFramework,Version=v4.6.1.
2020-01-10T13:44:14.7789665Z Package Microsoft.Extensions.FileProviders.Physical 3.1.0 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Microsoft.Extensions.FileProviders.Physical 3.1.0 supports:
2020-01-10T13:44:14.7791263Z   - netcoreapp3.1 (.NETCoreApp,Version=v3.1)
2020-01-10T13:44:14.7791736Z   - netstandard2.0 (.NETStandard,Version=v2.0)
```

If it works locally, it should work on our build server right?

P.S. Re-writing one of these projects to match the other .Net standard is not an option.

**Comment by anurse** [comment]
What kind of build tools do you have installed on your build server:

* What, if any, versions of Visual Studio are installed?
* What, if any, versions of the .NET Core SDK (`dotnet.exe`) are installed?

Can you get the output of both `msbuild /v` (if present) and `dotnet --info` (if present) on your build server?

**Comment by Ynot1234** [comment]
We use Visual Studio 2017 locally.    On the build server it is done via command line.   But this is the NuGet Restore task so it doesn't get to the build.

**Comment by Ynot1234** [comment]
Do you mean the entire log? As opposed to the excerpt I posted above?

**Comment by anurse** [comment]
> On the build server it is done via command line.

How is your command-line build invoked? `msbuild.exe` or `dotnet build`?

> But this is the NuGet Restore task so it doesn't get to the build.

It's the version of NuGet that's used that matters. What NuGet Restore task are you using?

**Comment by Ynot1234** [comment]
![image](https://user-images.githubusercontent.com/37936847/72187686-fc1fcf00-33bd-11ea-8386-0bcb9a942227.png)

This one.   

Also here is the relevant command line...

 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe /t:GenerateRestoreGraphFile /nologo /nr:false /p:RestoreUseCustomAfterTargets=true /p:BuildProjectReferences=false /v:q  /p:NuGetRestoreTargets="F:\Build\web_002\_work\_temp\NuGet-Scratch\ycq3wfir.nwc.targets" /p:RestoreTaskAssemblyFile="F:\Build\web_002\_work\_tool\NuGet\4.0.0\x64\nuget.exe" /p:RestoreGraphOutputPath="F:\Build\web_002\_work\_temp\NuGet-Scratch\bw5qe4pq.rti.result" /p:ExcludeRestorePackageImports=true  /p:RestoreRecursive=False  /p:RestoreProjectFilterMode=exclusionlist /p:RestoreContinueOnError=WarnAndContinue  /p:RestoreGraphProjectInput="F:\Build\web_002\_work\625\s\src\APICore\APICore.csproj;F:\Build\web_002\_work\625\s\src\ProjectName\ProjectName.csproj;" "F:\Build\web_002\_work\_temp\NuGet-Scratch\ycq3wfir.nwc.targets"

**Comment by anurse** [comment]
Since you're using Visual Studio 2017 tools, I can't see myself what could be wrong. The package certainly does restore properly in my environment. I don't see any issues with the way the package is authored that should cause it to fail to restore. The fact that it's saying `netstandard2.0` is not compatible with `net461` indicates that you're running a version of NuGet that doesn't understand that those frameworks are compatible.

I don't think there's action we can take here. I'd suggest posting feedback on TFS or engaging their support to see if there's something they can track down. Or you could ask on the [NuGet repository](https://github.com/nuget/home).
