### ISSUE TITLE
Do we really need the ILoggerFactory.AddProvider method?

### ISSUE THREAD

**Issue by yeah-boi** [dotnet/extensions#2849]
Do we really need the ILoggerFactory.AddProvider method?

Why would anyone want to change the list of providers for an ILoggerFactory instance after it has been created?

**Comment by anurse** [comment]
It's not something the newer model (DI-based) supports, but there can be reasons for it. Why are you interested in removing it? Is it blocking a scenario of yours? Removing an API is a major breaking change so we'd have to evaluate the benefit of *removing* the API against the major cost to customers who may be using it.

**Comment by yeah-boi** [comment]
The only reason I wanted to remove it was purley theoretical: It didn't seem to make any sense and ILoggerFactory would be simpler without it, but as you say it is probably too late to do this now since it would break backwards compatability.
