### ISSUE TITLE
NuGet package broken, packageIcon.png included twice, extraction failure

### ISSUE THREAD

**Issue by stroborobo** [dotnet/extensions#2853]
### Describe the bug
The current Version 3.1.0 of multiple packages (Microsoft.Extensions.FileSystemGlobbing, .ObjectPool we've found by now) have the packageIcon.png included twice, which results in a failure when extracting the zip file.  
Perhaps this doesn't error in VS because the important files like dlls have already extracted at that point?

### To Reproduce
1. Download the package file for version 3.1.0 of Microsoft.Extensions.FileSystemGlobbing
2. Extract the zip file

### Expected behavior
All files extracted without error

### Screenshots
On cli:
![image](https://user-images.githubusercontent.com/684180/72245711-71bfb100-35f1-11ea-8c00-2e2ab6439d69.png)
![image](https://user-images.githubusercontent.com/684180/72245891-d549de80-35f1-11ea-8818-b53cbf9ab68f.png)

Using Paket:
![image](https://user-images.githubusercontent.com/684180/72245774-9582f700-35f1-11ea-9a23-4adc020926ee.png)
(Bottom error in German, says: The file "...packageIcon.png" already exists)

**Comment by stroborobo** [comment]
Related to #2515 and #2768?

**Comment by Pilchie** [comment]
Yes, Dupes of those.  Paket also updated to support this case, so try updating paket before updated packages are published, which should be soon.

**Comment by wtgodbe** [comment]
This should be resolved as of 3.1.1
