### ISSUE TITLE
Should non-'nullable enable' code generate warnings?

### ISSUE THREAD

**Issue by ATimmeh33** [dotnet/extensions#2872]
Considering the following code:

```
	class Program
	{
		public static void Main(string[] args)
		{
			IConfiguration config = new Config();
			string value = config["value"];
		}
	}

	class Config
		: IConfiguration
	{
		public string? this[string key]
		{
			get => null;
			set => _ = value;
		}

		public IEnumerable<IConfigurationSection> GetChildren() => throw new NotImplementedException();
		public IChangeToken GetReloadToken() => throw new NotImplementedException();
		public IConfigurationSection GetSection(string key) => throw new NotImplementedException();
	}
```
With IConfiguration being from Microsoft.Extensions.Configuration

Shouldn't `config["value"]` generate a warning since the interface returns a regular string (non nullable enabled, thus nullable)? I was expecting "Converting null literal or possible null value to non-nullable type." to appear here.

Just wondering if this is by design, a bug or a flaw in my logic.

**Comment by rynowak** [comment]
See this section: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullability-of-types

Code that's not annotated for nullability (like `IConfiguration`) is *nullable oblivious*.

**Comment by ATimmeh33** [comment]
> See this section: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullability-of-types
> 
> Code that's not annotated for nullability (like `IConfiguration`) is _nullable oblivious_.

Thank you for the provided link. Is there any way to enable warnings for nullable oblivious code?

**Comment by rynowak** [comment]
That would be a question for the c# team (dotnet/roslyn) - but I'm pretty sure there isn't. 

One of the problems is that you'd have to be pessimistic and assume that everything is nullable. They might have tried something like this in the past - I'm betting that if an option like this existed, it would be really noisy - imagine the amount of warnings you'd have if everything was nullable!
