### ISSUE TITLE
Configuration's data overlapping in multiple projects of a solution.

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [dotnet/extensions#2906]
### Describe the bug
Let's say we have 2 projects in a solution (.net core library projects) using extensions.configuration in both of them, through below code:
```
internal static IConfiguration config;

config = new ConfigurationBuilder()
               .AddJsonFile("settings.json", optional: false, reloadOnChange: true)
               .Build();
```

Instead of showing values of their OWN projects, of their internal config.
Config object only loads the config of last loaded project config, which can be accessed in both the projects.

### To Reproduce
1. Using version '3.1.1' of package 'Microsoft.Extensions.Configuration & Microsoft.Extensions.Configuration.Json'
2. Run this code
```
namespace ProjectOne
{
    class Library
    {
        internal static IConfiguration config;

        internal static void Initialize()
        {
            config = new ConfigurationBuilder()
               .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
               .Build();
        }
    }
}

namespace ProjectTwo
{
    class Library
    {
        internal static IConfiguration config;

        internal static void Initialize()
        {
            config = new ConfigurationBuilder()
               .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
               .Build();
        }
    }
}
```
3. With different data in appsettings.json in both projects
4. You will see same config data will be loaded in both project's config object instead of their own specific config data.

### Expected behavior
Project should load configuration data of their OWN project in their own objects.

### Additional context
Issue **doesn't** arise if both projects json files have different names.

**Comment by fluxlife** [comment]
Would like to bump this. Had a problem related to this and it was a difficult to debug let alone understand if this is by design or a bug. 

Thank you.

**Comment by anurse** [comment]
What's the **app** that you're running this code in? Can you provide a runnable sample that reproduces the problem?

Configuration files are loaded relative to the **app** base directory, not the project that contained the library. It's not really designed as a system for per-library configuration.

**Comment by fluxlife** [comment]
I think your explanation then shows that things are working as designed, just not to what I expected. I cannot speak for OP.

My Expectations were:
Assuming I have 2 projects: Project A and Project B, and Project A has a dependency on Project B, I _assumed_ I could access configuration settings set of Project B from Project A. I now understand this doesn't allow for that scenario.

**Comment by NavjotSinghMinhas** [comment]
Hi everyone,

I tried to this with other projects in .NET Framework like ASP.NET just to confirm this behavior.
Looks like this is not a bug but is a general flow designed from beginning of .NET platform.

I still don't know why i was put that way, but really appreciate all of your time.
Thanks.
