### ISSUE TITLE
Best practice for localizing logging

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/extensions#2914]
with the deprecation of IStringLocalizer.WithCulture method It would be lovely if, in addition to CultureInfo.CurrentUICulture and CultureInfo.CurrentCulture we could allow the localization framework to hold the concept of the culture of the user and the culture of the log.

I can see a situation where my host machine is running US english as it's system locale, my end user is running german per his web browser settings and I want to generate logs in UK english. At the moment I can't easily do  this without changing the CurrentCulture on each logging request which is not efficient.

What is the best practice way to do this?

Thanks
Mark

**Comment by anurse** [comment]
I don't think we have a best practice here. It's not something we've really dug deep in to.

**Comment by MCFHTAGENTS** [comment]
Does the scenario make sense?

At the moment the IStringLocalizer piece assumes it is all in the current user locale which makes sense. And yet the analyzers all complain about any use of fixed strings. I don't know if you can refine the analyzer to ignore logging type calls - obviously they end up in a call to a ILogger method and deem that logging is done in the language of the user.

Alternatively, leveraging the broader localization code would seem sensible too but there is now no easy way to localize for a language that is not the current web users.


Thanks
Mark

**Comment by anurse** [comment]
> And yet the analyzers all complain about any use of fixed strings. I don't know if you can refine the analyzer to ignore logging type calls

Can you put together a runnable sample to repro the analyzer issue?

**Comment by MCFHTAGENTS** [comment]
It's pretty ubiquitous! I have 401 CA1303's reported in the project!

`Method  xxx passes a literal string as parameter 'message' of a call to 'void LoggerExtensions.LogCritical(ILogger logger, string message, params object[] args)'. Retrieve the following string(s) from a resource table instead: "There are no configured setup section for the gateway {0}".`

e.g. in a method defined in one of my services it makes the following call:
` this.logger.LogCritical("There is no configured setup section for the gateway {0}", site.GatewayId);`

where logger is an instance of ILogger<serviceName>

The code here in double quotes is flagged.

**Comment by anurse** [comment]
That seems like a gap in that analyzer then (which is built here: https://github.com/dotnet/roslyn-analyzers).

Is your goal to localize these messages? In our experience, log messages should not be localized as it makes diagnostics/debugging more challenging since the log messages might change depending on the user, browser or OS language.

**Comment by MCFHTAGENTS** [comment]
In the case I am doing here I don’t need to localize them and take your point about adding complexity. I went down that route initially as I was seeing the the system locale might not be the language I wanted to use but I agree enhancing the analyser also makes sense

**Comment by anurse** [comment]
Given that, I'd suggest reaching out to the team that builds those analyzers at the repo I linked above.

Closing as I don't believe there's actionable work from us here.
