### ISSUE TITLE
Add Caching/StackExchangeRedis to release/2.1

### ISSUE THREAD

**Issue by justRu** [dotnet/extensions#2916]
Originally StackExchangeRedis was developed and released in 2.2.
Some of our users used it but since 2.2 is no longer supported, we are moving to 2.1 LTS as it is easier to migrate to 2.1 than to 3.0 and also not everyone can move to .NET Core.
I think it is fairly easy to copy StackExchangeRedis from release/2.2 to release/2.1. The downside is obviously to support 2.1 version in future.
If you are OK with adding StackExchangeRedis to release/2.1, I can create create a PR.

**Comment by anurse** [comment]
We don't generally add packages in patch releases. This feature (support for the new StackExchangeRedis package) was added in 2.2 and we have no plans to backport it to 2.1.
