### ISSUE TITLE
AKV Configuration Provider with national clouds

### ISSUE THREAD

**Issue by guardrex** [dotnet/extensions#2919]
Moved from docs issue https://github.com/aspnet/AspNetCore.Docs/issues/16647 pertaining to the AKV Configuration Provider topic+sample app ...

@fiksen99 asked ...

> The example should indicate that the `AzureServiceTokenProvider` connects to the common AAD instance by default, in case users are targeting national clouds
>
> the example above indicates the user should create an `AzureServiceTokenProvider` using the default constructor.
>
> This is fair for 99% of use cases, however it is difficult to discover that you need to override the AAD instance when deploying to national clouds (e.g. in USGov, it should be constructed with `https://login.microsoftonline.us/` instead).
>
> A comment indicating this may be helpful

At this point without more knowledge, this seems more like a product issue/feature request than a docs issue. If an approach can be shown to me and if you want it in the topic, post here, and I'll re-open the docs issue to work it.

**Comment by anurse** [comment]
I don't think this is a product issue. We just expose the Key Vault configuration APIs and don't do anything to block or specifically enable National Clouds.

**Comment by guardrex** [comment]
I'm not aware of what steps must be taken outside of what we have, so I don't have anything actionable to document. Closing now.
