### ISSUE TITLE
Logging: AddConfiguration doesn't respect more specific provider setting

### ISSUE THREAD

**Issue by silkfire** [dotnet/extensions#2924]
### Describe the bug
Using `AddConfiguration` to add logging configuration from `appsettings.json` doesn't seem to work as intended. A more specific provider configuration should override the log level of `"LogLevel": "Default"`.

### To Reproduce
With the following configuration:

```json
"Logging": {
   "IncludeScopes": false,
   "LogLevel": {
      "Default": "Warning"
   },
   "Debug": {
      "Microsoft":  "Debug",
      "Default": "Trace"
   }
}
```

### Expected behavior
The **Debug** logger should print ASP.NET Core messages starting from the `Debug` log level. Instead it only prints messages starting from the `Warning` log level. Changing `"LogLevel": "Default"` to `Trace` or `Debug` prints the messages correctly, but this is not the intended functionality according to the documentation.

If I omit `AddConfiguration` and use `AddFilter<DebugLoggerProvider>("Microsoft", LogLevel.Debug)` instead, the logging works as intended, having in mind that the default log level for _all_ logging providers is `Information` (which is higher than `Debug`) .

**Comment by anurse** [comment]
I think it needs to be:

```json
"Logging": {
   "IncludeScopes": false,
   "LogLevel": {
      "Default": "Warning"
   },
   "Debug": {
      "LogLevel": {
          "Microsoft":  "Debug",
          "Default": "Trace"
        }
   }
}
```

(You need a `LogLevel` key below the provider name)

Does it work when you change it to that?

**Comment by silkfire** [comment]
Yikes! 😣 Per your suggestion I wrapped the values in a `LogLevel` block, which made it work just as intended. Thanks.

**Comment by anurse** [comment]
No worries! You aren’t the first person to make this mistake :). I’ll look at our docs to see if this can be clarified!
