### ISSUE TITLE
Named parameters for built in Microsoft DI Container

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/extensions#2937]
While using Microsoft Built In Dependency Injection, need of one feature often comes up:
**Passing Parameters to Resolve during runtime.**

Autofac provides this as in the example below.
`var reader = scope.Resolve<ConfigReader>(new NamedParameter("configSectionName", "sectionName"));`

In my opinion, this one feature will make the container complete in many aspects to use for any application that we create.

Is it still available and I am missing it how to use it, Or can it be included in some future release Or is there any work around to implement this?

Thanks

**Comment by dmytrohridin** [comment]
@satyajit-behera seems this feature request were raised several times and if I correctly remember - there was a comment that such an approach is some kind of anti-pattern and container will not be support this feature (but maybe things will cahnge)
https://github.com/dmytrohridin/DependencyInjectionNamedExtensions
I implement for my several projects extensions, it's in prerelease state and testing, but you can try and submit issue if needed

**Comment by anurse** [comment]
Triage: This isn't something we plan to do in the built-in container. Features we add to the built-in container are likely to be depended-upon by app developers and libraries, which means we have to take extreme care to ensure we support features that most external containers support.

The recommended approach here is to use a container that supports the features your app needed.
