### ISSUE TITLE
Running NetCore 3.1 console app as a systemd service not working on OpenSuse 15.0

### ISSUE THREAD

**Issue by andreijw** [dotnet/extensions#2947]
### Describe the bug
I am running a netcore 3.1 console app as a systemd service following Microsoft's documentation for [IHostBuilder ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostbuilder?view=dotnet-plat-ext-3.1). It should run my application as a systemd service, however it is failing with a (code=dumped, signal=ABRT). 

When I run a systemctl status on my service it shows as loaded but a failed active state.

However when I run the console app from the terminal directly, the application runs fine, and does not throw any error. 

I did not encounter any issues on Debian, Ubuntu or Centos.

### To Reproduce
1. Using netcore 3.1 build the console application.
2.  Publish the application with the following command: 
`dotnet publish -c Release --self-contained --runtime=opensuse-x64`
3. Take the publish folder and put it in your OpenSuse environment
4. Create a systemd service file. For example:  `/etc/systemd/system/test-service.service`
5. Modify the service file contents to be: 

`[Unit]`
`Description=Enable the test-service service at boot`

`[Service]`
`ExecStart=/home/username/Downloads/opensuse-64/publish/OpenSuseTestApp`
`Restart=always`

`[Install]`
`WantedBy=default.target`

Note that the ExecStart is pointed to our console application dll

6. Then run a daemon reload `systemctl daemon-reload`
7. Start the service  `systemctl start test-service.service`
8. See the service fails to start, however if you run the dll directly, it runs without any errors

### Expected behavior
The service should start without any errors just like in Ubuntu, Debian and Centos.

### Screenshots

![ServiceStatus](https://user-images.githubusercontent.com/31940904/74064351-1b5b4d80-49b8-11ea-9d7a-200d58cd4629.PNG)

### Additional context
This application was built with the self contained flag, and does not require dotnet to be installed on the target os.

**Comment by andreijw** [comment]
Any updates on this? I'm blocked by this issue and  was hoping that you guys could fix this some time soon. Thanks

**Comment by BrennanConroy** [comment]
Can you collect stdout and stderr and provide them?
