### ISSUE TITLE
IHostApplicationLifetime has incorrect doc comments for ApplicationStopped/ApplicationStopping

### ISSUE THREAD

**Issue by willdean** [dotnet/extensions#2962]
The documentation for IHostApplicationLifetime, which is just the doc-comments from the source code, contains the following text for **both** `ApplicationStopping` **and** `ApplicationStopped`:

> Triggered when the application host is performing a graceful shutdown. Shutdown will block until this event completes.

I think there are a few problems here:

1. The text shouldn't be the same for both properties - I guess it's correct for `ApplicationStopping` but wrong for `ApplicationStopped`?
2. Presumably one can't block shutdown at all by the time ApplicationStopped happens - it's too late.
3. Personally I find the "...will block until this event completes." text rather unclear, when there isn't an 'event' here at all - there's just a cancellation token.   Issue #2827 makes me think that I'm not the only person unsure precisely what this sentence implies in terms of behaviour.  The documentation for `CancellationToken.Register` manages to describe registering a callback on a CT without using the word 'event' at all - would it be clearer to mirror this terminology here?

I'd be happy to put in a PR, if my assumptions are correct:

* "Stopping" means a graceful shutdown has begun.  
* The shutdown will be blocked until any callbacks registered on ApplicationStopping have returned.
* "Stopped" means that graceful shutdown has completed.

**Comment by anurse** [comment]
A few tweaks but yes, in general you are correct. The "Stopped" event still *blocks the app from exiting* (by not returning from `StopAsync`) but doesn't allow you to block the shutdown of the various services in the app. Stopping happens before those services are shut down, so you can block shutdown in that one.

A PR clarifying this would be great!
