### ISSUE TITLE
How to overwrite a non-empty array config value by empty array [] ?

### ISSUE THREAD

**Issue by alvillain** [dotnet/extensions#2967]
Hi,

I am using environment variables in my setup. So, during service deployment I attach env vars. 
The problem I don't know how to overwrite existing non-empty array value by empty array value?

Example:

    appsettings.json
    {
         ConfigSection: {
             IntArray: [6678, 9091]        
         }
    }

I want to do something like this: 
 
    set ConfigSection__IntArray=[]
    ...run executable

As a result I would expect that during a config binding operation ```ConfigSection.IntArray``` will be an ```empty array``` or ```null``` (see https://github.com/dotnet/extensions/issues/1341 or https://github.com/aspnet/Configuration/issues/788)

So far I found a possibility to change the array values using an index of the element.
This is working:

    set ConfigSection__IntArray__0=5
    ...run executable

As a result  ```ConfigSection.IntArray``` will be set to ```[5, 9091]```

**Comment by derbur** [comment]
We are having a similar issue where we are trying to replace an array in the appsettings.json with an array from environment variables.
```f#
open Microsoft.Extensions.Configuration

[<EntryPoint>]
let main argv =
  let builder = new ConfigurationBuilder()
  let config = builder.AddJsonFile("appsettings.json")
                      .AddEnvironmentVariables()
                      .Build()
  
  // testValues1 resolves in the value from the environment variable: 
  // Path: AppSettings:TestValues
  // Value: "[ \"Four\", \"Five\", \"Six\" ]"
  let testValues1 = config.GetSection("AppSettings:TestValues")

  // testValues2 resolves in the value from the appsettings.json:
  // Path: "AppSettings:TestValues:0"
  // Value: "One"
  // etc...
  let testValues2 = config.GetSection("AppSettings:TestValues").GetChildren() |> Seq.cast<IConfigurationSection>
  
  0
```
This is the array in the appsettings.json:
```json
{
  "AppSettings": {
    "TestValues": [
      "One",
      "Two",
      "Three"
    ]
  }
}
```
This is the array in the environment variables:
![image](https://user-images.githubusercontent.com/13221868/81350736-9c49e400-9090-11ea-96c5-92277bd0480a.png)

Is it possible to override an entire configuration array from environment variables?

**Comment by anurse** [comment]
Unfortunately this is a tricky edge of the config model. Arrays don't actually exist in config, they are a convention layered on top based on the key suffix (`0`, `1`, `2`, etc.). We don't have a clear way to resolve that design conflict.

> So far I found a possibility to change the array values using an index of the element.

Probably the only option here without dramatically breaking the config model is to set indexes to an empty value (though of course you'd have to set as many empty values as you set in other layers).
