### ISSUE TITLE
OptionsBuilder Configure with scoped dependencies

### ISSUE THREAD

**Issue by rfaa-se** [dotnet/extensions#2987]
If you try to use the dependency injection together with a scoped service when using the Configure<TDep1, ...> method in the OptionsBuilder it will throw an exception saying that it can't resolve the scoped service from the root provider.

If we take a look at the source code here: https://github.com/dotnet/extensions/blob/master/src/Options/Options/src/OptionsBuilder.cs#L76 we can see that it's simply requesting the service from the service provider without creating a scope first. Is this intended? Is there a reason why scoped services are not supported?

A workaround is for now to inject the IServiceProvider or the IServiceScopeFactory and then creating a scope from which we can request the scoped services but I see no reason why this shouldn't be supported by default since both transient and singletons are available. Have I misunderstood something?

```
services.AddScoped<IService, Service>();
services.AddOptions<MyOptions>().Configure<IService>((options, service) => 
{
// Can't use the scoped service in here.
});
```

**Comment by anurse** [comment]
> Is this intended? Is there a reason why scoped services are not supported?

Options are registered as Singletons and Singletons *cannot* hold a dependency on Scoped services since it would cause a lifetime conflict (Singletons live longer than Scoped services, by definition). If you *really* need to read data out of a scoped service, you should be abel to do it manually by resolving an `IServiceScopeFactory` in your `Configure` method:

```csharp
services.AddScoped<IService, Service>();
services.AddOptions<MyOptions>().Configure<IService>((options, service) => 
{
	using var scope = service.GetRequiredService<IServiceScopeFactory>().CreateScope();
	//.. resolve scoped services from 'scope'
});
```
