### ISSUE TITLE
Tracking Environment configuration change 

### ISSUE THREAD

**Issue by shagilt** [dotnet/extensions#2991]
We have this code to read configuration from Environment variables. Is there a way I can track any change in environment variable?
```
public static IHostBuilder UseHostAppConfiguration(this IHostBuilder hostBuilder)
        {
            hostBuilder.ConfigureHostConfiguration(configHost =>
            {
        	  string basePath = AppContext.BaseDirectory;
                configHost.SetBasePath(basePath);
                configHost.AddJsonFile("hostsettings.json", optional: true);
                configHost.AddEnvironmentVariables();

                // add multiple environments support to generic host from asp.net core
                configHost.AddEnvironmentVariables(prefix: "ASPNETCORE_");
            });
  }
```

**Comment by jlestercastro** [comment]
> We have this code to read configuration from Environment variables. Is there a way I can track any change in environment variable?

Yes , hostsettings.json file to appsettings.json and add nested json file

- appsettings.Development.json
- appsettings.Test.json
- appsettings.{other}.json

It will get the parent appsettings.json and overwrite the declared configuration in each environment settings.

```
public static IHostBuilder UseHostAppConfiguration(this IHostBuilder hostBuilder, IHostingEnvironment environment)
        {
            hostBuilder.ConfigureHostConfiguration(configHost =>
            {
        	string basePath = AppContext.BaseDirectory;
                configHost.SetBasePath(basePath);
                configHost.AddJsonFile("appsettings.json", optional: true);
                configHost.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
                configHost.AddEnvironmentVariables();

                // add multiple environments support to generic host from asp.net core
                configHost.AddEnvironmentVariables(prefix: "ASPNETCORE_");
            });
  }
```

**Comment by shagilt** [comment]
Hi @jlestercastro  thank you for your reply. I think my question was not clear; my apologize for that.
Say I have a **windows environment variable** "ASPNETCORE_Foo" and initial value is "1". IS there a way to monitor when this variable updated to different value?

**Comment by jlestercastro** [comment]
Hello @shagilt ,I think this article might help you https://docs.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?view=aspnetcore-3.1

**Comment by davidfowl** [comment]
> Hi @jlestercastro thank you for your reply. I think my question was not clear; my apologize for that.
Say I have a windows environment variable "ASPNETCORE_Foo" and initial value is "1". IS there a way to monitor when this variable updated to different value?

AFAIK there isn't a way to monitor for environment variables changes (other than polling).

**Comment by anurse** [comment]
> AFAIK there isn't a way to monitor for environment variables changes (other than polling).

This is correct. In general Environment Variables aren't considered something that's likely to change (they can't be changed from outside the process for example).

Closing as this isn't something we intend to add.
