### ISSUE TITLE
IHttpClientFactory raising WINHTTP_CALLBACK_STATUS_REQUEST_ERROR

### ISSUE THREAD

**Issue by JustAnotherDev22** [dotnet/extensions#3013]
I'm getting the following error:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.WinHttpException (80072F8F, 12175): Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

The line that is causing the error is 

`var response = await client.SendAsync(request).ConfigureAwait(false);`

Here is my class:

```c#
public class MyService : IMyService
    {
        private readonly IHttpClientFactory _clientFactory;

        public MyService(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        public async Task<string> GetPage()
        {
            var requestHelper = new BnyMellon.Requests.RequestHelpers();
            var proxyConfig = requestHelper.ConfigureWebProxy();
            var getAccessTokenRequest = new GetAccessTokenRequest();
            var accessTokenConfig = getAccessTokenRequest.ConfigureGetAccessTokenRequest(proxyConfig);

            var proxy = new System.Net.WebProxy();
            proxy.Configure(accessTokenConfig.WebProxyConfiguration);

            var httpClientHandler = new HttpClientHandler();
            httpClientHandler.Configure(proxy, accessTokenConfig.SslProtocols);

            httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
            httpClientHandler.ClientCertificates.Add(new X509Certificate2(
                accessTokenConfig.PathToCertificate + accessTokenConfig.CertificateFileName,
                accessTokenConfig.PathToCertificate + accessTokenConfig.KeyFileName));

            httpClientHandler.ServerCertificateCustomValidationCallback = (sender, certificate, chain, sslPolicyError) => { return true; }; 

            var request = new HttpRequestMessage(HttpMethod.Post, accessTokenConfig.UriToGetAccessToken);
            request.Configure(accessTokenConfig.UriToGetAccessToken, HttpMethod.Post, accessTokenConfig.ContentTypes);

            request.Content = new StringContent("");
            request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/x-www-form-urlencoded");

            var formData = accessTokenConfig.FormData;
            request.AddContent(formData);

            AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
            var client = _clientFactory.CreateClient();
           

            try
            {
                var response = await client.SendAsync(request).ConfigureAwait(false);

                if (response.IsSuccessStatusCode)
                {
                    var responseContent = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    var data = JsonDocument.Parse(responseContent);
                    return data.ToString();
                    // return await response.Content.ReadAsStringAsync();
                }
                else
                {
                    return $"StatusCode: {response.StatusCode}";
                }
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e);
            }
            return "";
        }
    }
```

**Comment by JustAnotherDev22** [comment]
Note: When I send the request using curl and Postman I'm able to get the access token returned.

This is the curl command I'm using:

`curl -k --tlsv1.2 -d "grant_type=client_cert&scope=openid" -H "Authorization: Basic <REDACTED>" -H "Content-Type: application/x-www-form-urlencoded" --cert C:/MyCert.cer --key C:/MyKey.key https://the-url-im-calling/token`

**Comment by JustAnotherDev22** [comment]
This is what I see when I enter "request" in the Immediate Window:

`
{Method: POST, RequestUri: 'https://the-url-im-calling/token', Version: 1.1, Content: System.Net.Http.FormUrlEncodedContent, Headers:
{
  ContentType: application/x-www-form-urlencoded
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 35
}}
    Content: {System.Net.Http.FormUrlEncodedContent}
    Headers: {ContentType: application/x-www-form-urlencoded
}
    Method: {POST}
    Properties: Count = 0
    RequestUri: {https://the-url-im-calling/token}
    Version: {1.1}
`

**Comment by JustAnotherDev22** [comment]
Another note; am using Core 3.1.

**Comment by rynowak** [comment]
Hi @JustAnotherDev22 - based on what I can see from the code, you're configuring an `HttpClientHandler` but not actually using it. Calling `_clientFactory.CreateClient();` is not affected by the `httpClientHandler` variable in your method. 

You can use the `ConfigurePrimaryMessageHandler` method to configure the handler: https://github.com/dotnet/extensions/blob/557995ec322f1175d6d8a72a41713eec2d194871/src/HttpClientFactory/Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L179

I would also suggest using `SocketsHttpHandler` if you're on 3.1

**Comment by JustAnotherDev22** [comment]
Thanks @rynowak.  Will look into this.

**Comment by JustAnotherDev22** [comment]
Hi @rynowak,

Started looking into it but am confused as to how to actual implement ConfigurePrimaryMessageHandler.  I wasn't able to find all that much.

In Startup.ConfigureServices() I added:
`
    services.AddTransient<MyHttpClientHandler>();
    services.AddHttpClient<IMyService, MyService>()
        .ConfigurePrimaryHttpMessageHandler<MyHttpClientHandler>();
`
I created the MyHttpClientHandler class:
`
    public class MyHttpClientHandler : HttpClientHandler
    {
        public MyHttpClientHandler()
        {
                // I don't have any code in here yet.
        }
    }
`

I also updated the constructor to:

`
        public MyService(IHttpClientFactory clientFactory, HttpClient client)
        {
            _clientFactory = clientFactory;
        }
`
I was getting the following error:  A suitable constructor for type 'ClientFactoryDemoInWebApi.Models.MyService' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.  Found this link and it helped:  https://stackoverflow.com/questions/56087274/a-suitable-constructor-for-type-restdataservice-could-not-be-located.

But, now what do I do?  How do I actually attach httpClientHandler to _clientFactory?

Thanks for your help.

**Comment by rynowak** [comment]
Can we start at the beginning then? What are you trying to do? 😁

**Comment by JustAnotherDev22** [comment]
My problem is I'm unable to attach the certificates (.cer and .key) to the request.

**Comment by rynowak** [comment]
> My problem is I'm unable to attach the certificates (.cer and .key) to the request.

OK that makes this clear then. 

This is not a feature that the .NET HttpClient implementations have. Certificates are configured **per-HttpClient** (actually per message handler) not **per-request**.

@karelz - is this being addressed as part of dialers?

**Comment by karelz** [comment]
What does it mean to attach certificates to a request? What are the certificate associated with? TLS session? That is per connection (aka per-HttpClient).
Or what am I missing?

cc @davidsh

**Comment by rynowak** [comment]
> What does it mean to attach certificates to a request? What are the certificate associated with? TLS session? That is per connection (aka per-HttpClient). Or what am I missing?

I don't think you're missing anything. This is feedback that we get repeatedly. Users expect this to be more flexible and there is no guidance about how to achieve what they want.

**Comment by davidsh** [comment]
This is a reasonable ask. TLS client certificates are something that is not necessarily per-request since an HTTP request might re-use any existing TCP (TLS) connection.

However, a single HttpClient(HttpClientHandler) might be used to access many different server endpoints.

We made a design-related decision when HttpClient was designed to prevent changes to the HttpClientHandler properties after the first HTTP request was issued. This makes sense generally because you don't want to have race conditions on requests while changing the properties on the handler. However, that creates the limitation where HttpClientHandler.ClientCertificates can really only be used to access a single endpoint.

Our historical guidance was that in cases like this, devs should use a new HttpClient object so that they can assign a different client certificate. 

But it might be something we can consider changing in the future (revised API?) to make this scenario work better for devs.

**Comment by JustAnotherDev22** [comment]
In my situation I'm attaching the certificate to get an access token.  Afterwards, I will be using the token for all my requests.

**Comment by JustAnotherDev22** [comment]
What is the recommend way to do this?

I want to get/post, etc., data to/from 

`https://www.SomeUrl.com/.`  

The first request is to 

`https://www.SomeUrl.com/token` 

to get the access token.  Afterwards, I want to send another request to the same domain but another endpoint, e.g, 

`https://www.SomeUrl.com/api/GetDataForRequest1.`  

Afterwards, perhaps I send a post request to 

`https://www.SomeUrl.com/api/PostSomeData1`.

Thanks,

**Comment by rynowak** [comment]
Do you always use the same certificate to get an access token? (and do you always get it from the same host?)

If not, is it a different certificate per host you talk to? Multiple certificates per host?

**Comment by JustAnotherDev22** [comment]
Same certificate; until it expires (in some months or maybe next year).

**Comment by karelz** [comment]
How many endpoints to you  interact with?
Do all of them have different client certs?
Did you consider using multiple HttpClient(Factory) instances? One per each client certificate?

**Comment by JustAnotherDev22** [comment]
I have one certificate which I send to a single endpoint which returns an access token. 

Afterwards, I then use that access token to send it to the various endpoints (at the same domain).

The acccess token is valid for one hour, after which I need to resend the certificate to get a new access token.

My issue right now appears to be that I'm not attaching the certificate to the request and it's not clear how I should be doing so.

**Comment by karelz** [comment]
AFAIK there is no universal concept of "attaching certificates to a request" - it is not part HTTP spec or anything like that.
I think what you mean is that you need to establish connection with specific server, while using client certificates as part of the TLS connection. Is that correct?

TLS connect is established when you send first request.
Once your server recognizes your client certificate on the incoming TLS connection, your server will send respond to your first request with a custom token as data. You then use the token for other servers for 1 hour. The token is purely application-level token.

If all above is correct, then you can add the client certificate to first of your HttpClient(Factory) instances, use it as control HttpClient(Factory) instance and use it only to receive the 'token'. If you need to renew the token later, you just send new request via this control instance -- it will either reuse existing connection (already recognized by your server), or it will create a new one with the same client certificate.

**Comment by JustAnotherDev22** [comment]
Yes.  This sounds correct.

So, my question then is how to I implement this in C#?  What do I need to change in my code above?

Thanks,

**Comment by karelz** [comment]
Will [this article](https://damienbod.com/2019/09/07/using-certificate-authentication-with-ihttpclientfactory-and-httpclient/) help?

**Comment by JustAnotherDev22** [comment]
That's one of the articles that I used as a reference.

**Comment by karelz** [comment]
OK, which part is not clear then?
