### ISSUE TITLE
StartupLoader for GenericHost

### ISSUE THREAD

**Issue by mxplusb** [dotnet/extensions#3014]
### Is your feature request related to a problem? Please describe.

I'm trying to leverage the same DI logic ASP.NET Core uses with the `WebHostBuilder.UseStartup<T>()` extension, but the extension does not work with `HostBuilder`, only `WebHostBuilder`. Because of this, declaring environment-specific service dependencies is difficult for Console-based workloads.

### Describe the solution you'd like

I would like to see a generic host implementation of `StartupLoader` with a `UseStartup<T>()` extension for easily declaring a startup class where I can have a class like this:

```csharp
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)  {   }

    public void Configure(IApplicationBuilder app, IHostEnvironment env) {    }

    public void ConfigureStagingServices(IServiceCollection services)  {   }

    public void ConfigureStaging(IApplicationBuilder app, IHostEnvironment env) {    }
    
    public void ConfigureDevelopmentServices(IServiceCollection services)  {   }

    public void ConfigureDevelopment(IApplicationBuilder app, IHostEnvironment env) {    }
}
```

and then call the Startup class like this:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureHostDefaults(builder =>
            {
                builder.UseStartup<Startup>();
            });
}
```

### Describe alternatives you've considered

* Extracting `StartupLoader` from dotnet/aspnetcore
* Implementing a custom loader.

### Additional context

There's a lot of discussion going on https://github.com/dotnet/aspnetcore/issues/11050 but I wanted to make sure there was a feature request for a GenericHost extension. I think it would be good to agree on an interface, but also have a base `StartupLoader` that ASP.NET Core can then inherit or override as it now lives on GenericHost.

**Comment by Tratcher** [comment]
Startup is web specific due to `public void Configure(IApplicationBuilder app, IWebHostEnvironment env)`, adding it to the generic host builder doesn't make sense.

**Comment by mxplusb** [comment]
I accidentally had `IWebHostEnvironment` references in my example, I updated it to reflect `IHostEnvironment`, my mistake. Why wouldn't it make sense to have a proper implementation of `StartupLoader` for the generic host builder and then let ASP.NET Core consume it?

I can't speak for others, but I pushing Console-based workloads (i.e. [Orleans](https://github.com/dotnet/orleans)) through environments alongside HTTP workloads, is difficult when there isn't DI feature parity. Trying to manage differences in DI functionality from the generic builders is turning out to be difficult as they give different features.

**Comment by Tratcher** [comment]
IApplicationBuilder is also web specific. The only part of Startup that's not web specific is ConfigureServices, and you can access that directly from the host builder.

What do you mean by DI parity? Generic host's startup doesn't really allow DI anymore, it will only inject a few select types like IConfiguration.
