### ISSUE TITLE
Support for property injection in Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by pineapple216** [dotnet/extensions#3019]
When you have a base class which has several dependencies, 
all the dependencies need to be passed in the constructor of the child classes.

For every constructor I create I need to relay dependencies to the base class constructor.
Property injection would solve this issue by simply letting the DI mechanism handle the injection in the base class.

This leads to cleaner, more readable code.
For further clarification see the two examples below.

Example, without property injection

```
Class BaseClass
{
    public DependencyA depA { get; set;}
    public DependencyB depB { get; set; }

    public BaseClass(DependencyA a, DependencyB b)
    {
        this.depA = a;
        this.depB = b;
    }
}


Class ClassA: BaseClass
{
    public DependencyX x {get; set; }

    public ClassA(DependencyX x, DependencyA a, DependencyB b): base(a,b)
    {
        this.x = x;
    }
}

Class ClassB: BaseClass
{
    public DependencyZ z {get; set; }

    public ClassA(DependencyZ z, DependencyA a, DependencyB b): base(a,b)
    {
        this.z = z;
    }
}
```

Example with Property injection

```
Class BaseClass
{
    [Inject]
    public DependencyA depA { get; set;}

    [Inject]
    public DependencyB depB { get; set; }

    public BaseClass()
    {
        
    }
}

Class ClassA: BaseClass
{
    public DependencyX x {get; set; }

    public ClassA(DependencyX x)
    {
        this.x = x;
    }
}

Class ClassB: BaseClass
{
    public DependencyZ z {get; set; }

    public ClassA(DependencyZ z)
    {
        this.z = z;
    }
}
```

**Comment by davidfowl** [comment]
We're not going to add property injection to the default implementation. You should add use one of the 3rd party containers supported by the M.E.DI contract.
