### ISSUE TITLE
Azure Key Vault Configuration Provider doesn't allow customization on retrieving secrets

### ISSUE THREAD

**Issue by linkopingsommen** [dotnet/extensions#3027]
We have a use case where we want to get key vault secret for a specific version (not just the current one) but the AddAzureKeyVault extension method does not allow this.

Our intent was to use the keyvault secret tagging to define which version of the secret to use and for the configuration provider to use only those secrets.

Our use case would be resolved by either using Microsoft.Azure.KeyVault.IKeyVaultClient in the extension method (instead of the implementation type KeyVaultClient) or by making Microsoft.Extensions.Configuration.AzureKeyVault.IKeyVaultClient public and allow that to be passed in the AddAzureKeyVault extension method. That way we can customize the GetSecrets call to provide us with a custom set of secrets.

**Comment by anurse** [comment]
There are new Azure Integration packages published by the Azure SDK team (see https://github.com/aspnet/Announcements/issues/408 for details). This issue should be brought up with that team at http://github.com/azure/azure-sdk-for-net
