### ISSUE TITLE
SqlServerCacheServiceCollectionExtensions has wrong filename?

### ISSUE THREAD

**Issue by StefH** [dotnet/extensions#3036]
### Describe the bug
The filename `extensions/src/Caching/SqlServer/src/SqlServerCacheServiceCollectionExtensions.cs` has wrong name. It should be `SqlServerCachingServicesExtensions.cs`.

### To Reproduce
Go to source-code.

### Expected behavior
Filename should be `SqlServerCachingServicesExtensions.cs`.

**Comment by pivendren** [comment]
I can pick this one up.

**Comment by jbshu4546** [comment]
Is this issue still open?

**Comment by JunTaoLuo** [comment]
The fix was merged
