### ISSUE TITLE
AddLogging and LogFactory and LogBuilder

### ISSUE THREAD

**Issue by dazinator** [dotnet/extensions#3039]
### Describe the bug

The following API can end up with misleading service registrations, especially when you use a DI container that supports child containers, such as StructureMap / autofac.

Consider:
```
.AddLogging((builder=>{
  // add providers here
  builder.AddProvider(foo);
})
```

This doesn't register a `LoggerFactory` with the ILoggerProvider you specified. It instead registers an `ILoggerFactory` that has all ILoggerProviders injected / resolved from all service registrations which includes the one you registered or ones registered elsewhere.  This makes it hard to tell from the code exactly what is going on - for example on Azure environments other providers may be registered by default. You can work around this by:

```
.AddLogging((builder=>{
  // add providers here
  builder.ClearProviders();
  builder.AddProvider(foo);
})
```

However this doesn't work when using the same approach to configure a child container (when substituting out of the box ServiceProvider, for an alternative implementation like Autofac or Structuremap that support child containers) - as `ClearProviders()` can only clear registrations from the current container being built, it can't clear registrations from the parent container. In that case, when `ILoggerFactory` is resolved from the child container scope, it will still have ILoggerProvider's injected into it that have been registered at the root container level, even if you try and be explicity and do this:

```
.AddLogging((builder=>{
  // add providers here
  builder.ClearProviders(); // after this there are no ILoggerProvider's registered in this child container - but still some configured in the parent / root container that we can't clear here.
  builder.AddProvider(foo);
})
```

It took me quite a while to work out, why - when adding Logging to my child containers in structuremap / autofac, and trying to AddLogging() to the child container, my logs were still being handled by IProviders in my root container, and this is basically because AddLogging() doesn't register an actual instance of a configured LoggerFactory, it relies on DI to activate one instead.

Perhaps an extension method in the same guise as AddLogging() could be provided, that builds an ILogFactory instance, and registers that instead.

```
services.AddLoggerFactory((builder==>{
    builder.AddProvider<FooLogProvider>();
    builder.AddProvider<BarLogProvider>();   
});

```

This will replace an singleton instance of `ILoggerFactory` that may be registered previously, so there would be no need to `ClearProviders()`.

### Expected behavior
I expected AddLogging to enable me to control exactly which ILogProviders would be used, whether configuring a parent or a child container. However current behaviour doesn't do that, as ILoggerProvider's from parent scope will always be taken into consideration when activating the LoggerFactory, and those cannot be cleared by ClearProviders(). 

### Additional context
Include the output of `dotnet --info`

**Comment by davidfowl** [comment]
Can you provide a repro of your setup?

**Comment by dazinator** [comment]
@davidfowl sure - here is a repro in this branch: https://github.com/dazinator/Repros/tree/logging-child-containers

I've used Autofac, the same thing happens for using Structuremap child containers. 
The issue as you can see is that the child container gets a LoggerFactory instance which has ILoggerProviders injected into it that were registered at the root.

I have no idea whether this is by design. Obvioulsy now that i have spent considerable time understanding how it all works, I could not use `AddLogging` and register the services all myself but thought perhaps I'd raise an issue first.

**Comment by anurse** [comment]
This seems like a limitation of the built-in `LoggerFactory` implementation, but not one that we'd change. Child containers aren't something we see in common use, so some different behavior there would be expected.

I believe you always have the option of registering your own `ILoggerFactory` that completely replaces this behavior.
