### ISSUE TITLE
What is the best approach to handle Exception during IHostedService creation ?

### ISSUE THREAD

**Issue by klettier** [dotnet/extensions#3071]
### Is your feature request related to a problem? Please describe.

I'm searching some ways to handle **Exception** during the creation of an **IHostedService**.
For example you need a dependency that is missing because the provided configuration is invalid or a remote call is failing.

In the case above I want to be able to notify that something bad happened and stop the current application.

### Describe the solution you'd like

[Here](https://github.com/klettier/Hosted.Resiliency/tree/master/samples/ExHandle) is an example of what can be done for the scenario above .

In case of exception you can:

* Log the error using **ILogger**
* Resolve the **IHostApplicationLifetime** and call **StopApplication**
* Provide a default service without any behavior that will just return a  completed task (Task.CompletedTask).

### Describe alternatives you've considered

* Provide lazy dependencies and manage the **Exception** inside the **ExecuteAsync** method

### Additional context

* None

**Comment by Tratcher** [comment]
> I'm searching some ways to handle **Exception** during the creation of an **IHostedService**.

Let's clarify where that exception might be thrown. There are three steps to create and start an IHostedService:
1) IHostedService is resolved from DI and the constructor is called.
2) IHostedService.StartAsync
3) BackgroundService.ExecuteAsync

Which of these stages are you referring to specifically? The error handling will be different for each.

**Comment by klettier** [comment]
Just after the DI resolution.

If one of the dependency of my IHostedService could not be built due to an invalid configuration I don't have the hand on what will happen.

It would be nice to be able to manage the below scenarios 

* Stop all IHostedService and the whole App
* Stop only a desired IHostedService and keep running others
* Stop only some IHostedService and keep running others

So It would be nice to be able to override [the loop that call StartAsync](https://github.com/dotnet/extensions/blob/master/src/Hosting/Hosting/src/Internal/Host.cs#L52) and be able to provide more high level scenarios.

**Comment by Tratcher** [comment]
DI errors are not unique to IHostedServices and are generally considered unrecoverable. In most cases you work these out during development so having runtime error handling for them is less important.
