### ISSUE TITLE
Unable to create logger object

### ISSUE THREAD

**Issue by balukantu** [dotnet/extensions#3072]
Hi Team,

I am working on the .NET core project and included logging capabilities.  I am trying to create a wrapper class for LoggerT.cs class and trying to create a logger object but it is giving TypenameHelper is not found an error.

**Below is the code**

`            _logger = factory.CreateLogger(TypeNameHelper.GetTypeDisplayName(typeof(T), includeGenericParameters: false, nestedTypeDelimiter: '.'));
`

**Comment by davidfowl** [comment]
TypeNameHelper is an internal helper.

**Comment by balukantu** [comment]
Thanks for the update @davidfowl
