### ISSUE TITLE
IHostBuilder configure ShutdownTimeout

### ISSUE THREAD

**Issue by klyse** [dotnet/extensions#3073]
I'm trying to configure the `ShutdownTimeout` on the `IHostBuilder`. 

My expectation is that it works the same way as described [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingabstractionswebhostbuilderextensions.useshutdowntimeout?view=aspnetcore-3.1) for the `IWebHostBuilder`.

I did some digging in the framework and found that the `UseShutdownTimeout` is eventually just a configuration with the keyword `shutdownTimeoutSeconds`

Link to code:
https://github.com/dotnet/aspnetcore/blob/8cba1cbb231b37d56c352fad196619b11c5c6613/src/Hosting/Abstractions/src/HostingAbstractionsWebHostBuilderExtensions.cs#L179-L182

So I tried to implement this myself:
```csharp
var builder = new HostBuilder()
	.ConfigureAppConfiguration(configurationBuilder =>
	{
		configurationBuilder.AddInMemoryCollection(new Dictionary<string, string>
		{
			{ "shutdownTimeoutSeconds", "600" }
		});
	})
	.ConfigureServices(collection => collection.AddHostedService<SyncService>())
	.Build();
```
But this is not  working.

Is there a reason why `UseShutdownTimeout` extension method was not implemented for the `IHostBuilder`?

original issue:
https://github.com/dotnet/extensions/issues/3055#issuecomment-596003646

**Comment by Tratcher** [comment]
With the introduction of HostOptions, you can configure this more directly like this:
`services.Configure<HostOptions>(options => options.ShutdownTimeout = TimeSpan.FromSeconds(0.5));`

**Comment by klyse** [comment]
oh yes, with the additional information I found the docs as well:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#shutdowntimeout

The extension method could definitely help to make it more intuitive.
Another suggestion would be to pass options in the CreateDefaultBuilder. Example:
```csharp
var builder = Host.CreateDefaultBuilder(args, options => options.ShutdownTimeout = TimeSpan.FromSeconds(15))
	.Build();
```

Appreciate the help🙏🏻
