### ISSUE TITLE
Limitations when representing JSON in the configuration data model

### ISSUE THREAD

**Issue by anurse** [dotnet/extensions#3083]
I want to capture a few major limitations in the current configuration data model, when representing JSON object graphs. They come up frequently, and I'd like to centralize them a bit so we can prioritize the necessary changes appropriately. My plan is to put this issue on the backlog to provide a central point of discussion for improvements to this model. I don't know when those improvements could come, since they require fairly dramatic and costly changes that impact the ecosystem heavily, but I want to make sure we are *tracking* those limitations and can reassess.

Note: There aren't necessarily solutions here, this is more a description of the problems.

## Array Merging

(Example issues: https://github.com/dotnet/extensions/issues/1341)

Arrays don't co-operate well with the layering in the configuration system. For example, consider the following JSON file:

```json
{
  "Scopes": [ "Read", "Write", "Update", "Delete" ]
}
```

This emits the following key-value pairs, by the current data model:

```
Scopes:0 = Read
Scopes:1 = Write
Scopes:2 = Update
Scopes:3 = Delete
```

Now consider a production configuration layered on top of this:

```json
{
  "Scopes": [ "Read" ]
}
```

This emits the following key-value pairs:

```
Scopes:0 = Read
```

When merged, the final set is:

```
Scopes:0 = Read
Scopes:1 = Write
Scopes:2 = Update
Scopes:3 = Delete
```

Is this what the user intended? Not likely, since it appears that the user intended to limit the scopes in production to "Read" only.

### Workarounds

The standard workaround for this is to *expand* the collection in Development configuration rather than trying to *reduce* the collection in Production configuration. So instead of layering production config on top that limits the scopes to `Read`, the *base configuration* would only provide `Read` and the Development configuration would provide more expanded scopes.

## Modelling the presence of array/object prefixes

Consider the following JSON

```json
{
	"Scopes": []
}
```

This emits no key-value pairs, since there are no scalar values. There is no way to distinguish between the presence of an empty `Scopes` array, and the absence of the `Scopes` value entirely. The same applies to objects:

```json
{
	"Parent": {}
}
```

The `Parent` value is also never emitted anywhere since there are no scalars.

**Comment by rynowak** [comment]
> Modelling the presence of array/object prefixes

Usually this kind of thing ends up with you staring into the void. (Semantic differences between a present but empty value, and a non-present value). It always seems super low urgency to me because I wouldn't want to use something where details like this mean something 😆

**Comment by anurse** [comment]
I don't disagree, but wanted to capture the community feedback more centrally.

**Comment by anurse** [comment]
Closing after @rynowak pulled me back from staring into the V O I D :). The config model makes no distinction between "kinds" of absent values and we don't intend to change it. It's *explicitly* not an object-graph serialization system.
