### ISSUE TITLE
Make it easier for the community to find packages after the move

### ISSUE THREAD

**Issue by anurse** [dotnet/extensions#3084]
A few suggestions that came up from the [discussion thread on the package move](https://github.com/dotnet/aspnetcore/issues/19806) for ensuring people can find which packages live where more quickly. This issue is tracking doing that work. Some of it should be automatic, but we should validate it:

1. Ensure the Source Repository metadata in the packages is correct so that NuGet.org links will work

1. Add a list of all `Microsoft.Extensions.*` packages that used to exist in this repo linking to where they now live. This isn't necessarily designed to be a constantly-updated list as new packages are added, but should try to cover the ones that used to be maintained in this repo.

**Comment by anurse** [comment]
@bradygaster you were going to write up a README change right?

**Comment by bradygaster** [comment]
@anurse - yes the readme you authored in the announcements page was great IMO - anyone have any objection to us linking to that, or do folks think we need to essentially copy that content here?

**Comment by anurse** [comment]
Let’s do both. I think a link is easy for people to miss and if it’s copy-pasted it is Ctrl-F friendly. Maybe a copy-paste of the list and a link “for the complete announcement, see aspnet/Announcements#NNNN”
