### ISSUE TITLE
.NET core application insights vs ServiceFabric application insights

### ISSUE THREAD

**Issue by balukantu** [dotnet/extensions#3089]
Hi Team,

I am working on the ServiceFabric project. I have been using the ServiceFabric logging where ServiceContext and custom messages are being passed to logger methods so we have flexibility in ApplicationInsights to filter the values based on the service name, message, log level, etc.

As it is tightly coupled with service fabric, I am planning to integrate the .NET Core logging mechanism ( ApplicationInsights as a provider). 

Here, in .NET core logging, we can log messages/ objects but it is logged as JSON string. Also, we don't have the feasibility to filter based on properties.

Logging Implementation
---------------------------------

I have integrated the .NET core logging in my application by following the doc #link.
I have added the application insights provider to store the logs and able to log the messages and check those logs in application insights.

I have around 4-5 Web API projects and the same logging has been implemented as per documentation. However, I would like to filter the logs in application insights based on WebApiType, application name, etc.

In order to filter the logs, I have created the custom model and logging this custom object. But I am unable to filter the logs as the entire object is logging as a single object.

Custom Log Model
----------------
Class LogModel
{
property string ApplicationName { get; set; }
property string ApplicationType { get; set; }
property string ServiceName { get; set; }
property string Message { get; set; }
.
.
.
etc
}

Below are a couple of questions
-----------------------------
1. Do we have the feasibility to filter the logs in application insights using .NET core logging? If yes, how can we configure it?
2. ApplicationInsights are configured in ServiceFabric logging and .NET Core logging but there is no filtering capability for the logs which are being logged using .NET core logging. What is the difference between ServiceFabric ApplicationInsights and .NET core logging ApplicationInsights?

**Comment by davidfowl** [comment]
> Do we have the feasibility to filter the logs in application insights using .NET core logging? If yes, how can we configure it?

Where are you trying to filter the logs?

> ApplicationInsights are configured in ServiceFabric logging and .NET Core logging but there is no filtering capability for the logs which are being logged using .NET core logging. What is the difference between ServiceFabric ApplicationInsights and .NET core logging ApplicationInsights?

Can you point me to the ServiceFabric ApplicationInsights logic? I'm not familiar with it.

**Comment by balukantu** [comment]
Hi @davidfowl, Please check below link

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-analysis-appinsights

I am filtering the logs in application insights

**Comment by davidfowl** [comment]
Ah I see. That uses event flow, a different library that pushes logs to various sinks (including application insights).

Using the `ILogger` interface gets you a similar thing but with a different interface. What exactly do you want to know. Can you show your old and new code and what exactly you are trying to filter and accomplish?

**Comment by balukantu** [comment]
**Below is the log method in Service Fabric** 

![image](https://user-images.githubusercontent.com/18113877/76831067-9b44c500-684c-11ea-86aa-c828f3f979e8.png)

_Calling log method_

![image](https://user-images.githubusercontent.com/18113877/76831322-22923880-684d-11ea-9bc4-6ba1f41cb410.png)

_Filtering in Azure portal_

![image](https://user-images.githubusercontent.com/18113877/76831425-50777d00-684d-11ea-8387-725bd858e672.png)

![image](https://user-images.githubusercontent.com/18113877/76831454-62f1b680-684d-11ea-8e24-b0a94908a3c6.png)

**.NET Core logging**
![image](https://user-images.githubusercontent.com/18113877/76831570-946a8200-684d-11ea-8e6c-5945e227ae41.png)

_Log in Azure Appinsights_

![image](https://user-images.githubusercontent.com/18113877/76831728-e27f8580-684d-11ea-8e3f-9a2e3b71a274.png)


Please check and let me know if you need more details

**Comment by davidfowl** [comment]
@balukantu Thanks for that! I'd suggesting reading up on the logging abstractions here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1.

These sections on writing structured logs is probably what you care about:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-message-template

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-scopes

These will show up as custom properties you can write queries against.
