### ISSUE TITLE
Problem with raw IP endpoints for Microsoft.Extensions.Caching.StackExchangeRedis

### ISSUE THREAD

**Issue by ggprod** [dotnet/extensions#3100]
### Describe the bug
I recently debugged an issue connecting a .NET service using Microsoft.Extensions.Caching.StackExchangeRedis v2.2.5 (which uses StackExchange.Redis 2.0.593). The client could not connect to a Google Cloud MemoryStore managed Redis instance (these provide only private IP addresses for connectivity). It turned out the issue could be resolved by creating a name alias for the IP address and using the name instead. This seems strange and I'd expect raw IP address endpoints to work normally.

### To Reproduce
Connect from .NET service using the Microsoft.Extensions.Caching.StackExchangeRedis v2.2.5 to a Managed Redis service (in my case Google Cloud MemoryStore) via a raw IP endpoint

### Expected behavior
I would expect the client to be able to connect to a raw IP endpoint for Redis

### Additional context
By mapping a host alias to the raw IP I was able to resolve the issue.  This seems like it should be unnecessary

**Comment by anurse** [comment]
> I recently debugged an issue connecting a .NET service using Microsoft.Extensions.Caching.StackExchangeRedis v2.2.5

FYI, .NET Core 2.2 is end-of-life and no longer supported. You should strongly consider moving to a supported version of this package (3.1 is the latest Long-Term Support release). Having said that, I don't think this logic changed in 3.1 so I'll leave this open to investigate further.

**Comment by BrennanConroy** [comment]
This seems more appropriate in the StackExchange.Redis repo. We just pass through the options the user provides to the StackExchange.Redis package.
