### ISSUE TITLE
Feature request: Property Injection

### ISSUE THREAD

**Issue by athinboy** [dotnet/extensions#3136]
https://github.com/dotnet/aspnetcore/issues/2331
https://github.com/dotnet/aspnetcore/issues/2131

 @khellang @davidfowl 
 I do not understand ,why should we to use Autofac or Scrutor ? why do aspnetcore not support Property Injection?  just like :https://docs.spring.io/spring/docs/5.2.5.RELEASE/spring-framework-reference/core.html#beans

We are business application developer, the develop efficiency is very import!  why do  aspnetcore not support features that java has support ?

**Comment by davidfowl** [comment]
The answer hasn't really changed here (https://github.com/dotnet/extensions/issues/30190). The default dependency injection container isn't just an implementation but an abstraction that makes it possible to plug in other more advanced containers. We implement a basic spec that other containers already have support for and don't even consider adding new features unless they are supported in the containers that already work with the abstraction.

**Comment by athinboy** [comment]
OK，you are the decider。
But ，i think ,Injection is one of the  basic feature, aspnet.core support  injection completely  is  reasonbale. 
addtional,complete injection is basis of other import feature  such as monitor 、customer cache. 
more important, third inject implement  make thing become more complex, if there is bug/exception, i can not sure who is the helper. 
Any way,it seems to me that  whithout complete injection is not complete.  
thanks agagin!
