### ISSUE TITLE
IServiceCollection is not CLS Compliant

### ISSUE THREAD

**Issue by tmasternak** [dotnet/extensions#3147]
### Describe the bug
When compiling assembly that has `[assembly: CLSCompliant(true)]` written in C# that uses the `IServiceCollection` interface (version 3.1.3) in an argument to a public method on a public class, the compiler generates "Argument type `IServiceCollection` is not CLS-compliant" warning.

I could not figure out what is the exact reason for the interface being marked as not CLS-compliant.

Is this by design? Are there any information on what that might cause when used in different languages?

**Comment by anurse** [comment]
I don't know that it's "by design" that it's non-compliant but it's not designed to be explicitly CLS compliant (if that makes sense). Is CLS compliance required for your scenario?

**Comment by tmasternak** [comment]
@anurse thank you for the answer. 

I was trying to figure out the practical consequences of `IServiceCollection` not being CLS-compliant and if the team had any concrete case in mind that I should be aware of.

**Comment by anurse** [comment]
I believe it’s a somewhat outdated concept these days. What it means is that the assembly may not be usable from other languages that only implement the bare minimum required by the Common Language System ECMA spec. In practice, the commonly-used languages (C#, F#, VB) all work to ensure that they support the same feature set (which is beyond the CLS spec)

The CLS spec is quite a bit more limited, so CLS compliance means you can’t use certain features on public APIs, such as unsigned types. So we generally don’t try to stick to strict compliance these days.

**Comment by tmasternak** [comment]
@anurse thank you for the clarification.
