### ISSUE TITLE
Minimize the dependency subscriptions from this repository

### ISSUE THREAD

**Issue by ericstj** [dotnet/extensions#3210]
Now that we've removed most projects from dotnet/extensions we should be able to simplify the number of dependencies it subscribes to. 

Goals would be to ensure we're only subscribing to what we need so that we can recieve minimum updates.  We should also make sure the coherency is set up correctly so that we only get updates once they've flowed through ASPNETCore (or even higher stack) repo.

/cc @mmitche @JunTaoLuo @maryamariyan @anurse

**Comment by anurse** [comment]
Triage Notes:
* Everything in dotnet/extensions `master` today only depends on `dotnet/runtime`
* Probably some stuff in Version.Details.xml to clean-up.
