### ISSUE TITLE
Where is source for 'Logging.Abstractions'?

### ISSUE THREAD

**Issue by karataliu** [dotnet/extensions#3236]
### Describe the solution you'd like
It's present here:
https://github.com/dotnet/extensions/tree/d393ba3687063700bfebe900a20ecdd36ee59438/src/Logging

But not master, did it move to another repo?

**Comment by Herve-M** [comment]
Hello @karataliu, 

I was searching it too and I found this from an PR by `msftbot` : 

> As per [aspnet/Announcements#411](https://github.com/aspnet/Announcements/issues/411), we are currently migrating components from this repository to other repositories. This PR targets components that have been moved to [dotnet/runtime, in the src/libraries directory](https://github.com/dotnet/runtime/tree/master/src/libraries). 

So you can find `Microsoft.Extensions.Logging.Abstractions` src [here ](https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Logging.Abstractions) :-) 

Herve-M

**Comment by gfoidl** [comment]
FYI: https://source.dot.net/ is good tool to search sources within .NET Core.

**Comment by Pilchie** [comment]
Note that if you're looking for a specific, already released versions, they probably *did* come from this repo: https://github.com/dotnet/extensions/releases

**Comment by karataliu** [comment]
Thanks all for help.
Looks like this is what i'm looking for:
https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Logging.Abstractions
