### ISSUE TITLE
Support iLogger in DI with scoped lifetime

### ISSUE THREAD

**Issue by markm77** [dotnet/extensions#3259]
Hi there,

I am running integration tests on a .NET Core library using xUnit and have started to use the .NET generic host to allow same set up as most consuming apps would use.

I wanted to share a single .NET Generic Host between tests for efficiency and to avoid setting up and tearing down an IHost for each test. I set up an xUnit [collection fixture](https://xunit.net/docs/shared-context) for this purpose and then tried to set up an iLogger in DI with scope lifetime (each test was a scope) to allow independent logs per test but this proved impossible.

Due to xUnit's architecture the logging for each test needs to have a different provider which is mapped to the test's [ITestOutputHelper](https://xunit.net/docs/capturing-output) to capture logging output. If the DI supported an iLogger with scoped lifetime it would be possible to configure these providers at run-time using a technique like e.g. [this](https://stackoverflow.com/questions/40452263/configure-register-depdency-injection-scoped-service-from-within-the-scope).

Would you consider adding support for iLogger with scoped lifetime to the DI and .NET Generic Host?

BR,
Mark

**Comment by davidfowl** [comment]
No this is a breaking change. The alternative is using an async local within your logger implementation

**Comment by markm77** [comment]
Thanks @davidfowl , understand.

I'm trying to therefore find another solution.

Currently I log to the test log with the help of [xunit-logging](https://github.com/martincostello/xunit-logging) which allows wiring of each test's ```ITestOutputHelper``` to a *per-test* (not good I know) IHostBuilder as follows:

```csharp
            // Add XUnit logging
            builder.ConfigureLogging((hostingContext, logging) => { logging.AddXUnit(outputHelper); });
```

If I have a shared IHostBuilder  for all tests but yet still a single ```ITestOutputHelper``` per test, how can I set up logging to route to the correct ```ITestOutputHelper``` per test? Can you give me a few tips about this async local idea?

Many thanks for any help.

**Comment by markm77** [comment]
Okay I have a workaround - see https://github.com/martincostello/xunit-logging/issues/156. Will close this as not sure simply modifying ILogger to work with scoped lifetime is the right way forward anyway. For example what then happens to singletons depending on ILogger? I think more flexibility for ILogger logging to handle scenarios like this would be great but not sure I know enough to make a good proposal. Cheers!
