### ISSUE TITLE
Unsure about license

### ISSUE THREAD

**Issue by kbaley** [dotnet/extensions#3271]
The [Nuget page](https://www.nuget.org/packages/Microsoft.extensions.logging.abstractions) says the license is Apache-2.0. But I see in #2965 that the MIT license was adopted recently. Can I assume MIT is the license to be applied?

**Comment by Pilchie** [comment]
The existing shipped packages for .NET Core 3.1 and below are Apache-2.0, but we have relicensed for .NET 5, and Preview packages there and future versions will be MIT licensed.
