### ISSUE TITLE
TCP Connection limit reached due to KeyVault secret loading

### ISSUE THREAD

**Issue by matthijs-eigi** [dotnet/extensions#3295]
The changes introduced in this PR: https://github.com/dotnet/extensions/pull/944/files#diff-9500b0056e5444a814a78620512c46faR68

Do cause a huge spike in active TCP connections to an Azure KeyVault.
In our scenario we have an application that is loading four different KeyVaults. Every KeyVault holds somewhere between 80 and 100 secrets.

When the application starts, all the secrets will be listed first in a paging manner, and after all the secrets are listed, all tasks to get the actual secrets will fire all at once. This is causing a huge spike in TCP connections, and when running on standard app services this is causing issues and preventing any new TCP connections from being opened, and eventually this causes the application to hang during startup.

### Expected behaviour
The expected behaviour would be that the secrets are actually loaded in a paging manner, and not just listed in a paging manner.

**Comment by samuelbcollie** [comment]
I'm also having this issue and referenced it in this thread: https://github.com/dotnet/extensions/issues/3319

**Comment by matthijs-eigi** [comment]
Hey, is it possible we get some kind if update / acknowledgement on this issue? For now we downgraded the version of the NuGet Package.

**Comment by matthijs-eigi** [comment]
@Pilchie the issue is currently still open and unconfirmed. We had to downgrade our applications to the previous version of the keyvault package in order to actually be able to start them. Can we get some feedback on this issue?

**Comment by coder-candace** [comment]
Our team was able to get around this issue by adding some wait and retry logic around the code that connects to keyvault. Not ideal but at least keeps us from having to downgrade the package.

**Comment by BrennanConroy** [comment]
This will be fixed in the new Azure KeyVault package. https://github.com/Azure/azure-sdk-for-net/pull/15492
You should be able to upgrade to the Azure.Extensions.AspNetCore.Configuration.Secrets package once it is released.
