### ISSUE TITLE
 AddDistributedSqlServerCache to support Multiple Table References

### ISSUE THREAD

**Issue by j0nimost** [dotnet/extensions#3300]
### Challenge
I'm am trying to reference multiple cache tables but AddDistributedSqlServerCache only takes one
as shown below
```
services.AddDistributedSqlServerCache(options =>
            {
                options.ConnectionString = this.SeSPCache;
                options.SchemaName = "dbo";
                options.TableName = "VCache";
            });
```

### Describe the solution you'd like
If we could have an extension that can pick cache tables from `DbContext` then resolve to the correct cache table much like how modelBuilder for `Entity Framework` works.

### Describe alternatives you've considered
Currently, I have multiple data sources some sharing the same key so I have to concatenate a character to identify one from another.

**Comment by BrennanConroy** [comment]
@ajcvickers Do you understand the ask here? We don't quite understand it.

**Comment by ajcvickers** [comment]
@BrennanConroy No, sorry. No idea.

**Comment by BrennanConroy** [comment]
@j0nimost Could you explain your scenario please?

**Comment by j0nimost** [comment]
The question was if  `AddDistributedSqlServerCache` could support multiple table references. I had one service writing cache from different sources to the same table, 'VCache'. Ideally, I would like to have an option to write cache to different tables.

**Comment by BrennanConroy** [comment]
This is not a supported scenario.

It is possible if you manually add a service that creates instances of SqlServerCache with names internally.

**Comment by j0nimost** [comment]
Yes, I did that, though I was hoping for a simpler solution cause I ran to scenarios where there were too many reads on one table. It would have been simpler for my cache service to write cache to different tables and each service to consume its own cache accordingly thus distributing risk evenly.

**Comment by JunTaoLuo** [comment]
I think this is a feature we are unlikely to implement in 6.0 so I'm closing this issue.

**Comment by j0nimost** [comment]
Alright thanks @JunTaoLuo looking forward to it
