### ISSUE TITLE
Fix Configuration Serialisation

### ISSUE THREAD

**Issue by oliverjanik** [dotnet/extensions#3306]
Can we please reopen the discussion about null value handling in appsettings.json file?

The default behavior violates the principle of least surprise. I've just wasted 3 hours on this.

Previous discussions:
https://github.com/aspnet/Configuration/issues/788
https://github.com/aspnet/Configuration/issues/864
https://github.com/dotnet/extensions/issues/1341
https://github.com/dotnet/extensions/issues/3083
https://github.com/dotnet/runtime/issues/36510

Please understand that "this is how it works" and "by design" answers do not cut the mustard.

The entire world of JSON serialization serves as a precedent here. If I define a **null** I'm expecting a null not an **empty string**. It is appsettings.**json** after all.

Whatever the original design philosophy, you should look at addressing this. As evidenced by numerous links and questions on the internet, this issue trips people up.

**Comment by deeptowncitizen** [comment]
any updates on this?

**Comment by perason** [comment]
Also hit this issue...and need to know if this will be fixed or left as is?

**Comment by BrennanConroy** [comment]
Closing in favor of the Runtime issue https://github.com/dotnet/runtime/issues/36510
