### ISSUE TITLE
AddSingleton missing overload accepting variable args to pass directly to type ctor.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/extensions#3318]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example. I'm am trying to do [...] but [...]
I am trying to do this:
```cs
.AddSingleton<PatreonClient>(null, "PatreonToken.json")
```
However this would not work resulting in a compile error saying there is no overload accepting 2 parameters.

However doing this:
```cs
.AddSingleton(new PatreonClient(null, "PatreonToken.json"))
```
Works and compiles fine until you install the IDisposableAnyalzers then it says to not ignore created disposables.

There is a version that provides a way to do a custom factory however I do not want to create a custom factory to pass those in to it. I just want a version of AddSingleton that allows directly passing in the arguments that I want the DI library to then pass to the class's ctor.

### Describe the solution you'd like
I just want a version of AddSingleton that allows directly passing in the arguments that I want the DI library to then pass to the class's ctor.

### Describe alternatives you've considered
No other alternatives, I just do not want to implement a factory not just because it looks to not have examples on the microsoft docs.

### Additional context

![image](https://user-images.githubusercontent.com/15173749/84936497-511beb80-b0a8-11ea-8660-ab33ae2fdc9c.png)
![image](https://user-images.githubusercontent.com/15173749/84936624-89bbc500-b0a8-11ea-9583-34e696be0208.png)

**Comment by davidfowl** [comment]
A few things:
- Any feature we add needs to work for all 3rd party container implementations.
- Extra arguments for constructors messes with constructor selection.

It seems like you're trying to work around the analyzer? Do you want to own the lifetime or do you want the container to dispose it for you? If it's the latter then you can do this:

```C#
services.AddSingleton(sp => PatreonClient(null, "PatreonToken.json"));
```

**Comment by AraHaan** [comment]
I want to contain to dispose of it yes.

**Comment by davidfowl** [comment]
Then the workaround should be sufficient.
