### ISSUE TITLE
.NET Core Sdk is already installed. It is also prompt "dotnet-install:Downloading link :...."

### ISSUE THREAD

**Issue by StringZhang** [dotnet/extensions#3328]
### Describe the bug
.NET Core has not yet been installed. Running restore.cmd to install it.

.NET Core Sdk 3.1.301 is already installed,
But when I ".\startvs.cmd",
It is also Download .Net Core Sdk .

Is there something wrong with me?

https://s1.ax1x.com/2020/06/23/NYvbSH.png

![NYvbSH.png](https://s1.ax1x.com/2020/06/23/NYvbSH.png)

**Comment by Pilchie** [comment]
@dotnet/aspnet-build any ideas here?

**Comment by wtgodbe** [comment]
`startvs.cmd` checks to see if there is already a local dotnet installation, relative to where this repo is checked out on your box. If you just check out this repo and run `startvs.cmd`, it will install dotnet in a folder named `.dotnet` relative to the repo root - it doesn't care about the global dotnet installation on your machine. If you run `restore.cmd` then `startvs.cmd`, then startvs shouldn't need to install dotnet again.

**Comment by dougbu** [comment]
`startvs.cmd` only sets some environment variables before starting Visual Studio. It _requires_ you to have the correct SDK in the `.dotnet` folder. Running `restore.cmd` before using `startvs.cmd` is therefore necessary in a clean repo. But, something odd may be happening if you've done that.

What is the exact Visual Studio version you've got installed?

**Comment by StringZhang** [comment]
> 
> 
> `startvs.cmd` only sets some environment variables before starting Visual Studio. It _requires_ you to have the correct SDK in the `.dotnet` folder. Running `restore.cmd` before using `startvs.cmd` is therefore necessary in a clean repo. But, something odd may be happening if you've done that.
> 
> What is the exact Visual Studio version you've got installed?

Yes,I installed 3 versions of Microsoft Visual Studio
[

Microsoft Visual Studio EnterPrise 2015
版本 14.0.25431.01 Update 3

Microsoft Visual Studio EnterPrise 2017
版本 15.9.9

Microsoft Visual Studio EnterPrise 2019
版本 16.6.2

]

**Comment by dougbu** [comment]
Does `startvs.cmd` use 16.6.2❔

**Comment by StringZhang** [comment]
> 
> 
> `startvs.cmd` only sets some environment variables before starting Visual Studio. It _requires_ you to have the correct SDK in the `.dotnet` folder. Running `restore.cmd` before using `startvs.cmd` is therefore necessary in a clean repo. But, something odd may be happening if you've done that.
> 
> What is the exact Visual Studio version you've got installed?

Thanks !!! It is build success !

I download this file from this link "https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.301/dotnet-sdk-3.1.301-win-x64.zip",
Then copy the unzipped file to the {.dotnet} folder.
Run {restore.cmd}.
Finally open the solution with {Visual Studio}.

**Comment by StringZhang** [comment]
> 
> 
> Does `startvs.cmd` use 16.6.2❔

Yeah.
Open the soultion with {Microsoft Visual Studio EnterPrise 2019}


Thanks ! It is build success. :)

**Comment by StringZhang** [comment]
> 
> 
> @dotnet/aspnet-build any ideas here?

Thanks! 👍 🌹

**Comment by StringZhang** [comment]
Thanks everyone for this issue, 
Please forgive me for my poor english...
🌹
