### ISSUE TITLE
Ship Microsoft.Extensions.Logging.Analyzers

### ISSUE THREAD

**Issue by shirhatti** [dotnet/extensions#3434]
### Is your feature request related to a problem? Please describe.

`Microsoft.Extensions.Logging.Analyzers` is currently not a shipping package.

https://github.com/dotnet/extensions/blob/master/src/Logging/Logging.Analyzers/src/Microsoft.Extensions.Logging.Analyzers.csproj#L12

**Comment by shirhatti** [comment]
@pakrym Would you happen to remember why we never shipped this package?

**Comment by pakrym** [comment]
Lack of resources/desire.

**Comment by KalleOlaviNiemitalo** [comment]
Also requested in <https://github.com/dotnet/runtime/issues/36064>.

**Comment by slang25** [comment]
I'm really keen to see this released. We had a production incident that would have been avoided with this analyzer.

**Comment by slang25** [comment]
Hi @BrennanConroy, sorry to pester you, I'm curious where this sits in your current plans, can we expect to see this in the coming months?

**Comment by BrennanConroy** [comment]
Our team doesn't own this anymore, @maryamariyan could you triage this, or close if you want to use https://github.com/dotnet/runtime/issues/36064 to track the work instead.

**Comment by shirhatti** [comment]
Closing this as a duplicate of https://github.com/dotnet/runtime/issues/36064
