### ISSUE TITLE
Microsoft.Extensions.Caching.StackExchangeRedis AddStackExchangeRedisCache automatic connection string

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/extensions#3463]
AddStackExchangeRedisCache doesn't work like other Azure services, as it requires one to explicitly set the connection string, such as

```c#
                Action<Microsoft.Extensions.Caching.StackExchangeRedis.RedisCacheOptions> SetServiceOptions = (serviceOptions) =>
                {
                    serviceOptions.Configuration = configuration.GetValue<string>("CacheConnection");
                };
                services.AddStackExchangeRedisCache(SetServiceOptions);
```

Other Microsoft services will fetch a specifically named app setting, such as Azure__SignalR__ConnectionString, see https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core#add-azure-signalr-to-the-web-app - "This secret will contain the connection string to access your SignalR Service resource. Azure:SignalR:ConnectionString is the default configuration key that SignalR looks for to establish a connection." In other words, in the other services I have used it works without explicitly fetching the connection string from the secrets as the system will internally fetch a specifically named variable, while Redis requires you to explicitly set the configuration.

Furthermore this is not documented anywhere, pure trial and error led me to figure this out. I filed a bug about it not being documented at https://github.com/dotnet/AspNetCore.Docs/issues/19680.

**Comment by BrennanConroy** [comment]
This isn't something we generally do across the stack, but the docs would be great to update!
