### ISSUE TITLE
secrets.json not overiding information under Values

### ISSUE THREAD

**Issue by fvalencia12** [dotnet/extensions#3471]
### Describe the bug
I have information in my local.settings.json under Values that I need to keep secret. From the documentation it states that hierarchical values need to be flatten in the form of:

"Movies": {
    "ConnectionString": "Servocaldb;Database=Movie-1;Trusted_Connection=True;MultipleActiveResultSets=true",
    "ServiceApiKey": "12345" 

would turn into:

"Movies:ServiceApiKey": "12345"

I am doing the same for an item under Values. I have a queue connection string that I would like to keep secret.  I am doing the same and for some reason it is not working as expected. This is the format I'm using:
"Values:changerequestqueue": "DefaultEndpointsProtocol=https;AccountName=xxxxx;AccountKey=IVgw==;EndpointSuffix=core.windows.net"

When my azure function executes, it states "Storage account connection string for 'AzureWebJobschangerequestqueue' is invalid

### To Reproduce
1. Using versions 
    Function Runtime Version: 3.0.14191.0
    Azure Functions Core Tools (3.0.2798 Commit hash: d9d99872a51c04b1c2783198b1ee1104da6b064f)

Any idea of why the code is not doing what is expected or am I missing something?

Thanks
Regards

**Comment by BrennanConroy** [comment]
cc @fabiocav for functions

**Comment by BrennanConroy** [comment]
@fvalencia12 Just to double check, you've added user secrets to your csproj and app? A runable sample would be useful.

**Comment by fabiocav** [comment]
@fvalencia12 proper support for user secrets (the .NET feature) was added in version 3.0.2852 of the core tools. Can you please try with that version and follow up if you continue to have problems?

Some of the information here is also a bit vague, if you continue to run into issues, can you please open an issue at https://github.com/Azure/azure-functions-core-tools/issues and share your actual files?

**Comment by gzuber** [comment]
@fvalencia12 please @ me as well if you still run into this after upgrading -- I should be able to help with any issues related to user secrets support in functions

**Comment by fvalencia12** [comment]
> @fvalencia12 proper support for user secrets (the .NET feature) was added in version 3.0.2852 of the core tools. Can you please try with that version and follow up if you continue to have problems?
> 
> Some of the information here is also a bit vague, if you continue to run into issues, can you please open an issue at https://github.com/Azure/azure-functions-core-tools/issues and share your actual files?

It is working as expected now. Thanks for your help!!!
