### ISSUE TITLE
What about updating the docs to reflect this will break in future releases?

### ISSUE THREAD

**Issue by V4A001** [dotnet/extensions#3477]
What about updating the docs to reflect this will break in future releases?

https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#capturing-ilogger-logs-from-startupcs-programcs-in-aspnet-core-applications

_Originally posted by @gregpakes in https://github.com/dotnet/extensions/issues/1096#issuecomment-500589210_

**Comment by V4A001** [comment]
A wast to experience that documentation is not updated, and which the various teams of Microsoft working apart of eachother leading to a lot of confusion.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/MicrosoftDocs/azure-docs/pull/33059> already added a note about "ASP.NET Core 3.0 and later"; is that not enough?

**Comment by Pilchie** [comment]
@Rick-Anderson - can you help route this?

**Comment by Rick-Anderson** [comment]
@Pilchie  please close this, I created https://github.com/MicrosoftDocs/azure-docs/issues/61816

**Comment by Pilchie** [comment]
Thanks @Rick-Anderson !
