### ISSUE TITLE
Microsoft.Extension.Configuration.Json.AddJsonFile of an JSon Array file fails with Error: Unsupported JSON token 'Array' was found.

### ISSUE THREAD

**Issue by ppadial** [dotnet/extensions#3543]
### Describe the bug

Having a Json file with content

```json
[
 "hello", "world"
]
```

when i do

```csharp
IConfigurationRoot configuration =
                        new ConfigurationBuilder()
                            .AddJsonFile(PathToTheFile, optional: true, reloadOnChange: true)
                        .Build();
```

It throws: Error: Unsupported JSON token 'Array' was found.

Not sure if it's a bug or i'm missing something. When i save List<String> into the file using JsonSerialize it writes it in the same way i have it.

### To Reproduce
1. Using version '3.1.8' of package 'Microsoft.Extensions.Configuration.Json'
2. Run the code in the description
4. See error: Error: Unsupported JSON token 'Array' was found.

### Expected behavior

I think it should load the array, or at least don't fail due the file format.

### Additional context

SDK Version: 3.1.302

**Comment by BrennanConroy** [comment]
It makes sense that this is failing, config expects key-values, and that is just a value.

We can look at cleaning up the error message to be clearer.

**Comment by kevin-wittmer** [comment]
@BrennanConroy I'd like to work on this issue. How do you think we can clean up the error message to make it clearer?

**Comment by BrennanConroy** [comment]
Haven't looked into it too much, but we probably want to say something about expecting a key instead of a value.

**Comment by kevin-wittmer** [comment]
Ok, I'm going to start working on this issue. Can you assign it to me?
