### ISSUE TITLE
Backport Fix memory leak with OptionsMonitor #868 to .NET Core 2.1

### ISSUE THREAD

**Issue by shantha05** [dotnet/extensions#3552]
**Issue**
Currently there is a memory leak in using OptionsMonitor in .NET Core 2.1 and this has been fixed as part of .NET Core 3.0 and above. (https://github.com/dotnet/extensions/pull/868)

**Solution**
Given .NET Core 2.1 has LTS support until 21-08-2021, is it possible to backport this fix to .NET Core 2.1

**Alternatives considered**
There is no alternative other than upgrading to .NET Core 3.1 and we have a lot of dependencies that needs to be considered which is not going to help us to resolve the memory leak issue in a timely fashion.

**Comment by davidfowl** [comment]
Did you run into this l? If so where?

**Comment by shantha05** [comment]
Yes, we are using .NET Core 2.1 API hosted on Azure and we are seeing the memory leak behavior there.

**Comment by davidfowl** [comment]
How did you reproduce the issue? This particular one required multiple host instantiations and disposals. Did you track down what caused the problem in your case?

**Comment by shantha05** [comment]
We had multiple app services hosting this API on Azure and we noticed the memory leak behavior with the the implementation of OptionsMonitor and OnChange event and when I commented invoking the OnChange event the memory leak stopped.

**Comment by davidfowl** [comment]
@shantha05 were you disposing the `IDisposable` returned from OnChange in your scenario and it was still leaking?

**Comment by shantha05** [comment]
Yes, it was also tried and still it was leaking memory

**Comment by davidfowl** [comment]
Were you spinning up multiple instances of the host in a single process? The reason I'm asking these questions is because that PR fixes a very specific issue that would be hard to reproduce without doing something atypical.

**Comment by shantha05** [comment]
We had 2 different App Services in 2 resource groups hosted in 2 locations and routing traffic using Traffic Manager so it's 2 different processes

**Comment by davidfowl** [comment]
Then I don't see how that specific PR fixes the issue you're describing. Can you show the code snippet of the leak?

**Comment by shantha05** [comment]
This is the code that was commented to stop the memory leak.

productsOptions.OnChange((config) => {
    _productSettings = config;
});

where productOptions is IOptionsMonitor<Products> productsOptions

**Comment by davidfowl** [comment]
How often did you call OnChange? Once per application? Or once per request? Where is the code that stores the result and disposed it

**Comment by shantha05** [comment]
The API is called 'n' number of times as part of the CertificateAuthenticationHandler once per request. Every CertificateAuthenticationHandler registers itself to the OptionsMonitor.OnChange event.

**Comment by davidfowl** [comment]
Can you show the registration and disposal code?

**Comment by shantha05** [comment]
private IDisposable _listener;

        public CertificateAuthenticationHandler(
            IProductRepository repository, 
            IOptionsMonitor<Products> productsOptions,
            IOptionsMonitor<CertAuthenticationOptions> options, 
            ILoggerFactory loggerFactory, 
            UrlEncoder encoder, 
            ISystemClock clock) 
            : base(options, loggerFactory, encoder, clock)
        {
            _repository = repository;
            _productSettings = productsOptions.CurrentValue;
            _listener = productsOptions.OnChange((config) => {
                _productSettings = config;
            });
        }

        ~CertificateAuthenticationHandler() {
            _listener.Dispose();
        }

**Comment by davidfowl** [comment]
Why is there a finalizer? Make the `CertificateAuthenticationHandler` implement IDisposable and call _listener.Dispose in the Dispose method. That should solve your problem.

**Comment by davidfowl** [comment]
Even better would be to use IOptionsSnapshot\<T\> to get the current snapshot of options (assuming this service is scoped or transient). That would resolve the lifetime mismatch going on here.

**Comment by shantha05** [comment]
Thanks David. Let me give that a try
