### ISSUE TITLE
Is there a way to extend IDistributedCache to execute different Redis commands.  

### ISSUE THREAD

**Issue by ram62836** [dotnet/extensions#3592]
In my case, I need to create another method to execute Redis KEYS command to get keys matching wildcard search.
OOTB IDistributedCache only supports Get, Set, Refresh and Remove methods.

**Comment by BrennanConroy** [comment]
No, this is not possible. You can use redis directly.

**Comment by ram62836** [comment]
> No, this is not possible. You can use redis directly.

Thanks for the info.
