### ISSUE TITLE
Please make AzureKeyVaultConfigurationProvider public or add an Insert extension method

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/extensions#3642]
### Is your feature request related to a problem? Please describe.
The current problem is that AzureKeyVault configuration source should be lowest priority. That is, you should be able to override it with environment variables etc. but you can't because it is added last and as a result it takes precedence.

### Describe the solution you'd like
If AzureKeyVaultConfigurationProvider was public then people that need to change this could easily insert the source into the IConfigurationBuilder wherever they wished.

### Describe alternatives you've considered
Alternatively, adding an index to the Add or creating Insert equivalent extension methods would also work to solve the problem and allow end users to put it in whatever order of precedence they wished.

### Additional context
This is required all of the time for kubernetes, docker and many other places, especially local dev where you want most of your keys in Azure KeyVault but want to override a few for the specific environment without having to create and maintain an entirely new keyvault for no reason.

**Comment by Pilchie** [comment]
Note that this package has been removed, and support for KeyVault integration should now be done via the package Azure.Extensions.AspNetCore.Configuration.Secrets, as announced [here](https://github.com/aspnet/Announcements/issues/408)

**Comment by JohnGalt1717** [comment]
Thanks.... Yet another move of stuff with no indication that the stuff you're using is depreciated. This library should have all of it's calls marked as obsolete and a new version released so that anyone that gets the update sees the warnings.
