### ISSUE TITLE
How to Remove all keys?

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/extensions#3665]
Hi
We use Microsoft.Extensions.Caching.Redis in .net core 3.1 project.
We want to remove all redis key by prefix , for example remove all data that there keys start with customre (customer01,customer02,...)
How to find these keys and remove?

**Comment by jkotalik** [comment]
We don't believe there is a way to do this today with our distributed cache system. You may need to write something custom with StackexchangeRedis with a custom query.

What are you trying to accomplish by removing these keys?

**Comment by mammadkoma** [comment]
// inject
services.AddSingleton<IConnectionMultiplexer>(ConnectionMultiplexer.Connect("yourConnectionString"));

public YourController : Controller
{
    private readonly IConnectionMultiplexer _connectionMultiplexer;
    public YourController(IConnectionMultiplexer multiplexer)
    {
        this._connectionMultiplexer = multiplexer;
    }
}

// use
foreach (var ep in _muxer.GetEndPoints())
{
    var server = _muxer.GetServer(ep);
    var keys = server.Keys(database: _redisDatabase, pattern: "customer"+ "*").ToArray();
    _db.KeyDeleteAsync(keys);
}

**Comment by davidfowl** [comment]
I'd recommend using redis directly. IDistributedCache doesn't support this operation
