### ISSUE TITLE
Please update the redis package to fix problems and improve

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/extensions#3667]
Please update the redis package to fix problems and improve

update https://github.com/StackExchange/StackExchange.Redis

**Comment by BrennanConroy** [comment]
What issues are you seeing?

Are you not able to reference a newer version of StackExchange.Redis yourself to get any fixes/improvements?

**Comment by EngRajabi** [comment]
current version in idistributecache(redis) => 2.0.593
leates version => 2.1.58

release note => https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes

**Comment by jkotalik** [comment]
What specific problems are addressed between 2.0.593 and 2.1.58? 

You can also update the package manually by directly referencing the StackExchange.Redis package in your csproj.

**Comment by EngRajabi** [comment]
To reduce timeout errors as well as thread shortages.
https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/Timeouts.md

I do not have a problem with using the package update in my project ??
The changes may have been extensive and could not be used with the update

**Comment by BrennanConroy** [comment]
> I do not have a problem with using the package update in my project

Glad to hear it. Since there have been no breaking changes with StackExchange.Redis yet, there is no need for us to change our dependency.
