### ISSUE TITLE
dependency injection of internal services.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/extensions#3671]
I just found out that there's a limit on the services to be injected in aspnet core. It doesn't support `internal` classes 🤯

Like: 
```C#
internal MyService(IMapper mapper) { } 
internal interface IMapper { }
```

is there any workaround ?

**Comment by davidfowl** [comment]
It does support internal classes just not internal constructors.

**Comment by Bartmax** [comment]
Great piece of information! my ultimate goal was to have my entities internal and only expose Dto's only from this assembly.

Your comment totally helped me accomplish that by making an interface with internal methods and then implement those excplicit or an internal interface with public methods.

The problem I was facing is that by having public constructor with internal dependencies makes for parameter less accessible than method and it eventually bite me somewhere in the chain. Not sure if this is the common way to solve this scenario but definitely looks like it will work for my use case. 

Thank you @davidfowl 
For completeness this is what I ended up having:

```c#
public class InventoryController : ControllerBase
{
    public InventoryController(IInventoryService service) { ... }
}
public interface IInventoryService { ... }
internal class InventoryService : IInventoryService
{
    private readonly ApplicationDbContext db;
    private readonly IMapper mapper;

    public InventoryService(ApplicationDbContext db, IMapper mapper) { ... }
}
internal interface IMapper
{
    DeviceDto Map(Device entity);
}
internal class Mapper : IMapper
{
    public DeviceDto Map(Device entity) => new DeviceDto();
    // or explicit implemented
}

internal class Device { ... } // Mission accomplished.
public record DeviceDto { ... }
```
