### ISSUE TITLE
Make the Test environment a first class citizen in Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by vmrocha** [dotnet/extensions#3696]
### Is your feature request related to a problem? Please describe.
It is not really a problem, since we can extend it with a test environment ourselves.

### Describe the solution you'd like
Add a method to HostEnvironmentEnvExtensions to check for a test environment:
```csharp
        public static bool IsTest(this IHostEnvironment hostEnvironment)
        {
            if (hostEnvironment == null)
            {
                throw new ArgumentNullException(nameof(hostEnvironment));
            }

            return hostEnvironment.IsEnvironment(Environments.Test);
        }
```

Add Test to the Environments class:
```csharp
    public static class Environments
    {
        public static readonly string Development = "Development";
        public static readonly string Staging = "Staging";
        public static readonly string Production = "Production";
        public static readonly string Test= "Test";
    }
```

### Describe alternatives you've considered
Create an extension method ourselves.

### Additional context
Maybe we need a different configuration on the Startup class for the Test environment.

**Comment by BrennanConroy** [comment]
We have no plans on doing this. You can write your own extension method to do this.

These names have no meaning inside our library code. It is only used in our templates or by other users.
