### ISSUE TITLE
Scope services not fully scoped in ASP.NET/IIS

### ISSUE THREAD

**Issue by nevnet** [dotnet/extensions#3708]
Using Microsoft.Extensions.DependencyInjection **Version 2.1.1**

Having a bit of trouble with scoped services in ASP.NET, .NET 4.7.1, IIS (integrated pipeline mode)
I'm using a commercial product (Sitecore CMS) so I'll try to distill the issue without mentioning Sitecore specifics.

If I register a scoped service, then it appears to resolve correctly in most places that I need to use it (mostly MVC controllers).

However, in some of the more unusual places where I try to resolve the service, I *sometimes* but not *always* get back a different instance. In my use case, I'm trying to resolve a service in the EndRequest and PostReleaseRequestState events which had otherwise resolved just fine in earlier events in the request pipeline.

I believe it has something to do with this:

Scoped services are stored in CallContext. CallContext will only flow between IIS request pipeline events if IIS decides to allocate the same thread to each event. Most of the time - at least in my testing - I get the same thread, but there is no guarantee and I suspect a system under load will more frequently allocate different threads to each event. Also, the closer to the end of the request pipeline you get, the more likely you have picked up a different thread and lost your original CallContext. HttpContext.Items gets around this by explicitly doing something to copy itself to the new CallContext if there is ever a change of thread. The provider managing the scoped services, however, does NOT appear to do this when perhaps it SHOULD be doing something to preserve its state across IIS request pipeline events.

As it stands, I would only describe a scoped service as "Scoped, but only if IIS doesn't mess with your threads" - Which makes it dangerous to rely on.

I had tried to hack round this by hooking into the OnExecuteRequestStep event and trying to copy the provider's state before and after each pipeline executes but can't seem to get it working. I've also tried stuffing the provider or my scoped service into HttpContext.Items, but that suffers from another issue where the context is lost after any async/await call where the task is not resumed on the AspNetSynchronizationContext, and I still end up resolving a different object.

The savior here may actually be having the scoped provider backed by AsyncLocal. AsyncLocal has the benefit of not being tied to the synchronization context so this will survive in an async environment. AsyncLocal is still stored in CallContext, but this part could be solved copying the behavior of HttpContext.Items and having it flow across pipelines if there is a thread change using whatever magic the ASP.NET team uses here.

I don't feel like I'm trying to do anything radical here, but I would expect a scoped service to be resolvable from any event in the request pipeline without any additional effort from the developer. I'm finding it hard to believe that I'm the first person to come across this and I'm hoping it isn't a Sitecore specific issue.

**Comment by BrennanConroy** [comment]
When are you creating a request scope? You have to manage the scope state yourself in ASP.NET Full Framework so if you clean the scope up before running your EndRequest logic then you will get a different instance.

**Comment by nevnet** [comment]
Are you saying Sitecore is likely responsible for managing how scoped services work? I believe services are registered by way of IServiceCollection during the BeginRequest event. Any registered scoped services are definitely resolving in most pipelines until PostRequestHandlerExecute, but after that I seem to get odd behavior. I can't confirm if that is because I'm just lucky to keep getting the same thread until that point, or if Sitecore is doing something to ensure the scope's state survives to that point and then stops trying to preserve it after that and leaving it to chance.

If you're saying the scoped provider is managed by Sitecore, that provides an interesting opportunity to decompile their source code to try and find out what their doing to handle scoped services and might put me on a better path to finding a solution.

Perhaps I had incorrectly assume the Microsoft.Extensions.DependencyInjection component was responsible for or even cared about managing request-scoped services in ASP.NET? I'm happy to be wrong in this case as I can then make it Sitecore's problem and file a bug with them.

**Comment by nevnet** [comment]
Confirming that Sitecore has implemented their own IHttpModule that appears to be trying (poorly) to implement per-request scope. I suspect I can override their implementation to solve my issues. Clearly this is not a bug in Microsoft.Extensions.DependencyInjection, but hopefully my description is useful to the next Sitecore dev that comes along looking for an answer.

Thanks for the help!
