### ISSUE TITLE
Please add git tag for .NET 5.0 RTM

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/extensions#3715]
### Is your feature request related to a problem? Please describe.

I want to easily find source code for 5.0.0 versions of packages built from the <https://github.com/dotnet/extensions> repository. There is a Git tag and a GitHub release for [.NET 5.0 Preview 8](https://github.com/dotnet/extensions/releases/tag/v5.0.0-preview.8.20414.8) but no tag for .NET 5.0 RTM.

### Describe the solution you'd like

Please add a Git tag for .NET 5.0 RTM, and perhaps a GitHub release as well.

### Describe alternatives you've considered

Extract nuspec files from NuGet packages and get the commit ID from `<repository type="git" url="https://github.com/dotnet/extensions" commit="293a5600acbca18ecef424745d7a2543f86ee58e" />`, then create a tag in a local clone of the repository.

### Additional context

293a5600acbca18ecef424745d7a2543f86ee58e is listed as the commit ID in these NuGet packages:

* Microsoft.Extensions.Caching.SqlServer/5.0.0
* Microsoft.Extensions.Caching.StackExchangeRedis/5.0.0
* Microsoft.Extensions.Configuration.NewtonsoftJson/5.0.0
* Microsoft.Extensions.Hosting.Systemd/5.0.0
* Microsoft.Extensions.Hosting.WindowsServices/5.0.0
* Microsoft.Extensions.Http.Polly/5.0.0

I believe no other 5.0.0 packages are published from this repository.

**Comment by benaadams** [comment]
There's a branch for it? https://github.com/dotnet/extensions/tree/release/5.0

**Comment by KalleOlaviNiemitalo** [comment]
Isn't release/5.0 the branch from which 5.0.1 will also be released? So it won't match the 5.0.0 packages.

**Comment by BrennanConroy** [comment]
@rbhanda This should have been done automatically?

**Comment by Pilchie** [comment]
I think because no packages from extensions were reachable from the SDK it might have gotten missed?

**Comment by JunTaoLuo** [comment]
FYI the 5.0.0 RTM tags have been added manually for now.

**Comment by KalleOlaviNiemitalo** [comment]
How about a v3.1.11 tag, as well? That would be 77d62c5738da86985cf69ba0479539b6fdbc904e, according to the nuspec shown at <https://www.fuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices/3.1.11>.

**Comment by rbhanda** [comment]
Hi @KalleOlaviNiemitalo GitHub repo tagging is taking longer than expected. Current ETA is by EOD today (14th Jan 2021)
