### ISSUE TITLE
Restore InplaceStringBuilder

### ISSUE THREAD

**Issue by Lizzy-Gallagher** [dotnet/extensions#3800]
### Is your feature request related to a problem? Please describe.
My team at work maintains a series of internal NuGet packages. For one of these NuGet packages, we wanted to update to Microsoft.Extensions.Configuration version 5.0.0, but quickly found it to be incompatible with ASP.NET Core version 2.2.

Specifically, on startup, the following error is thrown:
```c#
System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```
with a stack trace deep in the internals of Razor compilation (can share if it is useful).

This makes sense because `InplaceStringBuilder` was made obsolete in https://github.com/dotnet/extensions/pull/878 and removed in some later version.

It is not feasible for us to require all consumers of our internal NuGet package to update to ASP.NET Core version 3+ (as that mandates updating to .NET Core at the same time). This means that we cannot use Microsoft.Extensions.Configuration version 5.0.0 in our NuGet package.

### Describe the solution you'd like
For InplaceStringBuilder to be restored (but remain obsolete). From our perspective, removing this API was unnecessarily disruptive given that it is required for ASP.NET Core v2.2 and below.

### Describe alternatives you've considered
Fixing our version of Microsoft.Extensions.Configuration until 100% of our consumers can update to .NET Core (which means we will likely never update to latest).

**Comment by davidfowl** [comment]
You can also consider cross compiling your package to target netcoreapp2.2 and using a lower version of **Microsoft.Extensions.Configuration**.

**Comment by Pilchie** [comment]
Typically, we don't test Microsoft.Extensions packages against older frameworks than the major.minor that matches their package version.  In some cases they work but we don't typically recommend it.  Instead, as @davidfowl suggests, a better path would likely to be have your package multi-target and have different dependencies depending on what TargetFramework it is being used in.

@DamianEdwards - did we ever get any library author guidance on this sort of scenario written up?

**Comment by Pilchie** [comment]
We don't plan to do this - our suggestion would be to multi-target your package so that apps targeting older versions use the matching version of the Microsoft.Extensions.Configuration package.

On a separate front, I'll point out that 2.2 has been [out of support](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core) since 2019-12-19, and is no longer being patched, including for security issues.  You should be using 2.1 if you need .NET Framework support or else updating .NET Core 3.1/.NET 5.
