### ISSUE TITLE
ApplicationLifetime borrows CancellationToken  to regisier and raise events, I feel is bad idea and confusing.

### ISSUE THREAD

**Issue by RyanLiu99** [dotnet/extensions#3801]
Look at sourc code,  https://github.com/dotnet/extensions/blame/494e2c53cd0ea075ba3783748d62c66bc4a353e2/src/Hosting/Hosting/src/Internal/ApplicationLifetime.cs, look at property like 

public CancellationToken ApplicationStarted => _startedSource.Token;

I see it uses  CancellationToken  mechanism to register event handler and raise events, I feel this is really bad idea, it is really confusing.  It is noting about "Cancellation", all about call back action. 

I think it is better never "borrow" things.  If it is event handing, do it "Event" way!

**Comment by gfoidl** [comment]
For a rationale why CancellationTokens are used you can read https://github.com/dotnet/runtime/issues/20242

**Comment by davidfowl** [comment]
Right, and that ship as long sailed.
