### ISSUE TITLE
Dead end the Config.NewtonsoftJson package

### ISSUE THREAD

**Issue by Anipik** [dotnet/extensions#3816]
There hasnt been any functional change After ```May 10, 2019```  in this package, so i think we should dead end the package.

We are moving the rest of hosting packages to dotnet/runtime https://github.com/dotnet/runtime/pull/47686.

cc @JunTaoLuo @dougbu @wtgodbe @ericstj @eerhardt @mmitche

**Comment by ericstj** [comment]
To do this we should add it to the readme that talks about the state of all the extensions packages.

When we do it, we should make sure all downstream repos in the product know to roll back to the 5.0.x version of the package rather than expect any updates to the 6.0.x prerelease package.
