### ISSUE TITLE
Archive the Extensions repo

### ISSUE THREAD

**Issue by Anipik** [dotnet/extensions#3834]
we are no longer producing any shipping assets from the extensions repo so it would make sense to archive the repo

- [x] Move the hosting tests to the runtime repo.
- [x] Decide what to do with non-shipping assets like logging analyzers.
- [x] Disable dependency updates for master

cc @ericstj @eerhardt @ViktorHofer @safern @maryamariyan

**Comment by ViktorHofer** [comment]
With "archive the repo" you don't actually mean using GH's archiving feature? We can't do that for the same reasons as for corefx and coreclr which is servicing until 3.x is out of support.

**Comment by Anipik** [comment]
> We can't do that for the same reasons as for corefx and coreclr which is servicing until 3.x is out of support.

basically do something similar to what we did in corefx and coreclr

**Comment by Anipik** [comment]
> @Anipik what's left to-do?

port the hosting tests.

**Comment by Anipik** [comment]
https://github.com/dotnet/runtime/pull/49716
