### ISSUE TITLE
aspnet core 3.0 DI Bug when constructor value type with default value

### ISSUE THREAD

**Issue by cyrusdargahi** [dotnet/extensions#3857]
### Description

When a class is registered with service collection as transient and that class constructor has a parameter with a value type, but that parameter has a default value, then when it is resolved in runtime, the first two times it works as expected and the parameter is set to the default value, but on subsequent service resolutions the parameter will be given "bizarre" values that are not declare anywhere within the application code.

I have created a repo with an example and explanation https://github.com/cyrusdargahi/aspnetcore3DIBug

### To Reproduce
Build and run the application. On first and the second load in the browser you should see the output 0.01.

### Error
On any page reloads after the (exactly) first two, weird thing start to happen. The output will now be a bizarre number taken from somewhere that isn't defined anywhere in the application code.

### Expected behavior
Expected result is the page should display the constant 0.01 result on any page (re)load.

**Comment by BrennanConroy** [comment]
@davidfowl I assigned you in October, are you planning on doing this or should we assign to someone else?

**Comment by eerhardt** [comment]
> [5.0 fix](https://github.com/dotnet/extensions/pull/2501)

Note to whoever backports this, the original 5.0 fix caused other regressions

- https://github.com/dotnet/runtime/issues/37337
- https://github.com/dotnet/runtime/issues/42037

So we will want to backport the original fix, plus https://github.com/dotnet/runtime/pull/42152 and https://github.com/dotnet/runtime/pull/44675 at the same time. All those together are the complete fix.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/extensions/pull/3861
