### ISSUE TITLE
Add support for Property Injection

### ISSUE THREAD

**Issue by geetmenon** [dotnet/extensions#3898]
We have a class that has around 15 optional dependencies. 1 or at most 2 of these 15 dependencies are required during any  api call. We have been using Unity's Property Injection feature for this until now. As part of migrating from .NetFramework to .Net Core, we now are moving from Unity to Microsoft.Extensions.DependencyInjection. We don't want to be including all of these 15 dependencies in the constructor, for one it becomes too long but more importantly most of them are really optional. So please add support for Property Injection. We really need this feature.

**Comment by geetmenon** [comment]
I am expecting Microsoft's typical answer would be something like "You are hiding your dependencies and that is a really bad thing to do". But in our case these are truly optional dependencies and we don't want all the dependencies to be injected via constructor knowing that 90% of them will never be used during the call. And that is the reason why Unity & AutoFac had added support for ProperyInjection. So why is Microsoft not providing this feature?

**Comment by adityamandaleeka** [comment]
Triage: We don't plan to add this feature in Microsoft.Extensions.DependencyInjection at this time. For what it's worth, Unity and AutoFac work on .NET Core so you could continue using what you were before.

**Comment by adityamandaleeka** [comment]
https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#default-service-container-replacement

**Comment by geetmenon** [comment]
This is disappointing. Is there a workaround to achieve something similar to Property Injection?

From what I understand, Unity does not provide the equivalent of a Transient (i.e. PerRequest) lifetime in Unity 5.0 and we are therefore forced to use Scoped (i.e. PerResolve) lifetime, and they have stopped adding any further changes to Unity. That is why we want to move from Unity to Microsoft.Extensions.DependencyInjection .

Hope Microsoft sees value in adding support for Property Injection in the near future.
