### ISSUE TITLE
Allow passing a ConnectionMultiplexerFactory or Instance to AddStackExchangeRedisCache

### ISSUE THREAD

**Issue by evilpilaf** [dotnet/extensions#3903]
Currently the implementation for `AddStackExchangeRedisCache` only lets developers configure a connection string or connection options for setting up the Redis connection, it'd be very useful if it was also possible to pass in a `ConnectionMultiplexer` instance or factory, dus letting us reuse connections to caches.

This would also let us plug in with OpenTelemetry as it requires a ConnectionMultiplexer object in order to set the telemetry information.

**Comment by adityamandaleeka** [comment]
@evilpilaf We added this in .NET 6 Preview 5: https://github.com/dotnet/aspnetcore/pull/32266/
