### ISSUE TITLE
Improve FakeTimeProvider into a canonical fake

### ISSUE THREAD

**Issue by danmoseley** [dotnet/extensions#3996]
The one in this repo has some issues/limitations, 

1. Consider allowing an arbitrary TimespanFrequency.

Currently it is set to 10^7 == TimeSpan.TicksPerSecond. The actual TimeProvider.System uses TimespanFrequency  == Stopwatch.Frequency == typically 10^6 or 10^9 (and does not change once the system is started).  A different TimespanFrequency could help spot bugs where code assumes TimeSpan.TicksPerSecond. 

Note that while GetElapsedTime() abstracts Frequency, Kestrel generally does math like `Expiration = currentTimestamp + timeoutTimeSpan.TotalSeconds * timeProvider.TimespanFrequency`, and then later `if (currentTimestamp > Expiration) ... `. See [here for some examples](https://github.com/dotnet/aspnetcore/pull/48081/files)

If TimespanFrequency changes we would need to take care about truncation. We [don't do math here](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.TimeProvider.Testing/FakeTimeProvider.cs#L93-L94) in order to keep stable test results - essentially long has more digits than double. GetElapsedTime() is not virtual, so can't be fixed; one option is possibly to ensure that the base ticks are rounded up front to the nearest 1ms or so.

2. Consider allowing an arbitrary base offset. Eg., one of the Kestrel ones [randomizes the base offset](https://github.com/dotnet/aspnetcore/pull/48081/files#diff-eb56b63e16641b4b01665470700a08c48b687ec6fc9eb6157fbf3906d68c187aR19). Many of the tests in this repo use UtcNow, which actually adds non reproducibility, [example](https://github.com/dotnet/extensions/blob/main/test/Libraries/Microsoft.Extensions.Http.Telemetry.Tests/Logging/HttpLoggingHandlerTest.cs#L341).

3. Look at the TimeProvider's in dotnet/aspnetcore and dotnet/runtime possibly elsewhere, and consider whether we can make one with the combined features that we can share via dotnet/arcade instead of each having our own. Ideally we have a single test TimeProvider that can be configured however needed. Right now we have numerous ones.

**Comment by danmoseley** [comment]
Here's some extension methods they used in Kestrel
```c#
    public static long ToTicks(this TimeSpan timeSpan, TimeProvider timeProvider)
        => timeSpan.ToTicks(timeProvider.TimestampFrequency);

    public static long ToTicks(this TimeSpan timeSpan, long tickFrequency)
    {
        if (timeSpan == TimeSpan.MaxValue)
        {
            return long.MaxValue;
        }
        if (timeSpan == TimeSpan.MinValue)
        {
            return long.MinValue;
        }
        return timeSpan.Ticks * (tickFrequency / TimeSpan.TicksPerSecond);
    }

    public static long GetTimestamp(this TimeProvider timeProvider, TimeSpan timeSpan)
    {
        return timeProvider.GetTimestamp(timeProvider.GetTimestamp(), timeSpan);
    }

    public static long GetTimestamp(this TimeProvider timeProvider, long timeStamp, TimeSpan timeSpan)
    {
        return timeStamp + timeSpan.ToTicks(timeProvider);
    }
```
are any of these useful to add here, or to the base TimeProvider? Note, some will have the truncation problem.

**Comment by egil** [comment]
> GetElapsedTime() is not virtual...

`TimeProvider` is not released yet, so it should be possible to make it virtual. This seems like a very good reason to do so.

**Comment by danmoseley** [comment]
> TimeProvider is not released yet, so it should be possible to make it virtual. This seems like a very good reason to do so.

I agree, it's possible. Feel free to open an issue.

cc @tarekgh

**Comment by tarekgh** [comment]
I am not seeing making GetElapsedTime virtual is right thing. `GetElapsedTime` works on the snapped time by the provider and measure the time according to the time provider frequency. Maybe it is better to expose some helper to convert from/to timespan frequency like the extension methods mentioned in the comment https://github.com/dotnet/extensions/issues/3996#issuecomment-1562135601. 

CC @stephentoub

**Comment by egil** [comment]
I generally think it is important that the FakeTimeProvider behaves exactly like the real timer, besides actually having time pass.

Another example where the current implementation (and my own) fail is how timer callbacks are invoked. Consider this test:

```c#
// This fails since the Change call blocks until the callback completes
[Fact]
public void Async_timer_callback_with_duetime_zero()
{
    // Arrange
    var sut = new FakeTimeProvider();
    var callbacks = new List<DateTimeOffset>();

    // Act
    using var timer = sut.CreateTimer(
        _ =>
        {
            Thread.Sleep(20);
            callbacks.Add(sut.GetUtcNow());
        },
        null,
        TimeSpan.Zero,
        Timeout.InfiniteTimeSpan);
    timer.Change(TimeSpan.Zero, Timeout.InfiniteTimeSpan);

    // Assert
    callbacks.Should().BeEmpty();
}

// This succeeds since the Change call does not block until the callback completes
[Fact]
public void Async_timer_callback_with_duetime_zero()
{
    // Arrange
    var sut = TimeProvider.System;
    var callbacks = new List<DateTimeOffset>();

    // Act
    using var timer = sut.CreateTimer(
        _ =>
        {
            Thread.Sleep(20);
            callbacks.Add(sut.GetUtcNow());
        },
        null,
        TimeSpan.Zero,
        Timeout.InfiniteTimeSpan);
    timer.Change(TimeSpan.Zero, Timeout.InfiniteTimeSpan);

    // Assert
    callbacks.Should().BeEmpty();
}
```

This particular issue bid me today in a scenario where `timer.Change()` was called while inside a lock, which the callback tries to enter, leading to a deadlock.

**Comment by geeknoid** [comment]
The FakeTimeProvider in this repo is the one we're shipping to customers. It has a robust feature set, so I'm closing this for now. We can create new issues when specific customer requests come in.
