### ISSUE TITLE
make code trim safe

### ISSUE THREAD

**Issue by danmoseley** [dotnet/extensions#4002]
Remove these suppressions and fix the issues.
https://github.com/dotnet/extensions/blob/e93439fc5f6ce14a27795bc63a99c0dbf182e448/Directory.Build.targets#L19-L20

Then apps using these libraries can trim them down to just what they need.

**Comment by danmoseley** [comment]
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained
https://github.com/dotnet/runtime/blob/472091827b6a266f9d964564a77ba11160622a50/docs/tools/illink/error-codes.md explains the codes.

@eerhardt is there any issue or doc somewhere where we have guidance on working through these things?

**Comment by danmoseley** [comment]
(And, you're welcome to. Perhaps @eerhardt can suggest the easiest code to start with)

**Comment by eerhardt** [comment]
>  is there any issue or doc somewhere where we have guidance on working through these things?

https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

**Comment by danmoseley** [comment]
@afroze9 my suggestion is that you do a small piece and offer a PR, rather than try to do it all at once. Maybe just clear the easiest of the warnings.

**Comment by EricStG** [comment]
Do you still need help on this one? Wouldn't mind giving it a go.

**Comment by RussKie** [comment]
> Do you still need help on this one? Wouldn't mind giving it a go.

Yes, the warnings are still there, so we do need help :)
Thank you
