### ISSUE TITLE
Unify Windows+Linux Resource Monitoring

### ISSUE THREAD

**Issue by danmoseley** [dotnet/extensions#4005]
Diagnostics.ResourceMonitoring currently has APIs to add a Windows provider or a Linux provider. Instead, we want a single set of APIs which dynamically determine whether the system is Linux or Windows and then does the right thing automatically.

Right now eg you can use Windows resource utililization API and run on Linux and it will crash.

I marked `help wanted` but this would need a design/API proposal.

**Comment by wcontayon** [comment]
@danmoseley I would like to give a try 🙂 if api is approved
Should I propose a design api ?

**Comment by danmoseley** [comment]
@joperezr @geeknoid should be able to advise.

**Comment by geeknoid** [comment]
Hi @wcontayon ,

We'd love your help with this issue. There are two challenges here:

* The resource monitoring code was originally split into distinct packages and this is reflected in the fact the implementation of the Linux and Windows code is more different than it needs to be. In particular, there are options that currently only apply to Linux. If we unify Linux and Windows into a single API, we'll either need to implement those options for the Windows code, or a least mark the Linux-only options as such in the docs.

* The Windows-side of things deal with publishing counters, which is somewhat orthogonal to the main mission of resource monitoring. I've been wondering whether this stuff should move to a completely different assembly.

@rafal-mz @tekian Do you guys have any recommendations you'd like to provide on these two topics?

**Comment by rafal-mz** [comment]
- Some of our existing 1P customers are using `IResourceUtilizationPublisher`s as the way to access utilization data in process and push it down the line to some monitoring software they are using. Probably, it would be useful to leave this capability (of accessing measurement values).
- The calculation of metrics should not be hardcoded (today I think it is Calculator.cs class). The values reported by different OSes doesn't match, and it is hard to provide it right to the common formula.
- Our 1P customers are (and probably will in the next forseable future) to migrate from Windows to Linux. Ideally, there shouldn't be any difference in the way data is published between platforms. So, that after the migration the team does not need to setup new dashboards and so on.
- Personally, I find three TimeSpan values to control `IResourceUtilizationTracker` more complicated than it has to be (look ResourceUtilizationTrackerOptions). I think the model with 'how often we will query OS for this data' that is implemented on the Linux counterpart is much simpler to understand. I would personally leap towards it.

**Comment by geeknoid** [comment]
Dibe,
