### ISSUE TITLE
Remove unclear FakeTimeProvider.Advance() overload

### ISSUE THREAD

**Issue by egil** [dotnet/extensions#4007]
I am not a fan of the `Advance()` overload method on `FakeTimeProvider` that does not take a `TimeSpan` and just increments time with 1ms. It is not obvious to the dev/user and is likely going to cause confusion to some.

I suggest removing it. If specific teams like the overload, they can easily add it back in via an extension method.

**Comment by danmoseley** [comment]
what about changing it thus

```diff
<         public void Advance() => Advance(TimeSpan.FromMilliseconds(1));
>         public void Advance(int milliseconds = 1) => Advance(TimeSpan.FromMilliseconds(milliseconds));

**Comment by egil** [comment]
Two comments:

1. My sense is that the modern API strategy is to avoid using primitives and use strong types where possible. Using an `int` instead of `TImeSpan` seems like a regression back to older times. Correct me if I am wrong.

2. The scenario of advancing by 1ms seems to be very specific. It is not something I have had a need for yet, and even if I did, I would prefer to still write `Advance(TimeSpan.FromMilliseconds(1))` just for clarity. 

   Is it something you have a need for in all your tests?
   
   Is it here because 1ms is the lowest support increment? Personally, I have used `Advance(TimeSpan.FromTicks(1))` in my own tests in a few places just to move time right past a `pastDateTimeOffset <= timeProvider.GetUtcNow()` conditional check and that does seem to work too. But perhaps I am not aware of edge cases that mean that 1ms is the lowest increment that should be supported.

**Comment by danmoseley** [comment]
1. I don't think this is the case -- we have innumerable API's that take integers, for example. Similar for strings. We don't wrap everything in structs for multiple reasons -- bloat, discoverability, efficiency, cognitive load. Most people use tools like Visual Studio that make clear what the number represents.

2. Bear in mind this is a type for use in tests. I'm guessing most of the places our tests call `Advance()` they don't really care it was a millisecond (although they may assume it was, for the purposes of validation). It could be a pico second or an eon and the test would still be valid. A millisecond just happens to be a reasonable pick.

**Comment by danmoseley** [comment]
> Is it something you have a need for in all your tests?

If our hope here is to make a universally useful fake, it might be interesting to look at tests in eg dotnet/aspnetcore and maybe dotnet/runtime where they currently abstract time. (There is more of this in aspnetcore).

**Comment by egil** [comment]
> 1. I don't think this is the case -- we have innumerable API's that take integers, for example. Similar for strings. We don't wrap everything in structs for multiple reasons -- bloat, discoverability, efficiency, cognitive load. Most people use tools like Visual Studio that make clear what the number represents.

My point is more was that recent time-based APIs like `PeriodicTimer` seem to shy away from adding a "millisecond overload" like it was common to have in older .NET APIs. Not having an `Advance(int milliseconds)` overload is not a hill I will die on though, but my impression is that it is not common in new APIs, and I would not use it myself over the TimeSpan variant.

In tests, I would rather have readability/understandability be high than worry about struct vs. primitives for performance, which is also why I dislike the `Advance()` method which just moves time forward 1ms.

>> Is it something you have a need for in all your test?
> If our hope here is to make a universally useful fake ...

Ahh, my question wasn't clear. I meant, are you seeing a need for `Advance()` in many tests or only in specific scenarios? In my usage where I primarily have been testing business logic, moving ahead with just 1ms doesn't happen, so I would never have though to add that.

**Comment by egil** [comment]
> 2\. Bear in mind this is a type for use in tests. I'm guessing most of the places our tests call `Advance()` they don't really care it was a millisecond (although they may assume it was, for the purposes of validation). It could be a pico second or an eon and the test would still be valid. A millisecond just happens to be a reasonable pick.

Yes, I do not see any other use cases than testing for `FakeTimeProvider` either.

Perhaps it is the nature of things (utility/generic features vs business logic) that are being tested that determine if a "move time forward" forward feature is useful vs. "move time forward by X" feature.

My opposition is specifically to the `Advance()`. It requires the reader to know implicitly that it is 1ms that is being advanced with (or read docs/use an editor that shows the info), and it is an overload that can be easily added via an extension method by teams that have the need. So since the goal is a generally applicable fake, I would recommend keeping the API surface clean and not including `Advance()` out of the box.

**Comment by danmoseley** [comment]
I don't feel strongly. How about a ms overload though?
```diff
<         public void Advance() => Advance(TimeSpan.FromMilliseconds(1));
>         public void Advance(int milliseconds) => Advance(TimeSpan.FromMilliseconds(milliseconds));
```

**Comment by danmoseley** [comment]
and maybe add an extension method Advance() just for this codebase.

**Comment by egil** [comment]
> I don't feel strongly. How about a ms overload though?
> ```diff
> <         public void Advance() => Advance(TimeSpan.FromMilliseconds(1));
> >         public void Advance(int milliseconds) => Advance(TimeSpan.FromMilliseconds(milliseconds));
> ```

I don't mind that. But it's also an API surface that you cannot remove later, and it's an easy extension method that those that needed it can add so I would be cautious about adding it and having to support it until .NET 1000.

**Comment by danmoseley** [comment]
I don't think it matters much at this point as if we end up supporting this publicly it will go through api review. Feel free to leave it out but I would have the extension method.

**Comment by egil** [comment]
Ahh ok. I was not sure where in the process we were. I'll send in a PR or two with additional suggestions and let you and the team take it from there as you see fit.
