### ISSUE TITLE
Remove duplication in Tracing.Sampling

### ISSUE THREAD

**Issue by noahfalk** [dotnet/extensions#4047]
Preferably Lets try to get the options support into OTel official APIs
Failing that, put this in a OTel specific package
If the two sampler types are duplicated we should remove the R9 copies and refer to the public types provided by OTel.

**Comment by joperezr** [comment]
@geeknoid is this also one of the items you plan to take care of with your Telemetry changes?

**Comment by dariusclay** [comment]
The core of tracing with options support will be migrated to OTel-dotnet-contrib until .NET has proper abstractions for it. Right now we've kept some basic classes here in abstractions which have no dependency on OTel.

**Comment by geeknoid** [comment]
Done.
