### ISSUE TITLE
Rename Metering->Metrics

### ISSUE THREAD

**Issue by noahfalk** [dotnet/extensions#4048]
.NET uses the terms "Metrics" in our namespaces. Dotnet/extensions currently uses the term "Metering". We should converge to "Metrics" both to match existing namespaces and the industry more generally.

**Comment by joperezr** [comment]
@geeknoid was this one of the things you were planning to tackle for RC1?

**Comment by geeknoid** [comment]
I don't know about RC1, but I'm planning to address before November.
