### ISSUE TITLE
Remove LogMethodAttribute

### ISSUE THREAD

**Issue by noahfalk** [dotnet/extensions#4050]
We'd prefer to simplify the source generated logging scenario around a single attribute 'LoggerMessage'. Currently dotnet/extensions introduces an alternative LogMethodAttribute that should be removed.

https://github.com/dotnet/runtime/issues/87254 tracks moving some current LogMethodAttribute constructors over to LoggerMessageAttribute.

**Comment by xakep139** [comment]
@noahfalk did you mean `LoggerMessage` instead of `LoggerMethod`?

**Comment by noahfalk** [comment]
Yes I did, thanks! You'd think I'd stop making that mistake at some point but apparently it still hasn't sunk in. I edited the message to fix it.
