### ISSUE TITLE
Rename EnableDetailedLatencyBreadkdown property

### ISSUE THREAD

**Issue by gewarren** [dotnet/extensions#4064]
### Description

The EnableDetailedLatencyBreadkdown property should be named "EnableDetailedLatencyBreakdown ". It has a spelling mistake.

### Reproduction Steps

Go to https://github.com/dotnet/extensions/blob/1c22dfd7f551a64280a45ba480a201432075cb24/src/Libraries/Microsoft.Extensions.Http.Telemetry/Latency/HttpClientLatencyTelemetryOptions.cs#L20 and inspect the name of the property.

### Expected behavior

EnableDetailedLatencyBreakdown

### Actual behavior

EnableDetailedLatencyBreadkdown

**Comment by geeknoid** [comment]
Fixed.
