### ISSUE TITLE
Remove LoggerProvider

### ISSUE THREAD

**Issue by noahfalk** [dotnet/extensions#4071]
The current [LoggerProvider](https://github.com/dotnet/extensions/blob/21ba7a0678869eaefec7ede1d7aee057bb1b813f/src/Libraries/Microsoft.Extensions.Telemetry/Logging/LoggerProvider.cs#L47) code appears to re-host OpenTelemetry processors inside of a new ILogger implementation and it is both duplicating OTel code and [taking dependencies on non-public APIs](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Telemetry/Logging/Logger.cs#L37) via reflection to accomplish this. We should remove this functionality and direct users to the offical OTel implementation. For enrichment we can author an OTel processor that utilizes the public OTel API and have extension methods that register this processor.

The removal should include LoggerProvider and all of the duplicated OTel code that was used to implement it.

**Comment by danmoseley** [comment]
meantime @RussKie can fix the attribution header so we don't need to wait on that.
