### ISSUE TITLE
`IDownstreamDependencyMetadataManager` accessibility

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4073]
https://github.com/dotnet/extensions/blob/21ba7a0678869eaefec7ede1d7aee057bb1b813f/src/Libraries/Microsoft.Extensions.Telemetry/Telemetry.Internal/IDownstreamDependencyMetadataManager.cs#L13
This interface is being used by unit tests in [Microsoft.Azure.Extensions.Telemetry.Test](https://github.com/Azure/dotnet-extensions-experimental/blob/0df1953616dd25e283a6b29021808a70699f7e28/tests/Microsoft.Azure.Extensions.Telemetry.Tests/AzureMetadataTests.cs#L16). To facilitate that Microsoft.Extensions.Telemetry declares IVT to Microsoft.Azure.Extensions.Telemetry.Tests. This is... bad.

This IVT causes compiler errors in Azure/dotnet-extensions-experimental repo when an attempt to build it without signing:
```
D:\Development\azure-dotnet-extensions-experimental\tests\Microsoft.Azure.Extensions.Telemetry.Tests\AzureMetadataTests.cs(16,22): error CS0281: Friend access was granted by 'Microsoft.Extensions.Telemetry, Version=8.0.0.0, Culture=neutral, PublicKeyTok 
en=31bf3856ad364e35', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly. [D:\Development\azure-dotnet-extensions-experimental\tests\Microsoft.Azure.Extensions.Teleme 
try.Tests\Microsoft.Azure.Extensions.Telemetry.Tests.csproj::TargetFramework=net8.0]
```

https://github.com/dotnet/extensions/pull/4072 removes the IVT, however, this change will break the AzureMetadataTests tests. 
![image](https://github.com/dotnet/extensions/assets/4403806/5acddd76-b82d-44f3-9ca2-efa215885538)

I see the tests are being actively developed (e.g., https://domoreexp.visualstudio.com/R9/_git/SDK/pullrequest/782810).
@geeknoid @mariamgerges please advise the best course of action here. Do we need to make `IDownstreamDependencyMetadataManager` public?

**Comment by geeknoid** [comment]
I don't want to make that type public, it's an implementation detail. I'm hoping there's a way to test the Azure stuff without needing this type.

@dpk83 ?

**Comment by RussKie** [comment]
With https://github.com/dotnet/extensions/pull/4072 merged I'll be disabling the [Microsoft.Azure.Extensions.Telemetry.Test](https://github.com/Azure/dotnet-extensions-experimental/blob/0df1953616dd25e283a6b29021808a70699f7e28/tests/Microsoft.Azure.Extensions.Telemetry.Tests/AzureMetadataTests.cs#L16) tests.

**Comment by dpk83** [comment]
We shouldn’t make it public, rather update tests to remove the dependency

**Comment by RussKie** [comment]
Opened https://github.com/Azure/dotnet-extensions-experimental/issues/22 and assigned to @dpk83.
