### ISSUE TITLE
Restore downgraded code coverage

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4099]
A number of projects have seen their code coverage metrics artificially downgraded while establishing the quality gates. To facilitate that, a custom attribute has been added which ultimately needs to be removed.
For example:
https://github.com/dotnet/extensions/blob/996fcd8344ac8f4601e464884e869bc0821a1cc2/eng/scripts/ValidateProjectCoverage.ps1#L44
https://github.com/dotnet/extensions/blob/052e6c8ca60dd6aad445f06db5f6d1a2f95e7f9f/src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Microsoft.Extensions.Diagnostics.Probes.csproj#L17

Here's the list of affected projects that need to be addressed:
https://github.com/search?q=repo%3Adotnet%2Fextensions%20TempMinCodeCoverage&type=code

**Comment by RussKie** [comment]
@geeknoid @dpk83 @tekian please triage and assign as appropriate.

**Comment by geeknoid** [comment]
I think we can close this issue. WDYT?

**Comment by RussKie** [comment]
We still have 5 libraries decorated with `TempMinCodeCoverage`
https://github.com/search?q=repo%3Adotnet%2Fextensions%20TempMinCodeCoverage&type=code
