### ISSUE TITLE
EventCountersListener enables all keywords and all log levels on enabled event sources

### ISSUE THREAD

**Issue by davidfowl** [dotnet/extensions#4104]
This leads to high CPU usage which leads to performance problems. 
I'm pretty sure it's this line of code coming from the event counter to meter translation layer:

https://github.com/dotnet/extensions/blob/996fcd8344ac8f4601e464884e869bc0821a1cc2/src/Libraries/Microsoft.Extensions.Telemetry/Metering.Collectors.EventCounters/EventCountersListener.cs#L234

It's turning on all of the keywords and all of the event verbosity.
 
For reference, here's the otel version:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/0de8b8a2755b1c5079d369aa63203184703c00c8/src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs#LL197C37-L197C37

We should make these match.

**Comment by xakep139** [comment]
@dpk83 FYI

**Comment by xakep139** [comment]
@davidfowl, @stephentoub since you were investigating the performance issues, can you try please try the fix from #4109?
Or I can do that if you have a benchmark/solution. Thanks!
