### ISSUE TITLE
Leftover references to R9 in repository

### ISSUE THREAD

**Issue by martincostello** [dotnet/extensions#4115]
### Description

The repo contains various references to the internal R9 project. At least some of these should be removed so that the open source repository is friendly to non-Microsoft contributors who are not familiar with that that is or what it means.

Here are all the references GitHub code search finds: [r9 results](https://github.com/search?q=repo%3Adotnet%2Fextensions%20r9&type=code)

I noticed this because the issue template contains this:

![image](https://github.com/dotnet/extensions/assets/1439341/58d8b58e-5bde-47f1-a5f7-6c8522e19734)

### Reproduction Steps

N/A

### Expected behavior

Correct terminology is used.

### Actual behavior

Internal code name is used.

### Regression?

N/A

### Known Workarounds

N/A

### Configuration

N/A

**Comment by danmoseley** [comment]
Thanks, yes much of this code came from an internal repo with that name. We should replace them with generic terms.

**Comment by danmoseley** [comment]
@RussKie @geeknoid some of these look like DI keys, event sources, counter names -- presumably fixed once shipped. Do we plan to ship these with R9 in the name? Can we avoid any R9 hits in the repo when we ship?

**Comment by xakep139** [comment]
> Yes, these are all telemetry things which Nikita will be taking care of soon.

Hopefully not only me 😀

**Comment by RussKie** [comment]
@xakep139 assigning to you for now. We all be cheering for you :)

**Comment by danmoseley** [comment]
Do we need to mark this somehow as "blocking release"/"necessary for GA"

**Comment by geeknoid** [comment]
Still more references remain, so let's keep this open.

**Comment by xakep139** [comment]
@geeknoid, I think this one can be closed once #4482 is merged and #4554 is unblocked
