### ISSUE TITLE
start-vs.cmd does not work

### ISSUE THREAD

**Issue by martincostello** [dotnet/extensions#4116]
### Description

The batch file `start-vs.cmd` in the root of the repository references a solution file that does not exist in the repository:

https://github.com/dotnet/extensions/blob/14917b87e8fc81f10d44ceea52d9b24e50e26550/start-vs.cmd#L26

### Reproduction Steps

Run the following commands on a Windows machine:

1. `restore.cmd`
2. `start-vs.cmd`

### Expected behavior

A solution file containing the repository's projects opens in Visual Studio ready to work on the code.

### Actual behavior

The batch file displays the following error and exits:

```
The system cannot find the file .\SDK.sln.
```

Visual Studio is not launched.

### Regression?

I guess there used to be a solution file in an old repo before the code was made public. If that was the case, then yes.

### Known Workarounds

Manually create a solution file with that name in the repository and then run the batch file.

### Configuration

N/A

**Comment by RussKie** [comment]
Thanks for the raising the issue. This script requires the solution to be generated first as described in https://github.com/dotnet/extensions/blob/main/docs/building.md#building-from-visual-studio.
