### ISSUE TITLE
Resolve CS0104: 'OptionsValidator' is an ambiguous reference between 'Microsoft.Extensions.Options.OptionsValidatorAttribute' and 'Microsoft.Extensions.Options.Validation.OptionsValidatorAttribute'

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4117]
https://github.com/dotnet/runtime/pull/87587 appears to implement the same functionality as currently provided https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Options.Validation.

See https://github.com/dotnet/extensions/pull/4101.

**Comment by RussKie** [comment]
@geeknoid assigning to you

**Comment by RussKie** [comment]
It appears https://github.com/dotnet/runtime/pull/87587 made into Preview6 branch, thus blocking https://github.com/dotnet/extensions/pull/4101 (and https://github.com/dotnet/extensions/pull/4107).

**Comment by geeknoid** [comment]
@RussKie So how should I address this? Should I add a commit to #4101 that removes the dotnet/extensions validation code generator?

**Comment by RussKie** [comment]
> Should I add a commit to #4101 that removes the dotnet/extensions validation code generator?

Yes, please pile on top of #4101. Then we can port the changes to the main branch as well.

**Comment by RussKie** [comment]
Resolved in #4129
