### ISSUE TITLE
Update HTTP in and HTTP out logging

### ISSUE THREAD

**Issue by JamesNK** [dotnet/extensions#4155]
.NET 8 improves built-in logging for HTTP in and HTTP out. Update packages in dotnet/extensions to use built-in logging and apply redaction and other features to them.

Blocked on:
* https://github.com/dotnet/runtime/issues/77312 to be completed for HTTP out logging.
* https://github.com/dotnet/runtime/issues/87914 for HttpClientFactory configure defaults functionality.

@Tratcher What is the state of HTTP logging in ASP.NET Core? Are required changes made there? Has dotnet/extensions been updated to use it?

cc @joperezr

**Comment by Tratcher** [comment]
I have draft PRs but haven't been able to work on them recently. https://github.com/dotnet/aspnetcore/pull/48679 https://github.com/dotnet/extensions/pull/4056. Not sure if they'll be a priority for this release.

**Comment by xakep139** [comment]
Outgoing part is covered within #4211

**Comment by xakep139** [comment]
Incoming part is covered in #4210

**Comment by xakep139** [comment]
@klauco @geeknoid should we close this issue since we have two specific ones?
