### ISSUE TITLE
Remove CustomConfigurationBinder from Microsoft.Extensions.Telemetry

### ISSUE THREAD

**Issue by ericstj** [dotnet/extensions#4171]
I was browsing the repo and noticed this:
https://github.com/dotnet/extensions/blob/ac3fca327aef1abb9b43df332f4b44ec9c12f807/src/Libraries/Microsoft.Extensions.Telemetry/Metering.Collectors.EventCounters/Internal/CustomConfigurationBinder.cs#L17-L20

Since https://github.com/dotnet/runtime/issues/66141 was fixed and this library references the package with that fix, can this be removed now?

cc @dotnet/area-extensions-configuration

**Comment by RussKie** [comment]
@geeknoid @dpk83 please assign as appropriate

**Comment by xakep139** [comment]
If we're referencing version 7.x (or newer) only of the "Microsoft.Extensions.Configuration.Binder" package, this custom binder can be safely removed
