### ISSUE TITLE
Remove Http and Http client metering and enrichment

### ISSUE THREAD

**Issue by klauco** [dotnet/extensions#4214]
Remove:
 - Http metering middleware
 - HttpClient metering
 - global metric enrichment
 - incoming http metric enrichment
 - outgoing http metric enrichment

**Comment by xakep139** [comment]
@klauco do we need to remove `Metering.Collectors.EventCounters`?

**Comment by klauco** [comment]
@xakep139 Yes, the removal of event counters is captured in issue #4213
