### ISSUE TITLE
Remove OTel-specific bits needed in tracing

### ISSUE THREAD

**Issue by klauco** [dotnet/extensions#4249]
We want to provide enrichment and redaction capabilities for tracing, but at the same time we don't want to depend directly on OpenTelemetry-dotnet. Therefore, we should keep abstractions and core helper methods in dotnet/extensions and provide the glue code, connecting this functionality with OTel processors etc in opentelemetry-dotnet-contrib.

**Comment by xakep139** [comment]
Already implemented abstractions are in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions.Enrichment

**Comment by RussKie** [comment]
Is there anything left outstanding?

**Comment by xakep139** [comment]
@dariusclay needs to check whether sampling has to be moved to abstractions or not

**Comment by dariusclay** [comment]
We don't have any real high level abstractions for tracing or sampling yet. The options and validator, which was used in our implementation of `DynamicSampler` could move in `Microsoft.Extensions.Telemetry.Abstractions`, but by themselves do not provide much value and not sure how useful it would be. What do you think folks?

**Comment by dariusclay** [comment]
We'll keep ITraceEnricher, all other bits will go into Otel.

**Comment by xakep139** [comment]
@dariusclay, I remember @evgenyfedorov2 initially added telemetry abstractions in OTel as abstract classes for easier future extension. Should we follow the same strategy here?

**Comment by dariusclay** [comment]
@xakep139 I started this conversation with the team, and yes we feel it's best to have the same here. I'll open a new issue for it.
