### ISSUE TITLE
Evaluate whether we can get rid of the generic virtual call in contextual options

### ISSUE THREAD

**Issue by geeknoid** [dotnet/extensions#4267]
The GetAsync is a Generic Virtual Method which ends up being expensive to call. Can we design to avoid this pattern?

https://github.com/dotnet/extensions/blob/184223ba6bade885c57a7e05fcf741eac39f7520/src/Libraries/Microsoft.Extensions.Options.Contextual/INamedContextualOptions.cs#L24

**Comment by rosebyte** [comment]
I see the Interface was changed to `INamedContextualOptions<TOptions, TContext>` so the method isn't generic now.
