### ISSUE TITLE
FakeTimeProvider with auto advance enabled - should calling ToString() cause time to advance?

### ISSUE THREAD

**Issue by egil** [dotnet/extensions#4268]
I was looking over the code and noticed that `ToString()` calls `GetUtcNow()`. If `AutoAdvanceAmount` is greater than zero, then this would advance time whenever ToString is invoked.

In normal operations that is likely not going to cause problems, but if I understand how (visual) debuggers work correctly e.g. the ones in Visual Studio, if I am debugging my app and I am inspecting a FakeTimeProvider instance, VS will call `ToString()` causing the clock to advance. That is going to make debugging time-related issues pretty damn hard.

I think the fix is pretty simple:

```diff
-public override string ToString() => GetUtcNow().ToString("yyyy-MM-ddTHH:mm:ss.fff", CultureInfo.InvariantCulture);
+public override string ToString() => _now.ToString("yyyy-MM-ddTHH:mm:ss.fff", CultureInfo.InvariantCulture);
```

**Comment by sebastienros** [comment]
Would you mind submitting a PR with your suggestion, and a unit test that checks that?

**Comment by egil** [comment]
Sure, ill see what I can do. Was not able to get the build/tests running locally, but ill see what github CI can do for me.
