### ISSUE TITLE
Consider leaving ConnectionTimeout library as experimental

### ISSUE THREAD

**Issue by joperezr** [dotnet/extensions#4297]
We've had discussions about this in the past, but I believe we haven't finalized on a decision yet. ConnectionTimeout library hasn't been validated by any customers, so it has been flagged in the past that we should either: A) not stabilize the package and keep it as preview post the release, or B) ship the package as stable but mark all of the APIs as experimental. Logging this issue to track finalizing on that decision and then for executing before our release.

cc: @Tratcher @geeknoid

**Comment by geeknoid** [comment]
This was removed.
