### ISSUE TITLE
Once Simmy V8 is ready, we need to re-implement our FaultInjection component.

### ISSUE THREAD

**Issue by joperezr** [dotnet/extensions#4306]
@vany0114 has been helping by working on https://github.com/App-vNext/Polly/pull/1459 and integrating Simmy V8 into Polly V8. Once that PR is merged, we'll need to react to those changes in our fault injection component that we have in this repo. @clpun will be working on these changes at that time.

**Comment by martintmk** [comment]
@joperezr 

Would be nice to get another review for https://github.com/App-vNext/Polly/pull/1459 just to get another point of view. Can someone take a look at it before the merging.

We are also wrapping up the API Review for Polly, however, Simmy did not had such pass yet so I am wondering how do we approach it?

- Keep the PR open and open a separate one just with the Simmy API. Merge once the API had feedback and is approved.
- Make all new Simmy APIs internal. Merge the PR. Open PR with API, approve it and make the API public afterwards.
- Merge the Simmy PR and do some breaking changes later based on the API review.

cc @vany0114 , @clpun

**Comment by vany0114** [comment]
> @joperezr
> 
> Would be nice to get another review for [App-vNext/Polly#1459](https://github.com/App-vNext/Polly/pull/1459) just to get another point of view. Can someone take a look at it before the merging.
> 
> We are also wrapping up the API Review for Polly, however, Simmy did not had such pass yet so I am wondering how do we approach it?
> 
> * Keep the PR open and open a separate one just with the Simmy API. Merge once the API had feedback and is approved.
> * Make all new Simmy APIs internal. Merge the PR. Open PR with API, approve it and make the API public afterwards.
> * Merge the Simmy PR and do some breaking changes later based on the API review.
> 
> cc @vany0114 , @clpun

I like the second option unless you guys @clpun @joperezr need the new Simmy asap. BTW the PR is pretty much done, I think there's only one comment from @martintmk that I need to review.

**Comment by joperezr** [comment]
I'm fine with either option 1 or 2. Ultimately the most important thing to know is if it's reasonable to expect that we would have the APIs ready and finalized in the next 2 weeks, as I think that would be the limit that would still allow us to react to the changes in dotnet/extensions in time to ship as stable for November. If that is not the case and we aren't able to get this done by then, that's okay too, we would just have to remove that API from dotnet/extensions  for now, and re-add it back post-November once it is ready.

**Comment by vany0114** [comment]
> [...] Ultimately the most important thing to know is if it's reasonable to expect that we would have the APIs ready and finalized in the next 2 weeks

Yeah that's totally feasible, as mentioned is almost done, one question I have @martintmk do you know what's the best way to see the missing code coverage that the CI is expecting so that I can add those missing unit tests? that would be the only thing left to merge the PR

**Comment by RussKie** [comment]
@vany0114 you PR will fail if the CC is insufficient. You can see the CC report for your PR on AzDO, e.g.,
![image](https://github.com/dotnet/extensions/assets/4403806/089044bd-091d-4dce-9d66-847264d74e54)
From there you can drill down to a specific component and see what's lacking CC.

You can also see the CC in VS itself. Once you run all tests (i.e., all TFMs) for your project, you can select all test projects and get the CC:
![image](https://github.com/dotnet/extensions/assets/4403806/08a04f25-4489-484a-83c8-6f28ccfa55de)

**Comment by martintmk** [comment]
> > [...] Ultimately the most important thing to know is if it's reasonable to expect that we would have the APIs ready and finalized in the next 2 weeks
> 
> Yeah that's totally feasible, as mentioned is almost done, one question I have @martintmk do you know what's the best way to see the missing code coverage that the CI is expecting so that I can add those missing unit tests? that would be the only thing left to merge the PR

In Polly you can also download code-coverage report that is attached in the "build" workflow:

![image](https://github.com/dotnet/extensions/assets/103487740/40bf1798-6369-4bb7-b809-37a1f1bcdafc)

**Comment by martintmk** [comment]
> I'm fine with either option 1 or 2. Ultimately the most important thing to know is if it's reasonable to expect that we would have the APIs ready and finalized in the next 2 weeks

@joperezr, I have created a PR with the API Shape:

https://github.com/App-vNext/Polly/pull/1571

Please forward to relevant folks

cc @clpun

**Comment by joperezr** [comment]
> > I'm fine with either option 1 or 2. Ultimately the most important thing to know is if it's reasonable to expect that we would have the APIs ready and finalized in the next 2 weeks
> 
> @joperezr, I have created a PR with the API Shape:
> 
> [App-vNext/Polly#1571](https://github.com/App-vNext/Polly/pull/1571)
> 
> Please forward to relevant folks
> 
> cc @clpun

@geeknoid @tekian @sebastienros FYI.

**Comment by geeknoid** [comment]
Simmy is in there, we don't need anything specific to enable it, so closing.
