### ISSUE TITLE
Breaking change `LoggerMessage` fails with IndexOutOfRangeException

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4310]
![image](https://github.com/dotnet/extensions/assets/4403806/f3a45a86-ce9f-4406-b448-3330b8253d25)

The issue manifested in MsalLogWrapperTest.LoggerWithPiiRedactionIsCalledFromLogCallback.

Steps to repro:

```cs
public class LogPropertiesTests
{
    [Fact]
    public void LoggerWithPiiRedactionIsCalledFromLogCallback()
    {
        var logger = new FakeLogger();
        var redactorProvider = new FakeRedactorProvider();

        var logWrapper = new LogWrapper(logger, redactorProvider);
        logWrapper.LogCallback(LogLevel.Information, "Test message");

        Assert.Equal(1, logger.Collector.Count);
        Assert.Equal(1, redactorProvider.Collector.AllRedactedData.Count);
    }

    internal sealed class LogWrapper
    {
        private readonly ILogger _logger;
        private readonly IRedactorProvider? _redactorProvider;

        public LogWrapper(ILogger logger, IRedactorProvider? redactorProvider)
        {
            _logger = logger;
            _redactorProvider = redactorProvider;
        }

        public void LogCallback(LogLevel msalLogLevel, string message)
        {
            MockLog.LogPrivateDataInternal(_logger, msalLogLevel, _redactorProvider!, message);
        }
    }

}

internal static partial class MockLog
{
    [LoggerMessage("{logMessage}")]
    internal static partial void LogPrivateDataInternal(ILogger logger, LogLevel logLevel, IRedactorProvider redactorProvider, [PrivateData] string logMessage);
}
```

**Comment by RussKie** [comment]
Likely the same issue is with both of these properties:
https://github.com/dotnet/extensions/blob/c8e34c57199a2e5e3864649f3bd16258b88ff67e/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Logging/LoggerMessageState.cs#L30-L35

The generator doesn't perform bounds checks before attempting to access elements of the collections:
![image](https://github.com/dotnet/extensions/assets/4403806/8380a0fe-f83d-4cb8-b241-248457842e53)

**Comment by geeknoid** [comment]
This is very strange, I'll investigate.

The generated code shouldn't need to do any explicit bounds checking, since there are those Reserve calls in there that should ensure the arrays are large enough to begin with.

**Comment by geeknoid** [comment]
This looks as though it's not using the ExtendedLogger from dotnet/extensions and is instead using the classic logger from dotnet/runtime. The ExtendedLogger is the one to perform redaction and hence prepares the RedactedTagArray array for use before invoking the formatting callback.

Could you try single-stepping through the call to the ILogger.Log method and see where you end up? You should be in ExtendedLogger.Log, but I think you won't be there.

**Comment by geeknoid** [comment]
https://github.com/dotnet/extensions/pull/4317 should make it so code generated by the new code generator will work correctly when using the legacy logger. Classified data will come out as null values, which prevents privacy leaks.

**Comment by geeknoid** [comment]
@RussKie  Can we close this?
