### ISSUE TITLE
Grab updates from R9 code base

### ISSUE THREAD

**Issue by geeknoid** [dotnet/extensions#4333]
Grab latest fixes/improvements and merge them here before launch. Last sync was May 28th.

**Comment by joperezr** [comment]
@tekian any updates on how is this going?

**Comment by joperezr** [comment]
From @geeknoid we think that this is mostly bug fixes, but we need to check.

**Comment by joperezr** [comment]
Update:
- @tekian went through changes from August through September for all the changes that are relevant. This is now merged.
- He is now going on changes from September through today.

**Comment by joperezr** [comment]
Update:
- @xakep139 flagged a couple of changes that were missed, @tekian is working on those, ETA is next week.

**Comment by geeknoid** [comment]
@tekian Any progress?

**Comment by joperezr** [comment]
The remaining PRs are just new features, so we will postpone the remaining work to 8.1

**Comment by evgenyfedorov2** [comment]
@RussKie @joperezr @geeknoid  is this still relevant? why was it reopened?

**Comment by geeknoid** [comment]
Nah, let's close this.
