### ISSUE TITLE
Standarize on Assembly names and namespace used for DependencyInjection libraries.

### ISSUE THREAD

**Issue by joperezr** [dotnet/extensions#4339]
We seem to have two extension libraries that are geared towards DependencyInjection:

- Microsoft.Extensions.DependencyInjection.AutoActivation
- Microsoft.Extensions.ObjectPool.DependencyInjection

IIRC, ObjectPool is using that pattern in order to reuse an existing namespace, while the AutoActivation is brand new. It feels wrong to have these two libraries using different naming conventions, so I think we should try to get them aligned to either both use `Microsoft.Extensions.DependencyInjection.*` or alternatively `Microsoft.Extensions.*.DependencyInjection`.

@geeknoid @sebastienros @tekian Thoughts?

**Comment by sebastienros** [comment]
Seems fine to me based on what they do. Microsoft.Extensions.ObjectPool.DependencyInjection is specific to object pools. Like you want a pool that works with DI. So you expect it to be in pools. Microsoft.Extensions.DependencyInjection.AutoActivation is features to improve DI.

**Comment by geeknoid** [comment]
I agree with @sebastienros , this is why they were named this way.

**Comment by joperezr** [comment]
Got it, didn't think of it that way, thanks both for confirming.
