### ISSUE TITLE
IServiceCollection and IApplicationBuilder should be in standard namespaces

### ISSUE THREAD

**Issue by JamesNK** [dotnet/extensions#4389]
I see many extension methods on `IServiceCollection` aren't in the `Microsoft.Extensions.DependencyInjection` namespace. That's different from what existing Microsoft.Extensions.* packages which do use `Microsoft.Extensions.DependencyInjection`.

See https://github.com/dotnet/runtime/issues/86885 as an example of where this point came up.

Likewise, `IApplicationBuilder` extensions should be in the `Microsoft.AspNetCore.Builder` namespaces. This is what ASP.NET Core does. See https://github.com/search?q=repo%3Adotnet%2Faspnetcore%20%22this%20IApplicationBuilder%22&type=code

Extension methods on other builder types can remain in their existing namespaces.

We place extension method types in these namespaces to make the `AddXXX` and `UseXXX` methods immediately available after adding a package. `Microsoft.Extensions.DependencyInjection` and `Microsoft.AspNetCore.Builder` are global namespaces in ASP.NET Core, so extension methods can be referenced without adding namespaces.

**Comment by JamesNK** [comment]
cc @joperezr

**Comment by geeknoid** [comment]
DOne.
