### ISSUE TITLE
Microsoft.Extensions.DiagnosticAdapter does not map properties from ancestor classes

### ISSUE THREAD

**Issue by sungam3r** [dotnet/extensions#439]
Microsoft.Extensions.DiagnosticAdapter package provides easy opportunity to wrap execution flow into the suitable well-configured methods like this
```
[DiagnosticName("Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting")]
public void OnCommandExecuting(DbCommand command, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, DateTimeOffset startTime)
{
}
```
initializing all known specified parameters in method signature, but it does not work with properties in ancestor classes, e.g [CommandExecutedEventData](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Diagnostics/CommandExecutedEventData.cs) because of this line of code ([link](https://github.com/aspnet/EventNotification/blob/28b77e7fb51b30797ce34adf86748c98c040985e/src/Microsoft.Extensions.DiagnosticAdapter/Internal/ProxyMethodEmitter.cs#L60)):
```
var properties = inputType.GetTypeInfo().DeclaredProperties.ToArray();
```
It uses only those properties, which are declared in this particular **inputType** type. And in case of CommandExecutedEventData there are only one property - Result. All other properties from CommandEndEventData, CommandEventData and EventData will be ignored. 

Consider to change the line of code mentioned above to
```
var properties = inputType.GetTypeInfo().GetProperties();
```
to allow mapping to any property in the chain of class inheritance, so we can use such methods:
```
[DiagnosticName("Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted")]
public void OnCommandExecuted(object result, bool async, TimeSpan duration, DbCommand command, Guid commandId)
{
}
```
Now all arguments except *result* have their default values - null for reference types and zeros for structs.

**Comment by rgueldenpfennig** [comment]
Can someone from the team comment the current status of this issue?

I got the same problem like @sungam3r explained in detail. I want to hook on the diagnostics that EntityFrameworkCore is offering.

```[DiagnosticName("Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted")]
public void OnCommandExecuted(
    DbCommand command,
    DbCommandMethod executeMethod,
    Guid commandId,
    Guid connectionId,
    object methodResult,
    bool async,
    DateTimeOffset startTime,
    TimeSpan duration)
{
}
```

But in that case currently only the `methodResult` object got any value.

**Comment by sungam3r** [comment]
Both of your links lead to the same page (current page).

**Comment by rynowak** [comment]
Fixed, thanks.

**Comment by anurse** [comment]
As per https://github.com/aspnet/Announcements/issues/411 DiagnosticsAdapter is no longer shipping in 5.0

**Comment by rgueldenpfennig** [comment]
> 
> 
> As per [aspnet/Announcements#411](https://github.com/aspnet/Announcements/issues/411) DiagnosticsAdapter is no longer shipping in 5.0

Is there any replacement? How are we going to handle stuff that has been offered in DiagnosticsAdapter in .NET 5? Would appreciate any information on that :)

**Comment by sungam3r** [comment]
@rgueldenpfennig  See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/#interception-of-database-operations  
Finally, the interceptors appeared, which we used in EntityFramework 6. It is **much easier** to work with them, although the lack of DI support is frustrating.
