### ISSUE TITLE
Resolve assembly-level experimental warnings

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4395]
As a result of updating to the newer SDK, we have hundreds of TBD warnings:
```
error TBD: (NETCORE_ENGINEERING_TELEMETRY=Build) 'Microsoft.Extensions.Options.Contextual.IOptionsContext' is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed. (https://aka.ms/dotnet-extensions-warnings/TBD)
```

These are the result of
https://github.com/dotnet/extensions/blob/80f8c709c81ed9975d6b2994ed6ef4232aaee963/Directory.Build.targets#L56-L62

We need to generalise how the assembly-level attribute is applied based on the workstream. We'll need a mapping between workstreams and the experiment areas listed in https://github.com/dotnet/extensions/blob/main/docs/list-of-diagnostics.md.

**Comment by geeknoid** [comment]
This was taken care.
