### ISSUE TITLE
Retire IResourceMonitorPublisher in favor of observable instruments

### ISSUE THREAD

**Issue by geeknoid** [dotnet/extensions#4404]
We can simplify and unify the resource monitoring API to have it produce observable instruments in place of the existing IResourceMonitorPublisher API.

**Comment by evgenyfedorov2** [comment]
@geeknoid Is this issue still relevant and if yes, what is the plan here? Just put the Obsolete attributes on the publisher's API and call it a day? We can't make breaking changes and have to support all existing APIs forever, right?

**Comment by geeknoid** [comment]
Correct, no breaking changes allowed. So if we add the logic to produce observable instruments, we'd keep the old stuff and add ]Obsolete] as you say.

**Comment by noahfalk** [comment]
In case folks weren't already aware I want to call out that .NET 9 added [runtime metrics](https://github.com/dotnet/runtime/pull/104680) using the Meter API which includes a few CPU and memory metrics. It doesn't cover everything these resource monitoring metrics do but I suspect there is some overlap. The metrics got merged a few weeks ago and I am just getting the [docs](https://github.com/dotnet/docs/pull/42180) for it up now.
