### ISSUE TITLE
Fix some Health checks on NuGet packages produced.

### ISSUE THREAD

**Issue by joperezr** [dotnet/extensions#4406]
If I look at one of the RC1 packages from the dotnet/runtime repo that were shipped yesterday to NuGet, I see the following when opening it with the NuGet Package Explorer:

<img width="261" alt="image" src="https://github.com/dotnet/extensions/assets/13854455/c2ae59d1-e261-4c36-9689-433f12a926be">

If you contrast that to one of the RC1 packages produced by dotnet/extensions, you'll see some differences:

<img width="285" alt="image" src="https://github.com/dotnet/extensions/assets/13854455/1124386a-7a0a-49fb-98cd-ae0397734a7e">

I believe we are pushing symbols to Msft symbol servers as well as part of our build, so I'm not sure why this is what is stated here but we should figure out what the problem is and fix it. @RussKie can you please take a look so we make sure we correct this before RC2?

**Comment by RussKie** [comment]
@mmitche was kind enough to help me root causing it, and we figured it boiled down to this line:
https://github.com/dotnet/extensions/blob/ef72a4125a8f7f76b62024e273e90f53453b8f68/eng/MSBuild/Packaging.props#L21

The Arcade SDK doesn't support snupkg format, and the debug symbols must be in a form of *.symbols.nupkg.
