### ISSUE TITLE
Ensure that the logged dimensions in HTTP logging follow the same naming conventions as defined for spans/metrics

### ISSUE THREAD

**Issue by klauco** [dotnet/extensions#4451]
Currently, OTel defines semantic conventions for HTTP for spans and metrics and there are none for logs. However, it makes sense to not reinvent the wheel and stick to the naming which is already available even though it's meant for a different pillar. 

**What needs to be done:**
- dimension names used for HTTP and HTTP client log autocollection should be aligned with dimension names used in span/metric semantic conventions

cc @noahfalk @xakep139 @geeknoid

**Comment by xakep139** [comment]
Todo: stick with the .NET dimension names in https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Http.Telemetry/Logging/HttpClientLoggingTagNames.cs

**Comment by xakep139** [comment]
Decide what to do with complex object logging in SG (separator is `_`)

**Comment by xakep139** [comment]
OTel conventions are here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md

**Comment by klauco** [comment]
we should check and update remaining enrichers as well (remove env_<partA>_ and use pascalCase)

**Comment by klauco** [comment]
@noahfalk what would you recommend as a delimiter for nested objects when doing complex object logging? "_" (right now) or "." or sth else?

**Comment by noahfalk** [comment]
IMO dots seem marginally more aligned with the conventions. It also aligns better with typical syntax used in many programing languages when doing field access. So barring some particular technical problem I'm unaware of, I'd pick dot.

**Comment by iliar-turdushev** [comment]
The following will be implemented:

* Use `PascalCase` for the names of dimensions and LoggerMessage parameters.
* Use dot "." instead of underscore "_" for HTTP header names and for complex object logging.
* Remove "env_" suffix from the names of enrichment dimensions.

FYI @xakep139 @klauco

**Comment by joperezr** [comment]
@iliar-turdushev are you also planning on looking at logging categories for this and making sure they match the rest of dotnet?

**Comment by geeknoid** [comment]
@Tratcher  FYI

**Comment by iliar-turdushev** [comment]
Reopened the issue, because here we'll address naming of dimension not only in HTTP Logging, but also in HTTP Client logging, Complex Object Logging (aka `LogPropertiesAttribute`), enrichers, and etc. See the following [comment](https://github.com/dotnet/extensions/issues/4451#issuecomment-1748840036).

**Comment by joperezr** [comment]
Update:

- Relative ETA for this is to have it in next week.
- For new dimensions we are trying to align with OTel.
- @joperezr will start a chat with @klauco @iliar-turdushev @noahfalk and @davidfowl to figure out what conventions should be used here.

**Comment by joperezr** [comment]
Update:

- We have approvals from the dotnet side, we just need approvals by Ludmila and/or Reily (OTel side).
