### ISSUE TITLE
[.NET 8] Disable release/8.0 -> main auto-merges

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4487]
See https://github.com/dotnet/versions/pull/913

**Comment by geeknoid** [comment]
Can we close this issue?

**Comment by joperezr** [comment]
I don't think so, auto merges will continue to happen until this section in dotnet/versions repo is deleted:

https://github.com/dotnet/versions/blob/e605d060807396b9740138cd0b01fc0bc80ffa40/Maestro/subscriptions.json#L815-L831

**Comment by RussKie** [comment]
I think we can close this as we expect the auto-merges to continue to operate. 
I opened this issue before we decided on our branching strategy.
