### ISSUE TITLE
AutoClient source generator should emit the DI extension methods under the DI namespaces for discoverability

### ISSUE THREAD

**Issue by joperezr** [dotnet/extensions#4513]
As a follow up for https://github.com/dotnet/extensions/issues/4389, looks like we ensured that IServiceCollection extensions were placed in the right namespace (`Microsoft.Extensions.DependencyInjection`) but we didn't seem to do this for extensions that get generated by one of our generators. Auto Client is one of the examples, it currently generates code that looks like:

```csharp
namespace AutoClientTest
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Gen.AutoClient", "8.0.0.0")]
    public static class AutoClientsExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyDependencyClient(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            return services.AddMyDependencyClient(_ => { });
        }
```

But this will make it so that in your Program.cs file you may not be using the same namespace as where you defined your interface, which will make it for the DI extension to not be discoverable. We should make it so that the generated code creates these extensions under the right DI namespace, so that Program.cs would be able to find these without an additional using statement.

cc: @JamesNK @geeknoid @dbarbosapn

**Comment by joperezr** [comment]
Moving this Post GA as it technically can come after shipping without a breaking change. I did try locally to take a stab at a fix which was mostly working, but I started hitting issues when I had two auto clients named the same but in different namespaces, and I'm not sure how should we resolve that when not using named clients. So for example, having `MyNamespace.IMyDependencyClient` and `MyOtherNamespace.IMyDependencyClient`

**Comment by geeknoid** [comment]
AutoClient is being removed.
