### ISSUE TITLE
.NET docs to include metrics emitted by extensions

### ISSUE THREAD

**Issue by xakep139** [dotnet/extensions#4522]
See https://github.com/dotnet/extensions/pull/4482#discussion_r1348028658 and https://github.com/dotnet/extensions/pull/4482#discussion_r1351062903 for details
Tl;DR: we need to update https://github.com/dotnet/docs/pull/37213 with metric/instrument names that our components emit.
Additionally, ResourceMonitoring metrics need to be marked as experimental.

**Comment by joperezr** [comment]
This one we want to make sure we have for November.

**Comment by joperezr** [comment]
Update:
- Once the PR with final instruments is done, @xakep139 will look into this one.

**Comment by xakep139** [comment]
@iliar-turdushev the full list of metrics with their attributes/tags is listed in https://github.com/dotnet/extensions/pull/4482#issue-1915945574

**Comment by iliar-turdushev** [comment]
Documentation describing extensions' metrics has been merged https://github.com/dotnet/docs/pull/37875.

**Comment by xakep139** [comment]
Thanks @iliar-turdushev !
