### ISSUE TITLE
[Quarantined] Http.Resilience.Test (net462)

### ISSUE THREAD

**Issue by sebastienros** [dotnet/extensions#4531]
Original issue states it has been fixed.

**Comment by sebastienros** [comment]
https://github.com/dotnet/extensions/issues/4531

**Comment by geeknoid** [comment]
What's this issue about?

**Comment by sebastienros** [comment]
I don't know, I just updated the projects with actual issues. If you look at the csprojs for the tests on Resilience the net462 ones are skipped. This issue is to track it.

https://github.com/dotnet/extensions/pull/4532/files#diff-83960f8241f5e8409e566cb210ad21a58c8474284f9393ea1f37b90ae0d80bb3R8

https://github.com/dotnet/extensions/pull/4532/files#diff-3a4b6dc303130f68a2fb4186e3fc89d24a14a0011b269af036fa4c45478246fdR12
