### ISSUE TITLE
Exception log dimensions not aligned with OTel

### ISSUE THREAD

**Issue by klauco** [dotnet/extensions#4558]
There are two potential problems with exceptions being logged in ExtendedLogger:
1. the dimension names are not aligned with [OpenTelemetry semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-logs.md) 
2. the set of dimensions required by OTel is different.

**Note:** the semantic conventions for exceptions are still in experimental stage

**Comment by klauco** [comment]
cc @reyang @noahfalk @iliar-turdushev

**Comment by dariusclay** [comment]
Related: same naming alignment to be done in the tracing stuff going to otel-dotnet-contrib
