### ISSUE TITLE
Add Span support to WebEncoders

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/extensions#456]
We should add span overloads to the WebEncoders class, and also use the Base64Encoder/Decoder classes from CoreFX
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/Text/Base64Encoder.cs

**Comment by anurse** [comment]
@gfoidl only members of the repo can be assigned, but if you're still interested in submitting a PR we'd welcome it!

**Comment by BrennanConroy** [comment]
Here is the previous attempt https://github.com/aspnet/Extensions/pull/338

I do really want at least part of this in so we can get rid of an allocation in SignalR 😄

**Comment by gfoidl** [comment]
> want at least part of this in

Tell which part you want, then I can submit a (new) PR. Also if you want to have it simd-based or pure scalar code.

**Comment by BrennanConroy** [comment]
I want `WebEncoders.Base64UrlEncode` to accept a span.

Here is the affected code
https://github.com/aspnet/AspNetCore/blob/7ee7f5ddeea480e4046f042af8d58182e7117d1b/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionManager.cs#L110-L113

**Comment by gfoidl** [comment]
I'll have a look and submit a PR.

**Comment by gfoidl** [comment]
I took a look :wink: -> https://github.com/aspnet/AspNetCore/pull/11047

**Comment by anurse** [comment]
Appears to have been done.
