### ISSUE TITLE
Logging Generator still throws warnings with "https://TODO" urls

### ISSUE THREAD

**Issue by joperezr** [dotnet/extensions#4570]
There seems to still be places where we emit warnings with https://TODO urls. This work item tracks finding all of those and replacing them with real aka.ms links.

**Comment by joperezr** [comment]
@RussKie can you please take a look at this one?

**Comment by RussKie** [comment]
I could find only three instances:
https://github.com/dotnet/extensions/blob/25a9b559aaa7502a79e12630191bb2f89b064b38/src/Generators/Shared/DiagDescriptorsBase.cs#L17
https://github.com/dotnet/extensions/blob/25a9b559aaa7502a79e12630191bb2f89b064b38/src/Analyzers/Microsoft.Analyzers.Extra/DiagDescriptors.cs#L140
https://github.com/dotnet/extensions/blob/25a9b559aaa7502a79e12630191bb2f89b064b38/src/Packages/Microsoft.Extensions.StaticAnalysis/build/Microsoft.Extensions.StaticAnalysis.props#L42


@geeknoid how should these be fixed?

* `DiagDescriptors` defines "EA00*" diagnostics. How are these diagnostics documented, and where should we link to?
* `DiagDescriptorsBase` is a based for the whole plethora of diagnostics (e.g., `AUTOCLIENTGENT*`, `CTXOPTGEN*`, `ENUMSTRGEN*, etc.). How are these diagnostics documented, and where should we link to?
![image](https://github.com/dotnet/extensions/assets/4403806/0ba3b782-f192-43b6-a1c5-31bd988be105)

**Comment by geeknoid** [comment]
@RussKie The reason all these say TODO is that they are not currently documented anywhere. I've been waiting for the documentation 'wave' to hit to deal with these. The internal code base has most of these already documented, so lift-and-shift is doable for most.

**Comment by joperezr** [comment]
We should create aka.ms links in the meantime (even if they point to the repo for example, we can update those later once the docs are available), and update the code so it uses those.

**Comment by RussKie** [comment]
Redirection links are created as well.
