### ISSUE TITLE
Forward-port Microsoft.Internal.Extensions.DotNetApiDocs.Transport logic to main, push to dotnet9-transport

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/extensions#4571]
The Microsoft.Internal.Extensions.DotNetApiDocs.Transport package is successfully getting pushed to the dotnet8-transport feed: https://dnceng.visualstudio.com/public/_artifacts/feed/dotnet8-transport/NuGet/Microsoft.Internal.Extensions.DotNetApiDocs.Transport/versions/

Please get the logic that generates this package forward-ported to main and make sure the package gets pushed to the dotnet9-transport feed.

**Comment by RussKie** [comment]
We are already publishing to all required feeds:
![image](https://github.com/dotnet/extensions/assets/4403806/fe99d66a-62b4-4301-b030-95972163f44a)
