### ISSUE TITLE
Should the client generated by AutoClient to be `sealed`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/extensions#4609]
Currently, the generated client looks like follows:
![1698105180602](https://github.com/dotnet/extensions/assets/7604648/0a9d612a-146e-498a-9d6e-5de9f8239e65)

Should `sealed` be added since there're no virtual members?

https://github.com/dotnet/extensions/blob/2521489db531649f4f22c696a314bbf2c670128e/src/Generators/Microsoft.Gen.AutoClient/Emitter.cs#L173

**Comment by WeihanLi** [comment]
> AutoClient was deleted in #4596.

Any reason for deleting this? 😢

**Comment by xakep139** [comment]
> > AutoClient was deleted in #4596.
> 
> Any reason for deleting this? 😢

@geeknoid?
