### ISSUE TITLE
Microsoft.Extensions.AsyncState readme suggestions

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/extensions#4611]
Suggestions for things that could be added to src/Libraries/Microsoft.Extensions.AsyncState/README.md:

* Why would one use this library instead of static AsyncLocal\<T\>?  There seem to be the following reasons:
  + The lifetime of values is explicitly controlled; if you call an async function that sets a value, the caller can also access this value.  With AsyncLocal\<T\>, values propagate only to called functions and not to callers of async functions, although you can change that by making the caller set up a holder object and mutating that in the called function.
  + Minimizes the number of async locals in the ExecutionContext, making it cheaper to copy (e.g. during ILogger.BeginScope).
  + Can explicitly reset the state and ensure that the values are no longer rooted by ExecutionContext in any long-lived task.
  + Can use the Microsoft.AspNetCore.AsyncState package to tie the lifetime of values to HttpContext, without the code that uses IAsyncContext\<T\> directly depending on ASP.NET Core.
* When to call IAsyncState.Initialize() and IAsyncState.Reset().  The default implementation of IAsyncContext\<T\> will throw if IAsyncState.Initialize has not been called, but the library itself never calls that.

**Comment by geeknoid** [comment]
@Tratcher Unfortunately, the few guys we had working on this stuff left the company a while ago. I think @davidfowl  and @tekian likely know what's what.

**Comment by geeknoid** [comment]
Internally, there's also some R9 docs here: https://eng.ms/docs/experiences-devices/r9-sdk/docs/http-processing/asynchronous-state
