### ISSUE TITLE
LoggerMessageState.ClassifiedTag is not hidden from docs, contrary to SuppressMessageAttribute

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/extensions#4628]
### Description

In the Microsoft.Extensions.Telemetry.Abstractions library, the LoggerMessageState.ClassifiedTag type has a SuppressMessageAttribute that claims it is "hidden from docs".  However, the type appears in docs.

### Reproduction Steps

See SuppressMessageAttribute here: <https://github.com/dotnet/extensions/blob/56133fba8a43ae14520a285d083d134bc6279314/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Logging/LoggerMessageState.ClassifiedTag.cs#L10-L18>

and the docs page here: <https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.loggermessagestate.classifiedtag?view=dotnet-plat-ext-8.0>

### Expected behavior

Either of the following:
- the type does not have an attribute that claims the type is hidden from docs,
- or the type is actually hidden from docs.

### Actual behavior

A SuppressMessageAttribute on the type claims it is "hidden from docs", but the type is not hidden from docs.

**Comment by geeknoid** [comment]
It's our expectation that stuff marked as EditorBrowsable.Never should not appear in docs, which is the case for docfx normally. Is this not the case for published docs on microsoft.com in general, or is this a bug because this is a nested type?

@joperezr

**Comment by RussKie** [comment]
Maybe @gewarren knows the answer?

**Comment by gewarren** [comment]
I think we'd manually need to filter out this type from learn.microsoft.com (it's not automatic). Similar to this:

https://github.com/dotnet/dotnet-api-docs/blob/6a41a84c8a301b8841b05df8d33e684e06ca0d77/xml/_filter.xml#L155-L162

**Comment by RussKie** [comment]
Thank you @gewarren.
Is this something we need to do (e.g., submit a PR somewhere); or is it something you and your team does?

**Comment by gewarren** [comment]
Either is fine. I can do it this time and will link the PR here.

**Comment by RussKie** [comment]
That'd be awesome, thank you.

It appears we have the following instances in the codebase:
https://github.com/dotnet/extensions/blob/89ba9815bf2bf672090a26ebab7f3c2615ec404c/src/Libraries/Microsoft.Extensions.AsyncState/IAsyncLocalContext.cs#L15-L20
https://github.com/dotnet/extensions/blob/89ba9815bf2bf672090a26ebab7f3c2615ec404c/src/Libraries/Microsoft.Extensions.Diagnostics.ExtraAbstractions/Logging/LoggerMessageHelper.cs#L15-L16
https://github.com/dotnet/extensions/blob/89ba9815bf2bf672090a26ebab7f3c2615ec404c/src/Libraries/Microsoft.Extensions.Diagnostics.ExtraAbstractions/Logging/LoggerMessageState.ClassifiedTag.cs#L15-L18
https://github.com/dotnet/extensions/blob/89ba9815bf2bf672090a26ebab7f3c2615ec404c/src/Libraries/Microsoft.Extensions.Diagnostics.ExtraAbstractions/Logging/LoggerMessageState.cs#L16-L17
