### ISSUE TITLE
Experimental ID is TBD

### ISSUE THREAD

**Issue by Tratcher** [dotnet/extensions#4643]
### Description

The default id for the Experimental attribute injected at the assembly level is "TBD". Should that have a value?
https://github.com/dotnet/extensions/blob/14943b99572078f1bcf2c51e9507cf2631133fae/Directory.Build.targets#L56-L58

### Reproduction Steps

Build the repo and then decompile any of the dlls marked as Stage dev like:
https://github.com/dotnet/extensions/blob/d1d66fc97f0e0eb387983a4fc89914f490026b15/src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Microsoft.Extensions.Diagnostics.Probes.csproj#L15

### Expected behavior

The Experimental attribute should have some id.

### Actual behavior

The id is "TBD"

**Comment by joperezr** [comment]
- We want to have one experimental ID per package. cc @RussKie
