### ISSUE TITLE
Clarify experimental package warning

### ISSUE THREAD

**Issue by Tratcher** [dotnet/extensions#4649]
https://github.com/dotnet/extensions/blob/7d69192a804087d6a4e67d91803072003666b54f/eng/MSBuild/ProjectStaging.targets#L20

This gets prepended to package descriptions. It should instead say something about being Experimental and link to what that means.

**Comment by joperezr** [comment]
@RussKie did you say yesterday you were also going to look into this?

**Comment by joperezr** [comment]
We should just change the text to say "Experimental package". Development Build is not a concept tied to Experimental APIs.

**Comment by joperezr** [comment]
We discussed this in the tactical sync, we shouldn't be making these packages stable.
