### ISSUE TITLE
Inconsistent behavior in extended logging

### ISSUE THREAD

**Issue by xakep139** [dotnet/extensions#4683]
### Description

Current implementation of ExtendedLogger enables both enrichment and redaction regardless of what was enabled.

### Reproduction Steps

**Scenario №1:**
```cs
using var loggerFactory =
    LoggerFactory.Create(builder =>
    {
        builder.EnableRedaction();
        builder.Services.AddLogEnricher<CustomEnricher>();
    });

var logger = loggerFactory.CreateLogger("MyDemoLogger");
```

Even though I haven't enabled enrichment, the `CustomEnricher` will be called.

**Scenario №2:**
```cs
using var loggerFactory =
    LoggerFactory.Create(builder =>
    {
        builder.EnableEnrichment();
        builder.Services.AddRedaction();
    });

var logger = loggerFactory.CreateLogger("MyDemoLogger");
```

Even though I haven't enabled redaction, the `ErasingRedactor` will be called to redact data annotated with data classification.

**Scenario №3:**
One more confusing thing is that when I enable redaction feature, but don't have any redactors registered, I would get sensitive data being emitted as-is. Consider this example:
```cs
using var loggerFactory = LoggerFactory.Create(builder => builder.EnableRedaction());
var logger = loggerFactory.CreateLogger("MyDemoLogger");
Log.LogMethod(logger, "Sensitive user name");

internal static partial class Log
{
    [LoggerMessage(Level = LogLevel.Warning, Message = "User {Name} has now different status")]
    public static partial void LogMethod(ILogger logger, [PrivateData] string name);
}
```

### Expected behavior

Each call to `EnableRedaction()` and `EnableEnrichment()` enables the corresponding feature only.

### Actual behavior

Any of calls `EnableRedaction()` and `EnableEnrichment()` apply both of them.

**Comment by xakep139** [comment]
One more confusing thing here is that when I enable redaction feature, but don't have any redactors registered, I would get sensitive data being emitted as-is. Consider this example:
```cs
using var loggerFactory = LoggerFactory.Create(builder => builder.EnableRedaction());
var logger = loggerFactory.CreateLogger("MyDemoLogger");
Log.LogMethod(logger, "Sensitive user name");

internal static partial class Log
{
    [LoggerMessage(Level = LogLevel.Warning, Message = "User {Name} has now different status")]
    public static partial void LogMethod(ILogger logger, [PrivateData] string name);
}
```

**Comment by geeknoid** [comment]
What's the actual issue with No 3?

**Comment by geeknoid** [comment]
From an implementation standpoint, calling either EnableRedaction or EnableEnrichment ends up activating the new extended logger, which enables all the new features.

**Comment by xakep139** [comment]
> From an implementation standpoint, calling either EnableRedaction or EnableEnrichment ends up activating the new extended logger, which enables all the new features.

I understand that, but think from a user's perspective. If we have two different APIs that do one thing - that we don't need two APIs. If these two APIs mean different things, then we need to do two different things.
We can update the implementation to have an internal mode (or two boolean properties) to adjust its behavior.

**Comment by xakep139** [comment]
> What's the actual issue with No 3?

That it doesn't redact anything - even though a user feels that redaction is enabled.
