### ISSUE TITLE
[LoggerMessage] Fails to compile if a ILogger property is used instead of a field 

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/extensions#4707]
### Description

 In when using the logging source generator, if you use a property for the logger object instead of a field, the source generator gets wonky and fails to produce valid C#.

👇 This code works as intended. ✅ 
```c#
    private partial class LogFunctions(ILogger<MyCode> logger)
    {
        private readonly ILogger<MyCode> loggerObject = logger;

        [LoggerMessage(1, LogLevel.Warning, "This is a warning message")]
        public partial void TestLogMethod();
    }
```

👇 This code fails to compile ❌

```c#
    private partial class LogFunctions(ILogger<MyCode> logger)
    {
        private ILogger<MyCode> loggerObject { get; } = logger; //note the use of a property

        [LoggerMessage(1, LogLevel.Warning, "This is a warning message")]
        public partial void TestLogMethod();
    }
```

The specific issue is that the source generator tries to use the property's backing field, which has a mangled/unspeakable name  of `<loggerObject>k__BackingField`. When this mangled name is injected into the source generator's code template, it breaks the code because it isn't valid C#.

Here is the output produced by the generator

```c#
// <auto-generated/>
#nullable enable

    partial class MyCode
    {
        partial class LogFunctions
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "7.0.7.1805")]
            private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.Exception?> __TestLogMethodCallback =
                global::Microsoft.Extensions.Logging.LoggerMessage.Define(global::Microsoft.Extensions.Logging.LogLevel.Warning, new global::Microsoft.Extensions.Logging.EventId(1, nameof(TestLogMethod)), "This is a warning message", new global::Microsoft.Extensions.Logging.LogDefineOptions() { SkipEnabledCheck = true }); 

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "7.0.7.1805")]
            public partial void TestLogMethod()
            {
                if (<loggerObject>k__BackingField.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Warning))
                {
                    __TestLogMethodCallback(<loggerObject>k__BackingField, null);
                }
            }
        }
    }
```

Also note that this becomes very weird to debug if you have multiple classes or logger methods using logger method. The compile errors show up on whatever method is the last in the source generated file, even if that method was using a field. That is to say that the use of just one class anywhere in your code that uses a property for ILogger will cause strange errors to all of the source generated logger code in your assembly

### Reproduction Steps

Entire C# program and csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0-rc.2.23479.6" />
  </ItemGroup>

</Project>

```

```c#
// See https://aka.ms/new-console-template for more information
using Microsoft.Extensions.Logging;

Console.WriteLine("Hello, World!");



public partial class MyCode
{
    public MyCode(ILogger<MyCode> logger)
    {
        Log = new LogFunctions(logger);
    }
    
    private LogFunctions Log { get; }

    public void MyMethod()
    {
        Log.TestLogMethod();
    }

    private partial class LogFunctions(ILogger<MyCode> logger)
    {
        private ILogger<MyCode> loggerObject { get; } = logger;

        [LoggerMessage(1, LogLevel.Warning, "This is a warning message")]
        public partial void TestLogMethod();
    }
}
```

### Expected behavior

Either 
- A compiler error specifically forbidding the use of a property 
OR
- No errors and correct behavior

### Actual behavior

The following errors on build

```
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(15,21): error CS1525: Invalid expression term '<' [D:\dev\loggermessagebug\loggermessagebug.csproj]
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(17,45): error CS1525: Invalid expression term '<' [D:\dev\loggermessagebug\loggermessagebug.csproj]
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(15,35): error CS0103: The name 'k__BackingField' does not exist in the current context [D:\dev\loggermessagebug\loggermessagebug.csproj]
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(17,59): error CS0103: The name 'k__BackingField' does not exist in the current context [D:\dev\loggermessagebug\loggermessagebug.csproj]
```

### Regression?

Seems to have been here since at least 7.0.0

### Known Workarounds

Use a field instead of a property

### Configuration

dotnet 8.0.100-rc.2.23502.2

**Comment by dariusclay** [comment]
I believe this is related to using the primary class constructor which was introduced in C# 12. Not necessarily due to using a property but the way it's being initialized. The logging source generator is picking up the `ILogger<>` type from the backing field, not the property.

**Comment by AlgorithmsAreCool** [comment]
@dariusclay 

> The logging source generator is picking up the ILogger<> type from the backing field, not the property.

If i understand the way primary ctors work, this should not have introduced a new field into the class.

But even so, I can change the source to a normal ctor and get the same compile errors

```csharp
    private partial class LogFunctions
    {
        public LogFunctions(ILogger<MyCode> logger)
        {
            loggerObject = logger;
        }

        private ILogger<MyCode> loggerObject { get; }

        [LoggerMessage(1, LogLevel.Warning, "This is a warning message")]
        public partial void TestLogMethod();
    }
```

```
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(15,21): error CS1525: Invalid expression term '<' [D:\dev\loggermessagebug\loggermessagebug.csproj]
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(17,45): error CS1525: Invalid expression term '<' [D:\dev\loggermessagebug\loggermessagebug.csproj]
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(15,35): error CS0103: The name 'k__BackingField' does not exist in the current context [D:\dev\loggermessagebug\loggermessagebug.csproj]
D:\dev\loggermessagebug\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(17,59): error CS0103: The name 'k__BackingField' does not exist in the current context [D:\dev\loggermessagebug\loggermessagebug.csproj]
```

**Comment by dariusclay** [comment]
So on the [official logger-message-generator docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator#basic-usage), only fields are explicitly mentioned. I've also compiled against 6.0.0 and 7.0.0 and have the same behavior. I don't think property was ever supported.

**Comment by AlgorithmsAreCool** [comment]
>  I don't think property was ever supported.
Thats fine, but it should degrade gracefully with a clear error message. Instead it currently just breaks in a confusing way that took me some time to figure out.

**Comment by geeknoid** [comment]
Properties were indeed not part of the original design, but there's no reason it shouldn't be supported. Or at the very least, the generator should produce an error instead of spewing out bad code.

**Comment by dougclutter** [comment]
I'm seeing this error in .NET 8 with a class that uses _neither_ a primary constructor _nor_ an ILogger property:
```
public partial class AppOAuthEvents : OAuthEvents
{
    private readonly ILogger<AppOAuthEvents> logger;

    public AppOAuthEvents(ILogger<AppOAuthEvents> logger)
    {
        this.logger = logger;
    }
...
    [LoggerMessage(
        Level = LogLevel.Warning,
        Message = "Remote OAuth failed; redirecting to {redirectUrl}")]
    public partial void LogRemoteOAuthFailure(string redirectUrl, Exception failureException);
}
```

Does anybody have any other work-arounds?

**Comment by AlgorithmsAreCool** [comment]
@dougclutter I can't repro that based on your snippet. What is the exact error message you are seeing?

**Comment by geeknoid** [comment]
@dougclutter Try changing your field to be of type ILogger without the generic, that'll likely fix it.

**Comment by dougclutter** [comment]
@AlgorithmsAreCool Here's are the errors:
![image](https://github.com/dotnet/extensions/assets/12717532/605e6024-44ea-4f6f-9c3f-57a3c96d77a4)

@geeknoid Tried changing to ILogger and the errors persist.

**Comment by AlgorithmsAreCool** [comment]
@dougclutter Was `Logger` a property in `AppControllerBase`? If so, then we are seeing the same issue.

From my initial comment:
> Also note that this becomes very weird to debug if you have multiple classes or logger methods using logger method. The compile errors show up on whatever method is the last in the source generated file, even if that method was using a field. That is to say that the use of just one class anywhere in your code that uses a property for ILogger will cause strange errors to all of the source generated logger code in your assembly

**Comment by AlgorithmsAreCool** [comment]
@geeknoid I'm assuming the approach to fix this is prefer an `ILogger` property over a field. Or maybe special case auto-properties? The generator correctly errors on multiple ILogger fields today.

**Comment by geeknoid** [comment]
@AlgorithmsAreCool (first, I have to say I love your GitHub handle :-))

A think there are a couple easy changes:

* Make the generator able to consume generic ILogger, not just the non-generic version.
* Make the generator recognize properties on par with fields, including in an inheritance situation.

Now separate from that is deciding on the behavior when there are multiple ILogger instances in scope. I worry that if the generator simply throws an error in tha case, it would make it so code that is storing ILogger in a field and then wrapping a property around it would fail because the generator would see both the property and the backing field. So I think if there are both property and field, the generator will silently just use the field.

**Comment by dougclutter** [comment]
@geeknoid - (head slap) You're absolutely right...ILogger was a property on `AppControllerBase`.  Sorry I missed that.

**Comment by dougclutter** [comment]
@geeknoid - I have to disagree with the behavior you recommended:

> Now separate from that is deciding on the behavior when there are multiple ILogger instances in scope. I worry that if the generator simply throws an error in tha case, it would make it so code that is storing ILogger in a field and then wrapping a property around it would fail because the generator would see both the property and the backing field. So I think if there are both property and field, the generator will silently just use the field.

While what you propose is logical, I think that approach is just too opaque.  If there are multiple ILoggers, I would rather be forced to *specify* which I want the generator to use.

**Comment by geeknoid** [comment]
@dougclutter I guess we could have another attribute that you apply to the thing holding the logger?

```csharp
[UseThisLogger]
private static readonly ILogger _logger;
```csharp
