### ISSUE TITLE
Missing stable package for Microsoft.Extensions.Http.Telemetry

### ISSUE THREAD

**Issue by martincostello** [dotnet/extensions#4723]
### Description

Most of the extensions packages received an 8.0.0 update today, but [Microsoft.Extensions.Http.Telemetry](https://www.nuget.org/packages/Microsoft.Extensions.Http.Telemetry) appears to be missing a stable version.

It's listed in an image for the extensions in the [Announcing .NET 8 blog post](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/), so I'd expect it to have also shipped a non-prerelease version.

### Reproduction Steps

N/A

### Expected behavior

A 8.0.0 package is present in NuGet.org.

### Actual behavior

No stable package is available in NuGet.org.

### Known Workarounds

Use a non-stable version.

**Comment by dariusclay** [comment]
Hi thanks for the feedback! This was renamed a few months ago as [Microsoft.Extensions.Http.Diagnostics](https://www.nuget.org/packages/Microsoft.Extensions.Http.Diagnostics). It's unfortunate the blog post didn't get the update.
