### ISSUE TITLE
HealthChecks stoped to work on version 8.0

### ISSUE THREAD

**Issue by zimbres** [dotnet/extensions#4725]
### Description

After upgrade project to 8.0, also Microsoft.Extensions.Diagnostics.HealthChecks to version 8.0, the HealthCheckPublisher is no longer called.

### Reproduction Steps

[https://github.com/zimbres/HealthChecksTest](https://github.com/zimbres/HealthChecksTest)

### Expected behavior

File "health" is create and HealthCheckPublisher is called on the timespan defined in HealthCheckPublisherOptions.

### Actual behavior

HealthCheckPublisher  is not called.

### Regression?

Using Microsoft.Extensions.Diagnostics.HealthChecks at version 7.0.14, even with project in version 8.0 works as expected.

**Comment by dariusclay** [comment]
Hi @zimbres thanks for contacting us. 

Since this feature is shipped as part of aspnetcore, you might want to file the issue there too:
https://github.com/dotnet/aspnetcore/issues
