### ISSUE TITLE
Add support to transitively log complex object graphs.

### ISSUE THREAD

**Issue by jabak** [dotnet/extensions#4738]
### Description

Using LogProperties attribute combined with the LoggerMessage to log a complex type doesn't output all properties including those that themselves are complex types. I would expect it to traverse the entire object graph outputting key/value pairs of all properties - flatten all properties so to speak.

### Reproduction Steps

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
var logger = app.Services.GetRequiredService<ILogger<Program>>();
logger.ForecastRetrieved(new WeatherForecast());
app.Run();

static partial class Log
{
    [LoggerMessage(LogLevel.Information, "Test")]
    public static partial void ForecastRetrieved(this ILogger logger, [LogProperties(SkipNullProperties = false)] WeatherForecast forecast);
}

public class WeatherForecast
{
    public DateOnly Date { get; set; }
    public int TemperatureC { get; set; }
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
    public string? Summary { get; set; }
    public GeoArea SubArea { get; set; } = new GeoArea();
}

public class GeoArea
{
    public string Name { get; set; } = "California";
}

### Expected behavior

Generated should look like this:

// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Compensate for https://github.com/dotnet/roslyn/issues/54103
partial class Log
{
    /// <summary>
    /// Logs "Test" at "Information" level.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Gen.Logging", "8.0.0.0")]
    public static partial void ForecastRetrieved(this global::Microsoft.Extensions.Logging.ILogger logger, global::WeatherForecast forecast)
    {
        if (!logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
        {
            return;
        }

        var state = global::Microsoft.Extensions.Logging.LoggerMessageHelper.ThreadLocalState;

        _ = state.ReserveTagSpace(6);
        state.TagArray[5] = new("forecast.Date", forecast?.Date);
        state.TagArray[4] = new("forecast.TemperatureC", forecast?.TemperatureC);
        state.TagArray[3] = new("forecast.TemperatureF", forecast?.TemperatureF);
        state.TagArray[2] = new("forecast.Summary", forecast?.Summary);
        state.TagArray[1] = new("forecast.SubArea.Name", forecast?.SubArea?.Name);
        state.TagArray[0] = new("{OriginalFormat}", "Test");

        logger.Log(
            global::Microsoft.Extensions.Logging.LogLevel.Information,
            new(0, nameof(ForecastRetrieved)),
            state,
            null,
            static (s, _) =>
            {
                return "Test";
            });

        state.Clear();
    }
}

### Actual behavior

// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Compensate for https://github.com/dotnet/roslyn/issues/54103
partial class Log
{
    /// <summary>
    /// Logs "Test" at "Information" level.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Gen.Logging", "8.0.0.0")]
    public static partial void ForecastRetrieved(this global::Microsoft.Extensions.Logging.ILogger logger, global::WeatherForecast forecast)
    {
        if (!logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Information))
        {
            return;
        }

        var state = global::Microsoft.Extensions.Logging.LoggerMessageHelper.ThreadLocalState;

        _ = state.ReserveTagSpace(6);
        state.TagArray[5] = new("forecast.Date", forecast?.Date);
        state.TagArray[4] = new("forecast.TemperatureC", forecast?.TemperatureC);
        state.TagArray[3] = new("forecast.TemperatureF", forecast?.TemperatureF);
        state.TagArray[2] = new("forecast.Summary", forecast?.Summary);
        state.TagArray[1] = new("forecast.SubArea", forecast?.SubArea);
        state.TagArray[0] = new("{OriginalFormat}", "Test");

        logger.Log(
            global::Microsoft.Extensions.Logging.LogLevel.Information,
            new(0, nameof(ForecastRetrieved)),
            state,
            null,
            static (s, _) =>
            {
                return "Test";
            });

        state.Clear();
    }
}

### Configuration

8.0

### Other information

I would suggest to make the depth of this object graph traversal configurable and also add an option to enable/disable it.

**Comment by iliar-turdushev** [comment]
@jabak Thank you for reaching out. In order to log properties of `SubArea` property which is a complex object itself, you need to decorate it with `LogProperties` attribute too.

**Comment by geeknoid** [comment]
This was an explicit design choice for control and consistency with how parameters are handled in log methods.

A lot method parameter is normally serialized by calling .ToString on it, but if you have [LogProperties] we don't call .ToString and instead emit the object's properties by calling .ToString() on each property. If you want to see a property's transitive properties, then you must apply [LogProperties] on the specific property.

We could consider adding a Transitive boolean property on the [LogProperties] attribute to make it "go deep" automatically.

**Comment by jabak** [comment]
"We could consider adding a Transitive boolean property on the [LogProperties] attribute to make it "go deep" automatically.": that would in my opinion be the optimal solution.
