### ISSUE TITLE
Type referenced in doc comments isn't public

### ISSUE THREAD

**Issue by gewarren** [dotnet/extensions#4746]
### Description

On [this line](https://github.com/dotnet/extensions/blob/f34d120d2654057a31dc96d7f86dc42629044472/src/Libraries/Microsoft.Extensions.Options.Contextual/NullConfigureContextualOptions.cs#L12), `NullConfigureContextOptions{TOptions}` isn't a public type and so it's not published to learn.microsoft.com, resulting in a broken link [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.contextual.nullconfigurecontextualoptions.getinstance?view=dotnet-plat-ext-8.0#definition). 

### Reproduction Steps

N/A

### Expected behavior

Reference a public type.

### Actual behavior

Reference an internal type.

**Comment by geeknoid** [comment]
We have an analyzer that can detect this situation, I'll port it over to this repo.
