### ISSUE TITLE
Enable mutation testing in dotnet/extensions

### ISSUE THREAD

**Issue by geeknoid** [dotnet/extensions#4749]

**Comment by RussKie** [comment]
I have a prototype, however there are two issues:
1. MT take a significant time - ~50 minutes. This is not usable for the PR CI.
2. MT currently fail for projects that use experimental API. This is a limitation of the Stryker, https://github.com/stryker-mutator/stryker-net/issues/2775.

**Comment by dupdob** [comment]
hi, not sure what is the issue here.
I am assuming this is the running time. The best approach to reduce time is to look into the [`since`](https://stryker-mutator.io/docs/stryker-net/configuration/#since-flag-committish) option.

**Comment by geeknoid** [comment]
@RussKie Is this using the same incremental mutation testing we do in the R9 repo? Perhaps we need to integrate DeltaBuild as well?

Can you explain the issue with the experimental attribute? Again, in the R9 repo we have many uses of experimental, so what's the actual problem?
