### ISSUE TITLE
AddExtendedHttpClientLogging() doesn't log Content headers

### ISSUE THREAD

**Issue by wjrogers** [dotnet/extensions#4769]
### Description

The new `HttpClient` logging facility in Microsoft.Extensions.Http.Diagnostics does not log content headers. `HttpHeadersReader` only inspects the request and response `Headers` property, not `Content.Headers`. Unfortunately, many of the interesting headers to log are only available via `Content.Headers`.

https://github.com/dotnet/extensions/blob/13a6288c9de8d8f83c40ae419803e6a990bf5825/src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpHeadersReader.cs#L39
https://github.com/dotnet/extensions/blob/13a6288c9de8d8f83c40ae419803e6a990bf5825/src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpHeadersReader.cs#L49

### Reproduction Steps

```csharp
using Microsoft.Extensions.Compliance.Classification;
using Microsoft.Extensions.Compliance.Redaction;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

using var host = new HostBuilder()
    .ConfigureLogging(builder =>
    {
        builder.AddJsonConsole(options =>
        {
            options.JsonWriterOptions = new() { Indented = true };
            options.IncludeScopes = true;
        });
    })
    .ConfigureServices(services =>
    {
        services
            .AddRedaction(builder =>
            {
                // docs suggest this should be the default, but AFAICT it's not
                builder.SetRedactor<NullRedactor>(DataClassificationSet.FromDataClassification(DataClassification.None));
            });

        services.AddHttpClient("test")
            .AddExtendedHttpClientLogging(options =>
            {
                options.ResponseHeadersDataClasses.Add("Content-Type", DataClassification.None);
            });
    })
    .Build();

var client = host.Services.GetRequiredService<IHttpClientFactory>().CreateClient("test");

using var response = await client.GetAsync("https://ifconfig.co/json");

System.Console.WriteLine($"Content-Type: {response.Content.Headers.ContentType}");
```

### Expected behavior

The log message includes the property `http.response.headers.content-type` = `application/json`.

### Actual behavior

```json
{
  "EventId": 1,
  "LogLevel": "Information",
  "Category": "Microsoft.Extensions.Http.Logging.HttpClientLogger",
  "Message": "GET ifconfig.co/REDACTED",
  "State": {
    "Message": "http.request.method=GET,server.address=ifconfig.co,url.path=REDACTED,Duration=297,http.response.status_code=200",
    "http.request.method": "GET",
    "server.address": "ifconfig.co",
    "url.path": "REDACTED",
    "Duration": 297,
    "http.response.status_code": 200
  },
  "Scopes": []
}
```

### Known Workarounds

I do not think a work-around is possible because the affected service, `IHttpHeadersReader`, is `internal`, so consumers cannot replace it.

### Configuration

- dotnet 8.0.100
- Microsoft.Extensions.Http.Diagnostics 8.0.0

**Comment by xakep139** [comment]
@wjrogers thank you for reporting this! The support has been added, it will be controlled by a switch in `LoggingOptions`: https://github.com/dotnet/extensions/blob/1e5ad82db35c057611f9743c2a40af074027ea2b/src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/LoggingOptions.cs#L161
