### ISSUE TITLE
Is there `ActivityCollector`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/extensions#4825]
We have LogCollector and MetricsCollector in https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Diagnostics.Testing

Then do we have ActivityCollector or something like that?

**Comment by gfoidl** [comment]
The [ActivityListener](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitylistener?view=net-8.0) is what you are looking for? (search also with your favorite search engine to find example on how to use it, it's quite easy to use BTW).

**Comment by WeihanLi** [comment]
I'm using the `ActivityListener` now, but it seems it has concurrent issues.

For example, I have an ActivityListener in a test case, when I have two activities at the same time, the ActivityListener would listen all activities even these two activities are not in the same test context.

**Comment by WeihanLi** [comment]
Ah, I think I could create an activity before running the test case method and filter activity by parentId, closed for now, thanks
