### ISSUE TITLE
Setup infrastructure for dependency flow for 2.x

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/extensions#484]
For release/2.1 and 2.2, we should automate consuming new dependencies. We can re-use the same dependency flow mechanism that we setup for aspnet/AspNetCore. See https://github.com/aspnet/Extensions/blob/master/eng/scripts/UpdateDependencies.ps1.

For master, we should work on setting up the 'darc' dependency tool. See https://github.com/dotnet/arcade.

**Comment by anurse** [comment]
Closing as this issue is out-of-date and is tracking work that is no longer needed.
