### ISSUE TITLE
[API Proposal]: Expose AddTcpEndpointHealthCheck

### ISSUE THREAD

**Issue by joegoldman2** [dotnet/extensions#4879]
### Background and motivation

Currently, `Microsoft.Extensions.Diagnostics.Probes` package provides a convenient method `AddKubernetesProbes` for registering three TCP endpoints (Liveness, Startup, and Readiness probes) internally using the `AddTcpEndpointHealthCheck` method.
However, the `AddTcpEndpointHealthCheck` method is marked as internal, limiting its accessibility for users who may not be hosting in Kubernetes (even if I understand that it's compatible outside Kubernetes as it just exposes TCP endpoints in fact) or those who do not require all three probes.

### API Proposal

I propose exposing the `AddTcpEndpointHealthCheck` method publicly to allow users more flexibility in configuring TCP health checks probes based on their specific needs:

```diff
namespace Microsoft.Extensions.Diagnostics.Probes;

- internal static class TcpEndpointHealthCheckExtensions
+ public static class TcpEndpointHealthCheckExtensions
{
-    internal static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services)
+    public static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services)

-    internal static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, string name)
+    public static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, string name)

-    internal static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, Action<KubernetesProbesOptions.EndpointOptions> configure)
+    public static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, Action<TcpEndpointOptions> configure)

-    internal static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, string name, Action<KubernetesProbesOptions.EndpointOptions> configure)
+    public static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, string name, Action<TcpEndpointOptions> configure)

-    internal static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, IConfigurationSection configurationSection)
+    public static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, IConfigurationSection configurationSection)

-    internal static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, string name, IConfigurationSection configurationSection)
+    public static IServiceCollection AddTcpEndpointHealthCheck(this IServiceCollection services, string name, IConfigurationSection configurationSection)
}
```

`KubernetesProbesOptions.EndpointOptions` should probably not be a subclass of `KubernetesProbesOptions` and renamed `TcpEndpointOptions` as well:
```diff
namespace Microsoft.Extensions.Diagnostics.Probes;

- public partial class KubernetesProbesOptions
{
-     public class EndpointOptions { }
+     public class TcpEndpointOptions { }
}
```

### API Usage

```csharp
var services = new ServiceCollection();
services.AddTcpEndpointHealthCheck(options =>
{
    options.TcpPort = 5000;
    options.MaxPendingConnections = 20;
    options.HealthAssessmentPeriod = TimeSpan.FromMinutes(1);
})
```

### Risks

Nothing I can see now. This package is still in "dev" stage so modifications to the exposed APIs (rename of `KubernetesProbesOptions.EndpointOptions` class) can be done.

**Comment by joegoldman2** [comment]
@geeknoid I'm interested in working on this issue if the API is approved.

**Comment by geeknoid** [comment]
Would it be sufficient to add a new boolean value in EndpointOptions to indicate whether a specific port should be enabled or not? Then the consumer could just enable one port out of the three and get the behavior you're seeking?

**Comment by joegoldman2** [comment]
Do you mean something like this?

```cs
services.AddKubernetesProbes(options =>
{
    options.LivenessProbe.IsEnabled = true;
    options.StartupProbe.IsEnabled = false;
    options.ReadinessProbe.IsEnabled = false;
})
```

**Comment by geeknoid** [comment]
@joegoldman2 Yep

**Comment by geeknoid** [comment]
All right,

We can't change the composition of EndpointOptions being a nested type inside of KubernetesProbeOptions as that would be a breaking change. This means we'd need a new top-level type to hold the tcp options. That means we'd need two implementations of the service, one consuming one kind of option, the other consuming the other kind of option.

In other words, given the compat constraints, I think we'd end up with no code sharing at all. Different extension methods, different options type, different service implementation.

**Comment by joegoldman2** [comment]
Even if this package is still in dev stage? Or is it because a rtm version has already been released?

**Comment by geeknoid** [comment]
Oh, I thought this had been released :-)

Then yes, we could make the changes you propose.

If you feel up to it, please go ahead and crank out a PR. I should be scheduling API reviews soon for the few packages still in dev mode, which will include this one.
