### ISSUE TITLE
Lack of cgroups v2 Support in Microsoft.Extensions.Diagnostics.ResourceMonitoring

### ISSUE THREAD

**Issue by mobratil** [dotnet/extensions#4885]
### Description

I am reporting an issue with `Microsoft.Extensions.Diagnostics.ResourceMonitoring` related to its incompatibility with cgroups v2. This issue is particularly evident when running applications in environments that default to cgroups v2, such as Debian GNU/Linux 12 (Bookworm).

### Issue Details

The library seems to be designed to work with cgroups v1, as it attempts to access `/sys/fs/cgroup/memory/memory.limit_in_bytes`, a path specific to the cgroups v1 hierarchy. In environments using cgroups v2, this path does not exist, leading to `System.IO.DirectoryNotFoundException`.

### Expected Behavior

For environments using cgroups v2, the library should be able to access the appropriate cgroups v2 paths and files to monitor resources.

### Actual Behavior

When running in a cgroups v2 environment, the library fails to find the required paths, resulting in an unhandled exception (`DirectoryNotFoundException`).

### Steps to Reproduce

1. Run an application using `Microsoft.Extensions.Diagnostics.ResourceMonitoring` in a Docker container on a system using cgroups v2 (e.g., Debian GNU/Linux 12).
2. Observe the `DirectoryNotFoundException` when the library attempts to access cgroups v1 specific paths.

### Suggested Solution

It would be beneficial for `Microsoft.Extensions.Diagnostics.ResourceMonitoring` to include support for cgroups v2, given its increasing adoption in newer Linux distributions.

### Additional Context

This issue is crucial for applications that are intended to run in modern Linux environments where cgroups v2 is the default or only available option.

**Comment by tarasevichvlad** [comment]
Good day. Is there any time frame for solving this problem? In our project this has a very high priority. And it is important for us to understand how quickly it will appear here or whether this package will simply be abandoned.

**Comment by madhub** [comment]
Most of the Linux distro are moved cgroup v2 & it is also available in the stable version of [kubernetes ](https://kubernetes.io/blog/2022/08/31/cgroupv2-ga-1-25/). I would be great if you support new version otherwise library can't be used in these environments

**Comment by mobratil** [comment]
The issue was resolved by this PR: https://github.com/dotnet/extensions/pull/5068

**Comment by tarasevichvlad** [comment]
Hi, @mobratil 
I faced error after updating.

"body": "Unable to gather utilization statistics.",
  "severity": "Error",
  "attributes": {
    "exception.message": "Expected proc/stat to start with 'cpu ' but it was 'estore_file 0\nworkingset_nodereclaim 0\npgfault 623476\npgmajfault 73\npgrefill 0\npgscan 0\npgsteal 0\npgactivate 2924\npgdeactivate 0\npglazyfree 0\npglazyfreed 0\nthp_fault_alloc 0\nthp_collapse_alloc 0\ncpu  1843193685 225438 690691436 5724483778 16007065 0 61993087 0 0 0'.",
    "exception.stacktrace": "System.InvalidOperationException: Expected proc/stat to start with 'cpu ' but it was 'estore_file 0\nworkingset_nodereclaim 0\npgfault 623476\npgmajfault 73\npgrefill 0\npgscan 0\npgsteal 0\npgactivate 2924\npgdeactivate 0\npglazyfree 0\npglazyfreed 0\nthp_fault_alloc 0\nthp_collapse_alloc 0\ncpu  1843193685 225438 690691436 5724483778 16007065 0 61993087 0 0 0'.\n   at Microsoft.Shared.Diagnostics.Throw.InvalidOperationException(String message)\n   at Microsoft.Extensions.Diagnostics.ResourceMonitoring.Linux.LinuxUtilizationParserCgroupV2.GetHostCpuUsageInNanoseconds()\n   at Microsoft.Extensions.Diagnostics.ResourceMonitoring.Linux.LinuxUtilizationProvider.GetSnapshot()\n   at Microsoft.Extensions.Diagnostics.ResourceMonitoring.ResourceMonitorService.ExecuteAsync(CancellationToken cancellationToken)",
    "exception.type": "InvalidOperationException",
    "logrecord.event.id": 1,
    "logrecord.event.name": "HandledGatherStatisticsException",
    "{OriginalFormat}": "Unable to gather utilization statistics."
  },
  "resources": {
    "deployment.environment": "Testing",
    "telemetry.sdk.language": "dotnet",
    "telemetry.sdk.name": "opentelemetry",
    "telemetry.sdk.version": "1.8.1"
  },
  "instrumentation_scope": {
    "name": "Microsoft.Extensions.Diagnostics.ResourceMonitoring.ResourceMonitorService"
  }

**Comment by mobratil** [comment]
@tarasevichvlad I'm afraid that this problem is caused by this issue: https://github.com/dotnet/extensions/issues/5114
