### ISSUE TITLE
Add informative tags/description to find packages (specifically FakeTimeProvider)

### ISSUE THREAD

**Issue by fbd** [dotnet/extensions#4958]
When searching for the package that contains the _FakeTimeProvider_ implementation it is natural to search for the name _FakeTimeProvider_.  Currently you will not find the _Microsoft.Extensions.TimeProvider.Testing_ if you search for FakeTimeProvider either in the NuGet Gallery or under Manage Nuget packages in Visual Studio.

Since this is a fairly simple change, i.e. adding _FakeTimeProvider_ as a tag or a mention of the class in the Description to aid in search, I don't think this warrants a PR, but maybe someone can do the change on an already open PR. :)

**Comment by RussKie** [comment]
Do you mean here?
https://github.com/dotnet/extensions/blob/a8e17517bd5150cc0f992b66aa6591c7c6fbdfc4/src/Libraries/Microsoft.Extensions.TimeProvider.Testing/Microsoft.Extensions.TimeProvider.Testing.csproj#L4
https://github.com/dotnet/extensions/blob/a8e17517bd5150cc0f992b66aa6591c7c6fbdfc4/src/Libraries/Microsoft.Extensions.TimeProvider.Testing/Microsoft.Extensions.TimeProvider.Testing.csproj#L7

**Comment by RussKie** [comment]
Pull requests are welcome :)
