### ISSUE TITLE
Update the Options Contextual API with feedback from R9 API Review Meeting

### ISSUE THREAD

**Issue by MrJosman** [dotnet/extensions#5011]
The required changes in the API are based on comments in [Pull Request 968281](https://domoreexp.visualstudio.com/R9/_git/ApiReview/pullrequest/968281): API.Microsoft.Extensions.Options.Contextual

**Comment by geeknoid** [comment]
I'm closing this in favor of https://github.com/dotnet/extensions/issues/5049
