### ISSUE TITLE
Resource Monitoring for Windows should report container memory usage

### ISSUE THREAD

**Issue by evgenyfedorov2** [dotnet/extensions#5108]
### Description

Resource Monitoring for Windows reports memory usage of the process the app is running in. Instead of that, it should consider memory usage of all the processes running in the container as there might be more than one process. Resource Monitoring for Linux does the right thing already - it reports container memory usage.

### Reproduction Steps

Check out [this](https://github.com/dotnet/extensions/blob/bf13bd72e08867410b65230f286c1ae3bb1f87e9/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Interop/ProcessInfo.cs#L47) line - Resource Monitoring for Windows uses process info to report memory usage.

### Expected behavior

Resource Monitoring for Windows sums up memory usage of all processes running in the same container and reports the result for the memory usage counters.

### Actual behavior

Resource Monitoring for Windows reports memory usage of the process the app is running in.
Resource Monitoring for Windows reports memory usage of the whole container, e.g. all processes running in the container.

**Comment by xakep139** [comment]
The issue seems to be a part of #4538

**Comment by RussKie** [comment]
Should #4538 be closed as superceded as the Linux side is now resolved?
