### ISSUE TITLE
Allow the Resilience package to access the TelemetryOptions of Polly for easier configuration

### ISSUE THREAD

**Issue by sander1095** [dotnet/extensions#5244]
The full context can be found here: https://github.com/App-vNext/Polly/issues/2162. In short:

Say we configure Polly to retry a HTTP request 3 times. Each time it fails, it logs an error. Say it would have succeeded the 3rd time. Then the errors (which might have triggered some alerts) were not truly errors, only warnings.

I would like to be able to configure Polly to only treat final attempts that fail as errors, and earlier retries to be configured as Warnings.

This is possible with https://github.com/App-vNext/Polly/pull/2072 but I don't seem to be able to edit this context/telemetry stuff when using the `Resilience` packages.

I would like to be able to modify Polly's severity levels for events.

**Comment by sander1095** [comment]
@iliar-turdushev this sounds perfect!

**Comment by iliar-turdushev** [comment]
@sander1095 thank you for the feedback. I'm closing the issue.
