### ISSUE TITLE
Minor Release 8.3.0 introduced major version bump on the transitive dependencies

### ISSUE THREAD

**Issue by dxynnez** [dotnet/extensions#5287]
### Description

[This](https://github.com/dotnet/extensions/pull/4976/files) commit bumped the 'Microsoft.IO.RecyclableMemoryStream' to 3.0.0 which contains several breaking changes.

Ideally any minor release should not bump major versions of its dependencies as major release might very well contain breaking change(s) while a minor release wouldn't - it's unexpected for someone who only bump the minor version of the 'Microsoft.Extension.*' series packages to suddenly introduce breaking changes.

### Reproduction Steps

N/A

### Expected behavior

No major version bump of any of the transitive dependencies in a minor release

### Actual behavior

Major version bump for 'Microsoft.IO.RecyclableMemoryStream' in 'Microsoft.Extensions.Http.Diagnostics' 8.3.0

**Comment by RussKie** [comment]
Yes, you're correct. It is an unfortunate situation, and it was an uneasy decision as you can see from the linked thread.
