### ISSUE TITLE
[Proposal] DependencyInjection.AutoRegistration

### ISSUE THREAD

**Issue by alrz** [dotnet/extensions#5314]
Normally, all types inherited from a particular interface are intended to be registered in DI. To always ensure that all implementations are registered in the DI an extension generator can be used.

```cs
[InterfaceUsage(ServiceLifetime.Singleton, AllowMultiple = false)]
interface ISomeService;
```
generates
```cs
namespace Microsoft.Extensions.DependencyInjection;

internal static class AutoRegistrationServiceCollectionExtensions
{
  internal static IServiceCollection AddInterfaceImplementations(this IServiceCollection services)
  {
      return services.AddSingleton<ISomeService, SomeImplementation>();
  }
}
```
or produces an error if there are multiple implementors.

**Comment by RussKie** [comment]
> Normally, all types inherited from a particular interface are intended to be registered in DI.

I disagree, I feel that this is a fallacy. 
There could be a base interface with several derived more-scoped API interfaces; there could be public implementations and internal-only (and test-only) implementations; there could be other scenarios too.

Whilst there are some merits to your proposal, it feels very niche - i.e., it is addressing a very narrow usecase, and with that it doesn't feel it'd to be useful for all or significant majority of users of dotnet/extensions libraries.
