### ISSUE TITLE
FakeTimeProvider - Continuations on Task.Delay do not run when FakeTimeProvider.Advance is called.

### ISSUE THREAD

**Issue by paul-walls** [dotnet/extensions#5326]
### Description

When using FakeTimerProvider in tests, continuations on Task.Delay do not run when FakeTimeProvider.Advance is called.

### Reproduction Steps

```
var counter = 0;
var provider = new FakeTimeProvider( startDateTime: DateTimeOffset.UtcNow );
var task = Task
    .Delay( TimeSpan.FromSeconds( 1 ), provider )
    .ContinueWith( task => ++counter );

provider.Advance( TimeSpan.FromSeconds( 2 ) );

//await Task.Delay( 1 );

Assert.Equal( 1, counter );
```

### Expected behavior

Continuations on `Task.Delay` should run when the time is advanced, regardless of whether the continuation task is awaited or not.

### Actual behavior

Continuations on Task.Delay do not run when the time is advanced (unless the original task is explicitly awaited or an unrelated Task.Delay is awaited).

### Regression?

Unknown

### Known Workarounds

Await an unrelated Task.Delay *after* calling Advance

### Configuration

.NET 8.0.300
Microsoft.Extensions.TimeProvider.Testing 8.7.0
xunit 2.9.0

**Comment by paul-walls** [comment]
Actually, this isn't a bug at all. The continuation is being properly scheduled after the original task completes. It was just being scheduled to run asynchronously (default). The following code works as expected:

```
var counter = 0;
var provider = new FakeTimeProvider( startDateTime: DateTimeOffset.UtcNow );
var task = Task
    .Delay( TimeSpan.FromSeconds( 1 ), provider )
    .ContinueWith( task => ++counter, TaskContinuationOptions.ExecuteSynchronously );

provider.Advance( TimeSpan.FromSeconds( 1 ) );

//await Task.Delay( 1 );

Assert.Equal( 1, counter );
```

**Comment by RussKie** [comment]
Thank you for sharing.
