### ISSUE TITLE
[API Proposal]: Make the ResourceUtilization.Snapshot property public

### ISSUE THREAD

**Issue by evgenyfedorov2** [dotnet/extensions#5389]
### Background and motivation

The [Snapshot](https://github.com/dotnet/extensions/blob/8fa03a9bafc6de229427346caca42fab06e54643/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceUtilization.cs#L44) property of `Microsoft.Extensions.Diagnostics.ResourceMonitoring.ResourceUtilization` struct is `internal`, but I suggest making it `public`, so that any implementation of the [public interface IResourceUtilizationPublisher](https://github.com/dotnet/extensions/blob/8fa03a9bafc6de229427346caca42fab06e54643/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/IResourceUtilizationPublisher.cs) would be able to access it. This is also required by for a 1P library and partners.

### API Proposal

```diff
namespace Microsoft.Extensions.Diagnostics.ResourceMonitoring;

/// <summary>
/// Captures resource usage at a given point in time.
/// </summary>
[SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Comparing instances is not an expected scenario")]
public readonly struct ResourceUtilization
{
    public double CpuUsedPercentage { get; }
    public double MemoryUsedPercentage { get; }
    public ulong MemoryUsedInBytes { get; }
    public SystemResources SystemResources { get; }

-   internal Snapshot Snapshot { get; } = default;
+   public Snapshot Snapshot { get; } = default;
```

### API Usage

```csharp
// a custom implementation of IResourceUtilizationPublisher:
internal class MyCounterPublisher : IResourceUtilizationPublisher
{
    ...
    public ValueTask PublishAsync(ResourceUtilization utilization, CancellationToken cancellationToken)
    {
        ...
        utilization.Snapshot // do something with it.
   }
}
```

**Comment by RussKie** [comment]
Sounds reasonable to me. Required to unblock 1P implementations.
Approved.
