### ISSUE TITLE
Test failure WaiterRemovedAfterDispose

### ISSUE THREAD

**Issue by amcasey** [dotnet/extensions#5450]
Microsoft.Extensions.Time.Testing.Test.TimerTests.WaiterRemovedAfterDispose

```
Assert.Equal() Failure: Values differ
Expected: 2
Actual:   1
```
```
   at Microsoft.Extensions.Time.Testing.Test.TimerTests.WaiterRemovedAfterDispose() in D:\a\_work\1\s\test\Libraries\Microsoft.Extensions.TimeProvider.Testing.Tests\TimerTests.cs:line 237
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=818533

**Comment by amcasey** [comment]
FYI @RussKie - last time you wanted to investigate, rather than skip

**Comment by amcasey** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=819061 too

**Comment by RussKie** [comment]
@dotnet/dotnet-extensions-fundamentals please triage

**Comment by amadeuszl** [comment]
I'm checking this one, verifying it's a problem with test itself or the actual logic

**Comment by amadeuszl** [comment]
I'll be checking pipelines from time to time, but let me know in case there's new failure.
