### ISSUE TITLE
Cache JSON schema generated in CompleteAsync<T>

### ISSUE THREAD

**Issue by stephentoub** [dotnet/extensions#5482]
Currently each call to `CompleteAsync<T>` generates a schema:
https://github.com/dotnet/extensions/blob/a7e4f3b402620610eaa02b32978efe229bff32e6/src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientStructuredOutputExtensions.cs#L137

This should be cached, e.g. via a ConditionalWeakTable associated with the corresponding JsonSerializer.

**Comment by stephentoub** [comment]
> To be clear, this should be reusing the same caching infrastructure used by the existing `InferSchema` helpers.

Only tangentially-related, you thought we should consider exposing some of that publicly, yes? If so, could you open an issue to track? Thanks.

**Comment by eiriktsarpalis** [comment]
Yes, given the current shape of function calling exposing these helpers to other implementers is almost mandatory.

**Comment by stephentoub** [comment]
Being addressed in https://github.com/dotnet/extensions/pull/5513
