### ISSUE TITLE
Expose `FunctionCallHelpers` as public API.

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/extensions#5496]
> To be clear, this should be reusing the same caching infrastructure used by the existing `InferSchema` helpers.
> 
> Only tangentially-related, you thought we should consider exposing some of that publicly, yes? If so, could you open an issue to track? Thanks. 

 _Originally posted by @stephentoub in [#5482](https://github.com/dotnet/extensions/issues/5482#issuecomment-2403350491)_

**Comment by stephentoub** [comment]
Being addressed in https://github.com/dotnet/extensions/pull/5513
