### ISSUE TITLE
ResourceMonitoring has 2 different meter names

### ISSUE THREAD

**Issue by makazeu** [dotnet/extensions#5537]
### Description

In [WindowsContainerSnapshotProvider.cs](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsContainerSnapshotProvider.cs), the meter name is  `Microsoft.Extensions.Diagnostics.ResourceMonitoring`. 
```
var meter = meterFactory.Create(ResourceUtilizationInstruments.MeterName);
```

But in [WindowsNetworkMetrics.cs](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Network/WindowsNetworkMetrics.cs), the meter name is `ResourceMonitoring`.
```
var meter = meterFactory.Create(nameof(ResourceMonitoring));
```

This library has 2 different meters, which is confusing to users. 

### Reproduction Steps

Just use the library.

```
_ = services.AddResourceMonitoring();
```

### Expected behavior

Both `WindowsContainerSnapshotProvider.cs` and `WindowsNetworkMetrics.cs` should use the same meter name, which is `Microsoft.Extensions.Diagnostics.ResourceMonitoring`.

### Actual behavior

`WindowsContainerSnapshotProvider.cs` uses the meter name `Microsoft.Extensions.Diagnostics.ResourceMonitoring` while `WindowsNetworkMetrics.cs` uses a different meter name `ResourceMonitoring`.

### Known Workarounds

if we only enable selected meters when collecting metrics, add the `ResourceMonitoring` one which we are likely miss.
![Image](https://github.com/user-attachments/assets/3d5fb508-65e8-4553-82ba-6e8f1f37a012)

**Comment by RussKie** [comment]
@evgenyfedorov2 would it be related to https://github.com/dotnet/extensions/issues/5404?
