### ISSUE TITLE
Consider alternate chaining pattern for DI/builder

### ISSUE THREAD

**Issue by stephentoub** [dotnet/extensions#5572]
(Written by @SteveSandersonMS; I'm copying this into the repo from an offline location...)

---

## Now

Currently the API looks like:

```cs
services.AddChatClient(pipeline => pipeline
    .UseDistributedCache()
    .UseFunctionCalling()
    .Use(new SomeConcreteClient()); // Or pass a factory (Func<IServiceProvider, IChatClient>)
```

... and the proposed Aspire+MEAI integration looks like:

```cs
services.AddOpenAIChatClient("service-name", pipeline => pipeline
    .UseDistributedCache()
    .UseFunctionCalling());
```

## Possibility

However, we could change `AddChatClient` so that it actually returns the `ChatClientBuilder` instead of the `IServiceCollection`. Then it would look like:

```cs
services.AddChatClient(new SomeConcreteClient()) // Or pass a factory (Func<IServiceProvider, IChatClient>)
    .UseDistributedCache()
    .UseFunctionCalling();
```

... and the proposed Aspire+MEAI integration would become:

```cs
services.AddOpenAIChatClient("service-name")
    .UseDistributedCache()
    .UseFunctionCalling();
```

In my opinion this looks a lot better, as it removes the lambda, nested brackets, and the meaningless-looking `pipeline => pipeline` that hangs at the end of the first line.

This would be a legitimate pattern for DI with plenty of prior art of `AddX` calls that return a builder you can chain further setup steps on.

## Challenges

* We'd have to change `ChatClientBuilder` so that, instead of accepting `IServiceProvider` as a constructor arg and exposing it as a property, it would have to work without access to an `IServiceProvider` until the DI service is resolved.
  * Mostly this is fine because the `Use(Func<ChatClientBuilder, ChatClientBuilder>)` method already has an overload that takes `Func<IServiceProvider, ChatClientBuilder, ChatClientBuilder>` and so that would become the only overload
  * The one thing that would have to change is its `Use(IChatClient)` that terminates the pipeline. This would have to change to `Use(Func<IServiceProvider, IChatClient>)`. And we should probably rename it to `UseInnerClient` or back to `Build` otherwise it gets really hard to differentiate.
    * Alternatively we remove that method entirely and change the constructor to have two overloads, one accepting `IChatClient` and the other accepting `Func<IServiceProvider, IChatClient>`. Then the usage pattern is that you pass the inner client (or factory for one) to the constructor, and any `Use` calls are assumed to come before that in the pipeline.
* It becomes harder for us to detect whether you've configured a pipeline or not. Today we can check if the `pipeline` func is null, and if so, have a default pipeline.
  * We could do something slightly trickier where `ChatClientBuilder` keeps track of whether any `Use` calls have been made, and then at service resolution time, we apply a default pipeline if not
  * Or we move away from the concept of a default pipeline, which is dubious anyway because it's weird that *adding* a pipeline phase erases the default pipeline you had before

Altogether I think the improved aesthetics of doing this without `pipeline => pipeline` make it worthwhile to pursue.

**Comment by stephentoub** [comment]
> The one thing that would have to change is its Use(IChatClient) that terminates the pipeline. This would have to change to Use(Func<IServiceProvider, IChatClient>). And we should probably rename it to UseInnerClient or back to Build otherwise it gets really hard to differentiate.

I think we should be doing something different here, anyway. I find it confusing that Use(x) and UseX() return different types and logically function differently.

**Comment by kzu** [comment]
This looks like an improvement. I'd just add that adding a `.UseDefaultPipeline()` or the like, to configure what's "automagic" now, would be fine. I found it actually unexpected that there was such a default pipeline in the first place.
