### ISSUE TITLE
Consider light RAG API

### ISSUE THREAD

**Issue by pdevito3** [dotnet/extensions#5578]
Potentially similar to the [light rag python library](https://github.com/HKUDS/LightRAG), it would be great if we had access to light rag capabilities with our AI extensions as well. 

[Here's an example of it used with ollama](https://youtu.be/g21royNJ4fw?si=ut7s5lRBXNlYfVe1).

Personally not set on any particular API, but wanted to at least get this out there and see what thoughts are on adding capability at all.

**Comment by stephentoub** [comment]
This is the kind of library I'd love to see written on top of Microsoft.Extensions.AI and Microsoft.Extensions.VectorData, but I don't think it needs to be a core .NET library in dotnet/*. Anyone could implement it and publish it on nuget.

**Comment by pdevito3** [comment]
Yeah figured it might be too granular but at the same time it's a common interaction/ask of ai functionality so there's something to be said first party support of it.

Either way, loving it so far!
