### ISSUE TITLE
Consider changing IChatClient/IEmbeddingGenerator.GetService to be non-generic

### ISSUE THREAD

**Issue by stephentoub** [dotnet/extensions#5607]
We currently have:
```C#
TService? GetService<TService>(object? key = null)
    where TService : class;
```

That prohibits its use if you only have a `Type`. If we instead had:
```C#
object? GetService(Type serviceType, object? key = null)
```
then you could use it with either a generic or non-generic, and we could provide a generic wrapper, e.g.
```C#
public static TService GetService<TService>(this IChatClient client, object? key = null) where TService : class =>
    (TService?)client.GetService(typeof(TService), key);
```
ala what's done with `IServiceProvider`.

I ran into this while experimenting while prototyping implementing a delegating chat client with delegates for all of its members. There isn't a good way to have a strongly-typed delegate that parameterizes an instance and provides an implementation for `GetService<TService>` today, because the `TService` can change with every call. If it were instead based on `Type`, that wouldn't be an issue.

cc: @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Agreed, accepting a `Type` seems very reasonable and inline with our APIs elsewhere.

**Comment by JohnGalt1717** [comment]
It appears that this borke a ton of stuff. Now I can use OllamaEmbeddingGenerator with Micrsoft.Extensions.AI.Ollama because you get the following: Method 'GetService' in type 'Microsoft.Extensions.AI.OllamaEmbeddingGenerator' from assembly 'Microsoft.Extensions.AI.Ollama, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.'


doesn't matter what combination of versions I try.

But here's what I have:

    <PackageVersion Include="Microsoft.Extensions.AI" Version="9.0.0-preview.9.24507.7" />
    <PackageVersion Include="Microsoft.Extensions.AI.Ollama" Version="9.0.0-preview.9.24507.7" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="9.0.0-preview.9.24507.7" />

**Comment by stephentoub** [comment]
Those are the versions from two months ago. This change isn't in those, so something else you're using is pulling in a newer version. Change your version numbers to be 9.0.1-preview.1.24570.5.

**Comment by JohnGalt1717** [comment]
It also does it with that version.

And I also get this:

Method 'GetService' in type 'Microsoft.Extensions.AI.OllamaChatClient' from assembly 'Microsoft.Extensions.AI.Ollama, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

So it's happening with ALL versions of Ollama (at least)

I have Kernel Memory also installed if that would matter and the Aspire Ollama stuff if that matters.

**Comment by SteveSandersonMS** [comment]
There was an update to OllamaSharp last week: https://github.com/awaescher/OllamaSharp/pull/144

It may be that explicitly referencing OllamaSharp 4.0.8 will fix this.

**Comment by stephentoub** [comment]
> It may be that explicitly referencing OllamaSharp 4.0.8 will fix this.

If you're using OllamaSharp, yes,  but you said you're using OllamaChatClient, which doesn't use OllamaSharp. 

(Are you using SK? SK needs to ship updated nuget packages to ship the changes that fold this in. cc: @RogerBarreto)

**Comment by JohnGalt1717** [comment]
I'm using KernelMemory not Semantic Kernel. Same problem though I would assume?

**Comment by JohnGalt1717** [comment]
FWIW, removing the Ollama stuff for Aspire and doing the connection info manually, solves the issue with 9.0.0-preview.9.24556.5

It doesn't solve the issue with: 9.0.1-preview.1.24570.5 which has the same error back again.

Major version issues here to get this to work across the entire ecosystem of aspire, SK, (or KM) and M.E.AI.

**Comment by stephentoub** [comment]
Can you share a standalone repro? I'm not sure what dependency is causing the problem, but to my knowledge everything on nuget that depended on the old version has an updated version that depends on the newest.
