### ISSUE TITLE
[API Proposal]: Add feature to use Open AI Assistant

### ISSUE THREAD

**Issue by sylvain-guillet** [dotnet/extensions#5611]
### Background and motivation

Open AI Assistant offers a good approach to integrate GPT in your own application : https://platform.openai.com/docs/assistants/overview
Allow developer to use assistant can improve the productivity because assistant handles message history, parallel function calling, RAG, code interpreter, ...

### API Proposal

```csharp
builder.Services.AddChatClient(c =>
        {
            c.UseFunctionInvocation();
            var openAIClient = c.Services.GetRequiredService<OpenAIClient>();
            var modelId = builder.Configuration["AI:OpenAI:Chat:AssistantId"] ?? "gpt-4o-mini";
            return c.Use(openAIClient.AsAssistant(modelId));
        });
```

### API Usage

```csharp
//Inject chat client in constructor and initialize it. Now the developer can benefit history management, RAG, parallel function calling, code interpreter as configured on the open ai platform
public AIServices(IChatClient chatClient)
    {
        _chatClient = chatClient ?? throw new ArgumentNullException(nameof(chatClient));

        _messages.Add(new ChatMessage(ChatRole.System, SYSTEM_DEFINITION));
    }

//then just send message to the thread 
```

**Comment by stephentoub** [comment]
We're not introducing any abstraction specific to OpenAI assistants. A non-provider-specific generalization of it would likely be around agents, and while we might look at an agents-related abstraction in the future, we currently have no plans to add one. I'd suggest looking at Semantic Kernel's agents framework, which includes an implementation for OpenAI assistants.
https://learn.microsoft.com/en-us/semantic-kernel/frameworks/agent/?pivots=programming-language-csharp

It might be possible to represent a particular thread with an OpenAI assistant as an IChatClient. If that's something you're interested in pursuing, I'd recommend prototyping it and sharing what you come up with. We've noodled on that in the past but we don't currently have anyone looking at it.

Thanks.
