### ISSUE TITLE
[Microsoft.Extensions.AI] - Add new Structured output support for JSON in Ollama

### ISSUE THREAD

**Issue by pdevito3** [dotnet/extensions#5726]
Would love to see support for the [new structured outputs](https://ollama.com/blog/structured-outputs) that ollama supports in a new `format` option to describe the json schema object we want to enforce.

```
curl -X POST http://localhost:11434/api/chat -H "Content-Type: application/json" -d '{
  "model": "llama3.1",
  "messages": [{"role": "user", "content": "Tell me about Canada."}],
  "stream": false,
  "format": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "capital": {
        "type": "string"
      },
      "languages": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "name",
      "capital", 
      "languages"
    ]
  }
}'
```

As far as the API for this, I'd think we could just add a new `Object` option to `ResponseFormat`, but not sure exactly what i'd expect for the actual schema definition offhand?

```
new ChatOptions<MyExpectedShape>()
{
    ResponseFormat = ChatResponseFormat.Object,
    Schema = typeof(MyExpectedShape)
}

// ...

new ChatOptions()
{
    ResponseFormat = ChatResponseFormat.Object,
    Schema = typeof(MyExpectedShape),
    SchemaSerializerOptions = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
    }
}
```

regardless, this would greatly enhance the capabilities for json handling and would be a great value add!

**Comment by stephentoub** [comment]
> I'd think we could just add a new Object option to ResponseFormat

This already exists:
https://github.com/dotnet/extensions/blob/953f93f011251892eca1e26ac3ee3b7a93a48838/src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseFormat.cs#L35-L39
Is there a reason that's insufficient?

I think this should just be a matter of updating the Ollama IChatClient implementation to propagate that.

**Comment by stephentoub** [comment]
(Also, with regards to `Schema = typeof(MyExpectedShape)`, the `CompleteAsync<T>` method already handles creating a schema from the `T`, using the also public `AIJsonUtilities`.)

**Comment by pdevito3** [comment]
sweet!

>  Is there a reason that's insufficient?

I wouldn't say what we have with `json` is insufficient _per say,_ but this new api has better baked in enforcement of a given json schema from what i can see in the ollama spec and would require  the new `format` shape to be sent in the api call. 

with that said, i guess we don't necessarily need to update this external api to leverage the new structured format if we just change the underlying implementation of how `json` format is sent, but then you'd be making assumptions about how the api call should be built vs giving the consumer control of a new feature or existing one

**Comment by stephentoub** [comment]
Sorry, I'm still not following. There are currently three ResponseFormats supported in the abstraction:
1. `ResponseFormat.Text` - requests a text response
2. `ResponseFormat.Json` - requests a JSON response
3. `ResponseFormat.ForJsonSchema(schema)` - requests a JSON response conforming to the specified schema

Isn't this exactly (3)?

What's missing then isn't needing new API, it's just teaching the OllamaChatClient what to do when it's passed the object returned from ForJsonSchema: today it ignores it, tomorrow it should propagate that information to Ollama.

**Comment by pdevito3** [comment]
Crap, sorry i misread the class on mobile! Yes, you're right. As you said, it should just be a matter of updating the Ollama IChatClient implementation to teach the OllamaChatClient what to do when it's passed the object returned from ForJsonSchema.
