### ISSUE TITLE
Investigate integrating Activities and Logging scopes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/extensions#596]
We want investigate how we can integrate activities with logging scopes. More details to come soon.

**Comment by davidfowl** [comment]
@pakrym can you link to you branch here?

**Comment by pakrym** [comment]
https://github.com/aspnet/Extensions/tree/pakrym/logging-activity-spike

**Comment by muratg** [comment]
We have limited time left in preview2. Any work to be done in the week here?
