### ISSUE TITLE
[Helix] UserSecrets GeneratesAssemblyFile test can't find solution root

### ISSUE THREAD

**Issue by HaoK** [dotnet/extensions#624]
Test probably needs to be updated for helix (or we need to publish the sln again) 

https://mc.dot.net/#/user/dotnet-github-anon-kaonashi-bot/pr~2Faspnet~2Fextensions/ci/20181210.14/workItem/Microsoft.Extensions.Configuration.UserSecrets.Tests~2Fnetcoreapp2.0/wilogs

```
[xUnit.net 00:00:00.76]     Microsoft.Extensions.Configuration.UserSecrets.MsBuildTargetTest.GeneratesAssemblyAttributeFile [FAIL]
Failed   Microsoft.Extensions.Configuration.UserSecrets.MsBuildTargetTest.GeneratesAssemblyAttributeFile
Error Message:
 System.IO.FileNotFoundException : Could not identify solution root
Stack Trace:
   at Microsoft.Extensions.Configuration.UserSecrets.MsBuildTargetTest..ctor(ITestOutputHelper output) in /_/src/Configuration/Config.UserSecrets/test/MsBuildTargetTest.cs:line 37
```

**Comment by HaoK** [comment]
Related to https://github.com/aspnet/AspNetCore/issues/6549 general issue for sln being missing

**Comment by anurse** [comment]
Closing as this issue is out-of-date and is tracking work that is no longer needed.
