### ISSUE TITLE
New Lines and Line Breaks

### ISSUE THREAD

**Issue by riaz-ahmad** [dotnet/extensions#641]
I would like to be able to configure logging so that the Console logger emits log messages in a single line. When exceptions are logged, line breaks should be removed so that they are logged on a single line.

There are times that I need to search my log content, but when content is spread across multiple lines, each line is treated as a separate record, so I cannot find all the lines for a log event when I run a search query in our log service.

There are also times when other services are writing to the log service which cause problems when multiple lines are written.  This can leave a long multi-line message defragmented as other log messages will write in between lines of a mult-line message.

Here is an example of current behavior of ConsoleLogger.cs:
INFO: ConsoleApp.Program[10]
       Request received

Here is the requested behavior:
INFO: ConsoleApp.Program[10] Request received

**Comment by anurse** [comment]
Closing this in lieu of #2479 . We're going to be looking at a single-line logging format (as well as custom formatting) as part of that.
