### ISSUE TITLE
Deduplicate test discovery logic between Common and Logging

### ISSUE THREAD

**Issue by Tratcher** [dotnet/extensions#652]
https://github.com/aspnet/Logging/pull/798/files#diff-4b2f9320dbf4947f20507c2b2a94118d duplicated a lot of logic from Common's Testing package. We assumed they wouldn't change, but then they did:
E.g. https://github.com/aspnet/Logging/pull/832

**Comment by anurse** [comment]
Closing as this issue is out-of-date and is tracking work that is no longer needed.
