### ISSUE TITLE
Consider - Expand on LoggerMessage.Define and LoggerMessage.DefineScope more

### ISSUE THREAD

**Issue by chassq** [dotnet/extensions#654]
I might see if you would consider expanding on LoggerMessage.Define and DefineScope a bit more. 

For example:
1. Allow LoggerMessage.Define to take more than 6 arguments and DefineScope to take more than 3
2. Have DefineScope return a Disposable Scope object, instead of just IDisposable, to be able to access more info about e scope (e.g. the arguments passed into the delegate).

Thanks!

**Comment by maryamariyan** [comment]
Related to: https://github.com/dotnet/runtime/issues/35060

**Comment by anurse** [comment]
> * Allow LoggerMessage.Define to take more than 6 arguments and DefineScope to take more than 3

This seems to be well covered by https://github.com/dotnet/runtime/issues/35060.

> 2\. Have DefineScope return a Disposable Scope object, instead of just IDisposable, to be able to access more info about e scope (e.g. the arguments passed into the delegate).

This would be a significant API change and I don't see a huge value in it. You can already define your own scope objects without using `DefineScope`.

Closing as we don't plan to take further action.
