### ISSUE TITLE
A mode of Console logger that outputs JSON

### ISSUE THREAD

**Issue by glennc** [dotnet/extensions#659]
This allows an app to output logs to the console that are redirected to a file or read by another process that can then parse the JSON to maintain structured logs.

The canonical example of this is a side-car container on a Docker host. The side car picks up all Docker logs and sends them to an external logging sink, like app insights or sending to an ELK stack.

**Comment by nvoskuilen** [comment]
I decided to write [JsonConsole](https://github.com/nvoskuilen/Nvosk.Extensions.Logging.JsonConsole) which is an extension for Microsoft.Extensions.Logging which outputs json to console.

It is in essence the source of Microsoft.Extensions.Logging.Console, but modified to output clean json and adjustable event names via application.json.

**Comment by anurse** [comment]
Duplicating over to #2479.
