### ISSUE TITLE
What drawbacks to expect from fiddling with ThreadPool.SetMinThreads?

### ISSUE THREAD

**Issue by bragma** [dotnet/extensions#699]
Hi,
I am trying to use "Microsoft.Extensions.Caching.StackExchangeRedis" in my ASP NET Core (.NET 4.7.1) web app and like many others I am struggling with timeouts, most probably caused by minThreads too low. I've tried increasing the value in steps, but I am wondering what brawbacks/problems to expect from fiddling with that values. At the moment I am trying to keep values as lower as possible, but should I need to set them to 100 or 500 or even 1000, documentations says that there may be some "performance problems". Is this the expected way to implement and use Redis? I'm a bit uncomfortable with this.
Thanks for any advice.

**Comment by anurse** [comment]
This is probably a more appropriate question for the StackExchange.Redis team at https://github.com/StackExchange/StackExchange.Redis . The Caching component is a fairly simple wrapper around that, so they would have more experience with the threading model and how changing the minimum threads would affect it.
