### ISSUE TITLE
Consider re-enabling some skipped tests

### ISSUE THREAD

**Issue by pranavkm** [dotnet/extensions#721]
The repo has 42 skipped tests that results in 84 build warnings being produced as part of building. Both of these are because the test expects infrastructure (Redis Server \ Sql Server) to be present on the machine.

Could we instead 

a) convert these in to conditional facts that attempt to check if the infrastructure exists (for instance all our build agents have Sql Server installed)? 
b) Just skip these from test discovery via `ExcludeFromTests` 
c) Delete them because what's the point of having tests that don't run regularly?

**Comment by anurse** [comment]
Closing this as we aren't likely to be able to prioritize it.
