### ISSUE TITLE
Cache provider for Service Fabric

### ISSUE THREAD

**Issue by maucaro** [dotnet/extensions#722]
It would be very nice for ASP.NET Core apps running on Service Fabric to be able to use SF itself as the IDistributedCache instead of having to rely on SQL or Redis. Any thoughts on implementing this?

**Comment by anurse** [comment]
We don't have plans to add a built-in Service Fabric provider. A quick search shows some third-party components covering this (https://github.com/SoCreate/service-fabric-distributed-cache) and we aren't able to prioritize further investigation into it.
