### ISSUE TITLE
Pool connections

### ISSUE THREAD

**Issue by sebastienros** [dotnet/extensions#727]
From experience, when using Redis with bigger that usual content like response cache (~100KB) on high traffic sites the tcp connection can reach its limit as all requests are pipelined on a single redis connection and be a bottleneck.

A solution could be to use a configurable number of pooled connections to parallelize the communication with Redis. A simple queue for instance. This would allow multiple requests to be processed in parallel.

**Comment by JunTaoLuo** [comment]
This is not a feature we are likely to implement. Closing.
