### ISSUE TITLE
Relocating CacheProfile to Caching.Abstractions

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/extensions#729]
The idea here is to move the `CacheProfile` from MVC https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/CacheProfile.cs to the `Microsoft.Extensions.Caching.Abstractions` package. The `CacheProfile` can then be resolved by middlewares such as ResponseCaching. Configuring the profile can also be implemented in a similar fashion to CORS options/policy.

cc @davidfowl @rynowak @Tratcher

**Comment by anurse** [comment]
Any thoughts on this ancient issue? Seems like it's not really that useful after all :).
