### ISSUE TITLE
More reliable cache operations

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/extensions#732]
As part of discussions while working on https://github.com/aspnet/Session/issues/99, there were proposals for adding logic in caching to make database operations more reliable. For example, sql database operations may fail intermittently. In this case it may be a good idea to add retry logic and allow users to specify retry policies. This probably needs some more design work.

cc @mikeharder @Tratcher @davidfowl

**Comment by anurse** [comment]
Seems like this hasn't gotten traction. Closing as it's not likely to be prioritized moving forward.
