### ISSUE TITLE
ASP.NET 5 distributed cache implementation on appfabric

### ISSUE THREAD

**Issue by satishbodke** [dotnet/extensions#735]
Are we going to have Caching implementation for AppFabric as well, the way we have implementation for Redis (Microsoft.Extensions.Caching.Redis)

Can I use my existing implementation of cache providers that was built and targeted .Net 4.5.1 using App Fabric (Microsoft.ApplicationServer.Caching.Client.dll, and Microsoft.ApplicationServer.Caching.Core.dll) by following ASPNET's classic ProviderBase model.

I have custom CacheConfiguration that read the configuration from Web config, and instantiate the provider. But this solution was completely design and used for MVC5, I want to use App Fabric with ASPNET 5 solution now

**Comment by anurse** [comment]
App Fabric is no longer supported by Microsoft, so this isn't really relevant any more. Closing.
