### ISSUE TITLE
Adding Diagnostics Source events/insight to Caching

### ISSUE THREAD

**Issue by avanderhoorn** [dotnet/extensions#736]
As a consumer of diagnostics data we would like to be able to know when a cache hits and misses occur. Having this data will allow us to start realizing/showing "case and effect" with cache hits and misses. I would imagine that as a very minimum we would find out when hits occur, what was the key, the data, how long it took, and the source of the data (in memory vs not), and when misses occur, what was the key, how long it took, and the source of the data (in memory vs not), etc. There might be more data that would be interesting, but we can flush that out in the issue.

@Tratcher @Eilon

**Comment by anurse** [comment]
Diagnostics Source isn't something we intend to expand in this way and we have #717 tracking other diagnostics here. Closing this.
