### ISSUE TITLE
SqlServer Cache Dependency

### ISSUE THREAD

**Issue by PrimeObjects** [dotnet/extensions#740]
Hello, 

I have a few questions here.
1. Do we still support SqlServer cache dependency on SQLServer Cache in ASP.NET? If yes how should I configure it? 
2. How can I define DI for SQLCacheDependency and what should I put  in the constructor of Controller ( IDistributedCache?)
3. I have been using table based cache dependency, is there a solution to manage SQLCacheDependency at record level?
4. I'm using RedisCache in ASP.NET 4, do you have performance benchmark between RedisCache on Azure cloud and SQL Cache in a local DB? 

Thanks lot!
Gary

**Comment by anurse** [comment]
We haven't prioritized this in the past 5 years and I don't expect that to change. This seems like a great distinguishing feature for a third-party SQL Server cache component. Closing as we don't expect this to be something we can prioritize.
