### ISSUE TITLE
[Tracking]XUnit.Console runs skipped theories

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/extensions#747]
This is a tracking issue for [this xunit issue](https://github.com/xunit/xunit/issues/1871). Once we get a reply from them we should do whatever is most appropriate about [this workaround](https://github.com/aspnet/Extensions/pull/586/files#diff-4fdfbbc661fd3f256faeef76b834a4f2R17).

**Comment by ryanbrandenburg** [comment]
Sounds like the fix they currently have in mind is to allow the pre-enumerate switch to be set regardless of the runner.

**Comment by anurse** [comment]
Closing as this issue is out-of-date and is tracking work that is no longer needed.
