### ISSUE TITLE
Provides option to silently ignore XML namespace than to throw exception

### ISSUE THREAD

**Issue by chuanboz** [dotnet/extensions#765]
In following code it throw exception like "System.FormatException: 'XML namespaces are not supported. Line 2, position 11.'"

https://github.com/aspnet/Configuration/blob/dc6fbde39f532bf154ee1eb02d8be08a0a1605e4/src/Config.Xml/XmlConfigurationProvider.cs#L153

Please provide some option in AddXmlFile to ignore such namespace check

**Comment by tvanbaak** [comment]
I also ran into this problem recently. I was able to preprocess the XML files by creating an IFileProvider that stripped the namespaces out, but it would have been much easier and less bug-prone just to have an option to allow what are, as I understand, a valid part of the XML spec.

**Comment by anurse** [comment]
The XML configuration provider is designed to read config files in the format *expected* by the config provider. It's **not** a general purpose XML parser. It seems more suitable here to build a provider specific to the config format you're reading from if it doesn't match the format expected by the config provider.
