### ISSUE TITLE
problem with Microsoft.Extension.Configuration.*

### ISSUE THREAD

**Issue by Eilon** [dotnet/extensions#787]
_From @iceoz on Wednesday, 10 October 2018 13:41:35_

Hi, i'm facing a strange problem, i make some microservices, some of them are just consoleApp with hostbuilder using only Microsoft.NETCore.App SDK, and others are webapi using Microsoft.NETCore.App SDK and Microsoft.AspNetCore.App everyone with 2.1 version

everything worked fine until i try to make some nugets for helpers, in console applications and class libraries i'm using Microsoft.Extension.Options.ConfigurationExtensions with version 2.1.1 without problem, but when i try to install my nuget on webapi i get a error with Microsoft.Extension.Configuration.Binder 2.1.1 with is not compatible with Microsoft.AspNetCore.App 2.1.0, so i need to make a rollback in all nugets i'm using, and there is no updates inside nuget, i'm using the latest version of sdk 2.1.4.....

_Copied from original issue: aspnet/Universe#1478_

**Comment by anurse** [comment]
Seems like this is pretty out-of-date now. Going to close it. If the original author is still encountering this, they can ping the thread or re-file the issue.
