### ISSUE TITLE
.net core read appsettings.json Chinese is Random code

### ISSUE THREAD

**Issue by Eilon** [dotnet/extensions#788]
_From @zhangxize on Monday, 15 October 2018 02:34:52_

appsettings.json:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",

  "Data": "LineZero",
  "ConnectionStrings": {
    "DefaultConnection": "dbconn1",
    "DevConnection": "数据库2"
  }
}
```
read code:
```c#
var data = Configuration["Data"];
string defaultcon = Configuration.GetConnectionString("DefaultConnection");
Debug.Print(defaultcon);
var devcon = Configuration["ConnectionStrings:DevConnection"];
```

devcon value：`���ݿ�2`

add row code:
```c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```
No use
Thanks.

_Copied from original issue: dotnet/core#1997_

**Comment by anurse** [comment]
I just tried this and the string is loaded properly by config, as far as I can tell. I think this is actually an issue with `Debug.Print` or other rendering systems (I see the same from Console.WriteLine when using `数据库2` in a literal string, for example). Closing as this does not appear to be a configuration issue.
