### ISSUE TITLE
Configuration.GetConnectionString intermittently returns null

### ISSUE THREAD

**Issue by BennieCopeland** [dotnet/extensions#790]
We are experiencing an issue where using `Configuration.GetConnectionString` intermittently returns null when used during an ASP.Net Core request scope. We are using SimpleInjector and Entity Framework Core and registering the context like this: `_container.Register(() => new TrexContext(Configuration.GetConnectionString("TrexContext")), Lifestyle.Scoped);`

**Comment by anurse** [comment]
Apologies for the delayed response, we're doing some backlog grooming. Are you still encountering this issue? I'm not aware of any other reports of an issue like this and I'd expect that if there was a race of some kind here. Can you provide a sample that reproduces the problem?

**Comment by BennieCopeland** [comment]
We are not having this issue anymore.
