### ISSUE TITLE
Read section as raw string

### ISSUE THREAD

**Issue by rprimora** [dotnet/extensions#793]
I have added a GeoJSON object as a value of one of my settings inside appsettings.json. 
```
{
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [ 45.760859, 15.936046 ],
            [ 45.760813, 15.936285 ],
            [ 45.760781, 15.936524 ],
            [ 45.760759, 15.936770 ],
            [ 45.760610, 15.936733 ],
            [ 45.760615, 15.936188 ],
            [ 45.760641, 15.935952 ],
            [ 45.760859, 15.936046 ]
          ]
        ]
      },
      "type": "Feature"
    }
```

I  wanted to read this as a raw string but Configuration cannot see it that way. This would be easy if this object was simple but it is not. Right now the object does look simple but for instance, if the type was MultiPolygon instead of Polygon than we would have array of Polygon objects. In any case this is treated as different type in C# but here the type is defined via property "type".

If I was able to read this section as a string than I could give it as such to Deserialize method of GeoJson providers that support this way of deserialization.

Is this possible?

**Comment by anurse** [comment]
(Apologies for the long delay, I'm sure you've moved on by now ;). We're doing some backlog grooming to clean up long-idle threads like this)

No, it's not really possible. The JSON configuration provider doesn't know anything about the target binding, it's loading the config into flat key-value pairs (with a heuristic of using `:` to separate hierarchical data). Then the binder is putting that back together into an object. Preserving the original JSON string isn't really something the design can accommodate here.

Closing as this isn't something our design model can accommodate.
