### ISSUE TITLE
UserSecrets error after upgrading to 2.2.0

### ISSUE THREAD

**Issue by dr3s** [dotnet/extensions#795]
Upgrading to 2.2.0 my test project with user secrets broke with the following error

```
Message: System.AggregateException : One or more errors occurred.
---- System.InvalidOperationException : Could not find 'UserSecretsIdAttribute' on assembly 'Doc.AspNetCore.CommonTests'.
Check that the project for 'Doc.AspNetCore.CommonTests' has set the 'UserSecretsId' build property.
If the 'UserSecretsId' property is already set then add a reference to the Microsoft.Extensions.Configuration.UserSecrets package.
```
 but I do have a UserSecretsId and the Microsoft.Extensions.Configuration.UserSecrets package as a direct dependency.

The only change in 2.2.0 that seemed related was:

https://github.com/aspnet/Configuration/pull/872

**Comment by raymens** [comment]
All our ASP.NET Core projects that we upgraded to 2.2.x are having issues. When debugging or running it locally it doesn't load the UserSecrets. It's also not listed as a provider. Using VS or the `dotnet user-secrets` tool doesn't seem to have any issues.

**Comment by johnny-chan** [comment]
I just experienced this problem when running a user secrets as part of an console app. Depending on how you configured the UserSecrets in the StartUp.cs, i replaced

builder.AddUserSecrets<SecretType>();

with 

builder.AddUserSecrets("your secret it");

hope that helps

**Comment by rkreisel** [comment]
dr3s is correct
Install-Package Microsoft.Extensions.Configuration.UserSecrets
fixed it for my project(s)

**Comment by anurse** [comment]
(Reviving this old thread as we dig through the backlog and try to resolve long-idle issues like this. If you've moved on by now, no worries and sorry for the delay!)

> but I do have a UserSecretsId and the Microsoft.Extensions.Configuration.UserSecrets package as a direct dependency.

Are you still seeing this problem? Where the `UserSecretsId` is not properly loaded **even though you have a direct dependency on `Microsoft.Extensions.Configuration.UserSecrets`**? That *should* be working. The fact that an indirect dependency doesn't work is a known issue in the SDK: https://github.com/dotnet/sdk/issues/4007

**Comment by anurse** [comment]
Closing this as we haven't heard from you.
