### ISSUE TITLE
Implement QueueBackgroundWorkItem

### ISSUE THREAD

**Issue by davidfowl** [dotnet/extensions#805]
Gives user code the ability to schedule a background task that's aware of shutdown semantics. Here's the original blog post of that feature in System.Web.

https://blogs.msdn.microsoft.com/webdev/2014/06/04/queuebackgroundworkitem-to-reliably-schedule-and-run-background-processes-in-asp-net/

@Tratcher wrote a prototype of it here https://github.com/aspnet/Docs/issues/3352#issuecomment-333593326. 

A few initial thoughts on the version that should exist here:
- It shouldn't be tied to anything Web specific, this is a generic host feature.
- We should think about the fact that people will want to use services in these background operations. That might mean that we need to provide a way to active a "Task" so it's not just a func. e.g. QueueBackgroundWorkItem<WorkItem>(arg1, arg2), etc.

/cc @glennc

**Comment by muratg** [comment]
@davidfowl Are you able to take this for 3.0?

**Comment by mixandmatch025** [comment]
Is the plan only to support a single background task at a given moment?

**Comment by muratg** [comment]
**ping** @davidfowl

**Comment by davidfowl** [comment]
No if we do this, the only point is to give background tasks a grace period to executing when the host is shutting down. Maybe we’d alsp support a model where we activated a class per invocation if the background task so that it is easy to inject scoped services.

@glennc maybe we lump this into the background worker work?

**Comment by mixandmatch025** [comment]
@davidfowl not sure if I understood. If I queue multiple tasks, they'll run concurrently?

**Comment by davidfowl** [comment]
@mixandmatch025 yes.

**Comment by omatrot** [comment]
@vegardlarsen I'm trying to use your code. How do you inject the backgroundTaskQueue in a SignalR hub for instance? Registering the Worker does not seem to do the trick. I have this error:

>System.InvalidOperationException: Unable to resolve service for type 'IBackgroundTaskQueue' while attempting to activate 'WebAdmin.SignalR.ServerHub'.

Thanks in advance.

**Comment by vegardlarsen** [comment]
@omatrot Here is how I register all of the things I use this for currently:

```cs
services.AddSingleton<IBackgroundTaskQueue, BackgroundTaskQueue>();
services.AddHostedService<QueuedHostedService>();
services.AddScoped<CustomerIoEventBackgroundWork.Worker>();
services.AddScoped<CustomerIoBroadcastBackgroundWork.Worker>();
```

**Comment by sravanthim** [comment]
@vegardlarsen I am trying to implement a queue to hold api calls when the backend db is down and process these queued api calls when db becomes available again. I am trying to implement your solution using worker and workorder and am running into "Cant access disposed object" exception. However, your solution that you gave on Aug 5,2018 will not work for me. I am trying add the task to the queue, and this task is coming from a microservice's controller method(like a http post).  Can you explain that answer a bit more please. Thank you.

**Comment by vegardlarsen** [comment]
@sravanthim The problem has to do with your IoC container's scopes. A scope can be described as the "context something is being done in". So when you are working in a controller action, you could say that the scope is the HTTP request, and that any services that are transient to that scope will be disposed when the scope ends (i.e. the HTTP request). This also means that a service being used from the wrong scope is at risk of having been disposed when you try to use it from the wrong scope.

For the background work implementation, we create a separate scope for each individual order being done, and we create a new worker for each order that comes through. It is therefore important that the worker implementation only accepts its dependencies through constructor parameters. It will then have its dependencies created by the IoC container with the correct scope.

To figure out your specific problem though, you will have to find out which of your objects is being accesses after it was disposed (it should be in the stack trace of the exception), and figure out if that object was instantiated correctly.

PS! Never pass services in the work orders. Work orders should only contain "simple" values (e.g. ints, strings, arrays, etc), never large objects that can carry state.

**Comment by kakins** [comment]
Sorry if this isn't the right forum for this question, feel free to redirect me elsewhere (documentation, etc).  How would I limit the number of concurrent threads being executed at a time using the background task queue?  I've tried setting some of the constructor arguments for SemaphoreSlim but ran into issues.

**Comment by hempels** [comment]
> I have a suggestion as to how to get services properly injected into the background tasks.

@vegardlarsen This solution is brilliant and is working marvelously for my needs. Thank you!

**Comment by LinusCenterstrom** [comment]
> @davidfowl not sure if I understood. If I queue multiple tasks, they'll run concurrently?


> @mixandmatch025 yes.

I've tested this out and it does not run more than one task at once, and I don't see how it could either since it dequeues a work item and then awaits it before proceeding, or did you mean the final version would be able to run multiple tasks at once?

Am I missing something @davidfowl?

I guess I could start multiple background tasks in the QueuedHostedService to accomplish this or is there a better solution to accomplish this in the prototype?

**Comment by hempels** [comment]
As written, each registered QueuedHostedService will run a single task at a time, queuing up work to be completed as soon as the previous task completes. That's a typical pattern for a task queue. Converting it to a concurrent task queue would introduce complexity. It could be done but at that point I would suggest it's likely no longer a good fit for asp.net and should instead be moved to a service bus, etc.

**Comment by kakins** [comment]
> As written, each registered QueuedHostedService will run a single task at a time, queuing up work to be completed as soon as the previous task completes. That's a typical pattern for a task queue. Converting it to a concurrent task queue would introduce complexity. It could be done but at that point I would suggest it's likely no longer a good fit for asp.net and should instead be moved to a service bus, etc.

I think as @LinusCenterstrom mentioned, does this seem to contradict the response from @davidfowl on this topic?

**Comment by hempels** [comment]
> Does this seem to contradict the response from @davidfowl on this topic?

Two different conversations. @davidfowl was describing what MS would build if they add support for background tasks into the framework. I was describing how the solution contributed by @vegardlarsen works as written. They are very different approaches.

**Comment by kjkrum** [comment]
I took an entirely different approach. Instead of explicitly maintaining a task queue, I let controllers schedule tasks in whatever manner is appropriate for the task, and register them with a singleton that will block graceful shutdown until all tasks complete.

```C#
    public class TaskRegistry : IDisposable
    {
        public CancellationToken ApplicationStopping { get; }
        private readonly CountdownEvent counter = new CountdownEvent(1);

        public TaskRegistry(IApplicationLifetime app)
        {
            ApplicationStopping = app.ApplicationStopping;
            ApplicationStopping.Register(() =>
            {
                counter.Signal();
                counter.Wait();
            });
        }

        public void Register(Task task)
        {
            if (task.Status == TaskStatus.Created)
            {
                throw new InvalidOperationException();
            }
            counter.AddCount();
            task.ContinueWith(t => counter.Signal());
        }

        public void Dispose()
        {
            counter.Dispose();
        }
    }
```
With this injected as `Tasks`, controllers simply call
 ```C#
    Tasks.Register(SomeAsyncMethod(Tasks.ApplicationStopping));
````

**Comment by Olanger0919** [comment]
Where should I put the code backgroundTaskQueue.QueueUpdateUserReputation("vegardlarsen"); if using window service .net core 2.1? Also, can you post an example on adding item queue to the service as well? Thank You!

**Comment by vegardlarsen** [comment]
@LFCYNWA2019 You just need to get hold of a `IBackgroundTaskQueue` instance to call it. You can do that by just adding it as a constructor parameter on e.g. a controller. Adding an item to the queue is easy if you look at the implementation of [`QueueUpdateUserReputation` above](https://github.com/aspnet/Extensions/issues/805#issuecomment-410539073).

**Comment by bidianqing** [comment]
@davidfowl Any update to this?

**Comment by davidfowl** [comment]
No, there's lots of great code in this thread that does the job.

**Comment by IGx89** [comment]
@davidfowl The [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio#queued-background-tasks) have a link to this issue labeled "tentatively scheduled to be built-in for ASP.NET Core". I'm assuming because of that and the fact that this issue is still open, that's still the plan?

**Comment by ssg** [comment]
Perhaps closing this issue is in order?

**Comment by smcl** [comment]
If the issue does get closed, please remember to update this doc which refers to this as "tentatively scheduled to be built-in for ASP.NET Core": https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=netcore-cli

**Comment by omatrot** [comment]
> @davidfowl not sure if I understood. If I queue multiple tasks, they'll run concurrently?



> @mixandmatch025 yes.

@davidfowl This is not the behavior I'm experiencing. I had a bug in a one of the queued tasks that made it trapped in a loop thus consuming CPU and running forever. All other pending tasks were patiently waiting in the queue. 

I'm building an app that will be used by multiple consumers concurrently. One task should not prevent the others for running. I'd like to introduce a worker for a groups of consumer and also be able for a task to timeout and be canceled automatically.

**Comment by davidfowl** [comment]
Not sure what you mean. I was referring to the API that exists in .NET Framework not the code on this thread. Maybe that’s where our wires for crossed.

Task queued to the thread pool execute in parallel.

**Comment by omatrot** [comment]
@davidfowl I was refereing to the code on this thread.

**Comment by davidfowl** [comment]
I wasn’t 😬

**Comment by omatrot** [comment]
@vegardlarsen I'm using your code and so far it was ok. Then, because of a bug, I had a queued task running forever trapped in a loop. The side effect was that other queued tasks were not processed at all.

I have 2 questions:

1. Can I make a running task cancel automatically after a tiemout?
2. Can I have a several queues processed in parallel?

Thanks in advance.

**Comment by vegardlarsen** [comment]
@omatrot 
1. You could modify the `BackgroundTaskQueue` to support timeouts, by adding a timeout when you add it to the internal list; and only allow it to be dequeued if the timeout hasn't passed. Or you could probably do something like `await Task.WhenAny(task, Task.Delay(10000));` instead of `await task;` to not wait for the results. Or you could set something even better up with `CancellationTokens`s.

2. Regarding multiple queues in parallell; I think it could be as simple as adding multiple instances of the `IHostedService`, basically multiple calls to `services.AddHostedService<QueuedHostedService>();`. Not sure if the runtime will prevent you from doing that though.

Note that my code above is just an example of how I did this in my code, and you can modify it freely. At this point I sincerely doubt if this will make it into the library; and I am not sure if it is enough utility in it to roll it into its own Nuget.

**Comment by hempels** [comment]
> 2. Regarding multiple queues in parallell; I think it could be as simple as adding multiple instances of the `IHostedService`, basically multiple calls to `services.AddHostedService<QueuedHostedService>();`. Not sure if the runtime will prevent you from doing that though.

This works, the runtime has no issue with it. We run multiple hosted service instances so that we can have parallel queues for different task types.

**Comment by omatrot** [comment]
@hempels how do you access a particular instance?

**Comment by hempels** [comment]
> @hempels how do you access a particular instance?

Each instance registered separately via DI, which resolves them as an IEnumerable.
```
services.AddSingleton<IBackgroundTaskQueue, BackgroundTaskQueue<UpdateNamesAndRolesBackgroundTaskQueue>>();
services.AddHostedService<QueuedHostedService<UpdateNamesAndRolesBackgroundTaskQueue>>();
```
```
public NamesAndRolesSync(IEnumerable<IBackgroundTaskQueue> queues) {
var queue = queues.FirstOrDefault(q => q.GetType().GenericTypeArguments.FirstOrDefault()?.Name == typeof(UpdateNamesAndRolesBackgroundTaskQueue).Name);
...
```
This can be generalized into helper methods, or done more automagically with DI.

**Comment by vflame** [comment]
Any advantages of using System.Thread.Channel versus this for implementation?

**Comment by davidfowl** [comment]
@vflame Advantages of which approach, there are varying implementations on this thread alone. Channels works fine, the thread pool works fine, it depends on the set of tradeoffs you're willing to make.

- Do you care about execution order of the scheduled tasks?
- Do you care about a best effort way of completing tasks in case of a shutdown?
- Do you care about the knowing the task definitely completed (What happens if it crashes?). None of these solutions handle that.

etc. These solutions are now pretty trivial to build because of the primitives in the system (channels, task.run, various synchronization primitives)

**Comment by anurse** [comment]
Triage: This thread has a lot of different suggestions for patterns and it feels like that means there's not a clear built-in solution for the base platform to provide. Closing as we don't plan to build this in to the product at this time. If there are issues blocking development of components that do provide queue-based background workers, we should look at addressing those in separate issues.
