### ISSUE TITLE
IFileProvider - changetoken for glob pattern which file changed?

### ISSUE THREAD

**Issue by dazinator** [dotnet/extensions#846]
How to know what files have caused a change token covering a glob pattern, to be signalled?
Created because #2549 was closed.

**Comment by dazinator** [comment]
As further clarification, issue is when calling IFileProvider.Watch() with a glob pattern like `**/*.txt` and getting an IChangeToken, how to tell what file changes were actually made when the change token is ultimately signalled? The only way I have found so far is to query the file system before and after to take my own snapshot of file modified dates and then compare them myself to work out the deltas - but this involves requesting the file provider each time. I am hoping there is a solution in which the file provider can tell you what the changes for a watch operation actually were..?

**Comment by anurse** [comment]
> how to tell what file changes were actually made when the change token is ultimately signalled

There isn't a built-in way to do this, it's a limitation of file system notifications at the OS level. We only get a notification that *something* changed in the directory.

> The only way I have found so far is to query the file system before and after to take my own snapshot of file modified dates and then compare them myself to work out the deltas I.e- which individual file change was made

This is probably your best bet here if you need to watch any file in the directory. You can get more detail about individual files that change by watching those files specifically but if you're watching a directory for changes matching a filter, this is a limitation in the system.

There certainly are options to improve this within the watcher itself but they all end up with some weird trade-offs so we likely won't be able to prioritize looking into that in depth. Finding a pattern that works well for your application is best here.
