### ISSUE TITLE
Remove `TestRunnerName` workaround

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/extensions#901]
[Here](https://github.com/aspnet/Extensions/pull/586#discussion-diff-245451698R16) I worked around a limitation in Aracade by setting TestRunnerName to the empty string. Once Arcade is more baked we should implement one of the suggestions made [here](https://github.com/dotnet/arcade/issues/1464) instead.

**Comment by pranavkm** [comment]
This is done.
