### ISSUE TITLE
Collect dumps on Linux and macOS

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/extensions#906]
Collecting dumps for LoggedTest was added in https://github.com/aspnet/Extensions/pull/905 but it's Windows only. We should look into fixing the implementation on Linux (see https://github.com/aspnet/AspNetCore/pull/6177) and explore options of macOS.

**Comment by anurse** [comment]
We could do this now with `dotnet-dump` (which now supports Windows in preview7!)

**Comment by anurse** [comment]
Not really relevant in this repo as we move forward with the split.
