### ISSUE TITLE
Consider adding App Service retention policy support to Blob and File loggers

### ISSUE THREAD

**Issue by muratg** [dotnet/extensions#959]
App Service has a feature to set up log retention policies for Blob and File loggers. Customers can configure how many days they want to keep their logs via Azure Portal.

Let's consider adding this feature to our App Service Blob and File loggers as well.

**Comment by muratg** [comment]
Note: I'm actually not sure about the File logger retention support on App Service, but App Service Blob logging definitely has the setting.

**Comment by anurse** [comment]
We're exploring other options for app service logging so I think this is probably not as relevant now.
